### ISSUE TITLE
Autowidth on Select

### ISSUE THREAD

**Issue by cbuv** [equinor/design-system#1004]
**Is your feature request related to a problem? Please describe.**
The Select must have width  equal to the the longest text in the items array to avoid having horizontal scroll in options. 
 The main friction is when filtering on big data set will cause column width to vary because we must have wide enough columns to avoid horizontal scrolling in a Select component within the table.  

**Describe the solution you'd like**
The options container should use necessary space horizontal.  (possible bigger the than the parent component)
A auto width property similar to material-ui.

**Describe alternatives you've considered**
Custom made select

**Additional context**
Material ui's Simple Select does solve this problem.  
https://material-ui.com/api/select/
![image](https://user-images.githubusercontent.com/48285335/104202669-81075380-542b-11eb-9d59-739aa78d6c78.png)

**Comment by mimarz** [comment]
Thanks for your feedback! 

Do you have an example of the use-case where this is a problem for you (since you cant't make a fixed width that works)?
We have several options here which would also be discussed with our designer, such as may the text be truncated with ellipsis or similar if width is max of parent.

We'll have a look at it on our next planning meeting and get back to you on priority :)

**Comment by cbuv** [comment]
I have a dropdown with labels of up to 36 characters in a table column. 
Being forced to set width on the column make the table too wide. 

Our tables have typically 10-15 columns. 
The designers could create worst-case design of a table with dropdown cell where options have up to 40 characters.

**Comment by mimarz** [comment]
We had a look at this during planning today, and I think we need to look closer at this use-case with our designers @equinor/eds-ux to determine what would be the best solution or approach to this problem. @akvam showed us some use-cases from (one-of) the app you are working on, but maybe we could have a meeting with you and our designers to have a closer look at this?

**Comment by cbuv** [comment]
Sure, lets arrange a meeting.

**Comment by mimarz** [comment]
Notes for self: https://github.com/floating-ui/floating-ui/issues/794
