### ISSUE TITLE
Power BI: make Equinor font available

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1023]
Explore possibilities to be able to use the Equinor font (or other fonts that aren't built into Power BI) . 
We checked into this some and it seems that if could be possible but the font needs to be installed in each user's machine. Equinor font is installed on some machines but not all. 
Power BI upgrades happen every month, so this might be easier in the future. 
We could investigate possibility to install Equinor font on all machines? Or is this not feasible?

**Comment by BirteThornquist** [comment]
Not possible now for technical reasons.
