### ISSUE TITLE
Power BI: collect examples of colouring standards in use in Equinor

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1024]
Have started doing this in the EDS template, but collect even more coloring standards that in are in use in projects today so people are aware of what it in use and where it comes from. Example is IOC and alarm colors. Other projects have sent us information.

**Comment by Hjaf** [comment]
This has been collected in this onenote: [Color Schemes](https://statoilsrm.sharepoint.com/sites/Designsystem/_layouts/OneNote.aspx?id=%2Fsites%2FDesignsystem%2FShared%20Documents%2FGeneral%2FPower%20BI%2FExamples%2FPower%20BI%20examples&wd=target%28Color%20schemes.one%7CC461E3B1-30B9-4CD3-AE59-C6112EFAADA9%2F%29)
