### ISSUE TITLE
Verify use of EDS components in compact Table

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1027]
Make example of using compact Table with the components used in [Figma desktop examples ](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=624%3A0)

- [x] Selection controls
- [x] Ghost button
- [x] Icon
- [x] Menu (opened from ghost button)
- [x] Textfield
- [x] SingleSelect

**Comment by pomfrida** [comment]
🚧  [LIST WIP] We need to make adjustments to some of our input components to fit into the compact table.

**Checkbox**
Remove paddings from the span to fit compact
Pressed overlay height is 40px but compact table height is 32px

**TextField & Select**
Adjust height to fit compact
Empty label needed to fit to compact, can column name act as label for screen readers?

**Ghost button (for Menu)**
Height is 40px but compact table height is 32
