### ISSUE TITLE
As a user I would like to see FAQs in the storefront so I can get started with EDS

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#103]
something like this is a good placeholder for us :) 

https://dev.azure.com/equinor-design-system/_git/Equinor%20Design%20System?path=%2FStorefront%2F06-help%2F03-faq.md&version=GBmaster&_a=contents 
- Added text from wiki in GitHub, we will fill this out much later when we know what kinds of questions arise
 - looks good, maybe add, what is a design system, who built it and why

**Comment by mimarz** [comment]
Is this still relevant? @BeckyBrekke
