### ISSUE TITLE
Adjustable size on progress indicator

### ISSUE THREAD

**Issue by ErlendLygre** [equinor/design-system#1041]
**Problem**
I spend more time than I should coming up with custom loading state for buttons, textFields and inputs/selects such as Checkboxes. 

I'd like to use a circular progress indicator for some of this work, but more often than not, i cannot use it because of its size.

**Describe the solution you'd like**
I want the progress indicator (at least the indeterminate circular one) to work with a "size"-prop, such any other EDS-icon. 
That way I can insert it into Buttons and as helper text the same way i do with normal icons.

**Describe alternatives you've considered**
A loading prop on Button that would handle the loading state for me.

**Comment by mimarz** [comment]
Thank you for your request, I see that we have the same feature requested a while ago (#417) that somehow got lost 🙈 We'll bring it this feature request up at our next planning meeting next week and get back to you on priority 😊

**Comment by mimarz** [comment]
Great news @ErlendLygre 🎉

We have decided to have a look at this feature soon™️ #1061 so any more feedback or insight to use-cases would be appreciated :)

**Comment by mimarz** [comment]
@ErlendLygre  You mentioned the need for progress-indicators inside textfield and checkboxes. Is it possible for you to provide us with any examples of how this feature would/is being used?

**Comment by mimarz** [comment]
Ahoi @ErlendLygre !

We have added the option to adjust the `size` and `color` on progress indicators; `Dots`, `Circular` and `Star` 

Only `Circular` and `Dots` have been adjusted and tested for use inside `Buttons`. We haven't tested with `Textfield` yet as we have some other stuff in the pipeline for that component for our next "component-revision".

We still have some other issues that needs to be done, but hopefully we'll get this released soon :)
