### ISSUE TITLE
Support for tree-shaking in eds-core-react package

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1043]
Commonjs does not support tree-shaking when deconstructing values from a provided object.

This means that when, for example, `import { Button } from '@equinor/eds-core-react'` in a commojs project, it will import all the other components in the library regardless. 

Since Typescript still uses `commonjs` for modules, we should look into providing named paths for components.

Example of relative path: `import Button from '@equinor/eds-core-react/Button'`.

- [ ] Research/Analyse on how to solve this
- [ ] Check wether this can configured in rollup or not.

Notes: 
- https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking
- https://rollupjs.org/guide/en/#outputpreservemodules

**Comment by trylle** [comment]
We're seeing similar issues with the `eds-icons` package. Are you considering this solution there, as well?

**Comment by mimarz** [comment]
> We're seeing similar issues with the `eds-icons` package. Are you considering this solution there, as well?

We are! 
Although I see we didn't have an issue for it. 
Added it now #1539 :)

**Comment by trylle** [comment]
Would also like to mention that the EDS packages are currently some of the biggest dependencies in our frontend - just to give some idea of the scale of the problem.

![127 0 0 1_8888_](https://user-images.githubusercontent.com/1915817/131837769-55608bf2-ad2e-42ba-b8bd-be4a9a415b05.png)

**Comment by mimarz** [comment]
> Would also like to mention that the EDS packages are currently some of the biggest dependencies in our frontend - just to give some idea of the scale of the problem.
> 
> ![127 0 0 1_8888_](https://user-images.githubusercontent.com/1915817/131837769-55608bf2-ad2e-42ba-b8bd-be4a9a415b05.png)

Awesome! I have added your picture to the epic #1540 for some gravitas 💪

**Comment by wenche** [comment]
I did some testing today, and this is just way to complicated 😓 

While testing, I came across [this comment](https://github.com/vercel/next.js/issues/12557#issuecomment-865142966) by the author of Webpack. EDS do indeed use barrel files, and that seems to add an extra layer of complexity. What we see is that even if I change to actually use the esm version (since umd doesn't support three shaking) it is way to big. Did some experiments with the "sideEffect" key, but I think that's not enough since it's esm? I might have worked if it provided the transpiled source code instead of a bundle? 🤔  Did I mention that this is complicated... 
![Skjermbilde 2021-09-17 kl  11 38 30](https://user-images.githubusercontent.com/1568252/133761802-a8af74d3-59be-4fcc-b38b-6b2f81e7d0c0.png)

**Comment by mimarz** [comment]
> I did some testing today, and this is just way to complicated 😓
> 
> While testing, I came across [this comment](https://github.com/vercel/next.js/issues/12557#issuecomment-865142966) by the author of Webpack. EDS do indeed use barrel files, and that seems to add an extra layer of complexity. What we see is that even if I change to actually use the esm version (since umd doesn't support three shaking) it is way to big. Did some experiments with the "sideEffect" key, but I think that's not enough since it's esm? I might have worked if it provided the transpiled source code instead of a bundle? 🤔 Did I mention that this is complicated...
> ![Skjermbilde 2021-09-17 kl 11 38 30](https://user-images.githubusercontent.com/1568252/133761802-a8af74d3-59be-4fcc-b38b-6b2f81e7d0c0.png)

Nice find! I have seen several components libraries not bundling their files, but never understood why. So maybe this is why 🤔  So maybe some tweaks to rollup to not bundle and just transpile the Typescript could do the trick? 

Also curious if we need to add some additional pointers for named paths. For example we want people to access `@equinor/eds-core-react/Checkbox` but not `@equinor/eds-core-react/Checkbox/Input`.

**Comment by oddvernes** [comment]
> 
> 
> We're seeing similar issues with the `eds-icons` package. Are you considering this solution there, as well?

@trylle we have a `@next` release of eds-icons out with umd removed. Would be great if you have the opportunity to test it out before we release it proper

**Comment by trylle** [comment]
@oddvernes Hi, the new version of eds-icons seems to be working fine in our app.

## Stats for our main application bundle
### No icons
```json
"statSize": 12148100,
"parsedSize": 4524143,
"gzipSize": 1230447,
```
### eds-icons 0.6.2 (what we currently use)
```json
"statSize": 12429922,
"parsedSize": 4743578,
"gzipSize": 1299744,
```
### eds-icons 0.8.0-dev20211028
```json
"statSize": 12411516,
"parsedSize": 4534525,
"gzipSize": 1234371,
```

So, if I'm reading my `webpack-bundle-analyzer` stats properly, the new version of eds-icons is now taking just shy of 4kb gzipped in our application as opposed to 70kb. We use about 40 unique icons, so this seems quite reasonable. Our frontend is quite large, and efforts are still ongoing on reducing its size, so every little helps. 👍🙂

Is there any similar progress on eds-core-react?

**Comment by oddvernes** [comment]
We have released a @next version of eds-core-react with tree-shaking enabled
- Umd removed
- Esm is now unbundled (which enables the tree shaking)
- babel target have been changed to 'defaults, not IE 11' which makes for considerably more modern output with less polyfill bloat

**Comment by oddvernes** [comment]
Since we could not reliably include the focus-visible polyfill in this unbundled form, we decided to remove it and add native support for this instead, while retaining support for the polyfill so users can add it themselves if safari keyboard-navigation support is required in their app
