### ISSUE TITLE
Defined valid combinations of compact and comfortable mode.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1044]
Decide what combination should be allowed, and have design suggestions related to how the user can switch between different modes. 

Examples: 
All Compact
Table Only Compact
Other combinations ? 

Need to be aligned with  implementation.

**Comment by mimarz** [comment]
On planning meeting 19.01.2021 it was decided by @equinor/design-system that we will go for a global compact toggle on all components (that it makes sense to be compact) to avoid confusing when to use and not use compact vs. comfortable. We will recommend to have a global density switcher for toggling between comfortable and compact mode of a application.

**Comment by BirteThornquist** [comment]
Put up an example for a density switch [here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=4950%3A0). Used radio button select instead of toggle since we might include other density in the future. Please review @lucasveil

**Comment by lucasveil** [comment]
Good to go @BirteThornquist
