### ISSUE TITLE
Add example of table (data grid) in comfortable & compact mode

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1047]
Build some examples page use all the states of the table components to give clear guidelines to end users.

**Comment by lucasveil** [comment]
Prototype ready for review @BirteThornquist [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1191%3A0). I also added a first draft of compact application.

**Comment by BirteThornquist** [comment]
Looks good @lucasveil 👍 Maybe we should give an example of validation also?  In row edit mode, should none edible cells be visualized? Or just disabled on hover?

**Comment by lucasveil** [comment]
As agreed on meeting today with @BirteThornquist, in row edit mode, the disabled cell won't show unless you hover over it. 
We also see that the table model as used today should be kept and introduce data grid as a new component. Prototype is ready for testing.

**Comment by lucasveil** [comment]
Meeting session with IOC, OPT, Fusion and Marita 17th February

**Comment by lucasveil** [comment]
Tried to find [different solution](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1307%3A0) for disable state. Maybe the best solution is to show disable [only on hover](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1170%3A831)? What are your thoughts @BirteThornquist ?
