### ISSUE TITLE
Update hover state for the menu component to make it more readable for Universal Design

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1048]
As follow up to this [slack discussion](https://equinor.slack.com/archives/CJT20H1B9/p1607695321253400) it appears that the hover state of the menu component is not seen on a low contrast screen. For a better readability suggested action are:

- [ ] change the weight of the text
- [ ] update the navigation token

**Comment by lucasveil** [comment]
[Material Design](https://material.io/components/menus), [Carbon](https://www.carbondesignsystem.com/components/overflow-menu/usage) and [Altassian](https://atlassian.design/components/dropdown-menu/examples) uses the same pattern for menus.
And here is the [WCAG documentation
](https://www.w3.org/WAI/tutorials/menus/flyout/)

**Comment by BirteThornquist** [comment]
Ready for review @lucasveil. I added a new text style for Navigation/Menu Title hover in the design tokens [here](https://www.figma.com/file/0TbIXrrObWj80Cf7KucKYFL0/Design-Tokens?node-id=278%3A0) And used this new text style for the hover state of the Menu Item [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17627%3A3322)

**Comment by lucasveil** [comment]
Nice work. Approved for me @BirteThornquist
