### ISSUE TITLE
Get insight from designers using EDS and map the usage

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1049]
The design team needs insight on how designers uses EDS in context of:

- [x] Figma usage
- [x] use of documentation
- [x] component library
- [x] communication with EDS team

this mapping will help us define what is good, bad, missing and needs to be improved.

**Comment by lucasveil** [comment]
Ready for first review in Teams @BirteThornquist

**Comment by BirteThornquist** [comment]
Looking good @lucasveil! I wonder if it is a bit too long though...? Lets have a talk about it later today.
