### ISSUE TITLE
Storefront alternatives

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1051]
Due to challenges in operating today’s storefront alternatives should be investigated. 
Write at document with cost/benefit between AS IS solution and suggested (1 -3 alternatives) TO BE solutions. 
TO BE solutions can include product with licensing cost. If so, the document should compare this to the cost of building our self. 
PO should be involved in setting correct requirement to the TO BE solution.

**Comment by mimarz** [comment]
We have gone for Zeroheight
