### ISSUE TITLE
Architecture Contract

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1052]
Need to establish an AC for EDS. This should cover both information sites (e.g. Storefront / Storybook) and technical solutions including the React Components.

Ref. https://github.com/equinor/architecturecontract

**Comment by mimarz** [comment]
https://github.com/equinor/architecturecontract/pull/414

AC PR is up. Next are meetings for review.

**Comment by mimarz** [comment]
AC PR is merged in. Closing this issue.
