### ISSUE TITLE
Add compact variant to Button

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1053]

**Comment by BirteThornquist** [comment]
@lucasveil Button is updated with a density compact property and ready for review [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=18442%3A38076)

**Comment by lucasveil** [comment]
2 fails i found :( 
When the button is resized and in compact state: 
- Focus state doesn't scale
- Icon leading and trailing are not fixed as they should
Other then that, really good work!
![Screenshot 2021-02-16 at 12 14 34](https://user-images.githubusercontent.com/65652493/108055799-c0d7e100-7050-11eb-9f87-211698daafeb.png)
![Screenshot 2021-02-16 at 12 15 03](https://user-images.githubusercontent.com/65652493/108055803-c2090e00-7050-11eb-943b-c50df175692c.png)

**Comment by BirteThornquist** [comment]
I have fixed the two design bugs regarding focus border and leading/trailing icons @lucasveil. Ready for another review.

**Comment by lucasveil** [comment]
Perfect! @BirteThornquist
