### ISSUE TITLE
Add compact variant to Select

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1054]

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17793%3A67) @lucasveil.

**Comment by lucasveil** [comment]
Review took in a meeting :)

**Comment by BirteThornquist** [comment]
As discussed with @mimarz today there is an issue with hover going over the bottom line of the field. We will update the dimension of the hover and focus states for compact components.

**Comment by BirteThornquist** [comment]
Ready for review @lucasveil

**Comment by lucasveil** [comment]
Good to go @BirteThornquist

**Comment by mimarz** [comment]
Does not look like spacings on options got update for compact? @BirteThornquist
We changed it from `24px` to `8px` in this mornings meeting.
