### ISSUE TITLE
Add compact variant to Icon

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1055]
Use 16x16 icons instead of 24x24 for compact components

**Comment by mimarz** [comment]
Adjustments: 

Textfield: 
* Comfortable Input icon: 24px
* Helper icon: 16px
* Compact input icon: 16px

Search:
* Icons 24px

Accordion:
* Cheveron icon: 24px

**Comment by mimarz** [comment]
duplicate #1403
