### ISSUE TITLE
Add compact variant to Textfield

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1056]

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) @lucasveil .
I ended up not doing a compact version of the multiline field, felt it didn't make much sense...

**Comment by mimarz** [comment]
@BirteThornquist Looks like the compact version is using the wrong color on "input text" ( placeholder color text). It has `default` on comfortable enabled and `tertiary` on compact enabled.

**Comment by BirteThornquist** [comment]
I cannot see that @mimarz? The input text for both default and compact in Figma is tertiary...?

**Comment by mimarz** [comment]
> I cannot see that @mimarz? The input text for both default and compact in Figma is tertiary...?
ahh, yeah. I was looking at the colored ones; error, warning & success. They all seem to have the same issue...

**Comment by lucasveil** [comment]
Great job @BirteThornquist ! Variant are implemented well. My only concern is actually with the multiline. In compact, if you select multiline, the first line looses it initial height: ![Screenshot 2021-05-07 at 09.54.40.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/d765ce39-79f3-4188-936f-483afd18194b)

**Comment by BirteThornquist** [comment]
That's a good point @lucasveil. I'll create compact variants of the multiline as well 👍

**Comment by BirteThornquist** [comment]
> > I cannot see that @mimarz? The input text for both default and compact in Figma is tertiary...?
> 
> ahh, yeah. I was looking at the colored ones; error, warning & success. Only these seem to have this issue...

Good catch @mimarz. Fixed. There was also a mix between dark/light mode where secondary color was used in dark mode while default in light mode for both default/compact. Changed to primary color for both.

**Comment by BirteThornquist** [comment]
Ready for review [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) @pomfrida @mimarz

**Comment by mimarz** [comment]
> Ready for review [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) @pomfrida @mimarz

@BirteThornquist Looks good. Only the height was adjusted? Should be ok. 

With icon the field is very compact, but I guess we have to live with that 🙈

**Comment by BirteThornquist** [comment]
Yes @mimarz I agree about the icon. We decided to keep the icon size for now, but it could be we need to look into the icon sizes again...
