### ISSUE TITLE
Add compact variant to Menu

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1058]

**Comment by lucasveil** [comment]
Ready for review [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17627%3A3322) @BirteThornquist

**Comment by BirteThornquist** [comment]
Good job @lucasveil ! Two small adjustments:

The focus frame does not scale (prob just need another constraint)
![Skjermbilde 2021-05-07 kl. 13.00.45.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/3084218f-9989-4e50-8719-dfa208c69355)

Press overlay mask is missing
![Skjermbilde 2021-05-07 kl. 13.02.44.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/4f05121a-4910-4a66-87d9-57bad29b8aa8)

**Comment by lucasveil** [comment]
I fixed the focus for compact. It actually wasn't applied on default, so i fixed it there too.
Don't understand the overlay mask? I used the compact token so it looks smaller but still has the same functionality @BirteThornquist 
Can you have a check @mimarz to se if it implements well in code?

**Comment by BirteThornquist** [comment]
> I fixed the focus for compact. It actually wasn't applied on default, so i fixed it there too.
> Don't understand the overlay mask? I used the compact token so it looks smaller but still has the same functionality @BirteThornquist

You have to mask the compact overlay and straight shape tokens @lucasveil 
![Skjermbilde 2021-05-10 kl  08 30 07](https://user-images.githubusercontent.com/74531659/117615704-62f7f880-b16a-11eb-9819-cc3bd67f4b8b.png)

**Comment by lucasveil** [comment]
Oh ok, got it now :) Fixed now

**Comment by mimarz** [comment]
Looks like just spacing changes? Eitherway, looks good @lucasveil

**Comment by lucasveil** [comment]
Yes the spacing and the press overlay token (changed from default to compact) @mimarz
