### ISSUE TITLE
Build the components needed for the storefront

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#106]
- [ ] Navigation: Drawer (#164)
- [x] Search (#171)
- [x] Accordion (#150)
- [x] Chips (#156)
- [x] Divider (#157)
- [x] Icon component (#177)
- [x] Link (#158)
- [x] Lists (#159) 
- [x] Navigation: Tabs (#132)
- [x] Navigation: Top Bar (#166) 
- [x] Sidesheet (#173)
- [x] Table (#148)
- [x] Textfield (#146)
- [x] Typography (#149)

**Comment by mimarz** [comment]
We created a separate navigation drawer in storefront since navigation drawer is not finished yet #164 . Closing this issue
