### ISSUE TITLE
Select - items list to be triggered on stateChange outside Select component

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#1064]
**Is your feature request related to a problem? Please describe.**

Trying to use SingleSelect  , passing in an array of strings to items. 
However, this array is created during render, and when click on the SingleSelect, the pop-down list is empty. 
If I add a character (preferably 'a') in the SingleSelect field, the list populates, but not before. 
I´ve tried UseEffect in order to get a re-render when the array is populated, but this has no effect on the SingleSelect list. The only way I get the list populated is when the list is hardcoded  as a constant as in the example you show in the StoryBook. 

So I think this occurs because SingleSelect (or any of the EDS selects) does not trigger of state changes after initial render.

**Describe the solution you'd like**

The ability to pass in a list of items in Select which is created during render and stored in a useState variable, and control re-render with useEffect (as possible with material UI select.)

**Describe alternatives you've considered**
The workaround (not elegant) I need to do now to get the list populated is to delay render of the Select until I know that the items list is ready.
```
{displayFields.length > 0 && 
     <SingleSelect id={"fields"} label={"Fields"} items={displayFields} handleSelectedItemChange={onChangeFieldFilter} />
}
```

The solution I would like would be something like this:
```
useEffect(() => {
  if (fields) {
      const list = fields.map((field) => field.name);
      setDisplayFields(list);
    }
  }, [])};

return (
    <SingleSelect id={"fields"} label={"Fields"} items={displayFields} handleSelectedItemChange={onChangeFieldFilter} />
)
```
**Additional context**

**Comment by mimarz** [comment]
Thanks for reporting this! 

We'll have a look at soon as possible, question is if this is a bug or not, because you should be able to have dynamic content 🤔  Is the content for select fetch from somewhere asynchronously? 

If possible a codesandbox would be perfect for us to test against this specific use-case (instead of us trying to replicate 😅)
