### ISSUE TITLE
As a user a need to see info in the storefront regarding known issues and change log

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#107]
Under release information, there is a page for changelog and known issues. (PRI 2)
- [ ] Add a shell for known issues and add anything relevant - say no known issues if nothing Just need a placeholder shell page, - will calm people down seeing that we have a system ready for issues. 😊 ref:
https://www.carbondesignsystem.com/updates/release-information/known-issues
- [ ] We talked about adding a changelog, can't remember what to put it. We referenced the carbon one, but that no longer exists:  https://www.carbondesignsystem.com/updates/release-information/changelog

**Comment by mimarz** [comment]
We are using the Github changelog & release log for this in code and designers have meets and figma for this.
