### ISSUE TITLE
Research how to support canvas apps

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1079]
- [x] Create simple example in the EDS environment
- [x] Document procedure in issue

**Comment by vnys** [comment]
## Power Apps Studio

Canvas apps are created in a web app called [Power Apps Studio.](https://create.powerapps.com/studio/) (apart from Teams Power Apps mentioned below). The studio is connected to an environment, where the default in Equinor is “personal productivity”. We have our own EDS environment where we can experiment without wreaking havoc on other peoples apps. 

## Layout

It’s possible to create responsive Power Apps – but the default is either tablet or phone, in portrait or landscape mode. The size of the screen can be changed if a maker creates an app that targets full hd monitors for example, but the result will be that it scales down on smaller devices instead of adapting to the size of the viewport. Font-size in PowerApps is specified in typographic points (Pica points) and not pixels – with the default font-size being 13pt (17.34px) – so most of the Power Apps we’ve seen internally use quite large font sizes, which makes it possible to still read text on a layout that’s been scaled down on a smaller device, but the user experience is not optimal compared to proper responsive design.

## Components

There are two types of components in Canvas apps, the default canvas components and code components. Code components are authored in typescript, and can be based on any frontend library/framework such as React – but there are some caveats – the biggest one being that every code component will have it’s own copy of React. When it comes to canvas components, there’s a difference between classic components in the Power Apps Studio – and Fluent UI components inside Power Apps for Teams (see section about teams further down). 

## Source control

It’s possible to save a Power App as a .msapp file – which in essence is a zip-file. This file can be extracted using a tool called PASopa.exe (referenced in the blob post [“Source code files for Canvas apps”](https://powerapps.microsoft.com/en-us/blog/source-code-files-for-canvas-apps/)) – and the files can then be edited using a text editor, packaged back into an .msapp file, and opened in the studio again. That also means it’s possible to keep Power Apps under source control, and that we can modify the built in themes. 

## Power Apps in Teams

When creating PowerApps inside Teams, there are some differences from the normal PowerApps studio:

- Each team has a separate dataverse for Teams environment
- The app is responsible by default
- The design matches the Teams design
  - Default font-size is 10.5pt (14px) instead of 13pt (17.34px)
  - Uses Fluent UI controls instead of classic controls
  
The difference between the controls is interesting. There’s [a comparison that shows the differences][fluent] but one obvious difference is that the button component has button type prop (the choices are Primary and Standard) similarly to how variants are used in the EDS.). It seems impossible to get the fluent controls out of the Teams environment, so as far as I’ve found you can’t create an app in Teams and keep it under source control. 

[fluent]: https://docs.microsoft.com/en-us/powerapps/teams/use-the-fluent-ui-controls#difference-between-fluent-ui-and-classic-controls

## Theming

…

**Comment by pomfrida** [comment]
**Component Library in Canvas Apps:**
I've been testing this experimental feature and found some drawbacks that we can't ignore. We could use this library for some of our simpler components, but it will not fully support components with variants and actions.

_Action handlers:_
Custom components does not yet support any action handlers. This makes our components static and users will have to add their own invisible button on top of the EDS button to add custom action handlers. This approach will compromise the hover effects on the EDS button. 

_Color/variant prop:_
Not supported as we would expect, but hacks are possible. We will have to create a different component for each of the colors/variants. A custom prop with datatype 'color' is possible, but this one supports all colors and should be avoided. Variants such as "primary", "secondary", "danger" is needed to fully support EDS.

**Comment by vnys** [comment]
> …it will not fully support components with variants and actions

I think a solution to that would be something similar to Bulb Digital where there’s a hidden screen in the template where makers can copy button variations for example. The default button can be styled with global variables so that when makers insert a button it looks like the EDS primary button, but they would then have to copy a button from that screen if they wanted to use a variant.

**Comment by vnys** [comment]
This is what a button looks like in Power Apps for Teams: 

![image](https://user-images.githubusercontent.com/2081882/106909572-b63c5400-6700-11eb-9abb-d9e11af536f7.png)
