### ISSUE TITLE
Radix with EDS & frontend help analysis

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1086]
Call for workshop with Radix team member
Walkthrough of tech solution, and give feedback.

**Comment by mimarz** [comment]
We had a small walkthrough of radix with the radix team. Will have a closer look at the https://github.com/equinor/radix-web-console and give a rough technical review on how much work it would be to update.

**Comment by mimarz** [comment]
# radix-web-console

* Good separation of components, inspired by atomic design as components structure.
* Good separation of view and app-logic, uses MVVM patterns
* There is a lot of frontend infrastructure in regards to development of components and application
* View built using CSS ( with classNames) and React
* SPA using Redux + saga
* Big code base with many layers/files of used for seperation of concern 
* Good documentation on parts and ideas behind the architecture
* Lots of boilerplate code support an app and a seperate development-area for components
* Some tests

## 1. EDS design implementation  

### Effort: Medium - High

#### Notes:

* Some components can easily be updated to use EDS inside existing components (button, chip, breadcrumbs, spiner ++)
* Some components will need to have a bigger change affecting unknown amount of pages (form-field, clickbox)
* Lots of custom application specific components which would need to be re-designed and implemented in EDS style.
* ~21 pages will need to be tested and updated manually
* `app-` and `page-` prefixes are used for template/complex views, but may be other, might require more exploring
* ⚠️ EDS does not currently support theming, so a new solution will need to be found for coloring/differentiate different environments.
* ⚠️ EDS does not support darkmode which 


## 2. Typescript

### Effort: High

* Big big code base with a lot of files that needs to be changed
* Typescript is best used when all files are typescript file types
* Initially written in javascript can pose conversion challenges when converting to a strict data-type language
* Some libraries might have less than optimal typescript support, but the most used ones have good typescript support

**Comment by lucasveil** [comment]
Design journey i available [here](https://www.figma.com/file/WApDiHKFeOTM89b0c1Fbxj/Journey?node-id=0%3A1)
