### ISSUE TITLE
Refactor sub-component stories to use correct style

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1088]
Refactor the remaining stories we have with sub-components to use "story-style" we agreed upon.

"Story style":
* Don't deconstruct sub-component, use it directly in jsx. Example -> `<Table.Cell>`
* Use generic "wrapper" name on positioning components we make in story
* Prefer multiple stories instead of every example inside one story
* Make it as easy as possible to see the actual code inside `View code` panel. Even if it leads to more duplicating of some code
* Use as few custom `Wrappers` as possible

Todo:
- [ ] Identify remaining stories that does not follow the correct story style
- [ ] Refactor stories to correct style

**Comment by wenche** [comment]
Nearly all of the sub components were already updated. But the stories had a lot of other issues with inconsistency. 

So I added some more tasks to the issue.
