### ISSUE TITLE
As a user I want to view the icons in the storefront 

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#109]
For product and system icons. 
- [ ] Product icons>Library - Build icon viewer: The page should have its own search within in the page, and be organised by the groupings from Figma.
- [x] System icons>Library - Build icon viewer: The page should have its own search within in the page, and be organised by the groupings from Figma.
- [ ] Documentation QA on product icons library page
- [ ] Documentation QA on System icons library page

**Comment by mimarz** [comment]
Outdated with #1522
