### ISSUE TITLE
Add white variant of Circular Progress Indicator

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1092]

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=18442%3A38075 @lucasveil )

**Comment by mimarz** [comment]
@BirteThornquist When using the `moss-green`  color we have mostly refered to it as "primary" color other places, for example buttons and textfield. 

When we implement these color variants in code we need a set of color values for our users to choose from. In this use-case, should that be `primary` and `white` (+ `danger` for dots?)

![image](https://user-images.githubusercontent.com/1070981/106272051-b506b500-6230-11eb-893c-9e75c8eabfea.png)

**Comment by BirteThornquist** [comment]
Primary and white sounds good to me @mimarz 👍

**Comment by vnys** [comment]
Using colour names in properties does not take theming into account 🎨 Why not use the neutral name as suggested above? Primary, neutral and danger for example?

**Comment by mimarz** [comment]
> Using colour names in properties does not take theming into account 🎨 Why not use the neutral name as suggested above? Primary, neutral and danger for example?

@vnys @BirteThornquist 

Hmm, good point, but is white really a color? What school of belief do we run with here? Do we believe in the light? huehuehue... 🤪 

Maybe `primary`, `neutral` and `tertiary`? 
`danger` feels so connected to validation in a way...

I see we are already using `green` and `white` in `DotsProgress` which needs to be fixed... but all this relates back to #801  🙄

**Comment by vnys** [comment]
>  …is white really a color?

No, it’s just a figment of imagination like everything else in this world 😜

My point is that ⚪️ will be ⚫️ in dark mode 😎 So then it doesn’t make sense to call it white…

**Comment by BirteThornquist** [comment]
Absolutely, my bad. We should not reference color by name only. I like the suggestion of primary, neutral and tertiary. I will fix this in the dots as well. When it comes to the transparent white used for the circle, we have a 20% transparent white token which we can use; Interactive/Pressed Overlay/Light.

**Comment by mimarz** [comment]
> Absolutely, my bad. We should not reference color by name only. I like the suggestion of primary, neutral and tertiary. I will fix this in the dots as well. When it comes to the transparent white used for the circle, we have a 20% transparent white token which we can use; Interactive/Pressed Overlay/Light.

Righto, will update color names.

Is it safe to use the "Interactive/Pressed Overlay/Light" color token? Is is semantically correct? In case we change pressed overlay light color in future to something else, this might result in an unwanted side-effect 🤔

**Comment by lucasveil** [comment]
Good to go @BirteThornquist
