### ISSUE TITLE
Accordion - return <> if props hidden is true

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#1102]
**Is your feature request related to a problem? Please describe.**

We use the accordion component in a hierarchy context where the DOM gets very lagre if all elements are expanded. To reduce the size of DOM we start out with having the components collapsed. 
However the Accordion as by now does not take this into account and renders  the whole DOM structure, which affects the responsiveness of our web app significantly.

**Describe the solution you'd like**
Accordion needs to check the hidden props and retur <> if true

**Describe alternatives you've considered**

The solution is fairly simple. Accordion should return <> if property hidden is true. 
My colleague Tor Christian will create a PR with a solution :-)

**Comment by mimarz** [comment]
Thanks for providing us with this feedback! Looking forward to a PR from your team with a proposed solution 😃

**Comment by cbuv** [comment]
I've a similar issue on performance when children is hidden.
I think AccordionHeader's toggleExpanded (should be named onToggleExpanded) will solve this issue. 

Its hidden from storybook but still a part of the components api. 
Am I correct to assume that toggleExpanded is broken?

**Comment by mimarz** [comment]
> I've a similar issue on performance when children is hidden.
> I think AccordionHeader's toggleExpanded (should be named onToggleExpanded) will solve this issue.
> 
> Its hidden from storybook but still a part of the components api.
> Am I correct to assume that toggleExpanded is broken?

I am not aware of a bug with `toggleExpanded`, could please submit a [bug issue](https://github.com/equinor/design-system/issues/new/choose) with steps to reproduce and expected behaviour? Sandbox example would be perfect :)

**Comment by mimarz** [comment]
@marmid74 We released a `onToggle` callback to help with defering rendering when using `Accordion` in [eds-core-react@0.8.5](https://github.com/equinor/design-system/releases/tag/eds-core-react%400.8.5). This should help solve your challenges here :)

**Comment by mimarz** [comment]
Closing this issue as we have not gotten a reply in two weeks.
