### ISSUE TITLE
Label as separate React component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1107]
notes #1015

**Comment by wenche** [comment]
Add an example in Storybook about aria-label for TextField without visible label

**Comment by wenche** [comment]
One obvious shortcoming of the current Label component @mimarz  is that you can't use it to wrap an input component.
```
<label>
  <input>
</label>
```
I don't know if we should fix this as well or delay this? 🤔

**Comment by mimarz** [comment]
> One obvious shortcoming of the current Label component @mimarz is that you can't use it to wrap an input component.
> 
> ```
> <label>
>   <input>
> </label>
> ```
> 
> I don't know if we should fix this as well or delay this? 🤔

Don't we put children inside a `label` element inside `Label`? 😅

**Comment by wenche** [comment]
Nope, only the label text and meta

**Comment by wenche** [comment]
I think my vote goes to fix it (if it's a low hanging fruit). If we are supposed to reuse the `<Label>` component for selection controls we're gonna need it anyway 🤷‍♀️

**Comment by wenche** [comment]
It was not a low hanging fruit, more like in the middle of the tree or something 😓  Beyond adding the `children` we need to rethink the styling. My suggestion would be to keep it like this for now, and attach the problem more holistically when we do the selection controls.
