### ISSUE TITLE
As a user I need guidelines in the on language choice and consistency

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#111]
Fonda: I think that this section, the glossary tab, could actually just easily merge into the **Patterns** sections. And that with time, when there are too many or there is a need to highlight 'terms' that we pull it out to be it's own page. I worry now that there are just sooo many pages to take it. 
Fonda:  I have been and am getting lots of questions about it we will have a 'Language Consistency' page. Not like the page we talk about for writing documentation - but something more like "We always use the term 'Save' or such" like this page: https://www.carbondesignsystem.com/guidelines/content/glossary
Might not be something that we get out in the first MVP, but I think it is a good idea and something we can make a page for and add notes to as we think/come across things. 
Common actions - words/verbs that match icons 
Examples for overview tab: 
- Voice + Tone
     Capitalisation
     Verb tense
- Data formats
     Date formats
     Date range
     Number formats
- Liquid volumes
     Gross and net volume
     Volume units
     Operational, capacity and accounting units
     Changes in density
- Types of measurement
***** All standard, unless project has own domain standard. 
- [ ] Decide if this page should go under patterns or under Guidelines > content page - glossary and overview  tabs  
- [ ] Write the content
- [ ] QA documentation

**Comment by mimarz** [comment]
Outdated
