### ISSUE TITLE
New Hero image for Zeroheight landing page

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#1116]
See how we best can create the landing page for Zeroheight given the limited (at the moment) design features you have.

- [x] Logo image - top left. Yes/no?  Create something new here? EDS icon. This is how users return to the landing page. 

- [ ] Hero image for top part of landing/cover page. 

- [x] Page body - what to show here? Any links to other pages?

**Comment by BeckyBrekke** [comment]
Assigning to Bente - limited formatting options for the cover page, but we have agreed to have a new hero image here.

**Comment by benteljones** [comment]
![Skjermbilde 2021-11-16 kl. 19.23.09.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/7a81ffae-0411-4473-80bf-3b5428eba85b)

**Comment by vnys** [comment]
Looks great! 🤩
