### ISSUE TITLE
Add density compact to selection controls

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1117]
Add compact variant to switch and radio selection controls

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=18442%3A38076) @lucasveil. For the switch control I decided to skip compact variant on the medium slider one, and only add it for the small toggle one. Do you agree?

**Comment by BirteThornquist** [comment]
@lucasveil I made some changes to the use of color for small switch (resting, focus, hover and pressed). Today the same color is used for on/off, I suggest to use the text/static icons/secondary color to signal off.  Agree? If so I´ll go ahead and change the colors for density/default as well.

**Comment by lucasveil** [comment]
Really good with the color changing! Good to go for me @BirteThornquist
