### ISSUE TITLE
Spike CSS variables

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#1118]
Spike the use of CSS variables for theming.

**Comment by wenche** [comment]
### Suggested approach

1. Focus on color variables first
2. Replace each color token in the components with color: `var(--eds-AccordionHeader-disabledColor, var(--eds_interactive_disabled__text, ${headerColor.disabled}));` where the first variable is for future compatibility, the second is the global variable name for theming somehow exposed from EDS library and the last is token name. This ensure compatibility with the current way things work, making it possible to do the change on the development branch.

**Naming format on global variables**
- No color names in the variables
Yes: 👍 
--eds_text_static_icons__default: rgba(61, 61, 61, 1);
--eds_text_static_icons__secondary: rgba(86, 86, 86, 1);
--eds_text_static_icons__tertiary: rgba(111, 111, 111, 1);
--eds_interactive_primary__hover_alt: rgba(222, 237, 238, 1);
--eds_interactive_secondary__highlight: rgba(213, 234, 244, 1);

No: 👎 
--eds_infographic_substitute__blue_sky: rgba(82, 192, 255, 1);
--eds_infographic_primary__moss_green_100: rgba(0, 112, 121, 1);

**To be decided:**
How much work will it take to change the CSS variable names to something along the SuitCSS format
```
:root {
  --ComponentName-backgroundColor
  --ComponentName-descendant-backgroundColor
  --ComponentName--modifier-backgroundColor
  --ComponentName-onHover-backgroundColor
  --ComponentName-descendant-onHover-backgroundColor
}
```
It will probably be easiest if we change the color names in the components first, then do a search-replace substitute with the new variable names. Otherwise we'll have to "translate" the variables when we rewrite, making the task a lot more error prone.

**Comment by vnys** [comment]
> How much work will it take… ⏳

I suggest rephrasing that question a bit – the important thing here is what’s the best naming convention for the CSS variables, we are going to have to live with this decision for a while. It’s inevitable that some work will have to be done in the Figma Broker, but I don’t it’s that much.

**Comment by wenche** [comment]
Discussed it even more... New suggestion is, to reduce complexity and focus on one thing at the time, to limit the first step to just add the css variable with the current naming pattern. Then we could rename or add another css variable by search-replace at a later stage. So

1. Focus on color variables
2. Replace each color token in the components with `color: var(--eds_interactive_disabled__text, ${headerColor.disabled});`

**Comment by vnys** [comment]
> …at a later stage…

That spells “technical debt” to me. Why not just do it now that we’re working on it? I think we have more than enough things we’ll do at a later stage…

Also, adding a locally scoped variable as a hook for later costs nothing at this point but requires yet another round if we postpone it.

**Comment by mimarz** [comment]
> ### Suggested approach
> 
> 
> 
> 1. Focus on color variables first
> 
> 2. Replace each color token in the components with color: `var(--eds-AccordionHeader-disabledColor, var(--eds_interactive_disabled__text, ${headerColor.disabled}));` where the first variable is for future compatibility, the second is the global variable name for theming somehow exposed from EDS library and the last is token name. This ensure compatibility with the current way things work, making it possible to do the change on the development branch.
> 
> 
> 
> **Naming format on global variables**
> 
> - No color names in the variables
> 
> Yes: 👍 
> 
> --eds_text_static_icons__default: rgba(61, 61, 61, 1);
> 
> --eds_text_static_icons__secondary: rgba(86, 86, 86, 1);
> 
> --eds_text_static_icons__tertiary: rgba(111, 111, 111, 1);
> 
> --eds_interactive_primary__hover_alt: rgba(222, 237, 238, 1);
> 
> --eds_interactive_secondary__highlight: rgba(213, 234, 244, 1);
> 
> 
> 
> No: 👎 
> 
> --eds_infographic_substitute__blue_sky: rgba(82, 192, 255, 1);
> 
> --eds_infographic_primary__moss_green_100: rgba(0, 112, 121, 1);
> 
> 
> 
> **To be decided:**
> 
> How much work will it take to change the CSS variable names to something along the SuitCSS format
> 
> ```
> 
> :root {
> 
>   --ComponentName-backgroundColor
> 
>   --ComponentName-descendant-backgroundColor
> 
>   --ComponentName--modifier-backgroundColor
> 
>   --ComponentName-onHover-backgroundColor
> 
>   --ComponentName-descendant-onHover-backgroundColor
> 
> }
> 
> ```
> 
> It will probably be easiest if we change the color names in the components first, then do a search-replace substitute with the new variable names. Otherwise we'll have to "translate" the variables when we rewrite, making the task a lot more error prone.
> 
> 

After doing some research and looking at how others do it, the first suggested approach looks like the best.

- - My only worry is the component css-variable naming. As @vnys mentioned, whatever we go for here, we have to live with. That said, its not something we need to officially expose/advertise as a festure, so changing name is still possible

I think we should ship the library with included eds-tokens css-vars on root level.

I suggest we try spike/refactor an actual component to use css-vars and look how that feels

**Comment by wenche** [comment]
We don't want to merge this PR into develop, but it can be used for future reference 👍
