### ISSUE TITLE
GRID: As a designer I need to review the suggestions from Figma/documentation QA 

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#112]
- [ ] Review suggestions/comments
- [ ] Decide if adjustments should be made
- [ ] Update documentation/Figma accordingly
- [ ] Perform documentation QA
Input from Ørjan Blytt Polden:
- The Grid/Small layout appears to be using a 12-column layout. Is this intentional? Not entirely sure if 12 columns would be necessary on a 600dp display.
- I'm also missing an X-Small grid, for working with designs all the way down at 320dp. This is entirely my own opinion, as I'd normally be using a 4-column layout at that size.
- As a lead-in into the guidelines, it is stated that it is the designer's responsibility to define a maximum width and choose the correct grid.
- Should it be stated more clearly that this is because the grid styles are all fluid?
- It feels as though the introducing guidelines are missing a clear overview of what grids are present and what screen sizes they are intended for. This is instead listed under Grid Columns, which itself does not actually list the grid columns.
- The point on Grid Influencers feels unclear. Would consider rewording to give more direct instructions to the reader.
- The documentation for Usage of the Grid component start off with instructions for adding a frame to the current page (Step 1.), but go from there directly to the settings for that panel.
- Perhaps Step 1 could be changed to assume the user already has a frame placed, with a sub-point stating that different frames can be found by pressing A or F?

**Comment by mimarz** [comment]
Is this still relevant? @BeckyBrekke

**Comment by mimarz** [comment]
@BirteThornquist will read through this and decided if we still need to do this

**Comment by lucasveil** [comment]
Outdated because of EDS 2.0
