### ISSUE TITLE
AccordionHeader toggleExpanded is broken

### ISSUE THREAD

**Issue by cbuv** [equinor/design-system#1120]
**Describe the bug**
AccordionHeader toggleExpanded does not work when it's used with Accordion and AccordionItem. 

**Steps to reproduce the bug**

1. see codesandbox (paste example from storybook in codesandbox)

**Expected behavior**
click on AccordionHeader should fire callback

**Specifications**

- Version: 
- Browser: 
- OS: 

**Additional context**
https://codesandbox.io/s/elastic-montalcini-bwg36
#1102

**Comment by cbuv** [comment]
I've looked more into this and possible solution is to don't mix the internal state with external props. 
Rename public toggleExpanded to onToggle (optional), and call this method in AccordionHeader onClick and onKeyDown should resolve this issue.

**Comment by pomfrida** [comment]
Thank you @cbuv for reaching out to us. We will take a look. But it looks like you have a solution here, if you don't mind opening a PR with your solution we would very much appreciate the contribution. 🥇
