### ISSUE TITLE
Storybook crashes when changing certain controls

### ISSUE THREAD

**Issue by yusijs** [equinor/design-system#1128]
**Describe the bug**

If you type something into the "inputIcon" control for [TextField](https://eds-storybook-react.azurewebsites.net/?path=/story/components-textfield--default) (e.g $) and hit backspace, it replaces the value with an empty object, and crashes the storybook

Happens for inputIcon and helperIcon. Some of it also happens with value (although that just sets the displayed value to [object Object] ). Seems to be storybook being a mess, but perhaps the icon-controls could just have a few pre-defined to select from instead?

**Steps to reproduce the bug**

1. Open https://eds-storybook-react.azurewebsites.net/?path=/story/components-textfield--default
2. Find "inputIcon" control
3. Type $
4. Hit backspace

**Expected behavior**

Should not crash.

**Specifications**

- Version: Storybook
- Browser: Chrome
- OS: MacOS Catalina

**Additional context**

![image](https://user-images.githubusercontent.com/11261560/108826694-e7ec6080-75c4-11eb-9c89-56e246f96285.png)
![image](https://user-images.githubusercontent.com/11261560/108826726-f33f8c00-75c4-11eb-9966-eb26475c9821.png)

**Comment by mimarz** [comment]
Thanks for reporting this! 

We are currently working on refurbishing our `Textfield` component, and in that regards we are having a look at the "unit" placement, so we'll make sure to test for this use-case and when we are having a pass at that part of the code in #1111 😁

**Comment by wenche** [comment]
This will be fixed in #1152
