### ISSUE TITLE
Assess use of Meta in Textfield & Select

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1131]
We have "meta" in Textfield label, and unit now. In a lot of uses-cases only unit is used and meta feels excessive. 

In making things more clear and simpler to use for our users we should assess use of meta

**Comment by BirteThornquist** [comment]
After a quick check we see that unit is used a lot, so the question is if we can go ahead and remove 'meta'. That would mean that if a designer use meta and has not detached the component from EDS, we would remove this info from their design. 
It will of course be important to inform our users in good time upfront if we go ahead and remove it.

Another question is if meta could be useful (in addition to unit). One scenario could be for character counts for instance; 
![image](https://user-images.githubusercontent.com/74531659/109953148-f3840980-7cdf-11eb-9ad7-0c08213ab882.png)
Then again, we sometimes have to draw a line to keep things more simple.... Any thoughts?
