### ISSUE TITLE
Data visualization color scheme options

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1133]
We had a kickoff meting about this this week, me, Lucas, Birte and Bente.
This is linked to the original Power BI request: https://github.com/equinor/design-system/issues/980#issue-767855237
We need some data visualization color palette options and guidelines on when and why to use which one - one with colors in the same color family, one with very distinguishable colors, maybe one for the different products (oil, gas, etc)

**Comment by BeckyBrekke** [comment]
Will get feedback from Bente Ljones this week. 
I will also make a file where we can test out the different colors in Power BI and see how they act in different visualizations.

**Comment by nilsml** [comment]
@BeckyBrekke is this in progress still perhaps?

**Comment by BeckyBrekke** [comment]
Not sure what the official status should be. Based on reviewing the work done in #1133, Birte and I have agreed on re-work in Power BI /zeroheight, so the one I have in progress with updates is this one:
Power BI EDS template - additional color examples<https://app.zenhub.com/workspaces/equinor-design-system-604f57c09e350a0011b654f4/issues/equinor/design-system/980>
