### ISSUE TITLE
Rewrite logic for full width media in <Card>

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#1141]
The Card's Media sub component provides an option `fullWidth`. Unfortunately the way [this is implemented ](https://github.com/equinor/design-system/blob/c6433df9f32fbb2c88bca0e768eda58940551baf/libraries/core-react/src/components/Card/CardMedia.tsx#L19)makes it less useful for aspect ratio / placeholder techniques for responsive images and also makes it hard to use other things than` <img>` inside Media. 

The fullWidth width is calculated to beyond 100%
![Skjermbilde 2021-03-01 kl  13 07 41](https://user-images.githubusercontent.com/1568252/109495168-30a58d00-7a8f-11eb-9692-0bf46572abb4.png)

A better solution would probably be to use grid columns, since the Card component already is a grid.

**Comment by laliq** [comment]
Create new `Card.Content` and swap it with `Typography`? Will it bring better control over Card component when it comes to padding, margins, grid and so on?
