### ISSUE TITLE
Update Banner in Figma. 

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1143]
Figma is not updated based on all decided variants.

- [ ] Add missing variants/colors  
- [ ] Validate icon colors 
- [ ] Conform on color names/types. Do we follow buttont color style or card color style?

Need to coordinate with how it is implement. 

Examples: https://eds-storybook-react.azurewebsites.net/?path=/docs/components-banner--default

**Comment by lucasveil** [comment]
I updated the color of the icon from energy red to moss green.

**Comment by benteljones** [comment]
I have some color suggestions ...

**Comment by BirteThornquist** [comment]
Closing this since we will have an updated banner in 2.0
