### ISSUE TITLE
Support proper validation errors in TextField

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#1145]
While working with the `TextField` component, we realized that the way helperText is implemented don't work with proper validation error feedback for screen readers.

We need support for aria-required and aria-valid and a way to link the actual error message to the input field by aria-describedby. It might be easier if the validation error and icon is a separate sub component, but how do we solve that it's also used for information messages 🤷‍♀️ 
It might also be easier to use the validation features with an external forms library if it's a separate component. 

Take a look at the `Checkbox` form example in the Storybook where react-hook-form is used for some inspiration and guidelines.

**Comment by mimarz** [comment]
Prioritzing this due feedback and its severity.

**Comment by oddvernes** [comment]
Is aria-required needed? [This](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute) says **Note**: HTML also specifies the `required `attribute which is supported well in user agents. Use `aria-required` for backwards compatibility only.

`Required ` works and is read by screenreader

**Comment by vnys** [comment]
If `required` works I suggest we use don’t use `aria-required`. The general rules for aria-attributes is to only use them where it’s necessary, if it can be solved with html then that’s better.

**Comment by wenche** [comment]
Native required used to have a lot of issues with form libraries and also didn't play well with custom form styles and behaviour. But that might not longer be the issue? 🤷‍♀️

**Comment by oddvernes** [comment]
Well both required and aria-required gets correctly applied to the input element either way as is
