### ISSUE TITLE
Figma "In the File" prep

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1147]
Figma has asked us to hold a one hour session for "In the File". Mickey and Lucas will do this, Rebecca to help. 
We need to estimate the prep time and come back to Figma with a date.

**Comment by BeckyBrekke** [comment]
I wrote to Figma and said that we were looking more at May/June for this since we are working on things that need to be finished for the demo. 
I said we could check in April some time. They said that was fine.

**Comment by mimarz** [comment]
Should put this back to the backlog @BeckyBrekke ? We got our hands full till Christmas... 🙈
