### ISSUE TITLE
Create Table Data Grid component

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1150]
Create new component for Table Data Grid

- [x] Create all states
- [x] Adjust size left and right
- [x] Documentation
- [x] Examples

Example #1047

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist . New component [here](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=20264%3A10826) and documentation / examples [here ](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1425%3A23308). One idea is to present a disable color state only if you have read/edit mode in a table. Not sure if this a good way to go.

**Comment by BirteThornquist** [comment]
Great job @lucasveil! Looking good. One small thing; the text color for Header/Disabled is different in default and compact density. Else 💯

**Comment by lucasveil** [comment]
Could you check my comment in figma for the disable state @BirteThornquist ?

**Comment by BirteThornquist** [comment]
✅

**Comment by lucasveil** [comment]
Can you have a last check in the [file](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1425%3A0) @akvam?
