### ISSUE TITLE
Update pagination with auto layout

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1151]

**Comment by BirteThornquist** [comment]
I added auto layout to the numbers frame in the component. I also fixed the colors in dark theme since some colors were the same as in light theme and others were a mix. Please review [here ](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=18442%3A38077)@lucasveil

**Comment by lucasveil** [comment]
Tremendous and epic job @BirteThornquist !!! Well done :)
