### ISSUE TITLE
Show tooltips with a delay

### ISSUE THREAD

**Issue by doctorplop** [equinor/design-system#1154]
Currently the EDS tooltip show up immediately, which can be distracting.  We believe that the user experience would benefit from delayed tooltips.  Desktop operating systems typically also use a delay before showing tooltips.  Material-ui tooltips support a "enterDelay" and "leaveDelay" parameters to control this behaviour.

**Comment by pomfrida** [comment]
Thanks for contributing with a feature request @doctorplop! 🎉  We're currently doing a makeover in [Tooltip](https://github.com/equinor/design-system/pull/1113), a delay is functionality you'll be able to add yourself once this is merged.  We'll also add an extra example on how to do this delay. (I think it will be similar to [Popover's](https://eds-storybook-react.azurewebsites.net/?path=/docs/components-popover--activation-types) hover example).
