### ISSUE TITLE
(Option) to automatically open the list of items on select / focus for Select

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/design-system#1165]
**Is your feature request related to a problem? Please describe.**
When I click on the `SingleSelect` component, the available items do not show until I click `down`, or click on the dropdown icon.

**Describe the solution you'd like**

I'd like to have the option to open the list of items automatically  when I click on the component to search.

**Describe alternatives you've considered**

I've considered triggering the function with the `onSelect` event, but I wasn't able to find a simple / non-hacky way to do it.

**Additional context**

**Comment by mimarz** [comment]
Thanks for suggesting this feature! 

We have planned a few improvements and tweaks for Select-components in the not to far future, so maybe we can get this done then as-well :)
