### ISSUE TITLE
Improve snackbar centering

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1172]
Using pixels as default for centering an element is bad pratice. 

Use dynamic values such as, 50% or 50vw

Using just left makes placement wrong. Use portals on body instead?

**Comment by pomfrida** [comment]
Dynamic value was already set; `left: 50%` and `transform: translateX(-50%)` but it's the `iframe` Storybook uses that makes it seem like the position is off. 

We also have the prop `leftAlignFrom` which defaults at `1200px`, so larger screens will get a left aligned Snackbar. Should we increase the default here?

**Comment by mimarz** [comment]
> Dynamic value was already set; `left: 50%` and `transform: translateX(-50%)` but it's the `iframe` Storybook uses that makes it seem like the position is off.
> 
> We also have the prop `leftAlignFrom` which defaults at `1200px`, so larger screens will get a left aligned Snackbar. Should we increase the default here?

Maybe using `vw` unit for `left` positioning in css would work better then 🤔
