### ISSUE TITLE
Clarify tooltip examples

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1174]
Remove examples of using tooltip on buttons (as its against [guidelines](https://eds.equinor.com/components/tooltip/) 🙈)

Also add delay on open, to fix feature request #1154

**Comment by pomfrida** [comment]
Why are we even allowing tooltips on disabled buttons when guidelines clearly say to not use tooltips on buttons with text 😆  Is it only for ghost icon buttons?
