### ISSUE TITLE
Optional label on multiple checkboxes stacked under a label header

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#1180]
Feature request from Slack channel:
I am required to pass in an empty string as label, even though my checkboxes are stacked beneath each other under a single label header. Should the label be optional to support cases where checkboxes arent individually labelled?

We should look into how this affects accessibility

**Comment by ErlendLygre** [comment]
Thanks for making the request Frida :)

Just to be clear: I was passing in an empty label, falsely thinking the "name" attribute would be the equivalent of an accessability label.

The reason I would want the option to hide labels, is so I don't have to override the internal label CSS of the Checkbox component with "visibility: hidden" whenever they're in a table/stacked layout.

**Comment by pomfrida** [comment]
Hi @ErlendLygre, optional labels are delivered in the next [release](https://github.com/equinor/design-system/releases/tag/eds-core-react%400.13.0) so I'm closing this issue. You can find the next release under the `next` tag (`@equinor/eds-core-react@next`).
