### ISSUE TITLE
New icons for Echo project: panoramic images, boundary select and invert model

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1189]
For ECHO project, new set of icons that needs EDS implementation.

**Comment by lucasveil** [comment]
Draft from ECHO Designer

![Screenshot 2021-03-29 at 12 51 11](https://user-images.githubusercontent.com/65652493/112826564-73a65080-908d-11eb-9bfb-2c3e7747b022.png)

**Comment by lucasveil** [comment]
Icons are now applied to grid and ready for review [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=2098%3A124348) @BirteThornquist

**Comment by lucasveil** [comment]
After discussion with the Echo team, we won't be implementing the 360 icon.
But will implement "inspect" icons.
Screenshot of the icons in use for Echo: 
![Screenshot 2021-07-02 at 16.21.54.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/50d9512f-d913-45f7-9a93-7943fc29fcb6)

**Comment by BirteThornquist** [comment]
Good to go @lucasveil !
