### ISSUE TITLE
Add possibility to place icon to left side of input for TextField

### ISSUE THREAD

**Issue by chormaz** [equinor/design-system#1209]
We would like to have the possibility to display TextField icon to the left side of the input. 
The image shows a TextField of type Search. We would like to have a prop to place the filter-icon on the left hand side.
![table](https://user-images.githubusercontent.com/78788930/114159690-56437300-9926-11eb-9ace-79740308400f.png)

**Comment by mimarz** [comment]
Thanks for reporting this! 

We have this in our inbox now and we'll try to have a look at it in not to long :)

We are currently focused on releasing core-react@v0.10.0 (#1163) so I won't be until after that (as both devs and ux need to weigh in on this feature-request) :)

**Comment by mimarz** [comment]
This will be solved as part of #2336

**Comment by oddvernes** [comment]
This was solved by #2336. A user can now add icon to the left side of an `Input` with the `leftAdornments` prop
