### ISSUE TITLE
Clean up usage of import React in libraries

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1222]
We have a few conflicting linting rules with `react` not having a default export which forces us to ignore linting to check if modules have no default export. This can cause unwanted errors in the future if we introduce new libraries or existing ( popperjs, downshift, ramda etc) change their apis.

Either we change the remaining imports the cause errors to `import * as React from 'react'` or just remove `react` imports all together as they are not needed in React 17 anymore.

Notes: 
* https://javascript.plainenglish.io/react-17-new-jsx-transform-c6f983f3464d

**Comment by Serjeel-Ranjan-911** [comment]
@mimarz so in short you want all the import React from "react" statements to be removed? is that it?

**Comment by mimarz** [comment]
> @mimarz so in short you want all the import React from "react" statements to be removed? is that it?

Thats correct, we do however need to still need to import react util functions (`useEffect`, `useState`, `useRef` etc..) where they are used. 

Its just the default `React` import we no longer need with v17 :)

**Comment by Serjeel-Ranjan-911** [comment]
yes yes that will be taken care.

**Comment by mimarz** [comment]
Nice! 

You will probably have to add this rule exception to our [eslintrc.js](https://github.com/equinor/design-system/blob/b2045bb8e1b0149be02211f74dd63e284ab9d442/.eslintrc.js#L115) file when you start working on this.
```javascript
   'react/react-in-jsx-scope': 'off',
```
