### ISSUE TITLE
As a Product Owner I would like to know the prosess for how others can contribute to creating React Components (for Desktop)

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#124]
- [ ] Define contribution process (a way to contact us is good enough
- [ ] Update Storefront with this information: https://github.com/equinor/design-system/tree/develop/apps/storefront/src/content/contributing
- [ ] Inform about our process on Slack 
- [ ] Describe "how to implement React Components" for EDS (if we think we need this now - copy from old board)
- [ ] Need backend/infrastructure setup?

**Comment by mimarz** [comment]
Outdated as most components are created
