### ISSUE TITLE
Fix bug in Desktop App example for dark mode

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1250]

**Comment by BirteThornquist** [comment]
Components are displaced, icons are missing and the labelling is not correct.

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=2311%3A8210) @lucasveil

**Comment by lucasveil** [comment]
Looking good @BirteThornquist
