### ISSUE TITLE
Conform Popover tokens

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1265]

**Comment by pomfrida** [comment]
Done but a few adjustments needed after #1295

**Comment by nilsml** [comment]
Hadde vært nyttig med noe mer tekst/kommentarer på dette kortet for å skjønne hva oppgaven går ut på og hvorfor den er blokket.

**Comment by nilsml** [comment]
Her hadde det vært fint med noe mer tekst om hva oppgaven går ut på og hvorfor den er blokket.
