### ISSUE TITLE
As I designer I need a date picker as part of EDS.

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/design-system#127]
- [x] Create component in Figma 
- [x] Add to component status (under construction)
- [x] QA Figma component
- [x] Create documentation 
- [x] QA documentation 
- [x] Update component status
- [x] Create issue for development #476

**Comment by benkeq** [comment]
@BeckyBrekke Do you have time to do QA of [this](https://github.com/equinor/design-system/blob/documentation/apps/storefront/docs/components/date-picker/overview.mdx)?

**Comment by BeckyBrekke** [comment]
Sure!

**Comment by mimarz** [comment]
Done
