### ISSUE TITLE
Zeroheight - switch over eds.equinor.com

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1282]
- [ ] Post about the new storefront in Slack when it has been moved.

**Comment by BeckyBrekke** [comment]
Not going so well - have IT support from Equinor and zeroheight helping.

**Comment by BeckyBrekke** [comment]
New RITM opened with the correct group to help this time.

**Comment by BeckyBrekke** [comment]
Certificate is in place - waiting for IT support to redirect eds.equinor.com to zeroheight.com

**Comment by vnys** [comment]
Internal DNS still points to the old storefront

**Comment by vnys** [comment]
I added comments in Service Now 4 and 6 days ago which I haven’t received any replies to yet. I contacted the person assigned to the task on Teams yesterday, he has taken Monday and Tuesday off apparently. I will create a new ticket and set a higher priority.

**Comment by vnys** [comment]
We’re back on the old storefront for now

**Comment by mimarz** [comment]
Closed as we are back on the old storefront now. Meeting tomorrow to discuss what to do further #1716
