### ISSUE TITLE
Documentation for data viz colors

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1287]
Need to create some documentation to go along with the issue for adding new color scheme. When to use this versus other, things to think about with color and data.

**Comment by mimarz** [comment]
Is this still relevant? @BeckyBrekke

**Comment by BeckyBrekke** [comment]
This is still relevant, these are the new colors Birth has worked on. Need to add these to the storefront. Should happen after we release zeroheight I think.

**Comment by BeckyBrekke** [comment]
I assigned @BirteThornquist and @benteljones to this, since this is what we discussed you would look at together before adding info about new data viz colors to the storefront.

**Comment by akvam** [comment]
Should be done after the "big" color walkthrough.

**Comment by BeckyBrekke** [comment]
Closing this since we have a separate issue that will include documentation: https://app.zenhub.com/workspaces/equinor-design-system-604f57c09e350a0011b654f4/issues/equinor/design-system/2254
