### ISSUE TITLE
Tooltip: Displays when title is ""

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#1292]
Should not be displayed when title is ""/blank. This is an old issue that reappeared with 0.10.1.

Also, why was the "open" property removed from tooltip? It was very handy

**Comment by mimarz** [comment]
![doh](https://user-images.githubusercontent.com/1070981/116363381-5c30c380-a803-11eb-9fd8-56f71a44532c.gif)

Sorry for the re-introduced bug 🐛 
We'll get it fixed for it next release 😊

We removed the `open` after improving the the open/close detection internally, as well as according to [best practices](https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip) its only supposed to show when a user interacts with the element. In addition to the newly introduced `openDelay` we thought we covered all use-cases. What use-case do you need to control the `open` state of the tooltip externally?

**Comment by HansKristianVikOlsen** [comment]
No worries, happy to report! I used the Open property to display tooltips of why something was disabled. For instance, if a WBS field was not provided in the project/study(as we call it), it will pop up automatically and users would immediately see what is missing instead of hovering it first. So it is not necessary, it just to make it more obvious why something was disabled :)

**Comment by mimarz** [comment]
> No worries, happy to report! I used the Open property to display tooltips of why something was disabled. For instance, if a WBS field was not provided in the project/study(as we call it), it will pop up automatically and users would immediately see what is missing instead of hovering it first. So it is not necessary, it just to make it more obvious why something was disabled :)

Ah, yeah. The designer for EDS have designed this use-case as the background/border would change to "error" color to indicate something was wrong, then tooltip shows on hover as to avoid to much clutter if you have x amount of fields

**Comment by mimarz** [comment]
@HansKristianVikOlsen We'll fix the opening of tooltip when string is empty. As for re-introducing the `open` functionality I have created a seperate feature request for this as it needs some coordination with our ux designers :)

**Comment by lucasveil** [comment]
The utility of a [tooltip](https://eds.equinor.com/components/tooltip/#main) is to displays information such as a text label or a short description on hover. From our understanding you want to use the tooltip if an information is missing. In most cases we suggest users to use an icon to indicate where the information is missing. If you provide us a screenshot from your page we can assist you with the proper solution :)
