### ISSUE TITLE
Density Compact

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1303]
EDS will, in addition to the default density, also offer a compact density for most of our components.

**Comment by BirteThornquist** [comment]
After a walk through of our components in regard to compact mode we landed on offering a compact version of the following components:

**Navigation**
App launcher*
Drawer
Menu
Pagination**
Table of  Contents
Tab
Top bar

*Need more info
**We need to look into how the pagination is solved today and how we can handle several digit numbers... We use buttons here today. Contact IOC and see how they are doing it.

**Data display**
Popover
Table
Table Data Grid

**Feedback**
Banner
Dialog
Snackbar
Progress indicators*

*We already have 5 different sizes of indicators. Figma must be updated.

**Inputs**
Button
Date picker input field (not the calendar)
Search
Select
Selection controls
Text field (text only)
Time picker 
Toggle button

**Surfaces**
Accordion
Toolbar
Side sheet?

Icons 

**For now we will not do a compact version of the following components:**
Slider
Calendar (in date picker)
Chip
Tooltip
List
Stepper
Breadcrumbs

**Comment by mimarz** [comment]
@equinor/eds-ux Our Switch has two sizes, 'small' and 'default'. Should we maybe rename this to conform to Density standards? So it would then be density; compact & comfortable.

**Comment by lucasveil** [comment]
Agreed. I think we use default instead of comfortable in some cases. It makes more sense to have it named comfortable. We will make sure to use this nomination from now on.

**Comment by mimarz** [comment]
> We decided to not offer the chip in a compact version, but I cannot quite understand/recall why? Chip is used in tables for instance, and in correlation with other compact components...?

I think it was because its already very small?

**Comment by BirteThornquist** [comment]
@mimarz True. Shape dimension is already 24. Maybe we need to update the clickbound which is 48...

**Comment by lucasveil** [comment]
This one is probably related to #1415 We need to created a new tokens for focus and clickbound for compact.

**Comment by akvam** [comment]
Closed since EDS 2.0 will cover what is needed, and we decided to remove this epic.
