### ISSUE TITLE
Missing properties for using Button as link

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1308]
**Describe the bug**

When using our `Button` component and setting the `href` property I expect to be able to set other properties related to the [`anchor` element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a).

**Steps to reproduce the bug**

1. Import `Button` from `eds-core-react`
2. Assign value to `href`

**Expected behavior**

Expected properties related to [`anchor` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) such as `target` or `rel` to be available.

**Additional context**

**Comment by BirteThornquist** [comment]
Solved.
