### ISSUE TITLE
User controlled open for Tooltip

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1312]
Feature request for allowing users to control the open state of a Tooltip externally. There might be some use-cases where this is needed?

We earlier had this function but removed it as to ensure showing of tooltips are done according to best practices. 

Requested in part from issue #1292

> I used the Open property to display tooltips of why something was disabled. For instance, if a WBS field was not provided in the project/study(as we call it), it will pop up automatically and users would immediately see what is missing instead of hovering it first. So it is not necessary, it just to make it more obvious why something was disabled :)

**Comment by lucasveil** [comment]
Replied to the user via #1292
