### ISSUE TITLE
Lagging Tooltip

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1325]
Reported on behalf of users in Slack.

When using `Tooltips` inside large tables we have recorded some use-cases where the opening would lag and open after the user has hovered over the an icon.

![Screenshot 2021-05-04 at 10.01.09.png](https://images.zenhubusercontent.com/605aea9d482116cb33bf4049/bb4c71b3-830f-47cb-ac47-a1b014756ae8)

**Comment by pomfrida** [comment]
This bug gave me deja vu 🤔

**Comment by mimarz** [comment]
This was fixed by better handling of `setTimeout` in `Tooltip`. Notes: https://overreacted.io/making-setinterval-declarative-with-react-hooks/
