### ISSUE TITLE
Wrong Tooltip positioning after being skewed

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1331]
Reported bug on behalf of user.

When using conditional rendering, and having a "section" appear that skews down items with a tooltip attached. 
Hovering on the skewed items with tooltip, its displayed on the position where it used to be. 

Scrolling the page (or anything that triggers a re-render) fixes the tooltip location to the new position of the skewed item.

before
![image (35)](https://user-images.githubusercontent.com/1070981/117276626-5ec49600-ae5f-11eb-8f7e-5b57b6717ea4.png)
after
![image (36)](https://user-images.githubusercontent.com/1070981/117276635-62f0b380-ae5f-11eb-815c-69b6feb282dd.png)

**Comment by HansKristianVikOlsen** [comment]
This also happens to the menu Component. I believe that this is the same issue? 
![image](https://user-images.githubusercontent.com/35257765/117422263-b296b400-af1f-11eb-964a-b9d9cf78656f.png)

**Comment by mimarz** [comment]
> This also happens to the menu Component. I believe that this is the same issue?
> ![image](https://user-images.githubusercontent.com/35257765/117422263-b296b400-af1f-11eb-964a-b9d9cf78656f.png)
> 
> Before:
> ![image](https://user-images.githubusercontent.com/35257765/117422413-dc4fdb00-af1f-11eb-80de-46288940c968.png)

Thanks for the input! Are you using conditional rendering for showing or hiding `Tooltip` or `Menu`? We noticed popperjs has a problem sometimes getting new anchor position when using conditional rendering outside...

**Comment by HansKristianVikOlsen** [comment]
Yes, the tooltips only displays if the user is not allowed to click the button, so that is conditional
