### ISSUE TITLE
How to get old Outlined buttons back?

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#1332]
I want my buttons to look like this: 
![image](https://user-images.githubusercontent.com/35257765/117288962-5e7ec780-ae6c-11eb-89f5-5a3178967432.png)

After updating to 0.11.0 they look like this: 

![image](https://user-images.githubusercontent.com/35257765/117289216-a1d93600-ae6c-11eb-90a2-d4a204edb7b2.png)

**Comment by HansKristianVikOlsen** [comment]
Looks like outlined = Ghost buttons now

**Comment by mimarz** [comment]
This looks definitely as a bug.  We'll have a look at it :)

**Comment by mimarz** [comment]
Thanks for reporting this! @HansKristianVikOlsen 

Its fixed now and we have one other edge-case improvement that we want to include in the next update, so we'll release it later today or tomorrow hopefully!
