### ISSUE TITLE
rowsMax on TextField

### ISSUE THREAD

**Issue by wigsnes** [equinor/design-system#1336]
**Is your feature request related to a problem? Please describe.**

I want to make it so that a text field expands as the content takes up to much space in the TextField, and not have a scroll-bar.

**Describe the solution you'd like**

Include rowsMax on TextField.

**Describe alternatives you've considered**

Switch to TextField from material-ui, which is boring to have to do just for rowsMax.

**Demo how I want it to work**

https://codesandbox.io/s/material-demo-forked-us7hp

**Comment by mimarz** [comment]
Doh, that sucks! We should be able to find a solution for this. Much love for providing a codesandbox 😍

I think the plan was to have something like this when we did a touch-up on `Textfield` in March, but we hit a snag in terms of adornments with multilines (#1155), so its still in the backlog... 🤔

We'll have a look at these issues in our next planning meeting next Tuesday and get back to you :)

**Comment by mimarz** [comment]
@wigsnes We have release this feature now and it can be found in the latest version of [eds-core-react](https://www.npmjs.com/package/@equinor/eds-core-react) (0.12.0)!

**Comment by wigsnes** [comment]
Thanks, this will work. I see some improvements that can be made if you have time, you can see [codesandbox here](https://codesandbox.io/s/material-demo-forked-7soyp?file=/demo.tsx).
