### ISSUE TITLE
How to make feature requests for non-developers

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1338]
This has been flagged as an issue since many designers don't have GitHub access. How should they make feature requests? 
In zeroheight it is possible to embed forms and collect info from users easily. We also have all the Power Platform tools that can help automate this. 
Users want to see an overview of requests and find out the status also.  Like an idea portal
Need to look into this more.

**Comment by nilsml** [comment]
There are tools that would do this for us, like f.ex. [Canny](https://canny.io/). With integrations for Slack, Github, Teams, etc, it would make it easy for people to engage. Comes at a cost though.

**Comment by BeckyBrekke** [comment]
We decided to use[ this text ](https://eds.equinor.com/0b0c666ab/p/29134f-support) regarding feature requests: Request a feature
GitHub users can create a new issue and fill out the feature request template. 

Non-GitHub users can get in touch using the channels above. Examples of feature requests can be added to the EDS designer sandbox in Figma.

**Comment by BeckyBrekke** [comment]
We decided to use[ this text ](https://eds.equinor.com/0b0c666ab/p/29134f-support) regarding feature requests: Request a feature
GitHub users can create a new issue and fill out the feature request template. 

Non-GitHub users can get in touch using the channels above. Examples of feature requests can be added to the EDS designer sandbox in Figma.
