### ISSUE TITLE
As a user I want an EDS theme file for Power BI so I can easily implement EDS design components

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#136]
Create a Power BI theming file (json) file that contains EDS components
- [x] Decide which components to add to json file (colors only, other things?)
- [x] Create json file and test
- [x] Decide where to store files 
- [x] Test using Equinor font
- [x] Communicate with Power BI users (replace existing color json already in use? or in addition?)
- [x]  Share data viz guidelines at the same time
https://eds.equinor.com/patterns/data-visualisation/

Aug 3 - ready to share a first draft with super users and those that have showed interest to get feedback. 
https://app.powerbi.com/groups/me/apps/2fc55c86-4da0-46d9-b0c3-5ad31c3aee82/reports/842ab784-828a-4e3a-b918-d3179a27a72e/ReportSection6733e16b600c25762a61?ctid=3aa4a235-b6e2-48d5-9195-7fcf05b459b0

**Comment by BeckyBrekke** [comment]
Sent to Berit Reppen Lorentzen, she will look at this, Her feedback: I'm starting up a project this week with DCoE that will result in the mandate, responsibilities and to-do's for a professional network covering data visualisation and analysis (final name TBD)

**Comment by vnys** [comment]
Created a user story for where to store the templates (#594) based on discussions from standup. Feel free to edit and comment.

**Comment by BeckyBrekke** [comment]
Agreed to close this and create new follow up tasks. Need a task to add to store front, follow up with users and add/update with improvements
