### ISSUE TITLE
Refactor Popover

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1365]
For making our components easier to use we have decided to remove the fixed close button inside the `Popover` component as there are other valid options for using an popover without "that" close button. The documentation serves as a guideline recommendation for the close button on certain types of content. 

Actions
* Remove fixed close button in `Popover`
* Add story with example where said close button is used but composed from existing components
* Update documentation to better reflect when to add a close button inside popover

**Comment by mimarz** [comment]
@equinor/eds-ux Based on our discussion on removing fixed close icon inside `Popover`. Does this look ok? We'll have to make sure to adjust the documentation... 🤔

**Comment by laliq** [comment]
### CHANGES:

- Add `Header` sub-component, wrap for `Title` & `Close Button`.
- Add `Actions` sub-component, wrap for `Button`.
- Remove negative style values.
- Move padding to sub-components.

### todo:

- [ ]  storybook description

**Comment by benteljones** [comment]
![Skjermbilde 2022-01-13 kl. 10.50.47.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/85d27f72-25a8-4767-a65a-5a2b5487d98a)
