### ISSUE TITLE
Add Input token adjustments to Theme.json

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#1377]
Continues #1227

- [ ] Textfield

- [ ] Dropdown

- [ ] Combo box

- [ ] Date picker

- [ ] List box

- [ ] Checkbox

- [ ] Radio 

- [ ] Toggle

- [ ] Pen input 

- [ ] Rich text editor

**Comment by Hjaf** [comment]
I have done some testing by essentially re-building  the Themes.json and rebuilding the app, at this point this appears to be somewhat unreliable and not likely to be future best practice.

I have not had time to dig deep after details or documentation on Themes.json, but experiments on more extensive manipulation of Themes.json result in breaking the studio session. Furthermore, the studio session do not issue any warning or error when loading into this broken state, which means we have to use a bruteforce approach to debugging and validating.

I propose putting this on hold, until we have a proper process to validate. And if we do any manipulation of Themes.json then we do not go beyond whatever the CreatorKit template or the Theming components from CoE starter kit (if they have done anything at all to these files).

**Comment by vnys** [comment]
Closed as this solution appears to be unstable / undocumented
