### ISSUE TITLE
Next tokens format

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1388]
With compact and theming (dark mode) we might need to change our tokens structure in code. The current format might get to messy with multiple possible mutations and we need to figure out how to handle ordinality of different modes (how does dark mode with compact work?).

Notes
* https://github.com/salesforce-ux/theo

**Comment by akvam** [comment]
Need to start in with investigating in "code".

**Comment by akvam** [comment]
Need to be done before dark theme. 
Is also relevant for the CSS library.

**Comment by BirteThornquist** [comment]
Will be solved by other issues. Closing this.
