### ISSUE TITLE
Create About EDS pages and QA

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1390]
**Write:**
- [x] About EDS

- [x] [Meet the EDS core team](https://zeroheight.com/0b0c666ab/v/latest/p/42fd06-meet-the-eds-core-team)
- [x] Getting started developers
- [x] Getting started designers
- [x] Getting started citizen developers (will see if I have time for this before the first release, if not will make an issue to write more later.
- [x] Getting started using Figma

There are separate issues for releases and road map. 

**QA:**
- [x] About EDS
- [x] Meet the EDS core team
- [x] Getting started developers
- [x] Getting started designers
- [x] Getting started citizen developers
- [x] Getting started using Figma

----------------------------------------------------------
Some text from issue #101, getting started for developers, might be relevant: 
Pages are located here: https://github.com/equinor/design-system/tree/develop/apps/storefront/src/content/getting-started/developers

How will versioning be handled?
How will I update/migrate?
How will it be distributed?
End of the page should push to the FAQ.

**Comment by BeckyBrekke** [comment]
Started on Meet the EDS core team

**Comment by BeckyBrekke** [comment]
@lucasveil @BirteThornquist 
Can you please check the getting started pages for Designers and Figma? 
https://zeroheight.com/0b0c666ab/v/latest/p/70f292-designers
https://equinor.zeroheight.com/styleguide/s/58798/p/12b5e3-figma/b/38b6b9

**Comment by BeckyBrekke** [comment]
Can you look at the About EDS page too? 

And I think we should explain some place that we have an EDS library of design components. Right now using the current storefront info we are very vague about this and don't actually explain it but go right into using Figma. Should this go on the getting started for designers page or the Figma pages? I thought Figma. 
@BirteThornquist @lucasveil

**Comment by lucasveil** [comment]
Good work Rebecca:
For the Designers page:
- I would change the title **Don't make your own** to **Contribution**. You can keep the text and add the link to the sandbox by writing something like: EDS is based on the contribution of its community. [Take contact](https://zeroheight.com/0b0c666ab/v/latest/p/29134f-support) if you have any feature request or refer to [EDS sandox](https://www.figma.com/file/hjpavZkeUoRfn1N7mhIniK/EDS-designer-sandbox) to get help from the community. 
We will take down the sandbox in January if nobody uses it.

For the Figma page, i think it would be usefull to have a video there. There is a lot to read and understand. A quick intro video would be helpful on how to start with Figma and how to set up your file. What do you think there @BeckyBrekke ?

**Comment by BeckyBrekke** [comment]
The suggestion was good, I wrote this (with links): EDS is based on the contribution of its community. Get in touch with the EDS core team if you have a feature request or visit the EDS designer sandbox to collaborate with the community.
I think a video would be really good. [Fonda did a video](https://web.microsoftstream.com/video/5cd3d523-cc80-46e2-9f0a-3edf7d1c0e38) in the beginning that covered the basics, but it should be redone.

**Comment by BeckyBrekke** [comment]
First draft is out there!
