### ISSUE TITLE
Create Support pages and QA

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1391]
**Write:**
- [x] report a bug
- [x] request a feature
- [x] [Get in touch](https://zeroheight.com/0b0c666ab/v/latest/p/03d039-get-in-touch)

**QA:** 
- [x] report a bug
- [x] request a feature
- [x] Get in touch

**Comment by BeckyBrekke** [comment]
Working on these. Will ask someone to QA them when done.
https://zeroheight.com/0b0c666ab/v/latest/p/299865-report-a-bug
Not sure what to tell non-GitHub users to do.

**Comment by BeckyBrekke** [comment]
Need to add information about the sandbox in Figma.

**Comment by BeckyBrekke** [comment]
Before summer I investigated some way for non-GitHub users to open issues using forms and GitHub connector but I couldn't get it to work properly. Lucas suggest we just mentioned the Figma sandbox info, so adding that and just linking to our get in touch page. We have [this separate issue](https://app.zenhub.com/workspaces/equinor-design-system-604f57c09e350a0011b654f4/issues/equinor/design-system/1338) in our board to look at how we handle non-GitHub users.

**Comment by BeckyBrekke** [comment]
@lucasveil , @BirteThornquist : Can you guys have a look at the support pages please? I added something about the sandbox in Figma. Let me know what you think about that. 
Do you want to have a separate page for bugs in the sandbox too, where people can add examples or not?

**Comment by BirteThornquist** [comment]
Good job @BeckyBrekke! Short and concise with links to examples, just how we like it. Regarding bugs I am not quite sure if we should include it...? In a way it is nice to keep the sandbox only for ideas and feature requests where people go to get and express ideas and inspiration....

**Comment by BirteThornquist** [comment]
@BeckyBrekke in todays stand up we agreed not to include bugs in the sandbox. We need to look into how to handle bugs/ feature requests in general at a later stage.

**Comment by lucasveil** [comment]
Looking good :) Wouldn't be easier for users that want to "report a bug" and "request a feature" to have directly the link to contact the EDS team. It will spare them an extra click and would be more user friendly. Like:

Report a bug
GitHub users can create a **new issue** and fill out the bug template. 

Non-GitHub users can get in touch with the EDS core team:
-Slack
-Email
-Yammer

And the same for Request a feature.

**Comment by BeckyBrekke** [comment]
It is a good suggestion - but I am trying to avoid having duplicate information in zeroheight. So, if I did it the way you suggest we would have three pages with the same information, and if we needed to update one of the links we would have to do it three places. I think it's best to keep the links on the one page and reference it. What do you think?

We do also have an issue to look at later how non-GitHub users can request features/report bugs without contacting us directly.

**Comment by lucasveil** [comment]
I try a last suggestion :) Why don't we call the page Get in touch and only have a one page with each section? It seems it is the same content on each page, so i would keep it simple by only having: 

**Contact the team**
The EDS core team maintains and provides support for the EDS and are here to help. 

They can assist with advice, onboarding, questions, improvement suggestions and incorporating contributions. 

Get in touch with the EDS core team here: 

Slack
Email
Yammer

**Do you want to report a bug?**
GitHub users can create a new issue and fill out the bug template. 
Non-GitHub users can get in touch with the EDS core team through the channels above.

**Do you want to request a feature?**
GitHub users can create a new issue and fill out the feature request template. 
Non-GitHub users can get in touch with the EDS core team. 
Examples of feature requests can be added to the EDS designer sandbox in Figma.

**Comment by BirteThornquist** [comment]
I think one page for getting in touch could be smart. Since we, at least for now, shall use our communication channels for FR and bugs for nonGitHub users it seems a bit overkill to have separate pages with the same content.

**Comment by BeckyBrekke** [comment]
This sounds good!!!

**Comment by BeckyBrekke** [comment]
Good suggestion! [How about this ](https://zeroheight.com/0b0c666ab/v/latest/p/29134f-support)@lucasveil and @BirteThornquist ? 
I moved everything directly under the Support page so it's only one click for the users.

**Comment by BirteThornquist** [comment]
This looks good @BeckyBrekke!

**Comment by lucasveil** [comment]
Yep! Really nice @BeckyBrekke
