### ISSUE TITLE
As a user I want differentiable names for the components, so I immediately know what type of component it is.

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1393]
From Slack:
Just a small comment: It would have been helpful if icons and selection controls had distinguishable names. E.g. “checkbox” appear as both, but is “impossible” to see what is what:

https://equinor.slack.com/archives/CJT20H1B9/p1622531927036500

**Comment by mimarz** [comment]
is this still relevant @BirteThornquist ?

**Comment by lucasveil** [comment]
Updated description for the icon to checkbox - icon. This information will come up as tooltip on hover.
