### ISSUE TITLE
Jest is bundled with eds-core-react

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1406]
Jest is bundled with eds-core-react. It uses process.env, with the result that the components don’t work with Webpack 5.

**Comment by mimarz** [comment]
This might be fixed in react-testing-library, https://github.com/testing-library/react-testing-library/commit/8a1c8e9396aa7f4843b54e31e2c95404ab8ad940

**Comment by mimarz** [comment]
The cause for this was that we had a custom test renderer we used for testing menu, popover etc that was under utils. This meant that the whole `react-testing-library` was bundled along since it was imported by this custom test renderer.
