### ISSUE TITLE
Clear selection for SingleSelect and MultiSelect

### ISSUE THREAD

**Issue by jamtrott** [equinor/design-system#1411]
Hi!

We are using SingleSelect and MultiSelect components from EDS. Unfortunately, there is apparently no way for the user to clear the current selection for either of these components. In the case of SingleSelect, there is no way to go back to an empty selection once something has been selected. For MultiSelect, on the other hand, it is possible to deselect each item. However, in our use case, the user might have selected half a dozen options out of a list of tens or hundreds, so it would be tiresome to have to deselect each one.

It would be really helpful if somehow the selection could be cleared and an event was generated, so that the UI could be updated accordingly.

**Comment by mimarz** [comment]
Thanks for suggesting this feature! 

We have planned a few improvements and tweaks for Select-components in the not to far future, so maybe we can get this done then as-well :)

**Comment by mimarz** [comment]
@equinor/eds-ux We need to have a look at how a potential clear selection function should behave and look for selects

**Comment by lucasveil** [comment]
We will definitely have a look at it. In the meantime, we suggest to have an "empty" state for single select that has the function to clear the field. For multi select, there have been some discussion to have the "chips" stacked just under with the close icon.  
![Screenshot 2021-08-02 at 12 05 18](https://user-images.githubusercontent.com/65652493/127844427-4e3c80a2-eba2-4fe3-830e-4e017952701a.png)
