### ISSUE TITLE
Focus state in design needs to be aligned to dev

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1415]

**Comment by lucasveil** [comment]
After change of focus in, the component needs to be adjusted.
Ref [Slack discussion](https://equinor.slack.com/archives/GEF6LDVT9/p1622716918048200)

**Comment by BirteThornquist** [comment]
@mimarz @pomfrida We will change the focus frame and hover circle dimension to 30x30px for selection controls and icon buttons in compact mode. 
For density default, we will keep todays hover circle dimension which is 40 x 40px, but adjust the focus frame from todays 52 x 52 px to 48x48 px. ![Skjermbilde 2021-06-15 kl. 12.40.24.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/b0a291e4-a02e-40eb-8d81-2f589a634b79)

Let's test this and see if it works.

**Comment by pomfrida** [comment]
@BirteThornquist I didn't think focus offset dimensions should be larger than the hover circle dimensions, as we talked about in the Slack discussion this causes overlap between the two states when they are stacked. This is because in code, the hover circle follows the actual dimensions of the controls, while focus outline is set with an offset relative to the controls and doesn't take up any space. Setting focus offset 39x39px instead of 40x40px would avoid any overlap. (And 29x29px vs 30x30px for compact)

**Comment by BirteThornquist** [comment]
@pomfrida to use odd numbers is cumbersome in Figma when it comes to alignment... and the dimension of the hover circle is already 40x40. When I use 40x40 and 30x30 it seems OK in Figma [here](https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/Birte-test?node-id=688%3A101691) 
Maybe it is OK if the dimensions are done a bit differently in code than in Figma as long as the design result is the same..?

**Comment by mimarz** [comment]
@BirteThornquist @pomfrida Do you have some time to look through the Figma sketches together? I notice some inconsistencies when looking at the sketches and whats being written here.

**Comment by mimarz** [comment]
Summary after online meet.

* We will introduce a _new focus frame token_ that has `0px` offset as to avoid overlap on stacked ghost components with interactions such as selection controls, ghost icon button etc.
* Existing focus frame token with `2px` offset will remain but be used on filled components such as contained/outlined buttons
* We will do an implementation in code on selection controls and ghost icon to test before doing any of these changes in Figma.

**Comment by mimarz** [comment]
TODO: Verify stacking checkbox, radio & selection controls.

**Comment by lucasveil** [comment]
For design, the focus frame is a [token](https://www.figma.com/file/0TbIXrrObWj80Cf7KucKYFL0/Design-Tokens?node-id=339%3A1806) that is applied to all component that has a focus state. If I want to update the focus state for selection controls and ghost button, I have to detach the component (that will then be a breaking change in the component). The right way of doing it, is to set up a new "focus with no offset" token for default and compact. Then we have to document it pretty well so that it doesn't get confusing. Is this the way we should go for @pomfrida ?

**Comment by pomfrida** [comment]
Yes, @lucasveil that is the way to go I think 👍  I implemented 0px focus offset on the different selection controls + ghost icon button earlier to test how it stacks and it looks good

**Comment by nilsml** [comment]
@lucasveil any comments on who should do what here?

**Comment by lucasveil** [comment]
A new focus token has been implemented and released [in Figma](https://www.figma.com/file/0TbIXrrObWj80Cf7KucKYFL0/Design-Tokens?node-id=12519%3A3099)
[Ghost buttons](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A47297) and [Selection control](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=18442%3A38197) has now been updated.
Ready for review @mimarz @laliq

**Comment by lucasveil** [comment]
Have set a new issue in #2123
