### ISSUE TITLE
Update eds-icons

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1417]
Update eds-icons using the figma-broker with new icons added to Figma in #1189

**Comment by lucasveil** [comment]
New set of icons @mimarz :

- [power bi](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3735)
- [engineering](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [boundaries](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [invert](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [inspect rotation](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [inspect 3d](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
