### ISSUE TITLE
Simplify the amount of selection controls (switch)

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1438]

**Comment by BirteThornquist** [comment]
After a discussion today we decided to cut down the variations of selections control. We will offer a compact version of todays small switch and a default version of todays medium.

**Comment by BirteThornquist** [comment]
This will be a breaking change for designers, since the small size switch is in use as density default in many instances today. We will explain and notifyour users in the Meet the Designer meeting 23.06 21 and also in EDS slack channel. They will need to detach their instances. We will delete the component variants from Figma after the summer holiday.

**Comment by akvam** [comment]
As discussed in meeting with the team, all US on epic compact is closed if they do not have any additional information.
