### ISSUE TITLE
As a User of the design system I want clear guidelines/patterns of how to use the EDS components.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#144]
- [ ] Identifying the most important patterns / guidelines to include. Then add them to the list below
- [ ] Patterns for editable, read only and disabled text fields 
- [ ] Placement of primary and secondary buttons
- [ ] How to display functionality earier often displayed as a set of "buttons" in a toolbar
- [ ] Capitalization guidelines for labels
- [ ] Gaps between components
- [ ] When to use Navigation Drawer and v.s.v. Table of Contents 
- [ ] Rules for spacing between text field especially with a combination with and without helper text
- [ ] Consider another solution for how to show unit on a field (AS is this is below the field.)

**Comment by mimarz** [comment]
Is this still relevant? @equinor/eds-ux

**Comment by lucasveil** [comment]
This needs to be taken in zeroheight @BeckyBrekke @akvam ?

**Comment by akvam** [comment]
This is a US from before Zerohight. Hope everything is solved => close the issue.
