### ISSUE TITLE
Zeroheight - add design info for DATA DISPLAY

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1440]
- [x]  DATA DISPLAY
- [x]  Chip
- [x]  Divider
- [x]  List 
- [x]  Popover
- [x] Table
- [x] Table Data grid
- [x]  Tooltip

**Comment by lucasveil** [comment]
@BeckyBrekke  ready for review :)

**Comment by BeckyBrekke** [comment]
Reviewed and ready
