### ISSUE TITLE
Zeroheight - add design info for FEEDBACK

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1441]
- [x] FEEDBACK
- [x]  Banner
- [x]  Circular
- [x]  Dialog
- [x]  Dots
- [x]  Linear
- [x]  Scrim
- [x]  Snackbar
- [x]  Star

**Comment by lucasveil** [comment]
@BeckyBrekke  ready for review :)

**Comment by BeckyBrekke** [comment]
Review is not complete!
