### ISSUE TITLE
As a EDS user I would like the EDS storefront Home page to give me an overview of what is new in EDS.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#145]
- [x]	Remove under construction 
- [ ]	Add some 'quick links:	cdn, Slack, npm packages, Figma, Github (report issues here text),  React library, icons, release info
- [ ] Component status - put in 3 sections - doing, done, to do. This is added to Home page
- [ ] Add information about the Core Team

**Comment by mimarz** [comment]
@equinor/design-system is this still relevant? Maybe make a separate task for bullet points

**Comment by BeckyBrekke** [comment]
This came from one of our gatherings and we seemed to agree on some improvements. Probably still relevant. Separate task for each bullet point sounds good.

**Comment by BeckyBrekke** [comment]
I'm closing this since we have implemented some of these changes in zeroheight now.
