### ISSUE TITLE
Compact Typography

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#1452]
Needed to align items better in a compact `Menu`

A compact `Typography` with `group="navigation"` and `variant="label"` should have height `12px` (is currently 15). (Or line height 1)

See `DataTable.stories.tsx` or https://github.com/equinor/design-system/pull/1451 for details, and remove the inline styles when this is implemented in Typography.

Update: After discussion with design we decided that line-height must be lowered to 1 for all Typography in compact. This has to be added to tokens: #1454

**Comment by pomfrida** [comment]
Blocked by #1454

**Comment by lucasveil** [comment]
Tokens for Table compact is now in Figma @pomfrida . All in-light have been adjusted to 16 px.

**Comment by pomfrida** [comment]
Tried to update tokens after Lucas updated figma but since I'm a figma broker n00b, @mimarz should probably do this

**Comment by mimarz** [comment]
> Tried to update tokens after Lucas updated figma but since I'm a figma broker n00b, @mimarz should probably do this 

Did you try to set the force flag to false @pomfrida ?

**Comment by mimarz** [comment]
This issue will be fixed by #1532
