### ISSUE TITLE
button cannot be disabled if href is passed

### ISSUE THREAD

**Issue by SvSven** [equinor/design-system#1456]
**Describe the bug**

The `disabled` property on the `<Button>` does not work if a `href` is passed and the button is used as a link.

**Steps to reproduce the bug**
See: https://codesandbox.io/s/modest-grass-nz1ie?file=/src/App.js

**Expected behavior**

Button should either be able to be disabled when used as a link, or documentation should reflect this behaviour

**Comment by pomfrida** [comment]
As a disabled link/button doesn't really need to pass an URL (a valid URL automatically transforms the button to a link and it's not possible to disable a link), so a workaround for this problem is to do something like this: 
`<Button href={isUrlValid ? 'the/valid/url' : undefined} disabled>`
