### ISSUE TITLE
Outdated code examples Storefront 

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#1461]
The code examples for compound components are outdated as we renamed them a while back. 

Example:
Outdated: https://eds.equinor.com/components/navigation-tabs/
Correct: https://eds-storybook-react.azurewebsites.net/?path=/docs/components-tabs--default

This was reported by one of our users in #eds-design-system on Slack.

**Comment by pomfrida** [comment]
Not sure if there's a point in fixing this in the Storefront when it can be fixed in the transition to Zeroheight.

**Comment by mimarz** [comment]
Closed as we are deprecating the Storefront in favour of Zeroheight.
