### ISSUE TITLE
Version 0.12.0 breaks the stacking context of the Menu component

### ISSUE THREAD

**Issue by tfrausin** [equinor/design-system#1462]
**Describe the bug**

Version 0.12.0 of EDS changed the rendering behavior of the `Menu` component. It is now attached to `document.body` using `React.Portal`. This changes the stacking context of the component and it will no longer be part of the stacking context where it is defined. E.g., if we now use `Menu` in conjunction with `TopBar`, where a header action opens a `Menu`, the header will now overlap and hide part of the `Menu` component.

**Steps to reproduce the bug**

1. Make an action in `TopBar` component open a `Menu` component. See CSB https://codesandbox.io/s/eds-stacking-context-bug-m1lmt

**Expected behavior**

`Menu` respects the stacking context where it is defined. I.e., `Menu` opens on top of and overlaps the `TopBar` component.

**Specifications**

- Version: 0.12.1
- Browser: Google Chrome Version 91.0.4472.114 
- OS: macOS Big Sur Version 11.4

**Comment by mimarz** [comment]
Thanks for reporting this @tfrausin ! 

I see we need to do some adjustments to the `z-index` values for our components as this use-case would also be the same for `Popover` 🙈  #1466
