### ISSUE TITLE
Update the Equinor typeface

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1507]
The Equinor typeface has been upgraded and improved for web usage. In addition to improved versions of upright and italic variants, we also have a monospace font now that can be used in data tables. We’ve also received a variable font, which means we can finetune the font weights based on font size for example. Figma does not currently support variable fonts, so we need to replace the fonts in Figma with the individual font-files, and then do the fine tuning in code. That’s the end result anyway, so it’s not optimal – but I expect Figma will catch up sooner or later.

This task is two-fold then:

1. [Update the fonts in Figma](https://github.com/equinor/design-system/issues/1509)
1. [Update the fonts in the CDN](https://github.com/equinor/design-system/issues/1508)

**Comment by akvam** [comment]
All US is in Done => Epic closed
