### ISSUE TITLE
Update the Equinor fonts in the CDN

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1508]
We will have to update the fonts in Figma first, but there are some limitations to what’s possible to do in Figma (no support for variable fonts) – so we need to do some tuning in code that’s not possible to do in Figma. I still put this as dependent on the Figma issue since the question of how to use the monospace font needs to be clarified before we do anything.

We also need to figure out how to solve versioning, how to prevent fallback to local versions of the old fonts and how to decrease the file size of the fonts. We now have one file with all the fonts, as well as individual files for each font. My gut feeling is that most projects download more font-files than they use, so maybe we should add two more files – one for uprights and one for italics for example, since we don’t use italics in the design system.

We’ve also received [a request from users in our Slack channel](https://equinor.slack.com/archives/CJT20H1B9/p1627894246007200) to include the font-display property using the fallback value, so we need to do some testing on that.

The fonts are uploaded to the EDS Core Teams channel. I’ve received the files in several emails, so it’s a bit of a mess. I’ll talk to the person in charge once he’s back from holiday in week 32 to make sure we have the latest version of all the files.

CC: @mimarz, @pomfrida, @spcttre, @ErlendAHall

**Comment by vnys** [comment]
The new fonts are uploaded to the CDN. I’m a bit hesitant about replacing the individual font-files with the new variable fonts since we don’t know how variable fonts are handled in all the apps that use the fonts from the CDN, so I’ve added some new css-files in addition to the original ones. I don’t think we need to update the private NPM packages on Github as nobody seem to use them. Even though users have the option of just using one of the fonts and not the entire package, my gut feeling is most users download all the fonts. Since we only use the uprights in the EDS I’ve made separate files for uprights and italics. The variable fonts are also split into two files even though technically it could have been one. (Since the italic fonts are really oblique and not italic, meaning they’re electronically slanted, that too could have been an axis in the variable font similarly to font weight.)

Users now have the following options:

- equinor-font.css (all 8 fonts)
- equinor-light.css
- equinor-regular.css
- equinor-medium.css
- equinor-bold.css
- equinor-lightitalic.css
- equinor-mediumitalic.css
- equinor-bolditalic.css
- equinor-uprights.css (new, only the uprights)
- equinor-italics.css (new, only the italics)
- equinor-font-vf.css (new, uprights and italics)
- equinor-uprights-vf.css (new, only uprights)
- equinor-italics-vf.css (new, only italics)

Since the fonts are new, we need to prevent the browser from falling back to locally installed versions of the font – so I’ll re-introduce the unicode smiley as the local font name, unless there are new techniques that solve the same problem. The font-display property is not implemented yet, I thought I’d create a couple of copies of the variable fonts with different settings to see if “fallback” is the best option.

**Comment by vnys** [comment]
_I’ve added `font-display: fallback` to_ 
- equinor-uprights-vf.css
- equinor-italics-vf.css
- equinor-uprights.css
- equinor-italics.css

I’ve also added a reference to a non-existing local font to prevent the previous version of the font to take precedence on Equinor PCs. This is based on an old technique by Paul Irish that I used back in the day. As far as I can tell this is still the best way to prevent local fonts from being loaded in the browser. If anyone has some new information that proves this to be wrong please let me know.

For the EDS components I recommend using `equinor-uprights-vf.css` since we don’t use italics in any components. This file favours `woff2` with a fallback to `woff` and finally the regular `woff` font. That means that for users with [browsers that don’t support variable fonts,](https://caniuse.com/?search=variable%20fonts) all the text will be displayed with Equinor Regular. Since we only support evergreen browsers anyway I think this is an acceptable solution.

```css
@font-face {
    font-family: Equinor;
    src: local('😊'),
        url(//eds-static.equinor.com/font/EquinorVariable-VF.woff2) format('woff2-variations'),
        url(//eds-static.equinor.com/font/EquinorVariable-VF.woff) format('woff-variations'),
        url(//eds-static.equinor.com/font/Equinor-Regular.woff) format('woff');
    font-style: normal;
    font-weight: 1 999;
    font-display: fallback;
}
```

**Comment by spcttre** [comment]
Hi, we test the new font `equinor-uprights-vf.css` and works just fine, but we realized that when the font-weight is different than 400 (Equinor-regular) the font looks a bit different, we saw this with our tests through a visual regression tool. The differences are minimum so perhaps they are ok.

For example:
eds-static.equinor.com/font/Equinor-Medium.woff2 -> That is font-weight: 500

Doesn't have the same result as:
https://eds-static.equinor.com/font/equinor-uprights-vf.css -> with font-weight: 500

_The differences are mark with yellow and red on the **Difference** picture and are based on the **Reference** picture_

Example using the accordion header that uses font-weight 500

**Reference** (using https://eds-static.equinor.com/font/equinor-font.css):
![chrome_iphone7_OPT_UI_Data_Display_Accordion_With_Buttons](https://user-images.githubusercontent.com/57752690/130753794-c50206be-4a79-4030-9bf2-e922af4f68b5.png)

**Difference** (Using https://eds-static.equinor.com/font/equinor-uprights-vf.css):
![chrome_iphone7_OPT_UI_Data_Display_Accordion_With_Buttons](https://user-images.githubusercontent.com/57752690/130753928-1178dda0-58dd-465a-8e2a-b4a2f58df6b2.png)


Another example with the button that also uses font-weight 500:

**Reference** (using https://eds-static.equinor.com/font/equinor-font.css):
![chrome_iphone7_OPT_UI_Data_Display_Popover_Base](https://user-images.githubusercontent.com/57752690/130754118-a45078e7-e828-4106-a2b2-a69787e99fc3.png)

**Difference** (Using https://eds-static.equinor.com/font/equinor-uprights-vf.css):
![chrome_iphone7_OPT_UI_Data_Display_Popover_Base](https://user-images.githubusercontent.com/57752690/130754156-59904ceb-2bfb-4967-9569-21e18aa5c30f.png)

Another example using a Menu component:

Reference (using https://eds-static.equinor.com/font/equinor-font.css):
![chrome_iphone7_OPT_UI_Navigation_Menu_Base](https://user-images.githubusercontent.com/57752690/130756126-7ab9ea0d-72b7-40a1-bc68-4215fb490b26.png)

Difference (Using https://eds-static.equinor.com/font/equinor-uprights-vf.css):
![chrome_iphone7_OPT_UI_Navigation_Menu_Base](https://user-images.githubusercontent.com/57752690/130756069-acadbd79-759f-4d48-83f7-d49b53cfa628.png)

**Comment by vnys** [comment]
That’s very interesting, it should be the same – thanks for the feedback 👍🏻 Are you sure you use the new fonts and not local ones? I’ve added a mechanism to prevent the browser from using a local fallback as noted above, but I haven’t done that for all the font-files yet. I’ll update the rest of the files too, then maybe you could try again and see if the difference is still there. I would expect a difference between the old and new fonts, but not between the individual font-files and the variable font-files.

**Comment by spcttre** [comment]
Yes every test is using the different fonts, at the end the tests are running in different instances of a docker through a headless chrome, so every tests runs without any local data (or it should run without).

Old version gets the fonts from: https://eds-static.equinor.com/font/equinor-font.css

new version gets the fonts from: https://eds-static.equinor.com/font/equinor-uprights-vf.css

Also cleaning cache and using my own vision i can even notice the small differences.
