### ISSUE TITLE
Add documentation for compact mode

### ISSUE THREAD

**Issue by nilsml** [equinor/design-system#1512]
Document guidelines for how to use compact mode for table.

**Comment by vnys** [comment]
Sub tasks:

- [ ] Add generic page about compact mode
- [ ] Update button docs
- [ ] Update menu docs
- [ ] Update table data grid docs
- [ ] Update text field docs
- [ ] Update select docs

**Comment by vnys** [comment]
It looks like we’re using personal accounts for the Figma integration, that’s potentially going to cause problems further down the road and something to should look into. Also, the components and styles that are imported from Figma look much better than the screendumps – should we do a spike on creating a dedicated documentation project in Figma and make components that we use for examples in Zeroheight?

@BirteThornquist, @lucasveil, @BeckyBrekke

**Comment by vnys** [comment]
Created three new issues based on discussion on Teams (#1879, #1880, #1881)

**Comment by vnys** [comment]
Examples of creating Zeroheight images in Figma → https://zeroheight.com/0b0c666ab/v/latest/p/898b16-density/b/56c665. It seems even if we choose “natural height”, there’s a fixed height for the image, so not sure what’s meant by “natural” 🤔 .
In the first row I’ve made comfortable and compact into components to get the description from Figma, but I think you can do the same with notes in Zeroheight, so not sure what value that brings for us. In the second row I’ve imported a frame, but I can’t control the height, so there must be some aspect ratio calculations that determine the height. I was hoping to get the original size from Figma.

CC: @equinor/eds-ux

**Comment by vnys** [comment]
@equinor/eds-ux Can this be closed?

**Comment by lucasveil** [comment]
The page and text Looks good to me @vnys 
But we didn't get the chance to talk about the 2 "ways" to import images in Zero Height. Should we standardise it?

**Comment by vnys** [comment]
> we didn't get the chance to talk about the 2 "ways" to import images

I know, I just picked the one I thought looked least awful 😁  Then we can close this compact documentation, and create a new one specifically for investigating the options.

**Comment by BirteThornquist** [comment]
Text and images LGTM too @vnys! But I can't see the two different ways of doing the images....?

**Comment by BirteThornquist** [comment]
Oh - sorry, missed your comment there @vnys 😄
