### ISSUE TITLE
Support for tree-shaking in eds-icons package

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1539]
Related #1043 

Commonjs does not support tree-shaking when deconstructing values from a provided object.

This means that when, for example, `import { sabe } from '@equinor/eds-icons'` in a commojs project, it will import all the other icons in the library regardless. 

Since Typescript still uses `commonjs` for modules, we should look into providing named paths for components.

Example of relative path: `import Button from '@equinor/eds-icons/save'` or if we include category  `import Button from '@equinor/eds-icons/ui-action/save'`.

- [ ] Research/Analyse on how to solve this
- [ ] Check wether this can configured in rollup or not.

Notes: 
- https://material-ui.com/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking
- https://rollupjs.org/guide/en/#outputpreservemodules

**Comment by wenche** [comment]
By some simple manipulation of the browser field in the package.json in node-modules, we load the esm version and that is working as expected, it's almost invisible in the analyze image

![Skjermbilde 2021-09-15 kl  09 41 34 (1)](https://user-images.githubusercontent.com/1568252/133762673-4dff5ed7-6c56-4d00-91d6-099618429289.png)
![Skjermbilde 2021-09-17 kl  08 30 24 (1)](https://user-images.githubusercontent.com/1568252/133762714-ac9c86ec-4067-44b6-b91e-36f4c53c4ba4.png)

I initially thought that it was not necessary to use the browser field, since this package should be usable on both client and server out of the box. Not 100% sure though. But for Webpack (5 at least), `browser` has precedent over `module` so I guess that's why it will load the umd non three shakable version out of the box.

**Comment by wenche** [comment]
To clearify, to test this I did the following

- Changed to "browser": "dist/icons.esm.js" 
- Used Next.js CLI to produce a new production bundle
Results:
- In the analyze tool, the package is almost invisible
- In the chunk file, the icons are three shaked as expected
`"use strict";(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[322],{3010:function(h,e,t){t.d(e,{G4Q:function(){return n},g99:function(){return a},Ba8:function(){return u},kKs:function(){return c},YNA:function(){return v},BHP:function(){return d},OdJ:function(){return r},KzR:function(){return i},XVJ:function(){return s}});const a={name:"add_circle_outlined",prefix:"eds",height:"24",width:"24",svgPathData:"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 5v4H7v2h4v4h2v-4h4v-2h-4V7h-2zm-7 5c0 4.41 3.59 8 8 8s8-3.59 8-8-3.59-8-8-8-8 3.59-8 8z"},n={name:"add_circle_filled",prefix:"eds",height:"24",width:"24",svgPathData:"M2 12C2 6.48 6.48 2 12 2s10 4.48 10 10-4.48 10-10 10S2 17.52 2 12zm11 1h4v-2h-4V7h-2v4H7v2h4v4h2v-4z"},i={name:"remove_outlined",prefix:"eds",height:"24",width:"24",svgPathData:"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zM4 12c0 4.41 3.59 8 8 8s8-3.59 8-8-3.59-8-8-8-8 3.59-8 8zm3-1v2h10v-2H7z"},r={name:"remove",prefix:"eds",height:"24",width:"24",svgPathData:"M2 12C2 6.48 6.48 2 12 2s10 4.48 10 10-4.48 10-10 10S2 17.52 2 12zm5 1h10v-2H7v2z"},v={name:"calendar",prefix:"eds",height:"24",width:"24",svgPathData:"M20 3h-1V1h-2v2H7V1H5v2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 18H4V10h16v11zM4 8h16V5H4v3z"},s={name:"time",prefix:"eds",height:"24",width:"24",svgPathData:"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zM11 7h1.5v5.2l4.5 2.7-.8 1.3L11 13V7z"},d={name:"external_link",prefix:"eds",height:"24",width:"24",svgPathData:"M5 3c-1.093 0-2 .907-2 2v14c0 1.093.907 2 2 2h14c1.093 0 2-.907 2-2v-7h-2v7H5V5h7V3H5zm9 0v2h3.586l-9.293 9.293 1.414 1.414L19 6.414V10h2V3h-7z"},c={name:"arrow_forward",prefix:"eds",height:"24",width:"24",svgPathData:"m12 4-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8-8-8z"},u={name:"arrow_down",prefix:"eds",height:"24",width:"24",svgPathData:"m20 12-1.41-1.41L13 16.17V4h-2v12.17l-5.58-5.59L4 12l8 8 8-8z"}}}]);`

**Comment by mimarz** [comment]
Solved in release #1658
