### ISSUE TITLE
The cache time to live (TTL) for eds-static is 1m

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#1543]
**Describe the bug**

I would like a more efficient cache policy for eds-static than 1m.

**Steps to reproduce the bug**

Check with Lighthouse
![Skjermbilde 2021-09-07 kl  14 06 07](https://user-images.githubusercontent.com/1568252/132342863-c126edf1-8429-4efd-8c24-ee6301c806ec.png)

**Expected behavior**

The caching time for these resources should be a year or something. At least not 1m.

**Specifications**

- Version: All
- Browser: 
- OS:

**Comment by mimarz** [comment]
Better late than never, increased cache to 6 months! 🕺
