### ISSUE TITLE
ZeroHeight - Video documentation

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1550]

**Comment by lucasveil** [comment]
Need to produce an explanation video for this component in Zero Height:

- [ ] Table
- [ ] Data Grid Table
- [ ] Buttons
- [ ] Selection controls
- [ ] Card
- [ ] Side sheet
- [ ] List

**Comment by BeckyBrekke** [comment]
@lucasveil I removed the references to the videos in zeroheight where they weren't ready in case we are ready to launch the new storefront before the videos we can without the videos looking like they are missing. :-)

**Comment by BeckyBrekke** [comment]
There was a [duplicate](https://app.zenhub.com/workspaces/equinor-design-system-604f57c09e350a0011b654f4/issues/equinor/design-system/227) on the board, so I am closing that one and referencing this.

**Comment by akvam** [comment]
Close this. We have other US to discuss and agree related to documentation.
