### ISSUE TITLE
onBlur does not work when inside Tooltip

### ISSUE THREAD

**Issue by chrisors** [equinor/design-system#1558]
**Describe the bug**

When wrapping a <Tooltip> around a component that has an onBlur event, the onBlur is not triggered.

**Steps to reproduce the bug**

1. Check link to CSB [here](https://codesandbox.io/s/eds-tooltip-bug-5hxqc)

**Expected behavior**

The onBlur event to trigger

**Specifications**

- Version: 0.13.0
- Browser: Google Chrome Version 91.0.4472.164
- OS: Windows 10 Pro

**Additional context**

none

**Comment by mimarz** [comment]
Thanks for reporting this bug! 

Can confirm this is a bug [here](https://github.com/equinor/design-system/blob/595ad3da3dd55a528c11178d38090eac594be4a1/libraries/core-react/src/components/Tooltip/Tooltip.tsx#L169) as `Tooltip` overwrites some of the "anchors" handlers for its own gain! 🏴‍☠️

Should be a quick fix 😄 🤞
