### ISSUE TITLE
Map related technical icons

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/design-system#1581]
**Is your feature request related to a problem? Please describe.**

We use `@eds` `icons` today and would like some more technical icons related to map use cases.

**Describe the solution you'd like**

Create some new technical icons. We could if wanted provide this as a community PR towards `equinor/design-system`, if you can give guidelines + review on how you want the icons included (figma details, other icon principles etc.)

Screenshot of current draft/sketches: https://github.com/equinor/webviz-subsurface-components/issues/568#issuecomment-927800745

The icons will be relevant for (subsurface) map components (see https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/deckglmap--default as an example of the one we develop)

**Describe alternatives you've considered**

We could include these icons downstream in our own repository, if out of scope in `eds` technical icons.

**Comment by lucasveil** [comment]
@lucasveil answered directly in slack:

Hi 
Always a great contribution to add icons in EDS. Detailed instructions on how to create an EDS icon are coming in our upcoming release of Zero Height.
In the meantime, i suggest you check todays documentation here.
Our icons are mainly downloaded from Google material outline version.
Once your are done creating the icon, we can have a check on it and implement it in our library!
Thanks a lot for contribution and in the mean time don’t hesitate if you have questions

**Comment by lucasveil** [comment]
@benteljones @BirteThornquist can you have a look at the [new set of icons](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=2907%3A106341)?
The black ones are those suggested by the team, the green ones are the one we can implement in EDS.

**Comment by BirteThornquist** [comment]
LGTM @lucasveil Great job!

**Comment by benteljones** [comment]
@lucasveil  I think you have done a great job, Lucas! You further developed them all, gave them much better shape and a clear EDS expression. Only one thing; should the individual gridlayer symbol been a little bit bigger, so that if you set all of them up against each other, they still have the same aligned size value?

**Comment by lucasveil** [comment]
New icon is on the way to approval for the team. Waiting for feedback in order to make it review by @BirteThornquist and @benteljones

**Comment by lucasveil** [comment]
Last version [here ready to review](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=2954%3A107161) @BirteThornquist @benteljones 
The idea was to start from the layer icon and show extra details

**Comment by BirteThornquist** [comment]
Looking good @lucasveil! Could the diamond frame line be a bit more narrow (maybe too picky now...)

**Comment by lucasveil** [comment]
I used layer icon (with the feedback from Bente) as a starting point. If you use both icons next to each other, they should look the same otherwise ou get the "jumping" effect.

**Comment by lucasveil** [comment]
Will be published when dev resolves #1772
