### ISSUE TITLE
Create token preview in Storybook

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1586]
Suggest using a `Card` for each token with relevant information in card content for individual token.
Categories for each token set.

Examples to draw inspiration from: 

* https://components.ruter.as/#/Visual%20Style/Design%20tokens
* https://www.lightningdesignsystem.com/design-tokens/

**Comment by mimarz** [comment]
Prioritising this as we currently are working on improving our developer documentation. This will also be important to have when/if we do any token changes for our developers to get familiar with changes

**Comment by vnys** [comment]
Solved with the design token addon in the EDS 2.0 workshop repo
