### ISSUE TITLE
Input & Label stories crash

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1593]
The stories for `Input` & `Label` are crashing on latest version. Not sure if the bug is caused by component or something in story.

Fix this before releasing #1584 

![image](https://user-images.githubusercontent.com/1070981/135429113-f581561a-e00d-411e-8c70-5316866ff4f8.png)

**Comment by wenche** [comment]
Looks like it's the same thing as @pomfrida  [fixed the other day](https://github.com/equinor/design-system/pull/1569)

**Comment by mimarz** [comment]
> Looks like it's the same thing as @pomfrida [fixed the other day](https://github.com/equinor/design-system/pull/1569)

Jepp, removing `<code>` from description did the trick! Thanks for the heads up :)  @wenche
