### ISSUE TITLE
Create Navigation: App launcher component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#161]
**Description**

An app launcher provides navigation for applications related to the application the user is currently viewing.

**Documentation**

- [The storefront](https://eds.equinor.com/components/navigation-app-launcher/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A12)
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1)

**General guidelines**

See [COMPONENT_GUIDELINES.md](https://github.com/equinor/design-system/blob/develop/COMPONENT_GUIDELINES.md) for general guidelines like browser support and common implementation details

**Sub tasks**

- [ ] Write tests
- [ ] Create set of tokens (from base tokens)
- [ ] Create react component

**Comment by akvam** [comment]
Decided to not build a React component for the App launcher
