### ISSUE TITLE
Naming / Coloring issues for Dark Mode

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1611]

**Comment by vnys** [comment]
We have issues with dark mode in general, there’s not a one to one mapping from light to dark, as this issue is an example of. I suggest that this is something the new UI Designer who starts Monday 18th can start working on.

**Comment by BirteThornquist** [comment]
Covered by #1709

**Comment by mimarz** [comment]
closing this issue as its covered by another issue
