### ISSUE TITLE
Support for children in Label

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1614]
Currently you need to use the `label` property to set the label text in `Label` and ignores provided children. This makes it confusing to use at it goes against native behaviour of a `label` element.
The reason for it not support `children` and only be set through `label` prop was due to support for a meta text and positioning.

Actions:
* Find a solution for how it can support provided children
  - `children` are rendered along with `label` property value inside `Label`. Children takes presidence. Do we still need `label` property?
* Refactor will affect `TextField` component and "Selects".

**Comment by oddvernes** [comment]
Speaking of native behaviour, one of the most common things to put in as a child of label is input, to avoid having to link them with id. So then if we allow children, i expect people will expect to be able to do this also. But then it becomes a bit of a challenge to position things correctly, i.e an input should be placed below label/text children and meta...

**Comment by oddvernes** [comment]
I think for now, adding children in addition to label prop and meta prop is a bridge too far as far as this component goes. We may instead consider creating a new input-wrapper component and a separate label-component that behaves more natively.
