### ISSUE TITLE
Add additional ref property to complex components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1620]
For some our more complex components such as Selects, Textfields, Search, Checkbox, Radio, Switch etc we are using a wrapped input or some other interact-able element. 

In some use-cases our users would want to manually trigger or have access to events on the interact-able elements so that they then integrate it better into their app logic.

Example:
* Fetching data from an api when someone does and action or starts typing inside a select..

Notes:
* Look to `TextField` and `inputRef` for example of additional ref property

Actions:
* Determine which components need an additional "ref" property

**Comment by laliq** [comment]
Breadcrumb - mismatch types if `href` is undefined

**Comment by mimarz** [comment]
> Breadcrumb:
> 
> * mismatch types if `href` is undefined
> 
> Breadcrumbs:
> 
> * feil type
> 
> Button:
> 
> * mismatch types
> * `as?: ElementType` returns any
> 
> List:
> 
> * `as?: ElementType` returns any
> 
> Search:
> 
> * the clear button is a `div` element while in Select Multi.Select the clear button is a `button` element
> 
> Single & Multi Select:
> 
> * `input` missing ref
> 
> Table:
> 
> * `HTMLTableDataCellElement` deprecated, preferred `HTMLTableCellElement`
> * `HTMLTableHeaderCellElement` deprecated, preferred `HTMLTableCellElement`
> 
> Typography:
> 
> * `as?: ElementType` returns any

* Made an issue for the `as` properties #1736 
* Made an isse for the `Search` and clear button #1737

**Comment by laliq** [comment]
> Breadcrumb:
> 
> mismatch types if href is undefined
> Breadcrumbs:
> 
> feil type
> Button:
> 
> mismatch types
> as?: ElementType returns any
> List:
> 
> as?: ElementType returns any
> Search:
> 
> the clear button is a div element while in Select Multi.Select the clear button is a button element
> Single & Multi Select:
> 
> input missing ref
> Table:
> 
> HTMLTableDataCellElement deprecated, preferred HTMLTableCellElement
> HTMLTableHeaderCellElement deprecated, preferred HTMLTableCellElement
> Typography:
> 
> as?: ElementType returns any

- Made an issue for the `Table` #1739

**Comment by mimarz** [comment]
Closing issue as we have identified and created separate issues.
