### ISSUE TITLE
Distance between radio button/checkbox and label is now too long

### ISSUE THREAD

**Issue by ErlendLygre** [equinor/design-system#1633]
**Describe the bug**

After upgrading to 1.14.1, there is a padding-left of 12px added to the span containing the label text for a radio button.

<img width="281" alt="Screenshot 2021-10-19 at 18 30 33" src="https://user-images.githubusercontent.com/8993868/137953665-f337c2b1-4216-4092-97b3-05022c990d4f.png">

This creates an excessive amount of whitespace on mobile views.

<img width="1303" alt="Screenshot 2021-10-19 at 18 37 17" src="https://user-images.githubusercontent.com/8993868/137954366-46aa4aba-3099-42ff-95ed-4f515db2c8d7.png">

**Steps to reproduce the bug**

1.Add a <Radio>-element with a label.

**Expected behavior**

No padding-left on the label.

**Specifications**

- Version:
- Browser:
- OS:

**Additional context**

**Comment by mimarz** [comment]
Thanks for reporting this! 

I see this was changed in v0.14.0 in PR #1580. I can't recall now why this was added but we'll have a look at it, and get back to you :)
