### ISSUE TITLE
Create Navigation: Drawer component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#164]
**Description**

A navigation drawer displays categories of navigational links in a vertical column that can be scrolled.

**Documentation**

_Edit the following links to point to relevant information_

- [The storefront](https://eds.equinor.com/components/navigation-navigation-drawer/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A14)
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1)

**General guidelines**

See [COMPONENT_GUIDELINES.md](https://github.com/equinor/design-system/blob/develop/COMPONENT_GUIDELINES.md) for general guidelines like browser support and common implementation details

**Sub tasks**

- [ ] Write tests
- [x] Create set of tokens (from base tokens)
- [ ] Create react component

_This component is used in the storefront (see #106)_

**Comment by mimarz** [comment]
good'ol drawer 🤦‍♂️ @vnys

**Comment by vnys** [comment]
> good'ol drawer 🤦‍♂️ @vnys

🙈

**Comment by akvam** [comment]
This have more functionality than the Side Bar, and the US is therefore keept.

**Comment by BirteThornquist** [comment]
This will be solved by the additions we are doing for the Sidebar #2608
