### ISSUE TITLE
Align on label spacing to selection controls

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1640]
We keep changing the spacing on our labels to selection controls ( Checkbox, Radio and Switch). This is causing confusion (#1633) and inconsistencies between our releases.

Actions:
* Decide on spacing between label and selection controls
* Implement

**Comment by oddvernes** [comment]
After discussing with @BirteThornquist it has been decided to remove the extra 12px padding so that the total distance is 12px.
