### ISSUE TITLE
Next and previous icon button for navigation in Tabs 

### ISSUE THREAD

**Issue by herda1** [equinor/design-system#1650]
**Describe the bug**

Scrolling of tabs horizontally does not have 'next and previous icon button for navigation' in navigation tabs as described in [EDS components](https://eds.equinor.com/components/navigation-tabs/). 

![image (20)](https://user-images.githubusercontent.com/24807240/138447059-4698bc01-ee83-4d2d-8b31-7666be363f48.png)

**Steps to reproduce the bug**

1. Go EDS storybook
2. Go to Components -> Tabs -> States
3. Reduced the browser width
4. Try to scroll
5. Check that the clickable next and previous icon buttons for navigation are missing  

![CPT2110221338-375x732](https://user-images.githubusercontent.com/24807240/138447589-e5362383-7965-464e-9162-816835043940.gif)
.

**Expected behavior**

- Add button (chevron) to scroll right or left when applicable
- Horizontal scrolling as clicking the button (chevron)
- Fade overlay to indicate more tabs

An example of tabs with the expected behavior is shown below: 

![image](https://user-images.githubusercontent.com/24807240/138448267-50d8ff03-415d-437e-a550-2c3a8f32a1b0.png)

**Additional context**

https://codesandbox.io/s/small-bash-qs5he?file=/src/App.tsx

**Comment by nilsml** [comment]
I have been told that two teams are waiting for this fix. We should discuss this is tomorrow's planning meeting.

**Comment by BirteThornquist** [comment]
Decided in todays planning meeting to find a way to help them so they can implement a previous/next chevron in their tab menu. We will not add the chevrons to the tab component in EDS. We will however look into how we can create a responsive tab menu. This will be handled in a separate issue  #1889

**Comment by akvam** [comment]
To do: 
* Help team with the technical solution
* Update the documentation

**Comment by vnys** [comment]
As I wrote in [the pr](https://github.com/equinor/design-system/pull/1915), Google is investigating how to solve the issue of too many tabs to fit in the tab strip. In Chrome right now you can test out different options and give them feedback.

<img src="https://user-images.githubusercontent.com/2081882/151013943-2ad07cf0-8c7c-497b-8de9-0dc5e509ca41.png" width="280">

**Comment by vnys** [comment]
Possibly something to look into
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap
- https://caniuse.com/?search=scroll%20snap
