### ISSUE TITLE
If placeholder in multiselect is undefined, it should display the standard text

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#1651]
Now it is like this
![image](https://user-images.githubusercontent.com/35257765/138665921-6a035bf8-de78-48f9-a53b-0f7867898cee.png)

We use this to have it say "all" when there is no items selected

**Comment by mimarz** [comment]
We have added support for providing your own placeholder text (in our [WIP] `Autocomplete` component). By default the "x/y items selected" will be shown unless placeholder is defined. If you are setting your own placeholder text for multiple selections make sure its declarative of whats selected in the dropdown, this is especially important for people using screen-readers.
