### ISSUE TITLE
Change the arrow icon in table sorting examples in Figma.

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1654]
The sorting arrow has been changed in code, and must also be changed in Figma examples.

**Comment by BirteThornquist** [comment]
Ready for review @lucasveil. I changed the chevron-down to an arrow-up for ascending sorting and arrow-down for descending order.

**Comment by lucasveil** [comment]
Could you give me the figma link @BirteThornquist ?

**Comment by BirteThornquist** [comment]
Ah, sorry @lucasveil . [Here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=977%3A30972) is the link

**Comment by lucasveil** [comment]
Looks really good :)

**Comment by benteljones** [comment]
Totally agree with Lucas; looks really good, @BirteThornquist!
