### ISSUE TITLE
Select components: Add helpertext - document variant property

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#1660]
Similar to TextField component, it would be nice to have the same properties to the select components. This would be useful to display error messages and other info

![image](https://user-images.githubusercontent.com/35257765/139027379-ca744a2a-9029-45b9-ae7c-9e5312f90cd7.png)

**Comment by BirteThornquist** [comment]
Select is changed to autocomplete.

**Comment by oddvernes** [comment]
resolved by #3139
