### ISSUE TITLE
MultiSelect: be able to clear searchvalue when unfocusing or clicking X

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#1664]
When searching for an item in the dropdown and no results/ or you do not select an option, it should be possible to clear the value entered somehow. I would say it should be cleared when clicking the X, like for instance here (picture under). And also if you have searched for somethig and do not click any options, and then unfocus the component

![image](https://user-images.githubusercontent.com/35257765/139404820-4c6157d8-c70a-4270-a564-c3023d7d49ff.png)

Similar to the SingleSelect component.

Now, we can do this in our application

![image](https://user-images.githubusercontent.com/35257765/139405020-b2f3820b-9dc8-496f-9bea-38d41520d482.png)

There is now way to clear the searchvalue without manually removing the text

**Comment by mimarz** [comment]
Sorry for the late reply! 😅

This does look like a bug to me, intended behaviour should be as you described :)
