### ISSUE TITLE
📝Spike using storybook-addon-jest

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#1665]
trying out this addon to see if it is useful during development

**Comment by oddvernes** [comment]
The question is how to make this useful during development. I tried running storybook and test:watch at the same time but it gets into an infinite loop of rebuilding storybook

**Comment by mimarz** [comment]
After testing the addon in storybook I agree that its kinda cumbersome to use with a lot of manual steps in Storybook. So no use for us as it can't beat having just having `test:watch` running in the terminal.
