### ISSUE TITLE
Menu Item onClick not running correctly in scrolling container

### ISSUE THREAD

**Issue by mariush2** [equinor/design-system#1668]
**Describe the bug**

Clicking `Menu.Item` doesn't run onClick event as expected when dynamically creating Menu component with max-height and overflow: auto.

**Steps to reproduce the bug**

1. Create Menu component with `overflow: auto` and `max-height: 'some-value'`
2. Create Menu.Item's inside Menu.Section(s) (same bug appears if all the items are in the same section) 
3. Click Menu.Item
4. Menu scrolls to bottom instead of running onClick

**Expected behavior**

Clicking Menu.Item's inside Menu.Section's which are in turn inside a styled Menu-component with max-height and overflow should just run onClick event and not scroll to bottom on first click.

**Specifications**

- Version: 0.14.2
- Browser: Chrome 95.0.4638.54
- OS: macOS

**Additional context**

Codesandbox: [https://codesandbox.io/s/focused-wind-7flk0?file=/src/App.js](https://codesandbox.io/s/focused-wind-7flk0?file=/src/App.js)

Video:

https://user-images.githubusercontent.com/24507952/139652458-0fc5e07b-124f-4eb5-982b-66fa7e2fdaea.mov

u

**Comment by mimarz** [comment]
Thanks for the feedback! 

This could be related to how we handle focus inside the `Menu` as it has support for keyboard navigation and "focus on open", possible related bug #605.
