### ISSUE TITLE
Add dark theme information on storefront

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#1670]
![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/c39c503f-ad4b-4796-b497-641468abf259)

Need updates to our color information on the storefront regarding dark theme

**Comment by mimarz** [comment]
Can one of you update this paragraph? @BeckyBrekke @lucasveil

**Comment by lucasveil** [comment]
Added a new section in https://eds.equinor.com/0b0c666ab/p/78c75b-colour/b/708097
with a text explaining that dark mode is only avaialble in Figma. Is this enough @BeckyBrekke ?

**Comment by BeckyBrekke** [comment]
What about in this paragraph we say we "don't allow" for dark mode. Should that be removed? Do we need to say anything about how to use dark mode in Figma? 
Should the dark mode color palette at least be added here so people know what it is @benteljones ? Or do we wait until it is available in code too?

**Comment by benteljones** [comment]
The colors of dark mode  will be adjusted in the new 2.0 version using Figma Tokens, and then become available in code afterwards. How do we convey this best @BeckyBrekke @lucasveil ?
