### ISSUE TITLE
Add new call to action component for button ghost icon

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1677]
We got a [feature request from eds sandbox](https://www.figma.com/file/hjpavZkeUoRfn1N7mhIniK/EDS-designer-sandbox?node-id=151%3A43705).
The example shown is from an application that needs to make a main CTA more visible than a ghost button icon. The request is to implement a ghost icon with moss green background and the icon in white.

**Comment by lucasveil** [comment]
We got a [feature request from eds sandbox](https://www.figma.com/file/hjpavZkeUoRfn1N7mhIniK/EDS-designer-sandbox?node-id=843%3A41839).
The example shown is from an application that needs to make a main CTA more visible than a ghost button icon. The request is to implement a ghost icon with moss green background and the icon in white.

**Comment by akvam** [comment]
Based on the sandbox example, is the request also about having a round buttons option ?

**Comment by mimarz** [comment]
> Based on the sandbox example, is the request also about having a round buttons option ?

yes. I updated the figma link in the issue as it was pointing to the wrong example in the sandbox.

**Comment by mimarz** [comment]
We had a meeting on 21 june where we decided to implement this as a new variant called `ghost_contained`.

**Comment by lucasveil** [comment]
Ghost Icon contained implemented in the system!
https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A47297
Ready for review @BirteThornquist @benteljones

And 50 new components on the way :)

**Comment by lucasveil** [comment]
Just remembered i need to write down the documentation.

**Comment by lucasveil** [comment]
Change the name of the component from Ghost Icon Contained to Icon Contained in order to keep consitensy in the system.

**Comment by benteljones** [comment]
👍🏻

**Comment by BirteThornquist** [comment]
Looking good @lucasveil! Just a few comments:
- I think we should name it "Contained Icon" so we keep the naming consistent with i.e "Ghost Icon". Maybe also add the heading at the top 
- the hover hand is missing
- for the Secondary/pressed the overlay color is wrong

**Comment by lucasveil** [comment]
Good catch @BirteThornquist 
- Name have been changed + name on the category added
- Hover hand won't be implemented in this version
- Color on Secondary / pressed have been rectified

Ready for new review
