### ISSUE TITLE
Plan EDS Core Team Workshop in April / May

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#1683]
Rename to reflect correct month

**Comment by akvam** [comment]
The plan is to have a 2 days workshops so all can meet each other. 
To limit traveling the workshop should be in Stavanger or Bergen.

**Comment by vnys** [comment]
Some topic suggestions:
- Meet the developers
- Promoting componens from other teams
- Adopting components from other teams

**Comment by vnys** [comment]
We’ll use the backlog meeting after Easter to decide which topics to include

**Comment by akvam** [comment]
For details after meeting see: https://www.figma.com/file/SsnSFw2KCSDHB8JAwiu93v/Road-Map---Teams-Workshop

**Comment by mimarz** [comment]
Completed!
