### ISSUE TITLE
⚡ Spike bold font on hover

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1684]
Relevant notes from meeting leading to this issue:
* using text-stroke was deemed not feasible as it ruins the font
* using "title-hack" works, but only for text. All our components accepts react nodes as children so any if anyone supplies anything other than text this approach would not work.

**Comment by vnys** [comment]
Going to deploy this to Azure for now, and revisit it when we have solved the colour issues

**Comment by vnys** [comment]
Can’t get Azure cli or the Blob Storage extension to work with Codespaces, so no deployment anywhere. But I’ve made a branch with Frida’s implementation which is called “frida-bold-hover”. Closing this issue for now.
