### ISSUE TITLE
The text and illustration overlaps on small devices

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1698]
Very limited options here, but as far as I can tell the best thing we can do is move the description out of the banner area, increase the image size, and anchor it to the right.What do you think, @equinor/eds-ux, @BeckyBrekke?

https://zeroheight.com/1a694e6b8/p/40bb6b-equinor-design-system

**Comment by BeckyBrekke** [comment]
Looks like that is the best option. I think Bente is ready with the new hero image. Can you guys coordinate the new image with the text outside of the banner area? 
Her issue: https://github.com/equinor/design-system/issues/1116
