### ISSUE TITLE
Don’t use the density prop directly in Storybook

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1707]
In the stories in Storybook we use `compact` directly as a value for the `density` prop. This is just the thing we _don’t_ want users to do – so these stories need to be updated asap.

Example: https://eds-storybook-react-development.azurewebsites.net/?path=/docs/components-button--default#compact

**Comment by mimarz** [comment]
Good point. I would not say this is something that needs to be done _asap_ though, fixing #1705 for example has higher priority as affects everyone.

What if we add a separate (or use our [existing examples](https://eds-storybook-react-development.azurewebsites.net/?path=/story/playground-examples--test-page&globals=backgrounds.grid:false)) page in Storybook and update the description for every compact sub-story that a density switcher should be used in conjunction with compact mode etc.  🤔

This should save us for lots of maintenance and clutter trying to have a switcher for each compact story (times 32).
