### ISSUE TITLE
Overview and review of current naming and color logic

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#1709]
We will review the color styles in EDS and make sure we have a good naming system that  is coherent between light and dark theme. The color tones itself will be evaluated to make sure they work regards to contrast and information architecture. Colors used for validation and states will also be reviewed, and we will introduce more colors to support information graphic and flexibility in general.

**Comment by BirteThornquist** [comment]
@benteljones I added a description - does it cover the issue?

**Comment by benteljones** [comment]
Well done, Birte!
