### ISSUE TITLE
Adjust Card.Media spacing

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1713]
We discovered inconsistencies for CardMedia in Card when its the last child that we need to adjust.

**Comment by benteljones** [comment]
![Skjermbilde 2021-11-23 kl. 14.14.37.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/e1cb228c-e0d4-4974-bf41-bcba907659a3)

https://www.figma.com/file/MDkIHZdkMUw23EKI5HT83T/Bente?node-id=169%3A53764

**Comment by mimarz** [comment]
Missing review with @lucasveil . Can you have a look?

**Comment by lucasveil** [comment]
Had a review and agreed with @benteljones and @birte at no there shouldn't be any spacing. I don't see any spacing noww in Figma. Did you @benteljones fixed it?

**Comment by vnys** [comment]
Update the documentation in Figma

**Comment by nilsml** [comment]
Code needs to be updated

**Comment by lucasveil** [comment]
Ready for review [here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=6598%3A112016) @benteljones @BirteThornquist

**Comment by benteljones** [comment]
LGTM 👍🏻

**Comment by mimarz** [comment]
During my review of PR #1735 I saw that we have not looked at how it should look when the images is not set to "fullwidth". How should it look then? @benteljones @lucasveil  @laliq

This is how it would look with "default" spacings:

Should the image also have a round edges when its not full width? (straight edges now)
![image](https://user-images.githubusercontent.com/1070981/143856833-41505e87-0865-47f9-a7aa-bd6de70066f6.png)

**Comment by laliq** [comment]
Good point @mimarz, i was thinking about it to today, when i did the adjustment. 
But then again, when you look at the other design systems it looks like Card with media has only full width.

**Comment by mimarz** [comment]
> Good point @mimarz, i was thinking about it too while making the adjustment. But then again, when you look at the other design systems it looks like Card with media has only full width. While fallowing your though Card looses its own defined look.

hehe, yeah, it would make it a lot easier to just remove the `fullWidth` toggle all-together.

**Comment by nilsml** [comment]
Discuss with designers about fullWidth

**Comment by nilsml** [comment]
@lucasveil add design in Figma

**Comment by lucasveil** [comment]
Example in Figma updated
