### ISSUE TITLE
Chip text seems misaligned

### ISSUE THREAD

**Issue by khollund** [equinor/design-system#1717]
**Describe the bug**

The chip text seems top aligned in both local code and on EDS storybook after some recent changes.

**Steps to reproduce the bug**

1. Visible in the storybook on EDS 

![image](https://user-images.githubusercontent.com/25321939/143207298-5113471a-3115-4091-8e3f-262ca935f132.png)

**Expected behavior**

Text to be vertically centered and aligned with x / remove icon

**Specifications**

- Version: 96
- Browser: Chrome
- OS: Windows

**Comment by mimarz** [comment]
Work on my machine! 🙈
![image](https://user-images.githubusercontent.com/1070981/143208766-839b598b-2c5a-4d1c-a147-0659063d4215.png)


I assume this has to do with text sizes in Windows OS and zoom level 🤔
What text/font size do you have in your windows OS?

**Comment by khollund** [comment]
Strangely, it is misaligned on the 100% 1440p monitor, on my 175% scaled 3000x2000 monitor it looks correct 😁

**Comment by khollund** [comment]
I'd assume setting the styling rules stricter would fix it though?

**Comment by mimarz** [comment]
> Strangely, it is misaligned on the 100% 1440p monitor, on my 175% scaled 3000x2000 monitor it looks correct 😁

Theres your problem! Now you have a excuse to upgrade to a new monitor 😂

**Comment by khollund** [comment]
> > Strangely, it is misaligned on the 100% 1440p monitor, on my 175% scaled 3000x2000 monitor it looks correct 😁
> 
> Theres your problem! Now you have a excuse to upgrade to a new monitor 😂

😀 Browser scaling being the preferred method of accessibility has some upcoming nice hurdles I think 🙀

**Comment by mimarz** [comment]
hmm, so what to do here? 🤔 @khollund

**Comment by khollund** [comment]
I would add some rules to make it stricter. But probably hard for you to test?

**Comment by oddvernes** [comment]
Looks to me like text is pushed up slightly because of the line height

**Comment by oddvernes** [comment]
After some more testing: Removing the line-height, while looking more centered on some screens, also looks too low on other screens/resolutions/scalings. So we are leaving it be for now

**Comment by bjartebore** [comment]
Probably not a fix worthy of a PR, but here is a hack for anyone who is as annoyed by this as I am.

```
import { Chip } from '@equinor/eds-core-react';
import styled from 'styled-components';

// This is a hack to adjusrt
export const AdjustedChip = styled(Chip)`
  @font-face {
    font-family: EquinorAdjusted;
    src:
      url(//cdn.eds.equinor.com/font/Equinor-Regular.woff2) format('woff2'),
      url(//cdn.eds.equinor.com/font/Equinor-Regular.woff) format('woff');
    font-style: normal;
    descent-override: 0%;
    ascent-override: 80%;
    font-weight: 400;
  }
  font-family: EquinorAdjusted;
  vertical-align: middle;
`;

```
