### ISSUE TITLE
The prettier extension in VS Code does not use prettier from the project

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1718]
**Describe the bug**

When using formatOnSave there is a particular line that ends up being formatted in a way that prettier complains about after formatting, even though prettier is the formatter. The code block in question is this one:

```tsx
export const Compact: Story<RadioProps> = () => {
  const [density, setDensity] = useState<EdsProviderProps['density']>(
    'comfortable',
  )
}
```

…which when running the format document command in VS Code gets formatted like this: 

```tsx
export const Compact: Story<RadioProps> = () => {
  const [density, setDensity] =
    useState<EdsProviderProps['density']>('comfortable')
}
```

This leads me to believe there are different versions of prettier at play here…

**Comment by vnys** [comment]
Turns out the symptom of the issue is made visible after [an assignment formatting improvement in prettier v2.3.0](https://prettier.io/blog/2021/05/09/2.3.0.html#javascript). But the underlying problem is that the version of prettier that’s used in VS Code is not the one installed in the project, as suspected.

**Comment by vnys** [comment]
Changing the format of package.yaml to json did not resolve this issue

**Comment by oddvernes** [comment]
I have resorted to turning off the formatOnSave setting in .vscode/settings.json since it breaks the linting in many files and is very annoying

**Comment by vnys** [comment]
Me too, but I want to find the root of the problem. There was a breaking change in `v2.3.0`, which may result in lots of files being reformatted. The solution to two different versions of vscode being used simultaneously is to add the following to settings so that the extension finds the locally installed module: `"prettier.prettierPath": "./node_modules/prettier"`. I first thought it could have something to do with the format of package.json since we use yaml in the root, but I now suspect it has something to do with monorepos and root `node_modules`.

**Comment by vnys** [comment]
Nope…

**Comment by vnys** [comment]
…but we do have different versions of prettier in the root and in core-react. Could have something to do with it.
