### ISSUE TITLE
Redesign homepage in Zeroheight

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1726]
In Zeroheight and using its limitations, redesign the homepage structure

**Comment by vnys** [comment]
Let me know if you want to discuss this @lucasveil, I’m going to work on #1728 so we should align a bit.

**Comment by BirteThornquist** [comment]
@lucasveil I think it's a good idea to structure the home page as you have done here (and I particularly liked the first section ;-) ) I just removed the H1 and used space instead. Think it can work...? Maybe the icons can be worked on, yes, and I'm not fan of that lichen green as I think it is too sharp. But that is just details. Well done!

**Comment by lucasveil** [comment]
Agreed, picture with icons are not the best. Will find a better alternative if the draft is approved. We should check with @equinor/eds-dev what is the best practice for spacing between sections

**Comment by vnys** [comment]
I think this looks good 👍🏻 I’ve uploaded the current version of the svg to https://zeroheight.com/1a694e6b8/v/latest/p/40bb6b-equinor-design-system, but I can add it to your frontpage instead. Currently working on embedding the font – and there are parts of the illustration missing at the moment.

**Comment by vnys** [comment]
About the images, I think we should use svg if that’s possible. And perhaps we should use a colour combination from the illustration?

**Comment by lucasveil** [comment]
After testing, you can import a .svg as an image. So i tried to set up up the svg with the pattern color of the header image. [Test is here](https://zeroheight.com/57e0c5760/v/latest/p/94d101-eds-homepage-test). Gives more space but unsure if it makes the trick @vnys @BirteThornquist @benteljones @BeckyBrekke

**Comment by BeckyBrekke** [comment]
I'm having a hard time seeing what is what now. Maybe we can look at it together Wednesday with the others?

**Comment by lucasveil** [comment]
- updated wht's new section
- changed "About us" to "Getting started"
- changed colors for categories
- updated "hr"
- cleaned all the <p> tags
- fix typo 

Need some more time to make custom icon for each category

**Comment by lucasveil** [comment]
Update the 'hr' so that it is pixel perfect with [figma design](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3011%3A107667)
