### ISSUE TITLE
Adjust color on Switch selection controler

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1731]
After discussion with designer in ECHO team, the selection control (medium) has bad contrast when it is on:

![Screenshot 2021-11-26 at 16.10.50.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/5297418f-29b9-42af-86eb-302047628450)

Can be related to #1685

**Comment by vnys** [comment]
Closed as this will be resolved in EDS 2.0
