### ISSUE TITLE
New icon set from Echo Team

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1734]
Echo team came in with a set of new icons that can be useful in EDS library

**Comment by lucasveil** [comment]
Ready for review [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=2932%3A106657) @BirteThornquist @benteljones

**Comment by benteljones** [comment]
The icons look very good, Lucas. Some may seem a little bigger than the others (heat-trace, manual-valve) but I know how extremely difficult this is –  to get an optical similarity on everyone. It will most likely just move the challenge to another location, reducing common form or line logic. I think it's as good as it gets. You are a master of icons, @lucasveil! 👏

**Comment by BirteThornquist** [comment]
LGTM! Great job @lucasveil 👍

**Comment by mimarz** [comment]
We need to follow up with icons export to `eds-icons` package when this is done.

**Comment by lucasveil** [comment]
That is the plan @mimarz When the icons are set in Figma, i will make a issue for release in dev and then publish :)

**Comment by lucasveil** [comment]
Will be published when dev resolves #1772
