### ISSUE TITLE
Casting elements using "as" and correct Typescript type

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1736]
We are using the property `as` to mimick styled-components api for casting an element-type to one or the other. 

We have used `ElementType` from `react` for this but are uncertain now if its the correct type to use as its flagged as "any" value in reality.

Casting components from one element type to another also poses a problem as the props type is not changed/updated to reflect the new set of native attributes a component has. Most notable example of this is when `Button` is casted from `button` to `a` when `href` is defined. You are unable to set any of the `a` [properties](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes) as type is still set to `button.`

Affected components `Button`, `List`, `Typography`, `Breadcrumbs.Breadcrumb`

**Comment by mimarz** [comment]
related issue #1308

**Comment by mimarz** [comment]
Based on the testing @oddvernes did in #1897, maybe we should add the polymorphic type in utils for use in other needed components. 

Based on [this reddit thread](https://www.reddit.com/r/reactjs/comments/tjwiak/what_is_the_best_way_of_writing_a_polymorphic/), I feel like this implementation was clean:

* Types: https://github.com/biswarup35/material-you/blob/v0.1.x/packages/material-meeu/src/types/PolymorphicWithRef.d.ts

* Usage in component: https://github.com/biswarup35/material-you/blob/v0.1.x/packages/material-meeu/src/Button/Button.tsx

**Comment by vnys** [comment]
Will be fixed by #2338
