### ISSUE TITLE
Add compact density for Search

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1747]
- [ ] Design/Figma

- [x] React

- [ ] Documentation

**Comment by mimarz** [comment]
@equinor/eds-ux Does anyone have time to look at this in code? We implemented a compact variant based on `TextField` dimensions.

**Comment by mimarz** [comment]
reopened as design & documentation still needs to be done.

**Comment by akvam** [comment]
Moved to Epic 2.0 so that the team can see all comments on this US. (All US on Compact should be closed or moved.)
