### ISSUE TITLE
Update eds-icons with new Figma icons

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1772]
New set of icon have been implemented in Figma. 
- [launch](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3731) (replacing external icon)
- [go-to](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3731)
- [fault](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730) 
- [grid layer](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [grid layers](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [hill shading](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [well](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [surface layer](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [electrical](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3728) 
- [ducting](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [function](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [manual valve](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [pipe support](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [heat trace](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905) 
- [instrument ](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [junction box](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [line](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905) 
- [telecom](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905)
- [tag main equipment](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3720)
- [tag special equipment](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3720)
- [tag more](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3720)
- [thumb pin](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3729)
- [log in](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=103%3A2380)
- [log out](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=103%3A2380)
- [miniplayer](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [miniplayer fullscreen](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3730)
- [tag relations](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3720)

**Comment by lucasveil** [comment]
@mimarz @oddvernes here is the list of icons to update in dev. We will release them in figma when your are done.

**Comment by mimarz** [comment]
As mentioned on slack, we need a different name for the icon named `function` as its a reserved work in javascript (since we use icon variables named after icon).

**Comment by lucasveil** [comment]
Waiting feedback from Echo-team

**Comment by mimarz** [comment]
> Waiting feedback from Echo-team

What the suggested name? `function-symbol` ?

**Comment by lucasveil** [comment]
Yes, need to know in which context they use it and which name could suits better than "function"

**Comment by mimarz** [comment]
> Yes, need to know in which context they use it and which name could suits better than "function"

Looking at the icons, its the symbol for "function" 🤔 Could you change it in the figma file to `function-symbol` for now atleast, so I can test the export and validate the other icons, its currently crashing due to this name.

**Comment by lucasveil** [comment]
Done :)

**Comment by lucasveil** [comment]
Echo team suggest "formula" could this work?

**Comment by mimarz** [comment]
@lucasveil I see `launch` has changed from 
![image](https://user-images.githubusercontent.com/1070981/145200307-e6216acb-5d3a-4bdd-9a8c-911509291a49.png) 
to 

![image](https://user-images.githubusercontent.com/1070981/145200344-fca51ee8-da27-4f39-9893-703d52ca1d98.png)

Is this correct?

**Comment by mimarz** [comment]
> Echo team suggest "formula" could this work?

`formula` should work 👍

**Comment by lucasveil** [comment]
Yes! This is correct. We used the same icon for "launch" and "external link" which was confusing for users
