### ISSUE TITLE
`fault` icon different in storybook and in downloaded `.svg`

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/design-system#1793]
**Describe the bug**

Storybook icon `fault` is not consistent with `.svg` download of same icon from storybook.

**Steps to reproduce the bug**

1. Go to https://eds-storybook-react.azurewebsites.net/iframe.html?id=icons--preview&viewMode=story and search for icon `fault`
2. Observe that one arrow is missing in the storybook...
3. ..while both are present if you download + open the `.svg` from the storybook.

**Expected behavior**

Consistent behavior between 2. and 3. above (and that both arrows are present in Storybook).

**Comment by mimarz** [comment]
This bug is probably due to svgo's optimize, since the svg file is not optimized by svgo.
