### ISSUE TITLE
Documentation on icon layer order

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1796]
In Figma, for complex icon, the order of vector layer is important when it is compiled as an .svg.
For example "fault" icon was missing an arrow because this layer was placed on the top.
We need to write a good documentation for eds-core team and other users that wants to contribute with icons.

**Comment by lucasveil** [comment]
Updated the text in [Documentation page](https://zeroheight.com/57e0c5760/v/latest/p/8487e9-system-icons/b/5072bd) with:

If you create an icon with multiple shapes and in order for your icon to convert in the right way as an .svg, you have to organise your layers from left to right.

![Screenshot 2021-12-10 at 15.09.27.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/f1bcc318-214d-44e2-bc94-fc7768c2a30f)

Does it make sense @BirteThornquist @benteljones @mimarz

**Comment by mimarz** [comment]
Suggestions for adding documentation on pixel preview. Create seperate issue for this? @equinor/eds-ux

**Comment by lucasveil** [comment]
Documentation is now updated and we need to have a deeper look into icon and svg. 
We have now a new issue for this:
