### ISSUE TITLE
Add wind turbine icon

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1801]
Wind turbine icon is missing in our library.

**Comment by lucasveil** [comment]
[Noe som fungere best](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3017%3A108241) @BirteThornquist @benteljones

**Comment by BirteThornquist** [comment]
Ser veldig bra ut @lucasveil ! Jeg syns kanskje nr. 2 på øverste raden passer best. Den er litt skarpere i kantene og jeg liker bedre når flatene i formen ikke er fylt, syns det passer best med de andre ikonene vi har. Men her er det jo små nyanser...

**Comment by lucasveil** [comment]
@equinor/eds-dev icon ready [in Figma](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3728)

**Comment by mimarz** [comment]
published in #1818
