### ISSUE TITLE
Add compact version of icons

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#1807]
- [x] Design

- [x] React

- [x] Documentation

**Comment by BirteThornquist** [comment]
In todays backlog meeting we decided to a compact version of a subset of the most relevant icons at first. We will inform our users about which icons we prioritize, and welcome input for other icons that also should be offered in a compact version. 

We will create a list of prioritized icons.

**Comment by lucasveil** [comment]
Main icon for first release:

- [ ] placeholder icon 
- [ ] chevron
- [ ] arrows
- [ ] subdirectory
- [ ] fullscreen
- [ ] alert
- [ ] accessibility
- [ ] check circle outline
- [ ] close
- [ ] calendar 
- [ ] search
- [ ] checkbox
- [ ] clock
- [ ] error filled
- [ ] warning filled
- [ ] thumbs up
- [ ] placeholder icon

**Comment by BirteThornquist** [comment]
I have made a small icon version of the first subset as a variant of the component. The property is called  "Density" with values Default (24px) and Small (18px).  
Pls review @lucasveil @benteljones @vnys

**Comment by lucasveil** [comment]
Looking good to me @BirteThornquist 
I have updated description for all the icons.

**Comment by BirteThornquist** [comment]
I updated the lines to 2 px where this can be done. Design is now done and ready for review @benteljones @lucasveil

**Comment by benteljones** [comment]
LGTM! 😊 @BirteThornquist

**Comment by mimarz** [comment]
> I updated the lines to 2 px where this can be done. Design is now done and ready for review @benteljones @lucasveil

I guess this means we need to export the icons again?

**Comment by lucasveil** [comment]
Looking very good @BirteThornquist :)

**Comment by lucasveil** [comment]
Depending on #1976

**Comment by lucasveil** [comment]
Documentation is ready to review [here](https://equinor.zeroheight.com/styleguide/s/58798/p/347dd6-system-icons/b/25520a) @BeckyBrekke 
Just added  "When using compact mode the size of icons are 18px"

**Comment by BeckyBrekke** [comment]
Reviewed and added to the latest release so it is visible to users now.
