### ISSUE TITLE
Update calendar icon

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1809]
There is an inconstancy in our calendar icons[Screenshot 2021-12-15 at 11.25.55.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/a3f18f0b-b8d3-4a79-acec-d8e7393d355e)

Ref to [this thread in slack](https://equinor.slack.com/archives/GEF6LDVT9/p1639144569135000), we need to set the right size to the calendar set.

**Comment by lucasveil** [comment]
It shows that the calendar icon is not following our grid:
![Screenshot 2021-12-15 at 14.53.41.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/a0d882aa-80b3-4124-8705-e1d54edc6d9d)
I have updated it [in Figma](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3718) for info @BirteThornquist @benteljones @vnys 
@equinor/eds-dev ready for release.

**Comment by mimarz** [comment]
published in #1818
