### ISSUE TITLE
Create Group component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1812]
Based on #394 we need a "Button group" component. Be it for only for internal and/or external use we need a way of grouping several elements together with a distinct styling to show they are related to one another.

The Button group component should be a simple container component that groups its children and only applies rounded corner to the outer edges.

Notes:
* Container which removes border-radius of its children
* Only applies rounded corners to its outer edges
* No spacing between its children
* Styling of children should work for all elements
* Naming of said component, discuss what makes most sense
  * `Group` ~`ButtonGroup` or  (sub-component)`Button.Group`~

**Comment by oddvernes** [comment]
The buttons in this might also need a different focus-visible design than normal buttons

**Comment by vnys** [comment]
> The buttons in this might also need a different focus-visible design than normal buttons

That’s true. We probably need to change the z-index on hover so the focus-frame doesn’t get hidden by adjacent buttons.
