### ISSUE TITLE
Use the Equinor logo in Zeroheight

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1851]
Somebody gave me a heads up that we may break company guidelines by not displaying the Equinor-logo in Zeroheight. Some action points:

1. Find out what the [styleguide](https://communicationtoolbox.equinor.com/brandcenter/en/equinor/) says
1. Determine how and where we should put it

Zeroheight has [a footer](https://help.zeroheight.com/3xlwst8/p/3911cb-styleguide-footer) too where we can have Equinor named and copyright, but we must upgrade to the enterprise agreement with them. 

Radix does not have logo or Equinor mentioned: https://radix.equinor.com/

Contact from COM (after Nick): Sheyda Aalgaard, Lead Cons Comm, sheaa@equinor.com

Examples from other design systems: 
[Intuit](http://wrclarke3.com/ids)
[Spectrum](https://spectrum.adobe.com/) - has Adobe logo but no copyright or link to Adobe
[Decatholon](https://www.decathlon.design/726f8c765/p/71b8e3-decathlon-design-system) has a separate section for legal

**Comment by BeckyBrekke** [comment]
Good point. I thought we asked about this before but not sure. I did ask COM about this with regards to IOC applications and they said it was totally unnecessary for internal applications but we are open externally . 
It doesn't say on the communication toolbox. We should probably talk with COM about this. We don't really say anywhere what or who Equinor is and how to get in contact with the company.

**Comment by BeckyBrekke** [comment]
I checked the other familiar design systems, and they all have a footer at the bottom with logon, copyright and link to main company site. Some have links to social media too. ![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/5e507ff4-a330-440e-9d15-8516e231bbd3)

**Comment by BeckyBrekke** [comment]
Opened a request in S@E to see what advice is given there: RITM2370997

**Comment by BeckyBrekke** [comment]
Got feedback: 
![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/345eee99-c138-4bc4-82fe-76d82a777055)
Will discuss how we proceed. Victor was going to speak with Nick directly I think first.

**Comment by vnys** [comment]
Nick says to contact Sheyda. And also “…the big issue for brand is the EDS is the main promotion for digital interfaces. If that doesnt feature the Equinor logo then it makes it harder to argue that other digital projects can neglect to feature it”. And that he thinks Omnia Radix should have the Equinor logo somewhere on their documentation site too.

**Comment by BeckyBrekke** [comment]
Victor booked meeting for Feb 10 with Sheyda and designers

**Comment by BeckyBrekke** [comment]
Decided on quick and dirty solution now, will make issues for more front page work for later. Discussed with Lucas, Birte and Bente - will add new divider to bottom of front page and add logo, some Equinor info.

**Comment by BeckyBrekke** [comment]
Updated the bottom of front page with the "easy implementation" as was discussed with the team. 
https://zeroheight.com/0b0c666ab/v/latest/p/238bf3-equinor-design-system
