### ISSUE TITLE
Remove fixed button height

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1858]
EnergyVision has buttons with multiple lines of text, which is currently not possible in EDS due to the fixed height on the component. Remove the fixed height, but make sure the button still takes up the same place vertically by using padding and line-height, by using a `padding-top `and `padding-bottom` of `0.625em` for example. This should ideally be solved in Figma Broker by transforming the values from Figma to relative units.

![image](https://user-images.githubusercontent.com/2081882/148091378-7ba85e9c-bcf4-4329-8499-5b05cc08fcbb.png)

This issue will solve [#653](https://github.com/equinor/energyvision/issues/653) in equinor/energyvision.

**Comment by mimarz** [comment]
We can also solve this isolated for `Button` by overriding its spacing values in the component token. This might be a safer approach for now than updating the spacing tokens in figma-broker from px to rems as it would affect all of our components. 

Might also be that we still want pixels spacings on some components and `em` on others in the future?

**Comment by vnys** [comment]
Yes, I agree this is a bigger task that will ultimately affect all the components. We should transition from fixed to relative units overall to improve accessibility, and style from the inside out instead of vice versa (with the exception of grids of course).

**Comment by mimarz** [comment]
Ref. todays discussions on standup @vnys, I think we should do this in `@equinor/eds-core-react` isolated for `Button` (and `Table` #1860) as this is a thing we need to do eventually with proper responsive support 🤔
