### ISSUE TITLE
As a designer I need to know what we do in regards to auto-layout on existing EDS components

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#187]
Need to find a strategy for how we deal with auto-layout.

- We could wait and see how the auto-layout functionality evolves. Will probably get better over time, and some functionality could change
- If we wait and do nothing, more projects will use the components as they are, so changing later could be more difficult.
- We need to do some research into auto-layout to better understand the consequences.

**Comment by benkeq** [comment]
This could be archived @akvam. Auto layout will be handled in issues connected to specific components.

**Comment by mimarz** [comment]
Outdated & done
