### ISSUE TITLE
Create a Documentation project in Figma under EDS

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1880]
Create a new EDS project called Documentation with a Zeroheight project were we collect all the frames, illustrations, screenshots and components we make for documentation purposes.

**Comment by lucasveil** [comment]
You can find the link [here ](https://www.figma.com/file/ZzsXOMjGnRmzG14pmAD8PM/Documentation?node-id=1%3A62) @vnys @BirteThornquist @benteljones @BeckyBrekke 
I needed to link it to ZeroHeight in order to make screenshot for documentation.

**Comment by BirteThornquist** [comment]
LGTM!
