### ISSUE TITLE
Create an Illustration project in Figma under EDS

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#1881]
Create a new EDS project called Illustration and move the Zeroheight homepage illustration

**Comment by akvam** [comment]
Goal: have a common place for all illustrations etc. independent on user.

**Comment by lucasveil** [comment]
@benteljones could implement the homepage illustration [here](https://www.figma.com/file/ZzsXOMjGnRmzG14pmAD8PM/Documentation?node-id=1%3A208)
And put this issue to done :)

**Comment by benteljones** [comment]
Yes, of course I'll do that right away. 😊 I only have view access to the folder. Can you add me with editing access, @lucasveil ? Thank you!
