### ISSUE TITLE
♻️ Refactor figma-broker to typescript

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1886]
There is some complex logic and processing pipelines in figma-broker that would increase legibility if we had types and better IDE support for when we need to do changes. 

Notes: 
* [esno](https://www.npmjs.com/package/esno) for running typescript scripts
* Some parts of the code are way complex to support features we no longer need
* Ramda and typescript might have problems with [pipe](https://stackoverflow.com/questions/65603918/typing-error-using-ramda-pipe-in-typescript)

**Comment by oddvernes** [comment]
Figma broker is getting deprecated over time and I don't thing we are ever going to get around to do this for the remaining parts
