### ISSUE TITLE
Update dependencies in figma-broker

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1887]
Update all dependencies. 

svgo has a deprecation warning: 
![image](https://user-images.githubusercontent.com/1070981/149149758-f6f6a173-0f25-466c-92f7-52a3a809becf.png)

**Comment by BirteThornquist** [comment]
Related: #2771

**Comment by oddvernes** [comment]
SVGO has been updated by #2771 , the remaining dependencies are

![Image](https://user-images.githubusercontent.com/4499531/226330656-79435026-6660-4215-bffc-f3baf489baa0.png)

which I am slightly worried about updating if it breaks something

**Comment by oddvernes** [comment]
This was has been covered by multiple pr's since, the latest being #3121
