### ISSUE TITLE
Research on compact

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1893]
Take a deeper look at the compact version of EDS.
Test different version of type, spacing and clickbound for component and tokens

**Comment by lucasveil** [comment]
File of research is located [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3103%3A108947). 
Took[ Buttons](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3111%3A124217), [Table](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3111%3A108962) and [Search](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3111%3A130615) component as starting point of discussion and made different test of size.

Had also discussion with @vnys around typography and height size, which is key for a good implementation for compact. As for example the size of the font inside a component should be consistent for all component.

**Comment by lucasveil** [comment]
After team meeting on the 28.02.2021 we agreed to make html/css prototype to validate the compact tokens choices.
We will have PitStop application as starting point and have a place holder the 7th March to develop the app.

**Comment by lucasveil** [comment]
Figma example is ready [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3281%3A125773)
Next step is implementation in code

**Comment by vnys** [comment]
This issue has been followed up by #2281. When that is done we will create specific issues for compact.
