### ISSUE TITLE
Import images routine in ZeroHeight

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1895]
There is different ways to import images in ZeroHeight. We need to align us on the proper way to do it and write documentation for it.

**Comment by lucasveil** [comment]
We have a meeting on thrursday 20th january to discuss the routine.

**Comment by lucasveil** [comment]
After meeting i need to write the documentation. This issue is related to #1880

**Comment by lucasveil** [comment]
Documentation is ready for review [here](https://equinor.zeroheight.com/styleguide/s/58798/p/367bf6-image-import) @vnys @BirteThornquist @benteljones @BeckyBrekke 

On main issue with the way to import images this way is that it is impossible to hyper link the images. This is a major issue for the homepage and component page. If we use this method, we need to copy paste the hyper link in the description which isn't optimal, :

![Screenshot 2022-01-20 at 13.13.58.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/e9c6fe71-3b10-4af5-94f8-55df20e0fc6f)

**Comment by BeckyBrekke** [comment]
I read through it and changed some small things in the text. I added an image label to the last image "Layout settings". Looks good!

**Comment by BirteThornquist** [comment]
Looks good to me @lucasveil !
