### ISSUE TITLE
Support large data sets in Autocomplete

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1909]
Selects/Autocompletes/Comboboxes are in most cases used for selecting tags in Equinor. Tags are usually very large data sets so we should probably do some optimising for our upcoming Autocomplete to support large data sets. 

[Examples from downshift using react-window](https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/downshift/other-examples/react-window/index.js)

**Comment by sindre-nistad** [comment]
We have a similar problem in a project, where ~5000 options is available in some cases.
This causes the component to be _very_ slow, and only render part of the items.

**Comment by oddvernes** [comment]
Interesting! Well since we are currently looking at lazy-rendering table in #2561 there may be some lessons learned there. I am moving this ticket higher up from the debths of the backlog 👍

**Comment by oddvernes** [comment]
@sindre-nistad We have a test release out now if you have the opportunity to check it out 👍  `@equinor/eds-core-react@next`. Currently virtualization is _always on_ just to avoid bloating this component with even more code but I may have to add a` virtualize` prop if this does not work in some cases like ssr (yet to be tested)

**Comment by sindre-nistad** [comment]
Great! I'll check it out

**Comment by sindre-nistad** [comment]
Initial testing shows great promise. I've tried it with a dropdown with ~5000 elements, and one with ~1800 elements.
Scrolling, and _really_ fast scrolling does not cause the app to slow to a crawl.
If I let the scroll wheel fly freely, the elements seem to render occasionally, but it still scrolls down. During _really fast_ scroll the elements may disappear completely.
Searching, and selecting works smoothly.
