### ISSUE TITLE
Create an icon for ZIP files

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#1917]

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist @benteljones  here:
https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=103%3A2380

If approved, it is ready to go @mimarz

**Comment by benteljones** [comment]
LGTM 👍🏻

**Comment by BirteThornquist** [comment]
Icon LGTM @lucasveil 👍🏻 I changed the name to zip-file. I was wondering if this should be placed under "Files and collections" instead under "UI-actions"?

**Comment by mimarz** [comment]
released in [eds-icons@0.11.0](https://github.com/equinor/design-system/releases/tag/eds-icons%400.11.0)
