### ISSUE TITLE
Portal component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1925]
Inspired by [Reach UI - Portal](https://reach.tech/portal/)

We are already using[ react portal ](https://reactjs.org/docs/portals.html)several places (`Tooltip`, `Menu`, `Popover` & `Combobox`) and maintaining code thats specific to portal handling in each of the components.

We should make a helper component that lives in `eds-utils` for our portal needs

* Handling mounting for SSR support
* Creating and using a pre-defind node container in `document.body` for portals called something like `eds-portal` or the likes. `Tooltip` has example code for this feature

**Comment by oddvernes** [comment]
Floating-ui's `FloatingPortal` serves this purpose now
