### ISSUE TITLE
Tooltip not showing with large z-index

### ISSUE THREAD

**Issue by jorgenherje** [equinor/design-system#1979]
Utilizing [tootip-component](https://eds-storybook-react.azurewebsites.net/?path=/docs/data-display-tooltip--default) in my React component. When placing my component in a parent component with large z-index - the tooltip disappear. 

My parent component has z-index: 1050

Temporary I've solved the issue by replacing the `Tooltip` from `@equinor/eds-core-react` with `Tooltip` form `@material-ui/core`.

**Comment by mimarz** [comment]
Hi! 

Did you try setting the z-index on the tooltip higher than the parent component? 
We can ofcourse set it astronomically high but I bet someone will always find a use-case for going higher 🤪

**Comment by jorgenherje** [comment]
Should it have an automatic z-index find algorithm? To prevent hardcoding the z-index. As of now it works with the `Tooltip`-component in `Material-ui`.

The issue is for the `VectorCalculator` in [`equinor/webviz-subsurface-components`](https://github.com/equinor/webviz-subsurface-components). The component is used in a Dash-plugin for [`equinor/webviz-subsurface`](https://github.com/equinor/webviz-subsurface). So I do not know which z-index the parent has. I'm using it in a Dash-plugin.

**Comment by mimarz** [comment]
The `mui` is hardcoded to be `1500` (overridable by its theming), which is why it probably works for you in this use-case. We have "only" `350` for our `Tooltip`, albeit maybe a bit low on our side, we can ofcourse set the default to be higher :) 

I have never heard of algorithms for automaic z-indexs, did you have a specific example in mind or?

**Comment by jorgenherje** [comment]
My colleague has made an implementation of such a utility previously: https://github.com/equinor/webviz-core-components/blob/master/react/src/lib/utils/dom.ts.

Not sure if it is applicable. As of now I'll stick with `mui` version due to the default - `350` is a bit low. My hope was to not think of the parents z-index. Everything else in my component works fine - only the `Tooltip` is hidden due to the `350` z-index

**Comment by mimarz** [comment]
We can increase our `Tooltip` z-index to `1500` for you (along with our other components) so the chances for it hiding a smaller :) 

The algorithm is not applicable for us as the performance hit for traversing the dom-graph in a `Tooltip` would be to big (even when memonized) and it doesn't really find the highest z-index as it only traverses the specifics graph for which the element resides in.

**Comment by mimarz** [comment]
This has been resolved in our latest release core-react@0.18.0!
