### ISSUE TITLE
Search icon wrong size in Search component

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#1980]
Search icon is the wrong size in the Search component.
Need to investigate if this is related to the new compact icon publish

**Comment by lucasveil** [comment]
Could you please [review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=18442%3A38194) @BirteThornquist

**Comment by BirteThornquist** [comment]
LGTM! @lucasveil
