### ISSUE TITLE
Increase our z-indexs

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#1981]
Some users are still experiencing our components being hidden due to "low" z-index relative to what they are using. 

Suggest updating our values to match that of [mui's z-indexes](https://mui.com/customization/z-index/) as this is what most people are either coming from or using instead. These values should be no high enough to account for anything else people might use.

**Comment by oddvernes** [comment]
The previous overhaul of this: [#883](https://github.com/equinor/design-system/pull/883)

**Comment by mimarz** [comment]
> The previous overhaul of this: [#883](https://github.com/equinor/design-system/pull/883)

* hmm, does chip need z-indexs? Can't remember why we have this.
* Menu and popover should have the same z-index i think?

**Comment by oddvernes** [comment]
> > The previous overhaul of this: [#883](https://github.com/equinor/design-system/pull/883)
> 
>     * hmm, does chip need z-indexs? Can't remember why we have this.
> 
>     * Menu and popover should have the same z-index i think?

The previous value for chip appears to have been 999 set by you 2 years ago at its creation
