### ISSUE TITLE
Menu and Popover tests passes but throws a lot of warnings about act()

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#1986]
**Describe the bug**

pnpm test:core-react Popover: 

`  console.error
    Warning: It looks like you're using the wrong act() around your test interactions.
    Be sure to use the matching version of act() corresponding to your renderer:

    // for react-dom:
    import {act} from 'react-dom/test-utils';
    // ...
    act(() => ...);

    // for react-test-renderer:
    import TestRenderer from react-test-renderer';
    const {act} = TestRenderer;
    // ...
    act(() => ...);
        at Popover (C:\git\design-system\packages\eds-core-react\src\components\Popover\Popover.tsx:122:7)
        at AllTheProviders (C:\git\design-system\packages\eds-utils\src\test\withAnchorEl.tsx:14:28)

      31 |   return react.useCallback(element => refs.forEach(ref => {
      32 |     if (typeof ref === 'function') {
    > 33 |       ref(element);
         |       ^
      34 |     } else if (ref && typeof ref === 'object') {
      35 |       ref.current = element;
      36 |     }`

**Comment by oddvernes** [comment]
> There are more test that throw this error. It looks to me that this is related to `async`, so it throws this error in every test where `async` is used (besides the a11y testing). Here are some links i came across related to this problem:
> 
>     * [Warning about using different versions of act() when wait()ing on an async effect testing-library/react-hooks-testing-library#173](https://github.com/testing-library/react-hooks-testing-library/issues/173)
> 
>     * https://react-hooks-testing-library.com/usage/advanced-hooks#async

Which other components have you seen this error in? 
I works if i import waitFor from `@equinor/eds-utils/src/test` instead of  `@testing-library/react` (that function in utils extends and re-exports testing-library-react),

Then there is only a problem with the axe test, which I fixed by doing this:
`    
await act(async () => {
      const results = await axe(container)
      expect(results).toHaveNoViolations()
 })
`

**Comment by laliq** [comment]
I have seen this error in Search, Banner, Accordion, Breadcrumbs, Scrim, Typography, Button. 
Well there is something funky going on with this; each time i run `pnpm --filter @equinor/eds-core-react run test` it will show this error on different components, sometimes will omit the one i have already  listed.

**Comment by oddvernes** [comment]
Hmm, I don't get this warning in Banner which does have the axe test merged, or anywhere else currently after fixing menu and popover

**Comment by laliq** [comment]
I have run the command again, Banner didn’t  show this error... 🤔
