### ISSUE TITLE
TextFiled-component (or any other inputs) support  in  Menu component

### ISSUE THREAD

**Issue by AndreaEsposit** [equinor/design-system#2001]
As of today, the Menu component does not support the TextField component (or other text inputs). Inputs will become unresponsive once placed in a menu  (not selectable). This is probably due to the rareness of this use case.

NB: 
The Search component works as expected. 

I would like the support of inputs in the Menu component

**Comment by AndreaEsposit** [comment]
In our case, we need to create e menu where a user can select existing tags, and create new ones directly in the menu (figma example below):

![image](https://user-images.githubusercontent.com/54411648/154965834-bea90185-f0f7-4718-99fb-10f10a4c6208.png)

**Comment by mimarz** [comment]
Have you tried using the [Popover](https://eds-storybook-react.azurewebsites.net/?path=/docs/data-display-popover--default)?

**Comment by mimarz** [comment]
hehe, good good :) A `Menu` is usually reserved for navigation-able content so having an input in there can be very weird for screen-readers, while popover is more free for all 😅 Although important to also have a title for your popover :)
