### ISSUE TITLE
Fix low color contrast on Text-field

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#201]
Low color contrast when variant is warning & success.

Border and helper (text + icon ) have to low contrast on white background.

- [x] Check Figma vs. Component colors (Figma says contrast is ok on helper text)
- [x] Find compliant UU colors

**Comment by lucasveil** [comment]
Storybook uses the wrong color for Helper text.
Color use for warning text is Interactive Warning/Text (Warning Dark Orange)
Color use for sucess text is Interactive Success/Text (Success Dark Green)

**Comment by mimarz** [comment]
@lucasveil I have checked the code and it has the same color codes as defined in figma, as you described....
