### ISSUE TITLE
Missing null check in MenuList

### ISSUE THREAD

**Issue by tfrausin** [equinor/design-system#2015]
**Describe the bug**

MenuList crashes when a child is `null`, e.g., from a conditional child where the clause is false (`condition && <Menu.Item>`).

If the conditional child is outside of a `Menu.Section`, `MenuList` crashes on [L55](https://github.com/equinor/design-system/blob/25f768a035973b81906b71aee0d34d95e7b57ebb/packages/eds-core-react/src/components/Menu/MenuList.tsx#L55) with error `TypeError: can't access property "type", child is null`. Otherwise `MenuList` crashes on [L61]() with error `Error: React.cloneElement(...): The argument must be a React element, but you passed null.`. 

**Steps to reproduce the bug**

1. Add a conditional to the inner JSX of a <Menu> component.

**Expected behavior**

The `<Menu>` renders without crashing.

**Specifications**

- Version: 0.18.0
- Browser: Chrome v98.0.4758.102
- OS: macOS v12.2.1

**Additional context**

[Codesandbox](https://codesandbox.io/s/pedantic-glitter-h2zrmb?file=/src/App.js)

**Comment by tfrausin** [comment]
Also seems to be a tiny cosmetic bug here. The `index` prop of the `MenuSection` component is not set, i.e., `null`, resulting `MenuSection` rendering the top divider even if the section is the first element of the `MenuList`. [Codesandbox](https://codesandbox.io/s/stupefied-hypatia-9bmlwp?file=/src/App.js:92-205)

**Comment by mimarz** [comment]
Thanks for reporting this. Someone on our team will take a look as soon as possible :)
