### ISSUE TITLE
Issue upgrading to version 0.16.0 or higher

### ISSUE THREAD

**Issue by nimsilva** [equinor/design-system#2021]
We are currently running version 0.14.2 of eds-core-react and upgrading to version 0.15.0 goes well but when attempting to upgrade to version 0.16.0 or higher we run into the following problem when we launch the application.

-  eds-core-react: Currently running ^0.14.2 without any problems upgrading to ^0.16.0 or higher causes the bug.
-  react: "^17.0.0"
-  webpack: "^3.12.0"
- @babel/preset-env: "^7.8.6",
- @babel/preset-react: "^7.0.0",
- @babel/runtime: "^7.8.4",
- Browser: Chrome

error:
```
Failed to compile
./node_modules/@equinor/eds-core-react/dist/esm/components/Accordion/Accordion.js
Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
|   children,
|   id,
|   ...props
| }, ref) {
|   const accordionId = useId(id, 'accordion');
```

This problem happens 76 times across different files according to the browser's console.

**Comment by mimarz** [comment]
Hi!

We did some changes in the the bundling for eds-core-react in version 0.16.0 to be more modern and up to date with how other libraries are doing it, so this might be also related to that. Outdated packages or missing setting in webpack(?) might also cause this in your application. 

Do you have a link to you repo so it might be easier to investigate?

**Comment by nimsilva** [comment]
Hi,

Our repo is internal to Equinor: https://github.com/equinor/prix

**Comment by mimarz** [comment]
Is it this one? https://github.com/equinor/prix/tree/master/src/Ras.Ui/ClientApp 

If strongly advise you to update your build dependencies. For example. the latest version of Webpack is v5, you are currently running v3, which is now 5 years old... A lot has changed during that time when it comes to compiling frontend

**Comment by nimsilva** [comment]
Yes, that is our react app.

Thank you, we want to do some major changes very soon to our repo and that will include a review and update of all our dependencies. :slightly_smiling_face:

**Comment by mimarz** [comment]
Happy to help :)

As far as I can see its loading the `esm` version of core-react for compiling, which it doesn't know how to transpile ( probably due to it being webpack3). 

We do however also ship a `cjs` version in the package (which it should pick by default) which is backwards compatible. Why it doesn't pick this one however is hard to see without deep-diving into all the build code 😅

**Comment by nimsilva** [comment]
I understand,
Do you have any suggestions on how we should proceed?

**Comment by mimarz** [comment]
I would start by figuring out how to update the create-react-app you have or setup all the webpack/eslint/babel stuff yourselves. The truth is when its gone this long without doing regular updates/maintenance of this stuff its going to be a lot of work 🙈

**Comment by nimsilva** [comment]
This project was created before create-react-app was introduced, the configuration of the project was made by one of our developers. Unfortunately most of the developers that worked on the project at the time have left the team.
We are thinking about trying to re-create our application using create-react-app, hopefully that might solve the issue.

Will there be any problems if we continue to use version 0.14.2 for the foreseeable future?

**Comment by mimarz** [comment]
There is no problem in using older versions :) 

Unfortunately you do miss out on fixes, improvements, new features and etc. in newer versions.

**Comment by nimsilva** [comment]
Thank you for your help 😃

We will follow up on this and try figuring it out 🙂

**Comment by mimarz** [comment]
Happy to help :) 

I'll close this issue now as its "resolved".
