### ISSUE TITLE
Variant accordion_header is missing from Typography

### ISSUE THREAD

**Issue by ErlendAHall** [equinor/design-system#2022]
**Describe the bug**

![image](https://user-images.githubusercontent.com/10920843/155500174-10b30eec-cb04-45e3-b8ba-d236b7c04c40.png)
The initial fault was found in a Dialog, and seems to be reproduced anywhere as far as I can tell.
I did not try to render this inside an actual EDS Accordion, but I assume this is not related.

**Steps to reproduce the bug**

Use Typography component anywhere and send variant="accordion_header" as prop.

**Expected behavior**
Should output an accordion_header formatted text.

**Specifications**

- Version: 0.18.0
- Browser: Vivaldi 5.1 (Chromium 98)
- OS: Linux

**Comment by oddvernes** [comment]
You need to add group="ui" and then it will work @ErlendAHall 

I think our documentation might need an update to explain this!

**Comment by ErlendAHall** [comment]
Can confirm it works for me now :)
