### ISSUE TITLE
Move the storybook to Radix

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2039]
This will result in a new url, so to avoid that the next time around, we should have a sub domain for the storybook – for example `storybook.eds.equinor.com`. Alternatively we could consider using something else than storybook, like `components` for example. 

We currently have two storybooks, one for core-react and one for lab(s)-react, but it is possible to have a storybook that pull in content from other storybooks, so that’s probably something we should look into.

**Comment by nilsml** [comment]
I have been looking into moving the Storybook as part of moving to new Azure subscription. As far as I can see a static website in an Azure storage is more suitable than both Radix and Azure container. What is the benefit of containerizing a static web site? @mimarz @vnys

**Comment by mimarz** [comment]
> I have been looking into moving the Storybook as part of moving to new Azure subscription. As far as I can see a static website in an Azure storage is more suitable than both Radix and Azure container. What is the benefit of containerizing a static web site? @mimarz @vnys

I agree that using a static website in Azure storage would be best for Storybook. 

Why its containerized is just left over hosting setup from when we had our own storefront and figma-broker apps running. No we don't have those anymore so no point in using containers anymore really.

**Comment by nilsml** [comment]
Will solve this through #2404
