### ISSUE TITLE
Menu / List item upgrade shown in Sandbox

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2058]
After discussion with Echo Team on the [menu item](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17627%3A3322) component, we can see that our user would have the need to have different variants:
![Screenshot 2022-03-02 at 11.07.10.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/c9533c2d-593b-4673-baf5-8d6486e092a3)

Echo team has already implemented the new version in their system and is a really good starting point for us to implement in EDS.

Here are some scenarios:

![Screenshot 2022-03-02 at 11.12.28.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/761e79a9-60f0-4567-a1f9-5332e5a58845)

**Comment by akvam** [comment]
Check with Ecco, put it into sandbox and ask for feedback from other projects.

**Comment by lucasveil** [comment]
Example from Echot Team is implemented in Figam Sandbox here: figma.com/file/hjpavZkeUoRfn1N7mhIniK/EDS-designer-sandbox?node-id=1703%3A43407
