### ISSUE TITLE
Sidesheet update

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2059]
After discussion with Echo Team, there is a need of a variant for side sheet that has multiple levels:

![Screenshot 2022-03-02 at 10.59.00.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/7e2fe0dc-baf1-4001-be1d-25b66b4256b4)

**Comment by akvam** [comment]
Here is some context: in the Algo Wall project the Side Sheet is defined like this by the designer (using H6 i think) 
![image.png](https://images.zenhubusercontent.com/60754619d2059fefad0fcc02/daf5c147-7ac1-4628-a611-65292f1269da)

**Comment by martalalik** [comment]
Consider to add tabs to? [Zeroheight](https://eds.equinor.com/0b0c666ab/p/17d96d-side-sheet/b/282ac1) mentioned this in description.

> Content in side sheets can be broken into tabs.

**Comment by akvam** [comment]
@lucasveil can you check if this will be solved as part of the work we now are doing on Side sheet ?
