### ISSUE TITLE
Integrate Amplify Sidebar

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2063]
[Link to amplify storybook](https://client-storybook-amplify-components-production.radix.equinor.com/?path=/docs/sidebar--no-create-action)

Some things needs to be decided still:

Currently,  the layout and components are hardcoded. The only thing configurable right now is to show or not show the "create item" button and change its label text. 
The only sub-component is menu items. 

Things that needs to be resolved:

**"CreateItem"**
![bilde](https://user-images.githubusercontent.com/4499531/161526105-10816462-3a7d-4582-bbad-b127ec227002.png)

This is meant for a specific purpose, so the icon is hardcoded and it has an `onCreate` callback on click.

What other use cases could this call-to-action button have, and let that inform:

- Should it have a more generic name?
- Should it be its own sub-component?
- Does it need the onCreate callback?
- Should the icon be replaceable?

**"ToggleOpen"**
![bilde](https://user-images.githubusercontent.com/4499531/161527373-9f4e60ae-f301-4142-95f9-cc78d7807fd4.png)

Controlled with an `onToggle` callback in the sidebar base component. Is fixed at the bottom above `LogoContainer`.

- Should this be a sub-component? (perhaps it makes more sense to have it built in but with a "position"-prop, depending on how html is structured)

**"SidebarItem"**
![bilde](https://user-images.githubusercontent.com/4499531/161533320-cadc14aa-4064-40e0-bd3c-9915d3f17e01.png)

This is the only sub-component and is a self closing component without children of its own.
It is a styled (eds) `Button` as="a". 
its props are 
- `icon `(eds iconData)
- `name` (string)
- `link` (string)
- `onClick`
- `currentUrl` (string)

It gets an active state if `currentUrl` includes `link`.

- Should there be a `SidebarMenulist` subcomponent similar to menu to put the items in? (perhaps this i required to organize the children and add support for another menu subcomponent with levels)

**"LogoContainer"**
![bilde](https://user-images.githubusercontent.com/4499531/161536729-b74e1388-0759-49f7-a6cc-245ec559f169.png)

In amplify this contains an equinor logo component that we don't have in eds. its just a div with a gray border on the top.

- Should there be a dedicated footer component where users can put whatever content they want? or perhaps a more generic `content` component that can be used as footer/header? But then the content inside would need to also be tailored for both expanded and narrow states...

the overall layout is

`Container` (div flex column)
- `TopContainer` (contains `CreateItem` & `SidebarItem`s)
- `ToggleOpen` (`margin-top: auto` to push itself & `LogoContainer` to bottom)
- `LogoContainer`

**Comment by vnys** [comment]
### Summary from discussion with @mimarz, @oddvernes and @vnys April 6 2022

#### Short term

- Initially we will make as few changes as possible to make it more generic and a little more EDS-like, but keep it in the labs-package for now
- onCreateAction will be renamed to something more generic, onAction for example
  - Label, Icon and callback must be configurable
- The placement of the expand button must be configurable, either at the top or the bottom of the sidebar
- The LogoContainer will be renamed to Footer to be more generic

#### Long term

- Use compound components similarly to other EDS components 
- Possibly look into container queries polyfill for collapsed state of menu items
