### ISSUE TITLE
Create Amplify sidebar in figma

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2064]
And decide what to keep as-is, what to change

**Comment by BirteThornquist** [comment]
Ready for a first review @lucasveil @benteljones I have set up det design of the component in my test area [here](https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/?node-id=1463%3A157257) It still need some more examples, but the components to build a side bar is outlined. I'm thinking we can have a "ready made" bar as you can see, in addition to all components needed to put it up bit by bit. I have started a documentation which is also right there + a few examples. Will set up more examples of different usages of a side bar (with actions etc).

**Comment by vnys** [comment]
Put on hold until week 18 (after compact)

**Comment by lucasveil** [comment]
This is a new component
