### ISSUE TITLE
DatePicker - missing css load

### ISSUE THREAD

**Issue by wigsnes** [equinor/design-system#2081]
Hi,

I am currently testing the DatePicker from eds-lab-react and I have some questions.

The first time I tried to use the component the styling was not working, I had to include 
`import 'react-datepicker/dist/react-datepicker.css';` to fix this. I see you also include this in the component, should it be necessary for us to include this to get it to work?

I think you should rename the onChanged to either onChange or something else. Is there ever a scenario you would need to use onChange from InputHtmlAttributes. There are a lot of props on the DatePicker that I feel it is not necessary and make it confusing what properties you should need to use.

I am also missing a way to select a range, using startDate and endDate options would be nice to include.

I know the DatePicker is still in development but hope this is some nice feedback.

**Comment by vnys** [comment]
We’re currently collecting feedback on the Datepicker, so we don’t know at this point when we’ll start working on it, but we’ve this issue to [the epic](https://github.com/equinor/design-system/issues/2137), and also added your workaround to the [@equinor/eds-lab-react README](https://github.com/equinor/design-system/blob/develop/packages/eds-lab-react/README.md#datepicker) for now. Thank you for the feedback @wigsnes!
