### ISSUE TITLE
Align colour names between light and dark mode

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2082]

**Comment by benteljones** [comment]
https://www.figma.com/file/2ksP8FU7CQImGOgatEhWp3/?node-id=2%3A522
You can find a start with an overview of today's colors and the naming in this folder.![Skjermbilde 2022-03-24 kl. 16.25.42.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/be0bdd1e-aec7-4831-83e8-4d141eb45259)

**Comment by benteljones** [comment]
![Skjermbilde 2022-03-31 kl. 17.14.53.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/94208ced-8a34-4a2e-84e8-154315e9d6bf)  I have dug further and find only two groups that have components that are 1: 1 – color tokens. All the others have deviations in the background colors, text colors, borders, color of icon etc.

**Comment by vnys** [comment]
Closed as this will be resolved in EDS 2.0
