### ISSUE TITLE
Reduce activity in disabled colours in dark mode

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2085]

**Comment by benteljones** [comment]
![Skjermbilde 2022-03-24 kl. 10.14.06.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/fb94c1c3-aca2-489e-93e4-1fc42e4d68b1)

**Comment by benteljones** [comment]
Suggestions have been made. A review will be taken when we color all the new components in 2.0. The new tasks will be added and we will take a review on them then.
