### ISSUE TITLE
Adjust the secondary/negative colour in dark mode

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2087]

**Comment by benteljones** [comment]
![Skjermbilde 2022-03-24 kl. 10.11.31.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/6b21e336-25f0-4eea-8a8b-504acf4bac7d)

**Comment by benteljones** [comment]
In EDS today,  I only find the Negative background color as a field, on Snackbar, Tooltip and on the Secondary button, Contained. Will there be a broader use of this later, new needs? ![Skjermbilde 2022-09-09 kl. 12.05.06.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/796e4d2c-a9ad-4af9-93d5-e6b7e4df3436)

**Comment by benteljones** [comment]
A new color suggestion have been made. A review will be taken when we color all the new components in 2.0. The new tasks will be added and we will take a review on them then.
