### ISSUE TITLE
Type error in SVG components 

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2108]
Our SVG components that are extending `SVGProps<SVGSVGElement>` props on their component props are throwing type errors of missing `fr` property. 

![image](https://user-images.githubusercontent.com/1070981/160840371-f404cfea-9fe5-444e-8b9b-ba9d65831d74.png)

[Sandbox with bug](https://codesandbox.io/s/late-brook-csd9xy?file=/src/App.tsx)

**Comment by mimarz** [comment]
Setting on hold as we waiting for codesandbox to update with latest version of `eds-core-react@0.19.0`

**Comment by bovan** [comment]
@mimarz I believe this was fixed 9 months ago actually: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b9754157a22b4645e97b4b6f4c663af64ea799a8

however the sandbox projects dev dependency for @types/react is [17.0.20](https://www.npmjs.com/package/@types/react/v/17.0.20)

updating our main projects type to 16.14.28 fixed this problem for us, so I assume by updating @types/react in sandbox will solve it

**Comment by mimarz** [comment]
> @mimarz I believe this was fixed 9 months ago actually: [DefinitelyTyped/DefinitelyTyped@b975415](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b9754157a22b4645e97b4b6f4c663af64ea799a8)
> 
> however the sandbox projects dev dependency for @types/react is [17.0.20](https://www.npmjs.com/package/@types/react/v/17.0.20) (10 months ago)
> 
> updating our main projects type to 16.14.28 fixed this problem for us, so I assume by updating @types/react in sandbox will solve it

Good catch! We are using `"@types/react": "^17.0.44` in `@equinor/eds-core-react` now, and updating the package version in sandbox looks to have fixed the problem there to!

**Comment by mimarz** [comment]
Considering this as fixed now
