### ISSUE TITLE
Fix icon name typos

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2109]
As reported in #2107 we have some typos in icon names. Since these are generated from Figma, we need to fix them in the "source of truth"

Icon typos & fix: 

`communte` -> `commute`
`headseat_mic` -> `headset_mic`
`desktop_windwos` -> `desktop_windows`
`breifcase` -> `briefcase`
`format_stikethrough` -> `format_strikethrough`
`mood_extreamly_sad` -> `mood_extremely_sad`
`mood_extreamly_happy` -> `mood_extremely_happy`

**Comment by mimarz** [comment]
@benteljones @lucasveil @BirteThornquist This needs to be fixed before we can export new icons in (because it will re-introduce the bugs in code) #2113, #1917 og #2111

**Comment by BirteThornquist** [comment]
@mimarz Typo bugs are fixed.

**Comment by BirteThornquist** [comment]
@benteljones @lucasveil  Maybe a quick review?

**Comment by benteljones** [comment]
100 % - LGTM! 😊
