### ISSUE TITLE
ADD anchor icon in EDS

### ISSUE THREAD

**Issue by chrleon** [equinor/design-system#2111]
I would like to add the ANCHOR icon from Material design to EDS.
https://fonts.google.com/icons?icon.query=anchor

This is used in maps to show the location of ports.

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist @benteljones  here:
https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3729

If approved, it is ready to go @mimarz

**Comment by BirteThornquist** [comment]
Great @lucasveil 👍🏻

**Comment by mimarz** [comment]
released in [eds-icons@0.11.0](https://github.com/equinor/design-system/releases/tag/eds-icons%400.11.0)
