### ISSUE TITLE
New icons for REN & offshore wind 

### ISSUE THREAD

**Issue by c-Purdy** [equinor/design-system#2113]
**Is your feature request related to a problem? Please describe.**

In Vortex we have come across the need for various icons that do not yet exist in EDS. 

Vessel - SOV (like the existing EDS icon, but waves were reduced)
Vessel - CTV
Craning & 
No Craning 
Handheld radio, aka TETRA Radio
Turbine / WTG  (on and offshore could be distinguished)
Tool bags, in 3 varieties - regular, wheel and rope
Substations, both on and offshore varieties

**Describe the solution you'd like**

Would like these icons reviewed by the EDS team, adjusted if need be and added to the EDS library. As it is possible that these icons will be useful to others as well. 

Note: neither the existing turbine icon (fan) nor the suggested one here (stick figure) are yet ideal. 

**Describe alternatives you've considered**

Material design icons were explored but found to be insufficient.

**Additional context**
![Screen Shot 2022-04-01 at 10 02 49](https://user-images.githubusercontent.com/91308891/161222566-7cc44ef7-774b-4e6a-aabf-5189ecf803c8.png)
![Screen Shot 2022-04-01 at 10 02 34](https://user-images.githubusercontent.com/91308891/161222568-300e35df-8311-4211-80a5-33bf54d91721.png)
![Screen Shot 2022-04-01 at 10 02 26](https://user-images.githubusercontent.com/91308891/161222569-100eda0d-a16d-4a2a-84e0-12dcafde9fda.png)

The components in out figma files: https://www.figma.com/file/vNUMP31ZD8KeP4kv3ZbXKI/Vortex-MVP-Concept-2021?node-id=3735%3A303167

Icon draft space: https://www.figma.com/file/vNUMP31ZD8KeP4kv3ZbXKI/Vortex-MVP-Concept-2021?node-id=8469%3A400572

**Comment by lucasveil** [comment]
We have actually some of the icon already in our system and updating them would be a breaking change. Need some time to invistigate if those change are actually usefull for the community.

**Comment by lucasveil** [comment]
New icon set ready for review @benteljones @BirteThornquist 
https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=86%3A3728

- substation onshore/offshore (energy category)
- toolbox regular/wheel/rope + craning/no craning (technical category)
- hand radio (hardware category)

**Comment by benteljones** [comment]
LGTM! 👍🏻

**Comment by BirteThornquist** [comment]
Great job @lucasveil 👍🏻 Only one comment: for the hardware/hand-radio icon, should the tiny line to the top right be a bit longer? Found it a bit difficult to see at least in view option 100%.

**Comment by lucasveil** [comment]
Hand radio icon is now updated @BirteThornquist
