### ISSUE TITLE
Spike - go through what Power Apps is done already

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2135]

**Comment by Hjaf** [comment]
- [x] Submitted request in service-now for creating new EDS Power Platform environments, @vnys and @BeckyBrekke to watchlist
- [ ] Establish solution in dev environment and begin importing existing apps or material

[https://www.figma.com/file/VdTGN8szaEEUE2ShlhBbMg/Side-activity-%26-Support?node-id=2%3A100](https://www.figma.com/file/VdTGN8szaEEUE2ShlhBbMg/Side-activity-%26-Support?node-id=2%3A100)

**Comment by Hjaf** [comment]
[https://github.com/equinor/EDSPowerPlatform/tree/ppdev](https://github.com/equinor/EDSPowerPlatform/tree/ppdev) 
I påvente av miljø har jeg bare startet med et lite utkast i Citizen Dev miljøet, flytter dette til EDS miljøene når de er oppe
[Test/demo versjon](https://apps.powerapps.com/play/cddf6366-5efb-41cf-b607-272a03c58570?tenantId=3aa4a235-b6e2-48d5-9195-7fcf05b459b0&source=portal&screenColor=RGBA(0%2C176%2C240%2C1))
