### ISSUE TITLE
TextField in Figma & Zeroheight is misleading  and unreadable.

### ISSUE THREAD

**Issue by laliq** [equinor/design-system#2142]
### Misleading
While building docs for `TextField` i have been looking to [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A51467) & [Zeroheight](https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a) for guidelines  and i found them bit misleading:

Figma
![Screenshot 2022-04-06 at 16 14 41](https://user-images.githubusercontent.com/7075271/161995531-a96bff44-3b9b-4075-861f-f05ea6c2faf9.png)
Zeroheight
![Screenshot 2022-04-06 at 16 14 57](https://user-images.githubusercontent.com/7075271/161995585-55427961-8d86-422f-b91c-afeda33dcf5b.png)

As expels show here there are `inputIcon` & `helperIcon` in the same `TextField`, wile [Storybook](https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--variants) says:

> Examples of validation states. You can add the icon in the helper text or inside the text input, both not in both places.

And then we have this:
Storybook
![Screenshot 2022-04-06 at 17 12 50](https://user-images.githubusercontent.com/7075271/162008065-7ec39973-64f5-4624-906a-ce8a8bdb6f4f.png)
![Screenshot 2022-04-06 at 17 33 08](https://user-images.githubusercontent.com/7075271/162012401-2db79f9c-edda-4c1f-bc5a-e62031a053d1.png)

Which statement is correct?

### Unreadable

In both platforms the examples are difficult to read:

Figma
![Screenshot 2022-04-06 at 16 25 55](https://user-images.githubusercontent.com/7075271/161997873-99a12e87-ec15-4d00-ad28-376f8261d370.png)
Zeroheight
![Screenshot 2022-04-06 at 16 24 05](https://user-images.githubusercontent.com/7075271/161997486-3c00bcf7-b3ff-4dca-81d4-58f9330562d5.png)

**Comment by mimarz** [comment]
From duplicate issue: 

Reported in May 2022 gathering 

	- Rebecca/Lucas look at some zeroheight things: 
		○ When inspecting in Figma the text is over top of each other. Also very small and blurry: 
		○ https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a/i/43041814
https://eds.equinor.com/0b0c666ab/p/77e7d5-text-field/b/86826a

		○ ![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/59159ddd-b889-4967-953e-53bdb21cb969)
		○ So small, blurry, can we fix: https://eds.equinor.com/0b0c666ab/p/31ae8d-select/b/86826a

**Comment by akvam** [comment]
Will be solved as part of EDS 2.0, close this issue.
