### ISSUE TITLE
Zeroheight documentation - update

### ISSUE THREAD

**Issue by laliq** [equinor/design-system#2153]
Looking at few UI libraries, i found nice features for the documentation, that could be taken into consideration, such as:
- [priority description](https://material.io/components/banners#usage) - for feedback elements.
- [anatomy description](https://material.io/components/banners#anatomy) - it has simple and visual description, which gives nice intro to more detailed description of each piece of the UI element.
- [accessibility description](https://mantine.dev/core/pagination/#accessibility) - to give an idea and additional info for the developers.

**Comment by akvam** [comment]
This is a huge documentation task, and will not prioritized it now. Can be discussed after Figma 2.0.

**Comment by BirteThornquist** [comment]
This ties into the upgrade of EDS 2.0 documentation. Closing issue.
