### ISSUE TITLE
Process for giving Figma access for EDS core team

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2184]
Look at how we give access to EDS core team members to files in Figma. Victor tried to move a file last week and had problems .
Task - agree how to give access to the team, project files, and to who in the EDS core team. 

Document how this is done so new people coming to the team are aware 

Also discussed as important in May 2022 gathering

**Comment by akvam** [comment]
See #2209

**Comment by BirteThornquist** [comment]
This issue is over a year old. The on/off-boarding processes need to be documented in a different issue. Closing this.
