### ISSUE TITLE
Change default density for compact stories in Storybook

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2190]
Gotten feedback on at-least two occasions that; "compact is not compact enough" when looking at compact stories in our Storybook. Turns out they didnt understand they needed to click the meny to change density or it wasn't present in our story... 

Action:
* Suggest changing the compact stories to have compact as default, as that is what people are looking for in this story. Having a toogle makes it just confusing for our users...

**Comment by martalalik** [comment]
The main issue was with `Table` component.
All the stories with `compact` are correctly displayed.
There are few components like `Accordion`, `TableOfContetns` or `Tabs`, that they dont look like a  compact, even we have a compact story of them. This might be related to a `Typography`.
