### ISSUE TITLE
Accordion Header title is not affected by headerLevel property

### ISSUE THREAD

**Issue by Pespiri** [equinor/design-system#2199]
**Describe the bug**

Header level is never applied to Accordion header text

![image](https://user-images.githubusercontent.com/32248439/168263780-98538f0d-4707-4eca-b862-0eb1d3723a2e.png)
headerLevel is set to 'h1'

![image](https://user-images.githubusercontent.com/32248439/168264259-7cb26805-5912-4f54-bcc8-1e5caf5376ae.png)
headerLevel is set to 'h6'

**Steps to reproduce the bug**

Create a simple Accordion with a Header and set the headerLevel property

**Expected behavior**

```html
<Accordion headerLevel="h1">
  <Accordion.Item>
    <Accordion.Header>Header</Accordion.Header>
    <Accordion.Panel>Panel content</Accordion.Panel>
  </Accordion.Item>
</Accordion>
```

Given this html a header of `h1` is expected, but header title remains unaffected.
Looking into the HTML it seem like the `h1` have been applied to the incorrect part of the DOM.

**Specifications**

- Version: "@equinor/eds-core-react": "0.19.0"
- Browser: Google Chrome v101
- OS: Windows 10 (21H2)

**Additional content**

As a sidenote the header title also changes color between being open and closed, which seems like an unintentional side effect of some styling.
If this is intentional it would be nice to be able to disable it or set a constant color for the title.

![image](https://user-images.githubusercontent.com/32248439/168268100-ad789d72-1733-4c0b-b054-1fd8373524ab.png)
![image](https://user-images.githubusercontent.com/32248439/168268137-3bdd0d0c-9740-492b-94f3-31904d0546ff.png)

**Comment by mimarz** [comment]
Thanks for reporting this! 

I was not able replicate the bug with `headerLevel`, tested using latest with codesandbox here: https://codesandbox.io/s/ecstatic-swartz-jwd5qr?file=/src/App.tsx (Make sure you inspect the parent node when clicking inspect element)

Thus header changing colors when open, might however be a bug, we'll have someone take a a look at that atleast :)

**Comment by Pespiri** [comment]
Are you sure? The header sizing remains the same no matter the headerLevel, even in your `codesanbox` example to me
I do see that the headerLevel is applied, but it has no effect on the actual header than being a container for the contents within.

In other words, the headerLevel only seems like a glorified version of the `as="h1"` property for Typography and does not affect the styling of the Header title

![image](https://user-images.githubusercontent.com/32248439/168275227-4ad377ca-d564-4b0c-a684-8fb1d838b03a.png)


Here's some test code to display every headerLevel available in "@equinor/eds-core-react": "0.19.0"
```jsx
import { Accordion } from "@equinor/eds-core-react";

export default function App() {
  return (
    <div className="App">
      {["h1", "h2", "h3", "h4", "h5", "h6"].map((x, i) => (
        <Accordion headerLevel={x as "h1" | "h2" | "h3" | "h4" | "h5" | "h6" } key={i}>
          <Accordion.Item>
            <Accordion.Header>{`Header is ${x}`}</Accordion.Header>
            <Accordion.Panel>Panel content</Accordion.Panel>
          </Accordion.Item>
        </Accordion>
      ))}
    </div>
  );
}
```

**Comment by mimarz** [comment]
Its not meant to change the styling but important for accessibility, SEO and semantical HTML to have correct header levels in your application as a whole, thats what this property is for :) 

You make a good point on that its almost the same as `as`, albeit this is just restricted to headings. This is something we could clarify/streamline.

**Comment by Pespiri** [comment]
The problem we get is that we would like to style the title as an `h4`, but that will result in the `h4` being a child of an `h2`.

The somewhat hacky workaround will be to use the `as="span"` to get our title styled as an `h4`
```jsx
<Accordion.Header>
  <Typography variant="h4" as="span">
    Header actual 'h4' title
  </Typography>
</Accordion.Header>
```

**Comment by mimarz** [comment]
Understandable :) 

We have had some discussions on this in general for `Typography` in regards to styling vs element type. Something we would like to make it easier in the future. 

We do also have an issue in the backlog for changing how the `Accordion.Header` is used. This use-case will be good to take into consideration here #2091

**Comment by BirteThornquist** [comment]
@oddvernes to check

**Comment by oddvernes** [comment]
I think the "workaround" above using Typography is good enough, the `headerLevel` is only meant for accessibility, Part of the reason Typography have separated style from element-type is use cases such as this.
