### ISSUE TITLE
Power Apps 101 with team

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2208]
From May 2022 gathering	

- Power Apps - have separate session of Hjalmar to demo what it is to rest of the team. 
		○ Existing apps, Figma integration coming, tasks to be delivered

Rebecca encouraged team to attend May 18th DigiTalk as a basis

**Comment by Hjaf** [comment]
I did a presentation during the December meetup.

I believe that it would be necessary to attend the power platform certification course and have a full power apps workshop for the EDS team for a deeper understanding in a design system context.
