### ISSUE TITLE
Decide on how to document design decisions

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2210]
From May 2022 gathering

	- Design Documentation - more of it! Better **process** to document the context of what we are working on and decisions. Find a way to do this similarly.

**Comment by akvam** [comment]
This US is to decide how to do this in Figma  =>  a team agreement. 
Examples will be added when working on other tasks.

**Comment by BirteThornquist** [comment]
We have decided to document in a separate area in Figma. Closing issue.
