### ISSUE TITLE
Establish EDS guidelines/process for GDPR handling

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2216]
From May 2022 gathering 

- Need a EDS core team process for GDPR handling of videos we record - meet the designer, other recordings. When we are included and when others outside of team are included.

**Comment by Hjaf** [comment]
@BirteThornquist could this already be covered by [GL0473](https://docmap.equinor.com/Docmap/page/doc/dmDocIndex.html?DOCKEYID=540838), do we need to refine it more? This guideline is linked to [WR1495](https://docmap.equinor.com/Docmap/page/doc/dmDocIndex.html?DOCKEYID=541362)

CfE recently decided (https://github.com/equinor/powerplatform/issues/248) add the data protection compliance course as a prerequisite for certified low-code developers. 
> *[Data Protection Compliance course](https://statoil.plateau.com/learning/user/deeplink.do?OWASP_CSRFTOKEN=57PG-MAXC-I5X9-AWZ6-83V4-6LJC-QHNQ-V343&linkId=ITEM_DETAILS&componentID=52777542&componentTypeID=E-LEARNING&fromSF=Y&revisionDate=1571303880000) - This eLearning will give you an introduction to internal and external data protection requirements. The Equinor Binding Corporate Rules (BCR) apply to all personal data which are protected by applicable EU data protection law.

**Comment by Hjaf** [comment]
https://statoilsrm.sharepoint.com/sites/ComplianceforMeetingVideoRecording

**Comment by BeckyBrekke** [comment]
@BirteThornquist @Hjaf 
We have older videos that various people have recorded in EDS in the past 5 years and those people are no longer in the company. 
[EDS stream channel](https://teams.microsoft.com/l/channel/19%3A08081ac3d7134608b312d8480aa87efc%40thread.tacv2/tab%3A%3A8811928f-4ce0-4460-a391-cffb915ddc0b?context=%7B%22channelId%22%3A%2219%3A08081ac3d7134608b312d8480aa87efc%40thread.tacv2%22%7D&tenantId=3aa4a235-b6e2-48d5-9195-7fcf05b459b0)

They should be deleted, but maybe someone wants to go through them first and see if this is something you want to make a newer version of? People found them very helpful at the time and was a way to onboard to Figma and EDS.

The idea with this issue is that the EDS core team would decide how long to store videos like this, have a policy that is agreed on and is available. As long as there is a business need to have these recordings and make them available it is fine, but it should agreed how long these videos will be stored, and a procedure for removing them. Now I see @Hjaf shared a new procedure for recording sessions/meetings that I wasn't aware of so someone should definitely look at that too. 
Here is the policy we created for the hackathon for how we handle photographs taken: 
[Hackathon photo handling](https://statoilsrm.sharepoint.com/:w:/s/PowerPlatformHackathon2023/EWhsCUZTFqpAssRfvTXYUMkBJ5VTWTFOSyom22ZW-r-eng?e=qQO69M)

**Comment by oddvernes** [comment]
We need to look into 4 videos and see if there are some that we need to delete
