### ISSUE TITLE
Operational Maintenance & Support

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#2224]
Edited by @mimarz 

Have a look at different resources and decide on how we want to improve release managment. Currently incrementing package versions, writing release log and releases are done manually, we want to automate this as these tasks are time consuming and prone to errors/typos.

Resources found which can be beneficial to investigate and lay a plan for how these tasks can be solved: 

Change management
- https://github.com/marketplace/actions/conventional-commits-pr
- https://pnpm.io/using-changesets

release notes generating
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- https://github.com/semantic-release/release-notes-generator

**Comment by akvam** [comment]
The purpose of this epic is to have a way to group tasks belonging to operational maintenance and support. 

Since Safe and Stable operation always is pri. 1, these tasks will not be prioritized by PO. Making sure that the needed tasks is done is the team’s responsibility. This also includes fixing bugs that need to be fixed.

**Comment by nilsml** [comment]
Not in use. Managed through new board instead.
