### ISSUE TITLE
As a designer I would like to see an example of what the menu should look like that appears below the accessibility icon 

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/design-system#223]
Especially the menu that appears below the accessibility icon (to show the users how they can access usability functionality (in the browser / switching between compact/comfortable or light/dark).)

**Comment by mimarz** [comment]
This has was solved [here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=4950%3A0)
