### ISSUE TITLE
Missing elevation on components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2230]
* Card
* Banner
* Snackbar
* Topbar

Are used with elevation in Figma but not implemented in our react components. 

TODO: update with more information

**Comment by oddvernes** [comment]
- Snackbar already use paper with `elevation="overlay"`
- Card does not use paper. I would argue card should use paper and expose elevation prop to the developers.
- Banner does not use paper. I don't see  it using shadow in figma?
- Topbar I feel should have elevation prop so the users can add elevation for a sticky topbar that scrolls over content, or have no elevation for topbar that is not sticky (or there is no scroll in the app anyway)

But this needs some designer input @BirteThornquist
