### ISSUE TITLE
Update Avatar component

### ISSUE THREAD

**Issue by martalalik** [equinor/design-system#2252]
Component update suggestions:

- **ANATOMY** ➡️  allow user insert not only `image` but also `icon` or `letters`. If so, `alt` attribute shouldn’t be mandatory .
![Screenshot 2022-05-31 at 08 30 39](https://user-images.githubusercontent.com/105340174/171108160-bce2651c-6566-4af6-b3da-beb69e0d0950.png)

- **COLORS** ➡️  when user has a chance to use `icon` or `letters`, will need guidelines for color usage.

- **SHAPE** ➡️  in [Zeroheight](https://eds.equinor.com/0b0c666ab/p/96f1b1-image-placeholder/b/85d6bc) description mention `square corners`:
![Screenshot 2022-05-31 at 08 52 04](https://user-images.githubusercontent.com/105340174/171110523-32e79f8e-6bc5-4029-93af-7706a471f8f4.png)
Inconsistence with source code.

- **DOCS** ➡️  create documentation for `Avatar` in `Zeroheight`.

Interesting example in [Goldman Sachs DS](https://design.gs.com/components/avatar#related-content).

**Comment by lucasveil** [comment]
Avatar are ready for review here: https://www.figma.com/file/vzPw0CuUu6T9dFO5fKQVp8/EDS-2.0-alpha?node-id=28906%3A91393
Not sure which category it falls in as a new component. 
Nice to have @vnys @BirteThornquist @benteljones have a look at it and give extra love to the Initials variants

**Comment by BirteThornquist** [comment]
The design of avatar is done in EDS 2.0. Closing issue.
