### ISSUE TITLE
Normalize on story margins in Storybook

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2253]
Before officially announcing new Storybook documentation we should normalize on how we apply more "air" to our stories.

We currently use one or the other apporach:

* Override margin/padding on `Stack` compnent
* Use decorator on individual story
* Just a div with style margin/padding

We should standarize on one approach for doing this to make it easier to maintain and provide clear code example for "inspect code" feature in SB. 

Notes:
* Decorators in SB still messes up "inspect code" for props table example but works fine for the other stories

With decorator:
![image](https://user-images.githubusercontent.com/1070981/171125503-58bec36f-5b5f-47bd-afe5-fb33dcbaab93.png)

Without decorator and some props set using table:
![image](https://user-images.githubusercontent.com/1070981/171125937-a9a14262-a7f0-4312-b7b1-c981c48de485.png)

**Comment by martalalik** [comment]
### Dynamic snippet includes decorator:
- [Discussions](https://github.com/storybookjs/storybook/issues/12022)
- [Solution](https://github.com/storybookjs/storybook/pull/14652)
