### ISSUE TITLE
Revisit infographic and data visualisation colors 

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2254]
Brand has totally removed the infographics pages and colors that we added and refer to in EDS (substitute infographic colors): https://eds.equinor.com/0b0c666ab/p/78c75b-colour/b/708097

We were not satisfied with these colors anyhow and started looking into add our own package for data visualization. 

We have announced at EDC that new infographic colors were coming in Dec 2021, but then we waited until Bente could do a color review. 
https://statoilsrm.sharepoint.com/:p:/r/sites/Designsystem/Shared%20Documents/General/EDC[…]ZMa6&nav=eyJzSWQiOjIxMzkxMTgwMTIsImNJZCI6MTM3MDU3NTQ0OX0
![image.png](https://images.zenhubusercontent.com/6075453285eb60bb55b90568/6e955885-fa72-498b-9eb0-b90ac9ab16c0)

Here are the colors Birte and Rebecca worked on in 2021: https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/Birte-test?node-id=360%3A948

We need to update documentation on zeroheight. 

Here is Rebecca's notes with lots of screenshots and examples: https://statoilsrm.sharepoint.com/:o:/s/Designsystem/Ekj7d0e5a85Ph6eKUmqnBXwBw8baCPPhNOvBm16cRR2s7g

**Comment by benteljones** [comment]
Connected to #2475
