### ISSUE TITLE
Create documentation for Input

### ISSUE THREAD

**Issue by martalalik** [equinor/design-system#2262]

**Comment by martalalik** [comment]
`Input` components looks outdated. 

1. It is not introduced in Figma.
2. Lacking documentation.
3. GUIDELINES:
[GOV.UK](https://design-system.service.gov.uk/components/text-input/) describes `Input` component in nice & clear way.
Some of the main points are:

- it's a one-liner,
- must have labels, and in most cases the label should be visible,
- avoid placeholder text,
which are the fundamentals.

**Comment by oddvernes** [comment]
I see it is used internally in Textfield search and Select where it is further modified and have labels etc added. But it seems to also be exposed publicly so people could use it. So it comes across as mainly meant for internal use and that is why there is no documentation? @mimarz

**Comment by mimarz** [comment]
Yeah, talked with @martalalik about it and I suggest we just add a short description that this is the input used in all our components and can be used to make your own components (dropdown, slider etc)

**Comment by mimarz** [comment]
Something like this? @martalalik @oddvernes 
> This is the `Input` which is used internally in our components. Use this if you need the barne bone input for making your own custom components or layout.

**Comment by oddvernes** [comment]
Yes something like this 👍
