### ISSUE TITLE
As a designer I would like to see some tutorial videos on how to use components in Figma

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/design-system#227]
Time box this to max 3 hours, as a way to see what we manage to produce on a very short time frame. Important to include announcements of the videos on Slack. 
Figma Topics:  
[ ] Navigational drawer 
[ ] Drop down menu 
[ ] Context menu 
[ ] Table (put in examples and maybe add a video)

**Comment by BeckyBrekke** [comment]
This is a [duplicate](https://app.zenhub.com/workspaces/equinor-design-system-604f57c09e350a0011b654f4/issues/equinor/design-system/1550)
Lucas is currently working on 1550 as part of zeroheight work, so I will close this.
