### ISSUE TITLE
Additional Icons 

### ISSUE THREAD

**Issue by c-Purdy** [equinor/design-system#2271]
**Describe the solution you'd like**

Looking for additional icons 

- UAV /drone
- technician 
- badge /swipe card
- grip (drag & drop reorder)
- Sign
- approve
- wind farm (no suggestions yet)

**Describe alternatives you've considered**

The majority are from material design I believe. 
The sign icon is custom.

**Additional context**

![Screen Shot 2022-06-03 at 12 09 42](https://user-images.githubusercontent.com/91308891/171834731-633c47dd-e23f-4bdf-aa18-add811d9a9ef.png)

![Screen Shot 2022-06-03 at 12 11 00](https://user-images.githubusercontent.com/91308891/171834942-d38ce6d2-8473-4454-9738-043f4dc728cf.png)

![Screen Shot 2022-06-03 at 12 11 48](https://user-images.githubusercontent.com/91308891/171835049-f2a1d9d1-fc55-49ad-86fe-ef875a2b82e0.png)

![Screen Shot 2022-06-03 at 12 12 39](https://user-images.githubusercontent.com/91308891/171835172-7155cea9-744b-4fda-9c69-ceb602ead080.png)

**Comment by lucasveil** [comment]
Thanks for this request :) 
We have newly implemented 3 types of drone (land, shore and air) that have been released. 
The Technician icon can be found under the name engineering in our library.
We will implement the other suggested in our next release.

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist @benteljones 

- Wind farm: latest in Energy Category
- Badge: latest in People Category
- Approve and Signature: latest in UI Action

@mimarz ready to deploy if review is approved :)

**Comment by benteljones** [comment]
@lucasveil I first wondered if the lower line on the body could be increased to a whole px (badge) but then you get some new challenges. Never mind! 😉 LGTM! 👍🏻

**Comment by BirteThornquist** [comment]
LGTM @lucasveil  👍🏻

**Comment by lucasveil** [comment]
There is some issue with the wind farm icon that we didn't manage to solve. I need to have a deeper look into it so that design and dev is aligned and that the icon exports correctly.
