### ISSUE TITLE
Spike Figma Tokens

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2281]
Let’s test out [the Figma Tokens plugin](https://docs.tokens.studio/). See the [design file in Figma](https://www.figma.com/file/09T03w9Ct7mOWGYsYIP5CT/Figma-Tokens?node-id=0%3A1).

Some things left to explore:
- [ ] Naming: Create spreadsheet (one column for each segment in token name)
- [ ] Can themes be changed using Automator

**Comment by vnys** [comment]
**Update 11.06.2022**

Bente and I have created colour tokens for Moss Green. We decided to follow the same naming convention as Google and Adobe, with numbers in the hundreds. We’re keeping the same values as before, and also filled in the blanks so the palette is more complete. In dark mode the colours have to be slightly more saturated. We haven’t concluded on how to address that, but a saturation variable in the HSL colour space is one way to solve that. There is currently a large step from the darkest to second darkest colour, so the darkest one may have to be renamed to a higher number. Materials range stop at 900 (or was it 950? 🤔), while Adobe continue to 1400 or something along those lines.

![image](https://user-images.githubusercontent.com/2081882/173293483-53d0cc9b-1cf8-49e9-855a-e96b5d3825c9.png)

We also looked at the colour palette that COM recommends for brand illustrations, where they use for example a gradient from Moss Green to Mist Blue with a resolution of 7 steps to create depth in the landscape, since we have a similar need to create depth and hierarchy in user interfaces. We filed [a ticket in Service Now](https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=770e9f30474c1d9000ad1382e36d4395) where we asked COM what the specific values are for the intermediate steps, and also which methodology or application they used to create the intermediate colours, to gain a better understanding of the thought process and also make sure we’re in line with that thinking.

![image](https://user-images.githubusercontent.com/2081882/173294034-4d1f998d-2192-4462-b0a9-c8ca00dc2c37.png)

Historically we have deliberately kept the colour palette in EDS quite dull to not compete with alarm colours. We still think there may be room for more colours to create more space, so this could be one way to do that.

**Comment by benteljones** [comment]
![Skjermbilde 2022-06-14 kl. 21.16.46.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/d59815b1-f409-44ed-9397-a4c1e8036b79)

**Comment by vnys** [comment]
We'll focus on creating the following button variations:

- Contained
- Hover
- Outline
- Icon
- Primary

**Comment by vnys** [comment]
Success 🎉
