### ISSUE TITLE
wrong/missing body/font-family reference for tabs

### ISSUE THREAD

**Issue by Hjaf** [equinor/design-system#2283]
https://eds-storybook-react.azurewebsites.net/?path=/story/navigation-tabs--with-search

**Comment by mimarz** [comment]
Seems to be something wrong with Zeroheights embed on this site as it works for the other pages 🤔

**Comment by Hjaf** [comment]
But should it not be correct in storefront then?

**Comment by oddvernes** [comment]
The canvas view is missing font, but it is there in Docs view

**Comment by BeckyBrekke** [comment]
I link to the canvas view on the zeroheight design page, and link to the docs view on the zeroheight code page. I am just displaying what I am linking to.

**Comment by akvam** [comment]
Need to investigate, and fix it now as we are working on the developer documentation.

**Comment by mimarz** [comment]
Tabs is missing our `typographyTemplate` and is not using the correct typography tokens defined in Figma. This needs to be added to fix this problem.

**Comment by oddvernes** [comment]
I found out accordion is also missing `typographyTemplate` so AccordionPanel and AccordionActions seems to be affected. Title is inside a button which has its own template
