### ISSUE TITLE
Storybook links in zeroheight not working

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2299]
Design and code pages:
https://eds.equinor.com/0b0c666ab/p/392109-table/b/398446

Code page in: 
https://eds.equinor.com/0b0c666ab/p/50d3be-tabs/b/94939a

**Comment by Hjaf** [comment]
https://eds.equinor.com/0b0c666ab/p/392109-table/b/398446 is broken

**Comment by BeckyBrekke** [comment]
I fixed the links in zeroheight, but not published it yet. Can you check in zeroheight that it looks up in the latest version there?
