### ISSUE TITLE
Autocomplete, onOptionsChange not called on single select.

### ISSUE THREAD

**Issue by wigsnes** [equinor/design-system#2300]
**Describe the bug**

onOptionsChange not called when autocomplete is not multiple. Check CodeSandbox.

**Additional context**

[CodeSandbox](https://codesandbox.io/s/great-pine-lwvndj?file=/src/App.tsx:1094-1109)

**Comment by mimarz** [comment]
Thanks! We'll have a look at it as soon as someone is available :)
