### ISSUE TITLE
Polymorphic types for our "casted" components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2338]
Investigate and see if we can find a generic type we can use for our "casted" components in typescript.

Examples being a `Button` being casted to an `a` element, we want the type to dynamically change to show the type for `a` elements.

Copy of text from #1736 

> Based on the testing @oddvernes did in #1897, maybe we should add the polymorphic type in utils for use in other needed components. 
> 
> Based on [this reddit thread](https://www.reddit.com/r/reactjs/comments/tjwiak/what_is_the_best_way_of_writing_a_polymorphic/), I feel like this implementation was clean:
> 
> * Types: https://github.com/biswarup35/material-you/blob/v0.1.x/packages/material-meeu/src/types/PolymorphicWithRef.d.ts
> 
> * Usage in component: https://github.com/biswarup35/material-you/blob/v0.1.x/packages/material-meeu/src/Button/Button.tsx

Another example: https://github.com/mantinedev/mantine/blob/master/src/mantine-styles/src/theme/types/Polymorphic.ts

**Comment by oddvernes** [comment]
I randomly came across [this](https://github.com/navikt/Designsystemet/blob/master/%40navikt/core/react/src/util/OverridableComponent.ts), which might be a simpler implementation (didn't look super closely at it)
