### ISSUE TITLE
Add new contained_icon button in react

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2340]
EDS design team has implemented the new variant of button Ghost Icon Contained:
https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A47297
This variant needs to be implemented in React and Storybook

**Comment by mimarz** [comment]
After some discussion we renamed this button to `contained_icon` as it makes more sense since its filled and not ghost
