### ISSUE TITLE
Refactor Popover to floating-ui

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2344]
`Popperjs` (along with `react-popper`) has evolved to [floating-ui](https://floating-ui.com/) and we need to replace our `usePopper` with equivalent in `@floating-ui`

Actions
- Have a look at [examples in floating-ui ](https://floating-ui.com/docs/react-dom-interactions#examples) documentation for our respective component 
- Replace any of our `useIsMounted`, `useOutsideClick` and `useHideBodyScroll` hooks with `floating-ui` middleware.

**Comment by oddvernes** [comment]
A note before i start: The current popover is not rendered in a portal, and is hidden merely with css visibility. I don't know if this was done for a reason (to preserve state of content or something), or if this should be improved by using portal and conditional rendering.

**Comment by oddvernes** [comment]
Made a separate issue for portal + focus trap #2386
