### ISSUE TITLE
New icon for collapse / expand

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2348]
For the new design of the sidebar the eds design team need a new set of icon for collapse / expnd since the chevron icon is not clear enough

**Comment by benteljones** [comment]
LGTM! 👍🏻

**Comment by BirteThornquist** [comment]
LGTM! 👍🏻

**Comment by lucasveil** [comment]
This one should be fixed now @mimarz !
The issue was that the background was a fill white colour. It has been deleted so it should export just fine :)
