### ISSUE TITLE
Create top bar with auto layout

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2359]

**Comment by BirteThornquist** [comment]
Ready for [review](https://www.figma.com/file/vzPw0CuUu6T9dFO5fKQVp8/EDS-2.0-alpha?node-id=28447%3A83654) @vnys @lucasveil @benteljones . Added a note with the changes done to the right of the component.

**Comment by benteljones** [comment]
The height is 64 px on the old one, while it is 72 px on the new one. I might be because of the room for a product icon? I still think we have to look at the height. A recurring feedback is that the top bar takes up too much space, even with only 64 px.

**Comment by BirteThornquist** [comment]
Yes,  72px  is too high and was not intentional :-) It was the custom content container that was set to 48px hight. Changed it to 40px so now the Top bar is 64px high as the old one.
Agreed about the full screen size being smaller than the other icons, let's adjust it.

**Comment by benteljones** [comment]
😊👍🏻

**Comment by BirteThornquist** [comment]
The final review of this will be done in correlation with the Side bar.

**Comment by benteljones** [comment]
Could it be that the very last changes after we synchronized with Side bar are missing in the component? That the distance to the icon box is adjusted to 20 px, visually 24?![Skjermbilde 2022-10-25 kl. 10.01.23.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/6ddcc255-87ea-43f5-b13e-0b336b6411d1)

**Comment by BirteThornquist** [comment]
When it comes to adjusting the label/text to fit the hard grid, this will be done when the spacing tokens will be applied to the component. We will create a separate issue for tokenizing the top bar component.
