### ISSUE TITLE
Create menu with auto layout

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2360]

**Comment by benteljones** [comment]
If the Section title follows this component; I suggest to change the left padding from 26 to 16 px, as icon/text in items.![Skjermbilde 2022-10-25 kl. 16.07.29.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/2719b029-c853-4fb3-af8e-7ae0d78fa29d)

**Comment by BirteThornquist** [comment]
Good catch @benteljones. Fixed.
