### ISSUE TITLE
Create textfield with auto layout

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2363]

**Comment by vnys** [comment]
Started working on the component in Figma, but there are a couple of things we should discuss. Are we happy with the features we have? Should something be omitted or added to the next version? Perhaps a short discussion after standup tomorrow?

**Comment by mimarz** [comment]
We had a small revisit of the _manual resizing_ for "textfield" yesterday as we were unsure if this feature should be enabled in code. Discussion here: #1155

**Comment by benteljones** [comment]
I think Error, Success and Warning are missing the suffix icon choice in the menu. 
Could it be that Prefix icon and Prefix text has switced places?

A lot of really good work has been done here!
