### ISSUE TITLE
DatePicker: Move calender icon to correct spot

### ISSUE THREAD

**Issue by v3gard** [equinor/design-system#2366]
**Describe the bug**

Calender icon position on `DatePicker` is incorrect on Chromium based browsers (Edge and Chrome).

![image](https://user-images.githubusercontent.com/343078/176449759-b4cb0a43-0827-4442-af24-4e42e51ea6a7.png)

**Steps to reproduce the bug**

See code sample here with proposed solution: https://codesandbox.io/s/festive-booth-xhmuxp?file=/src/App.tsx

**Expected behavior**

|Chrome|Firefox|Edge|
|-|-|-|
|![image](https://user-images.githubusercontent.com/343078/176449480-0e5fa3dd-378f-4fc5-85db-189d23091fa1.png)|![image](https://user-images.githubusercontent.com/343078/176449548-b9c4aeb5-0786-433e-a365-f92ce7be6425.png)|![image](https://user-images.githubusercontent.com/343078/176450037-103db8c7-56fa-4a86-818c-0941d02e27c3.png)|

The calender icons renders in the correct spot.

**Specifications**

- Version: 102.0.5005.115
- Browser: Chrome
- OS: Windows

**Comment by oddvernes** [comment]
I am unable to reproduce this bug, the calendar icon is in the correct spot for me in firefox/chrome
