### ISSUE TITLE
Autocomplete onOpen after selection showing wrong options

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2373]
After an selection in single select mode for `Autocomplete` all items are supposed to be shown. For some reason they are still showing filtered items. 

Slack discussion ongoing with examples here: https://equinor.slack.com/archives/CJT20H1B9/p1656595261051539

**Comment by v3gard** [comment]
Is there a timeline for when we can expect a fix for this @mimarz?

**Comment by mimarz** [comment]
I don't have a definitive answer for you except for that its the next batch of work in the pipeline for me after I finish #2336 and #2407 . The InputWrapper has tho taken up a lot more time than expected as there has been a lot of edge-cases and shortcomings of old components that needed to be fixed 😅 When I get to it is unsure, but very soon I hope!

**Comment by v3gard** [comment]
A workaround for this issue is to add a EOL character after the label, e.g. U+00A0 (no-break-space).

[Example](https://codesandbox.io/s/friendly-dan-8c3sls-forked-x4e0ot?file=/src/ItemSelector.tsx)

**Comment by mimarz** [comment]
> A workaround for this issue is to add a EOL character after the label, e.g. U+00A0 (no-break-space).
> 
> [Example](https://codesandbox.io/s/friendly-dan-8c3sls-forked-x4e0ot?file=/src/ItemSelector.tsx)

Nice! Will be easier to track down whats actually wrong and a potential fix 👍

**Comment by mimarz** [comment]
Hi @v3gard!

We are trying to simplify the logic thats bring used to determine wether to show all options or not. 

I have [forked your sandbox](https://codesandbox.io/s/friendly-dan-8c3sls-forked-xt4jw0?file=/src/App.tsx) with an updated dev version so you can test if this would work for you.

We are now testing a new logic where; 
- If a value is typed but no option is selected, it will show filtered options.
- If you have selected an option, it will show all options on re-open
- If you start typing again after an option has been selected, the list will show filtered options
