### ISSUE TITLE
Add link to Graphics team from eds.equinor.com

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#2374]

**Comment by akvam** [comment]
In Equinor we have a Graphics team with a team site. 
Please add alink to their site from our eds.equinor.com.
The context must clearly show/state that this is not part of EDS, but is information that is relevant (similar to the illustrations figma pages). 

The link is: MDV8MDF8fGZjOTRlMGE0ZWU4NjRhNjJhYTkxMDhkYTUzNmNlMGZhfDNhYTRhMjM1YjZlMjQ4ZDU5MTk1N2ZjZjA1YjQ1OWIwfDB8MHw2Mzc5MTQwMjQzMjI0NDM5MjF8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2WWpBNU1EVTBPV1l0WXpNeU5DMDBaR016TFRsbE5Ea3RZV1V3TnpkaVlUTmtORGswWDJZeU9XWTJaR1JrTFRJNFl6Y3RORGcwWmkxaFpUZzJMVE16TkRabU1qY3lZamt5TmtCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw

**Comment by lucasveil** [comment]
Link updated in ZeroHeight and have been approved by Torill Stokka
