### ISSUE TITLE
Scroll bar for Table component

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/design-system#2380]
**Is your feature request related to a problem? Please describe.**
In our app we have a Table with many entries. It would be beneficial to have the option to have a scroll bar to the table body if the table height is too big.

I have looked at this example: https://eds-storybook-react.azurewebsites.net/iframe.html?id=data-display-table--introduction&panel=false&nav=false&addons=0&stories=0&full=1&viewMode=docs#fixed-table-header
 but here the scroll bar is not fixed to the right side of the Table. The scroll bar is floating to the far right, which looks weird. 

**Describe the solution you'd like**
Add a prop to the Table component to set max height, and if the height of the table exceeds this, add a scroll bar. This is equivalent to using the max-height property and overflow: auto css properties.

**Describe alternatives you've considered**

**Additional context**

## Current view using the code from example mentioned above
![image](https://user-images.githubusercontent.com/69512295/177995357-ed187840-8c6d-4b98-83ea-acdb9f973a4f.png)

## Ideal view
![image](https://user-images.githubusercontent.com/69512295/177995663-eca8cdb0-11c8-4d21-94ff-43ffb9e59db3.png)

**Comment by mimarz** [comment]
Thanks for reporting this! 

Could this work for you? https://codesandbox.io/s/nervous-hermann-tx9ftr?file=/src/App.tsx
It's maybe not ideal with the scrollbar position, but ideally we want people to have freedom themselves on how to encapsulate the table.

**Comment by KristianKjerstad** [comment]
> Thanks for reporting this!
> 
> Could this work for you? https://codesandbox.io/s/nervous-hermann-tx9ftr?file=/src/App.tsx
> 
> It's maybe not ideal with the scrollbar position, but ideally we want people to have freedom themselves on how to encapsulate the table.

That seems like a nice alternative, thanks!

**Comment by mimarz** [comment]
Happy to help! 

Closing issue as its resolved then :)
