### ISSUE TITLE
Autocomplete automatically scrolls to top after searching for option and selecting it.

### ISSUE THREAD

**Issue by awallemo** [equinor/design-system#2387]
## Autocomplete automatically scrolls to top after searching for option and selecting it.

I have noticed that after searching within the Autocomplete input and choosing an option the Autocomplete scrolls automatically back to the top.

**Steps to reproduce the bug**

1. Open an Autocomplete component
2. Search for one of the options
3. Click one of the options that appear
4.The Autocomplete automatically unfilters from your search and scrolls back to top

**Expected behavior**

After clicking one of the options that appear from searching, I would expect that the options shown would persist so that I could choose other similar options as well. 

**Specifications**

- Version: 0.20.4
- Browser: Edge
- OS: Windows 10 pro

**Additional context**

https://user-images.githubusercontent.com/54357341/179472698-368b00f1-b639-404c-873b-b8fe07c018e2.mp4

**Comment by mimarz** [comment]
Thanks for reporting this! 
I can see how this is annoying. I've prioritised it up to "todo" so someone should have a look at it in not to long :)

**Comment by mimarz** [comment]
Looks like we need to enable this feature in downshift for this feature https://github.com/downshift-js/downshift#scrollintoview

**Comment by mimarz** [comment]
Hey @awallemo !

Do you have a moment to show us this in your application? We were not able to reproduce this behaviour...
