### ISSUE TITLE
Sidebar: Review before release

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2389]
Before releasing `Sidebar` for testing and public review, the team should have a review together on how the component feels and works in accordance with EDS react components.

**Comment by oddvernes** [comment]
Make sidebar 72px, make topbar left padding 24

**Comment by oddvernes** [comment]
We are changing the sidebar border and sidebar item border to 2px ui.background__light (from 1px ui.background__medium) to make it the same border as topbar.

adding margin-top 16px to expand button (it already have 16px margin-bottom)
