### ISSUE TITLE
Fix links in storefront after communication toolbox site updates.

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2400]
Communication toolbox has made some changes to their site. 
Check EDS storefront and see if links still work or need updating. 

- [x] This link is broken for example - so need to check the others. https://communicationtoolbox.equinor.com/brandcenter/en/equinorbc/component/default/103 on our storefornt here: https://eds.equinor.com/0b0c666ab/p/31cfac-product-icons/b/248e6c

- [x] This one here too: https://eds.equinor.com/0b0c666ab/p/78c75b-colour/b/708097 - design tokens - colour, and also under infographics

- [x] The one on data visualisation under infographics is fixed now

- [x] Fixed the one on the logo page

**Comment by BeckyBrekke** [comment]
Searched for all instances and updates links.

**Comment by martalalik** [comment]
Look into it and found these: 

- Foundation - Accessibility ->
1. ![Screenshot 2022-08-26 at 15 12 39](https://user-images.githubusercontent.com/105340174/186911359-9c3842a3-70f8-44e1-ad44-ca0111f0957c.png) - outdated link. This is a new updated version: https://www.w3.org/WAI/ARIA/apg/ (there are 2 links on this page).
2. ![Screenshot 2022-08-26 at 15 27 28](https://user-images.githubusercontent.com/105340174/186914276-b7252b54-6876-4e73-86b9-feb98c49c82b.png) - broken.

**Comment by BeckyBrekke** [comment]
Good! I will fix.

**Comment by martalalik** [comment]
I checked (hopefully) all the links and i found just this one in [Support](https://zeroheight.com/0b0c666ab/p/29134f-support)

![Screenshot 2022-08-29 at 14 05 20](https://user-images.githubusercontent.com/105340174/187197239-fe015a35-c31a-40a7-aafd-b24b9abb5e4e.png)

Sends to a wrong url.

**Comment by BeckyBrekke** [comment]
Fixed the Figma sandbox links, they were broken in 2 places. 
Need to fix the Difi and WCAG links that Marta mentions.

**Comment by BeckyBrekke** [comment]
All fixed now.
