### ISSUE TITLE
Change azure resource group & subscription

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2404]
Our resource group is currently flagged as develop and OMNIA subscription is getting removed on 01.01.2023: https://web.yammer.com/teams/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTQ2NjM3NDI4MDYwMTYwMCJ9

## Acceptance criteria
* New subscription created
* New resource group created
* Storybook running under new subscription

## Actions
- [x] Setup new production resources group using new OMNIA production subscription model
- [x] Configure static website
- [x] #2753 
- [x] #2754 
- [x] #2755 
- [x] #2756 
- [x] #2757 
- [x] #2758 
- [x] #2759 
- [x] #2761 
- [x] #2861 
- [x] #2762

**Comment by akvam** [comment]
Is this in progress @nilsml ?

**Comment by nilsml** [comment]
I am currently working on this issue, but when going through the old subscription, I can see the need for specifying what we really need. We need a set of acceptance criteria where all the resources are listed.

**Comment by nilsml** [comment]
Very basic setup of infrastructure as code is done. Resourcegroup, keyvault and storage being provisioned through GH action now. To continue we need to define the actual needs.

**Comment by nilsml** [comment]
Comment from #2039 

> This will result in a new url, so to avoid that the next time around, we should have a sub domain for the storybook – for example storybook.eds.equinor.com. Alternatively we could consider using something else than storybook, like components for example.

> We currently have two storybooks, one for core-react and one for lab(s)-react, but it is possible to have a storybook that pull in content from other storybooks, so that’s probably something we should look into.

**Comment by nilsml** [comment]
Current state is that most resources are now automatically deployed using Bicep. However getting the certificate from the keyvault is not working as the CDN application does not have access. Created an issue in ServiceNow to get it resolved. Started on documentation in FigJam as well: https://www.figma.com/file/0W3fL2wyPzqAmXRazRfst9/Azure-architecture?node-id=0%3A1&t=QfUy31ArR7vplXRZ-0

**Comment by nilsml** [comment]
Remember to check CORS settings for CDN

**Comment by nilsml** [comment]
Documentation moved to Miro:
https://miro.com/app/board/uXjVPiRRT0k=/?share_link_id=840601281155

**Comment by nilsml** [comment]
Closing this as everything is done except onboarding the team. This will be done as part of handover from me before I leave the team.
