### ISSUE TITLE
Avoiding typos in styles

### ISSUE THREAD

**Issue by martalalik** [equinor/design-system#2417]
If in a property appears typo, ts-styled-plugin will highlight the error, but if a value contains typo, no warning will appear. 

![Screenshot 2022-08-16 at 13 50 29](https://user-images.githubusercontent.com/105340174/184872717-a55f8352-1f2d-40c3-a326-aca0fbe45b99.png)

**Comment by mimarz** [comment]
First we need to fix this error and secondly this could be avoided by introducing tooling such as Stylelint, we briefly touched upon earlier #2071

**Comment by mimarz** [comment]
this will be addressed by #2526
