### ISSUE TITLE
List of empty storefront pages that need to be updated later:

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#242]
**Ref.** discussion: https://equinor.slack.com/archives/GEF6LDVT9/p1582023866009600

1.  **DEV** Getting started developers: _https://eds.equinor.com/getting-started/developers/_ Can you look at these pages? The intro page needs to be updated, I can try but better if one of you do it. What about the other 3 pages? Do we need to add links to storybook ++  ? 
1.  **DEV** Remove this? What were we going to say about tokens https://eds.equinor.com/guidelines/tokens/
1. **DEV** https://eds.equinor.com/assets/product-icons/library/
   What do we do here? Remove the page? We have like 2 product icons now.  
1. **DEV** https://eds.equinor.com/contributing/developers/ **We should have something here, contact info, something else? **
1. DEV https://eds.equinor.com/help/resources/ **I think this was supposed to be one page with EDS downloads and links like Material and Carbon and others have. Should we have that or remove?**
1. **DESIGN** https://eds.equinor.com/patterns/common-actions/  **some draft content here - might just be copy/paste from Material**
1. **DESIGN** https://eds.equinor.com/patterns/data-formats/ **some draft content here - might just be copy/paste from Material**
1. **DESIGN** https://eds.equinor.com/patterns/loading/ **some draft content here - might just be copy/paste from Material**
1. https://eds.equinor.com/components/buttons-toggle/ **content coming**
1. https://eds.equinor.com/components/date-picker/usage/ and overview **Lotte working on this, just remove from menu**
1. https://eds.equinor.com/help/faq/  **some content here  - delete for now**
1. https://eds.equinor.com/patterns/empty-states/ **Empty - remove**
1. https://eds.equinor.com/patterns/launch-screens/ **Empty - remove**
1. https://eds.equinor.com/patterns/onboarding/ **Empty - remove**
1. https://eds.equinor.com/assets/system-icons/usage/ Mode was Publish instead of publish. **Fixed**

**Comment by mimarz** [comment]
@BeckyBrekke is this still relevant?

**Comment by BeckyBrekke** [comment]
Don't think these are relevant anymore.
