### ISSUE TITLE
Create oil / oil barrel icon

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2437]
Need to create an oil and oil barrel icon in our Assets library

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist @benteljones 
It falls under the category Technical https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905

**Comment by benteljones** [comment]
LGTM! 😊
