### ISSUE TITLE
Component overview design vs code

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2440]
While updating documentation in Zero Height, there are some component that have multiple variant in code that doesn't exist in Figma. In order to be aligned with code and with the update of EDS 2.0 eds-designers want to have an overview in order to see what can be implemented or not.

**Comment by lucasveil** [comment]
While updating documentation in Zero Height, there are some component that have multiple variant in code that doesn't exist in Figma. In order to be aligned with code and with the update of EDS 2.0 eds-designers want to have an overview in order to see what can be implemented or not.

**Comment by lucasveil** [comment]
Overview ready here https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=3827%3A132373 @BirteThornquist @benteljones 
Anything missing? Should we have this page somewhere else so it is easier to find than in Lucas test environement?

**Comment by BirteThornquist** [comment]
LGTM! Maybe we could have a separate page in the new structure Victor is putting up?

**Comment by benteljones** [comment]
Yes, I also think that we should have this page somewhere in a new structure, easy to find. 👍🏻

Someone who knows why the chevron icon has different sizes on accordion in code?
![Skjermbilde 2022-09-06 kl. 11.27.54.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/b2b80737-bea0-4147-8912-0bad710e3893)

**Comment by lucasveil** [comment]
Checking Design vs Code routine will be implemented in new releases of component in EDS 2.0
