### ISSUE TITLE
Update the design of side bar to be aligned with the top bar.

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2448]
In review we discovered an imbalance between the side bar and the top bar. They both must have the same padding, hence increase the with of the side bar.

**Comment by BirteThornquist** [comment]
Changed the side bar container to 74 px width, including the 2px right border. Changed the items width to 27px which gives a 24px left/right padding for the items. The divider was also set to 2px to follow the other borders.

**Comment by benteljones** [comment]
@LGTM, just some few questions @BirteThornquist:
List currently has a width of 240, but it is responsive. Should it be the same width by default as the items (w=254)?
The Divider has a width of 80. Should it be the same as collapsed container (w=74) by default?
Should the user be able to expand the width of the container/items? It might be that some of the teams need a wider field.
![Skjermbilde 2022-09-06 kl. 14.55.53.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/8971f591-a190-4d53-b471-6cedb5d176c2)

**Comment by BirteThornquist** [comment]
Will be solved by the new EDS 2.0 component. Closing issue.
