### ISSUE TITLE
MDX not working as intended in storefront

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#245]
Probably related to latest updates to MDX support in gatsby (new plugin) and tab support?

https://www.gatsbyjs.org/docs/mdx/writing-pages/

* Using import statements in MDX files does not work, only result in undefined. 
* `pageContext` as written in is undefined
* use of `grapql` throws error pages

**Comment by wenche** [comment]
Closing this as we have ported to the docz gatsby theme #474   and these issues shouldn't be relevant anymore.
