### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by martalalik** [equinor/design-system#2450]
### Goals

- [ ] Add & update variants in Figma.
- [x] Create ToggleButton.
~~Create ToggleButtonGroup.~~
- [x] Add ToggleButton to Storybook.
- [x] Update Zeroheight.

#### _Requirements_

1. [Materials](https://material.io/archive/guidelines/components/buttons.html#buttons-dropdown-buttons):

- Focus and pressed states may reinforce that toggles are part of a group. For example, when one button segment is focused, focus may be displayed simultaneously on the rest of the segment.
- Have at least three toggle buttons in a group.
- Label buttons with text or an icon.
- The following combinations are recommended: 
-- Multiple and unselected
-- Exclusive and unselected
-- Exclusive only

#### _Variants_:

1. [Exclusive selection](https://mui.com/material-ui/react-toggle-button/#exclusive-selection) - With exclusive selection, selecting one option deselects any other. Exclusive selection does not enforce that a button must be active.
3. [Multiple selection](https://mui.com/material-ui/react-toggle-button/#multiple-selection) - Multiple selection allows for logically-grouped options, to have multiple options selected.
4. [Vertical buttons](https://mui.com/material-ui/react-toggle-button/#vertical-buttons).
5. [Enforce value set](https://mui.com/material-ui/react-toggle-button/#enforce-value-set) - If you want to enforce that at least one button must be active.
6. [Custom](https://mui.com/material-ui/react-toggle-button/#customization) - customise the component.
7. With `Menu` 
![Screenshot 2022-08-25 at 10 03 35](https://user-images.githubusercontent.com/105340174/186610376-306a89ea-936d-427b-ada7-a74abb9a3644.png)

8. In `TopBar`.
9. Text only.
10. Icon only.
11. Text & icon.

#### _Accessibility_:
1. [ARIA](https://mui.com/material-ui/react-toggle-button/#accessibility) - ToggleButtonGroup has role="group". You should provide an accessible label with `aria-label="label"`, `aria-labelledby="id" `or `<label>`. ToggleButton sets `aria-pressed="<bool>"` according to the button state.You should label each button with aria-label.
2. [Keyboard](https://mui.com/material-ui/react-toggle-button/#keyboard) - Navigate between buttons with the tab key. The button behaviour follows standard keyboard semantics.

#### _Practice_: 

- https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/
- https://www.w3.org/TR/wai-aria-1.1/#switch
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed
- https://joshcollinsworth.com/blog/accessible-toggle-buttons
- https://inclusive-components.design/toggle-button/

#### _Additional info_: 
- https://medium.com/tap-to-dismiss/a-better-segmented-control-9e662de2ef57

**Comment by martalalik** [comment]
### Research

#### _Requirements_

1. [Materials](https://material.io/archive/guidelines/components/buttons.html#buttons-dropdown-buttons):

- Focus and pressed states may reinforce that toggles are part of a group. For example, when one button segment is focused, focus may be displayed simultaneously on the rest of the segment.
- Have at least three toggle buttons in a group.
- Label buttons with text or an icon.
- The following combinations are recommended: 
-- Multiple and unselected
-- Exclusive and unselected
-- Exclusive only

#### _Variants_:

1. [Exclusive selection](https://mui.com/material-ui/react-toggle-button/#exclusive-selection) - With exclusive selection, selecting one option deselects any other. Exclusive selection does not enforce that a button must be active.
3. [Multiple selection](https://mui.com/material-ui/react-toggle-button/#multiple-selection) - Multiple selection allows for logically-grouped options, to have multiple options selected.
4. [Vertical buttons](https://mui.com/material-ui/react-toggle-button/#vertical-buttons).
5. [Enforce value set](https://mui.com/material-ui/react-toggle-button/#enforce-value-set) - If you want to enforce that at least one button must be active.
6. [Custom](https://mui.com/material-ui/react-toggle-button/#customization) - customise the component.
7. With `Menu` 
![Screenshot 2022-08-25 at 10 03 35](https://user-images.githubusercontent.com/105340174/186610376-306a89ea-936d-427b-ada7-a74abb9a3644.png)

8. In `TopBar`.
9. Text only.
10. Icon only.
11. Text & icon.

#### _Accessibility_:
1. [ARIA](https://mui.com/material-ui/react-toggle-button/#accessibility) - ToggleButtonGroup has role="group". You should provide an accessible label with `aria-label="label"`, `aria-labelledby="id" `or `<label>`. ToggleButton sets `aria-pressed="<bool>"` according to the button state.You should label each button with aria-label.
2. [Keyboard](https://mui.com/material-ui/react-toggle-button/#keyboard) - Navigate between buttons with the tab key. The button behaviour follows standard keyboard semantics.

#### _Practice_: 

- https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/
- https://www.w3.org/TR/wai-aria-1.1/#switch
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed
- https://joshcollinsworth.com/blog/accessible-toggle-buttons
- https://inclusive-components.design/toggle-button/

**Comment by martalalik** [comment]
![1_X3iZ5B0n3AnV39lGIVbUIw](https://user-images.githubusercontent.com/105340174/189349632-4955d04a-44d2-4ce2-8736-84f0759ff5bd.png)

**Comment by mimarz** [comment]
Released in [eds-core-react@0.22.0](https://github.com/equinor/design-system/releases/tag/eds-core-react%400.22.0)!
