### ISSUE TITLE
Top bar: change header gap to 12px

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2456]
At design meeting on August 30 we agreed to reduce gap in topbar header from 24 to 12px to align with the new design in figma, where app launcher button is to be replaced with "product icon" / "logo"

![bilde.png](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/b844279c-9ae8-4ccf-a617-13994d74f787)

**Comment by akvam** [comment]
Need to take a check against project using the app launcher. 
Then we can describe the scope of this US.

**Comment by BirteThornquist** [comment]
Yes. We have a 12px spacing between the icon and title in the ESD 2.0 top bar.
