### ISSUE TITLE
Custom content in tooltip

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#2459]
**Is your feature request related to a problem? Please describe.**

More often than not, the standard tooltip does not have space for all the information the designers want in it

**Describe the solution you'd like**

To have a flexible tooltip (in addition or as a property) to the one we have today

**Describe alternatives you've considered**

Can make one ourselves, or use another package

**Additional context**

From what we have in design for instance
![image](https://user-images.githubusercontent.com/35257765/187896097-c642bbaf-b3ed-4764-b95f-6f93e959f7f6.png)

**Comment by oddvernes** [comment]
It sounds to me like you are describing the [popover](https://eds-storybook-react.azurewebsites.net/?path=/docs/data-display-popover--introduction) component, which can be used as a tooltip with any content. Is there a reason you cannot use this? If so are there any improvements we can do to the popover component?

**Comment by HansKristianVikOlsen** [comment]
Yes, that should do the trick. Thank you!
