### ISSUE TITLE
EDS TextField adds an aria-describedby for a non-existing item if there is no helper text

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#2469]
**Describe the bug**

We are using the `TextField` component with the multiline feature. Axe devtools reports an error regarding the aria-describedby. It seems like it is because the TextField component always adds an `aria-describedby` even if there is no helper text added.

**Steps to reproduce the bug**

1. Create a TextField (multiline, no helperText)
2. Use the inspector tool and notice that `aria-describedby="eds-helpertext-number"` is added even if this element doesn't exist

**Expected behavior**

Should not add aria-describedby for non-existing elements

**Additional context**
![Skjermbilde 2022-09-07 kl  11 04 17](https://user-images.githubusercontent.com/1568252/188838135-870b64a9-a64f-4f01-8fa2-fddee8fff7af.png)

![Skjermbilde 2022-09-07 kl  11 05 07](https://user-images.githubusercontent.com/1568252/188838340-287ae3c1-5f95-430f-84d4-7251f1b4618f.png)

**Comment by mimarz** [comment]
Doh! Thanks for the notice.

We are currently re-writing all our "input" components, so we'll fix this in the "new" component.

Will be fixed by #2336

**Comment by oddvernes** [comment]
There was a bug in the inputwrapper so id was always set to null on the helpertext. I'll fix it
