### ISSUE TITLE
New icon set from Fusion

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2476]
3 new icons needs to be implemented and a redesign of "reorder" icon:

![image](https://user-images.githubusercontent.com/65652493/189292956-2997aa85-e606-4baa-8a9d-2220da92ecc2.png)

**Comment by lucasveil** [comment]
Add the slack icon as a input from Trond Roar Eide

**Comment by benteljones** [comment]
LGTM, @lucasveil  😊👍

**Comment by BirteThornquist** [comment]
LGTM as well @lucasveil 👍

**Comment by lucasveil** [comment]
Change name from **maximize** to **expand screen** and from **minimize** to **reduce screen** since those icons already exist in the library.
