### ISSUE TITLE
Customise individual items in <Autocomplete>

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/design-system#2487]
**Is your feature request related to a problem? Please describe.**

When using the `Autocomplete` selector / dropdown, I'd like to be able to customise the different items.
In my use case, I have a list of projects, some of which the user have read access to, while other they can write to.
I'd like to convey this information with an icon, and tooltip (or different) for each element in the list.

I'd like write something like this

```typescript tsx
<Autocomplete
    multiple
>
    {projects.map((project: string) => <Autocomplete.Item
        text={project}
    >
        <Icon variant={useHasAccess(project, user) ? 'writable' : 'readable' />
<Autocomplete.Item />
<Autocomplete />
```

**Describe alternatives you've considered**

It could be possible to simulate this behaviour with `useRef`, and some CSS, or simply give an indication after the user has made their selection.

**Additional context**

**Comment by mimarz** [comment]
Thanks for requesting this feature! 

I remember we wanted to do it like you requested to begin with, but got defeated in the end by `downshift` not supporting this way of interacting with the data and rendered elements. 

Not sure what we can do there, but maybe we can have a separate render function you can define for each item or something like that 🤔

We are currently working on our two next releases; `Sidebar` and a re-write of all "input" components. Both are developed, but currently in testing and bug-fixing. So it'll probably be a while before we can have a look at this again.
