### ISSUE TITLE
Adding more alternatives for "value" prop in the TextField component

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/design-system#2492]
**Is your feature request related to a problem? Please describe.**
In our project, we use the TextField EDS component to select the number of iterations for an algorithm. This should only be a positive number >= 1. Right now we have to do validation on the backend that the number is >= 1. It would be nice to have this validation directly in the TextField component

**Describe the solution you'd like**
Adding more options for the value prop in [TextField](https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--introduction):
For example
* positiveNumber
* strictlyPositiveNumber

**Describe alternatives you've considered**

Alternative:  do number validation on the backend
**Additional context**

**Comment by mimarz** [comment]
How about you get access to the input directly? 😁

We currently have a big change internally on streamlining how we handle our inputs coming up! #2336 The `InputWrapper` (as its called now) was made for internal use, but we might expose it publicly or have an easier way of implementing some similar feature like this. 

We'll have a look on how validation and such as this might be solved when we land our feet on the `InputWrapper`

**Comment by BirteThornquist** [comment]
@oddvernes will check up what the status of this

**Comment by oddvernes** [comment]
Front end validation should be handled outside our components, there are a couple examples in the [storybook](https://s478stedsstorybookdev.z16.web.core.windows.net/?path=/docs/inputs-textfield--introduction#validation) 

Closing this issue
