### ISSUE TITLE
Update storefront landing page

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2497]
Got feedback from several people that they couldn't find the necessary information at glance when they arrived to eds.equinor.com.

Suggestions for improvements
- [x] Remove "whats new" as its just copy paste, outdated and is not as good as githubs own [releases page](https://github.com/equinor/design-system/releases)
- [x] Have "for developers" card link directly to github, instead of interim page

**Comment by lucasveil** [comment]
New section deleted and new link implemented.
Ready for review @BeckyBrekke

**Comment by BeckyBrekke** [comment]
Looks good, there was just an extra space down at the bottom in the community based section I removed.

**Comment by BeckyBrekke** [comment]
Preview link for the changes: https://zeroheight.com/0b0c666ab/v/latest/p/238bf3-equinor-design-system
