### ISSUE TITLE
Autocomplete hidden when used inside of a Menu

### ISSUE THREAD

**Issue by mariush2** [equinor/design-system#2501]
**Describe the bug**

When using an autocomplete inside of a menu the options are hidden when opening the autocomplete

**Steps to reproduce the bug**

1. Open menu with autocomplete inside
2. Open Autocomplete

**Expected behavior**

Expected autocomplete options to be visible above Menu

**Specifications**

- Version: 0.21.0
- Browser: Chrome
- OS: mac os

**Additional context**

[CodeSandbox example](https://codesandbox.io/s/awesome-shtern-gxi2gk?file=/src/App.tsx)

**Comment by mimarz** [comment]
Thats a weird combination of components, whats the intended use-case here? 🤔 

Menu is meant for listing a set of actions/choices, so semantically each menu item is a button for beste `a11y` support.

**Comment by mariush2** [comment]
Here's an example of our use-case 😄 

https://user-images.githubusercontent.com/24507952/191222920-445e377a-a2d3-4b0c-99b5-d63f8f09f362.mov

**Comment by mimarz** [comment]
I suggest using the `Popover` for this use case :)

**Comment by mariush2** [comment]
Tried using a `Popover` now but the Autocomplete options are still being put behind the `Popover` component. 

https://user-images.githubusercontent.com/24507952/191228539-5f5aadd0-e718-4964-951a-0e34b1e5717a.mov

**Comment by mimarz** [comment]
Now that looks like a bug we need to fix! 🐛

**Comment by mimarz** [comment]
This was solved in the latest release of `eds-core-react@0.22.0`
