### ISSUE TITLE
`Autocomplete` dropdown when inside `Popover` is underneath

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#2502]
[from comment](https://github.com/equinor/design-system/issues/2501#issuecomment-1252121377) in #2501 

When `Autocomplete` is used inside our `Popover` the dropdown menu is displayed underneath the popover.

https://user-images.githubusercontent.com/24507952/191228539-5f5aadd0-e718-4964-951a-0e34b1e5717a.mov

Notes:
- This might be due to stacking content and how we use portals?

**Comment by oddvernes** [comment]
Popover is not in a portal but it does have a z-index of 1400

**Comment by mimarz** [comment]
> Popover is not in a portal but it does have a z-index of 1400

yeah, and I don't think we've assigned anything to the dropdown on `Autocomplete`. If not it should maybe be the same as `Menu`. @oddvernes
