### ISSUE TITLE
Split Button .Group & .Toggle into sub-directories 

### ISSUE THREAD

**Issue by martalalik** [equinor/design-system#2509]
Suggesting to split `Button` docs into  sub-directories. There’s a bit too much in the docs after adding `ButtonGrout` & `ToggleButton`.

**Comment by mimarz** [comment]
Suggest following the same breakdown we have for selection controls or progress.

Maybe something along the lines of;
* Buttons
  * Button
  * Group
  * Toggle
  
Alternatively to reflect where they can be found (but we dont do this for progress, so maybe change one or the other to match 🤔)
  
* Buttons
  * Button
  * Button.Group
  * Button.Toggle

**Comment by mimarz** [comment]
> I lean towards
> 
> > * Buttons
> >   
> >   * Button
> >   * Group
> >   * Toggle
> 
> Just because users are familiar with progress naming 🤔

Jepp, the stories, usage and code example will all show `Button.Group` and `Buttong.Toggle` so should be easy to discern :)
