### ISSUE TITLE
Create Avatar component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#251]
We already use this "component" in Cards & Chips.

Extract it to a standalone component in Figma to draw the red line with code and write documentation on usage and limitations.

Notes
* Image is cropped to circle and centered
* Define sizes
* Should it support text?  

- [ ] Figma component
- [ ] Storefront page
- [ ] Design documentation

Examples: 
- https://material.io/design/communication/imagery.html#informational-imagery
- https://material-ui.com/components/avatars/
- https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=5155%3A17713

**Comment by martalalik** [comment]
Closing this issue. Avatar exists in EDS.

**Comment by BirteThornquist** [comment]
Closing this issue as this will covered in the 2.0 version.
