### ISSUE TITLE
Create side bar with auto layout

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2518]

**Comment by benteljones** [comment]
Can we take a look at where we place the text vertically in the Side bar? I think it's wise that we run all similar components together. For example, same location as in Menu.![Skjermbilde 2022-10-25 kl. 10.12.05.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/21b1126a-eb4a-4d72-9046-69ef783b97a7)

**Comment by BirteThornquist** [comment]
When it comes to adjusting icon/label to the hard grid, this will be done using spacing tokens. We will create a separate issue for tokenizing the side bar component.
