### ISSUE TITLE
DatePicker from "eds-lab-react". A couple issues

### ISSUE THREAD

**Issue by aslakihle** [equinor/design-system#2546]
Hey! Im using the DatePicker component from “eds-lab-react”. I’ve come across a couple of issues.

**Describe the bug**

I am using the DatePicker inside another div that has to have “overflow:scroll”. This results in the calendar popup to select dates gets hidden within this “overflow: scroll” rule.

**Steps to reproduce the bug**

Put a DatePicker within a parent div that has the css “overflow:scroll”, but currently is only a little taller than the DatePicker input field.  Click the DatePicker to open the calendar, and it is hidden. You can scroll to see it, but would like it to just ‘override’ the overflow:scroll from the parent. 

Here is a simple code sandbox showing the problem, and an AutoComplete component that behaves like I expected the DatePicker to: https://codesandbox.io/s/angry-tess-qlrquk?file=/src/App.tsx

**Expected behavior**

Next to the DatePicker I am using AutoComplete (as a dropdown input) from “eds-core-react” that opens ‘outside’ of the “overflow: scroll” rule. For my case I would like the DatePicker to open like the AutoComplete currently does.

**Specifications**

- Version: 0.4.2
- Browser: Google Chrome
- OS: MacOS

**Additional context**
Snippet showing a the hidden calendar
![Screenshot 2022-10-04 at 15 19 21](https://user-images.githubusercontent.com/17411650/193829710-a3812ca3-b344-4b9c-94a2-7f1f5f9e1212.png)

Another issue that I'm just throwing in here is that the calendar does not close when selecting a date. In this case I expected it to work like when you select an option on the AutoComplete.

**Comment by mimarz** [comment]
Hi @aslakihle !

The `DatePicker` is a community contribution and not something we are currently maintaining as this date/time pickers a very complex to get right nor do we have the ressources.

We recommend using the `Input` or `TextField` with appropriate type. You can find an example here: https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--datepicker

If this still doesn't suit your needs, your are welcome to make a PR with changes to the `DatePicker`. The eds-lab is more experimental and free for all :)

**Comment by lucasveil** [comment]
This issue is not prioritised right now consider adding **help wanted** for external contributors

**Comment by BirteThornquist** [comment]
@oddvernes will check up on this an conclude.

**Comment by oddvernes** [comment]
I believe I forgot to close this issue, closing now
