### ISSUE TITLE
DatePicker from "eds-lab-react" - "disableAfterDate" prop

### ISSUE THREAD

**Issue by aslakihle** [equinor/design-system#2547]
**Is your feature request related to a problem? Please describe.**

I need to select dates between two specific dates. The existing prop “disableBeforeDate” works perfectly, but, yeah, I also need its counterpart “disableAfterDate” in my case.

**Describe the solution you'd like**

I would like to see is a “disableAfterDate” prop on the DatePicker component, that works similarly to "disableBeforeDate. I am aware of the “disableFuture”, but in my case it does not fit.

**Comment by mimarz** [comment]
If you want this feature your going to have to make a PR 😉

**Comment by lucasveil** [comment]
Similar to #2546

**Comment by oddvernes** [comment]
resolved by #2830
