### ISSUE TITLE
Status-halv full icon

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#2551]

**Comment by akvam** [comment]
To show status there is a need for a status halv full icon.


![image.png](https://images.zenhubusercontent.com/60754619d2059fefad0fcc02/d61b292f-77fe-4edc-a3b8-394df8955b81)

Ref. The form i shown in the Designer Sandbox - feature request Added

**Comment by lucasveil** [comment]
Icon created under the name In-progress.
Ready to review under UI Views category @BirteThornquist @benteljones

**Comment by BirteThornquist** [comment]
LGTM! @lucasveil
