### ISSUE TITLE
Example of virtual scrolling in Table

### ISSUE THREAD

**Issue by yusijs** [equinor/design-system#2561]
**Describe the solution you'd like**

I would love to have a demonstration of best practice ™️ on how to implement virtual scrolling in the React table, as we often have vast amounts of data on the screen at any given time.

**Describe alternatives you've considered**

If I had the expertise in react to create a best practice ™️ example this would be viable
![image](https://user-images.githubusercontent.com/11261560/194518361-ee51eff6-d564-476f-9b27-f82800c24b9c.png)

Alas I would probably make a hacky example that would be more like this
![image](https://user-images.githubusercontent.com/11261560/194518657-8882b3ee-d492-47c7-96c0-1c6275286b27.png)

**Additional context**

**Comment by mimarz** [comment]
😂

**Comment by mimarz** [comment]
Maybe we could use [react-window](https://www.npmjs.com/package/react-window) for this?

**Comment by mimarz** [comment]
Related issue #1909

**Comment by martalalik** [comment]
[React-window ](https://www.npmjs.com/package/react-window)relies on using divs for its infinite scroll capabilities making it hard to implement with our table components as they are native table elements. Most examples online also use divs styled as table for this functionality. We need to investigate what to do next, do we make our table components be castable to divs, find some other way to apply table styling to other elements or try to implement this feature our selves using table elements (if possible).

**Comment by oddvernes** [comment]
We should investigate https://tanstack.com/virtual/v3 which is used internally by [material-react-table](https://github.com/KevinVandy/material-react-table/blob/main/src/body/MRT_TableBody.tsx). Could this be used externally with how our table is set up?

**Comment by yusijs** [comment]
I fucked around and I found out a bit - I created a very basic example using the IntersectionObserver api. Made a codesandbox for it that loads and renders 5000 rows from jsonplaceholder.com. Not perfect but it does - at least partly - what I want it to. It's a bit jumpy on col-widths because native table-elements are an absolute PITA

https://codesandbox.io/s/confident-stitch-p98uni
