### ISSUE TITLE
Autocomplete in Dialog makes dropdown have wrong position

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/design-system#2574]
**Describe the bug**

The dropdown list is not located next to the Autocomplete text field as expected

**Steps to reproduce the bug**

1. Create an EDS Dialog
2. Inside the Dialog add an Autocomplete
3. Add a button that sets the Dialog's open property to true
4. The Autocomplete dropdown automatically opens, but at the wrong position

**Expected behavior**

**Specifications**

- Version: 0.20.4
- Browser: Firefox/Chrome
- OS: Mac

**Additional context**

<img width="918" alt="Screenshot 2022-10-11 at 16 24 34" src="https://user-images.githubusercontent.com/64828956/195118160-a1fb2324-e3f7-476c-a020-acc75f33cd18.png">

**Comment by mimarz** [comment]
Hi @ingeridhellen!

Could you try upgrading to the latest version of core-react (v0.23.0) and test again? 
We change the library in charge of position floating elements in v0.21.0 (popperjs with floating-ui).

**Comment by ingeridhellen** [comment]
Hi @mimarz

Thanks, that solved it. Sorry to bother you, I honestly thought we had the newest core-react version already
