### ISSUE TITLE
Autocomplete value cleared when pressing ESC

### ISSUE THREAD

**Issue by mholta** [equinor/design-system#2611]
**Describe the bug**

When using the `Autocomplete` component from `eds-core-react`, the selected options is being cleared when pressing `ESCAPE` after selecting an option. The happens after both keyboard and mouse selection. The component also fires `onOptionsChange` with 0 options.

**Steps to reproduce the bug**

Follow the steps in this simple reproduction: https://codesandbox.io/s/stupefied-snowflake-uov3hb?file=/src/App.tsx

1. Navigate to the combobox using TAB / click the combobox
2. Select option with keys / click option
3. Press ESCAPE

**Expected behavior**

"Escape closes the menu, keeping the currently highlighted option selected" to support WCAG (I assume this is WCAG behaviour). From https://www.24a11y.com/2019/select-your-poison/#:~:text=Escape%20closes%20the%20menu%2C%20keeping%20the%20currently%20highlighted%20option%20selected

**Specifications**

- Version: 0.25.0
- Browser: Chrome
- OS: MacOS

**Additional context**

https://codesandbox.io/s/stupefied-snowflake-uov3hb?file=/src/App.tsx

**Comment by mimarz** [comment]
Interesting, its not what the [APG for combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) says: 

> Escape: Closes the popup and returns focus to the combobox. Optionally, if the combobox is editable, clears the contents of the combobox

This behaviour is also the default behaviour from downshift which is the library we use for "combobox".

Not sure what to do here 😅

**Comment by oddvernes** [comment]
Closing as our component follows the ARIA Authoring Practices Guide on this interaction
