### ISSUE TITLE
Storefront links to icons on storybook broken

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2619]
Storybook has been updated and there are new links to the icons. All links in storefront need updating. 

https://eds.equinor.com/0b0c666ab/p/196746-resources
https://eds.equinor.com/0b0c666ab/p/347dd6-system-icons/b/25520a
https://eds.equinor.com/0b0c666ab/p/347dd6-system-icons/b/7568e4

**Comment by lucasveil** [comment]
Links are updated and made a new release.
If you can have a second look @BeckyBrekke  :)

**Comment by BeckyBrekke** [comment]
@lucasveil 2 were fixed but the one on the resources page was broken (storybook - icons). I fixed it and just made a new release. Do you want to check now?

**Comment by lucasveil** [comment]
Yep works for me @BeckyBrekke :)
