### ISSUE TITLE
As a designer I need rules for how to (or not to) combine primary and secondary colors on buttons.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#262]
Include rules for how to use contained and outlined. 

Comments from worksho:
Need to define sequence rule, including both positive and negative rules . 

=> EDS to use Windows rules, use the main button to the left. 

=> Exception: Critical actions, the conform button is to the right, to be sure that the user does not do this automatically without thinking.

**Comment by benkeq** [comment]
[Ready for review](https://github.com/equinor/design-system/commit/ece43ecfc5f603daab14020c3661bb195709a839) @lucasveil 

You could also take a look in [Figma](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/?node-id=624%3A0)
