### ISSUE TITLE
Input with type="number" allows letters in Firefox

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/design-system#2636]
**Describe the bug**

**Steps to reproduce the bug**

1. Go to https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-input--types
2. In the Number field, write "hei"

**Expected behavior**

If you're using Chrome, these characters would be ignored, but if you use Firefox, they will not. Issue seems to come from https://bugzilla.mozilla.org/show_bug.cgi?id=1398528, and Firefox does not seem to have any plan of fixing it themself.

**Specifications**

- Version:
- Browser: Firefox
- OS:

**Comment by oddvernes** [comment]
Hello and thank you for the report!
EDS form elements does not handle input validation, since it would be very difficult to capture all use cases here. See the last comment in the bugzilla link, by Daniel Holbert, why this is the case and even chromes built in solution is incomplete. 
Instead we suggest projects implement their own input validation, or use a third party solution such as [react-hook-form](https://react-hook-form.com/) like in our [storybook example](https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-textfield--introduction#validation-with-react-hook-form) 🙂

**Comment by ingeridhellen** [comment]
That makes sense. However, it is problematic that an EDS component behaves so differently from one browser to the next. Since not all development teams use all browsers, this can cause long-lived bugs. I would suggest removing "number" as an input type and instead encourage developers to use pattern to validate their input.

**Comment by ingeridhellen** [comment]
My biggest concern regarding type="number" is that in Firefox, if you input "1.3" it works nicely, but if you write "1,3" it interprets it as if you've written nothing at all. This mistake is so easy for an end user to make, and they get by default no feedback about it. If the input is optional, you risk simulations are run with different input than intended.
And as a developer using Firefox and looking at this exact component for a time, it took a while before I realized this issue. I suspect many teams have not considered it at all.

**Comment by oddvernes** [comment]
I agree this is problematic, but this is a native prop on the native input inside the eds component, so it is not something we can do anything about really. I suggest using type="text" and have your own validation to make it consistent across browsers. 
I see [MUI](https://mui.com/material-ui/react-text-field/) does the same thing we do, while [Mantine](https://mantine.dev/core/number-input/) have made seperate components for number text and password. Seems like their custom numberInput is type="text" with their own home made validation built in kind of similar to firefox behaviour maybe (1,2 turns into 1, 1e24 turns into 1e+24). This might be something we could consider in the future

**Comment by ingeridhellen** [comment]
That is exactly what I did, and the issue is solved in my case. But it was time consuming and unintuitive. Perhaps a simply, temporary solution would be to update https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-input--types to not list type="number" as an alternative? And perhaps have an example of how to instead use type text with pattern validation?

**Comment by oddvernes** [comment]
Yes, we can write a note about why type=number is problematic and recommend to use type=text and homemade/third part validation instead for this in the storybook. And maybe make another example. Currently we already have an example how to validate number using react-hook-form 👍

**Comment by ingeridhellen** [comment]
Sounds great! For inspiration, here's how I solved it in our project
```ts
import { Input } from '@equinor/eds-core-react'
import { useState } from 'react'

export const InputExample = (props: {
  value: string
  setValue: (x: string) => void
}) => {
  const [isValid, setIsValid] = useState<boolean>(true)
  return (
    <Input
      id="inputExample"
      value={props.value ?? ''}
      pattern="^\d+(\.\d+)?([eE][-+]?\d+)?$"
      variant={isValid ? 'default' : 'warning'}
      onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
        setIsValid(
          event.target.checkValidity() && !isNaN(Number(event.target.value))
        )
        props.setValue(event.target.value)
      }}
    />
  )
}

```

**Comment by ingeridhellen** [comment]
@oddvernes The PR only updates the info for the TextField. Shouldn't the documentation for the Input component be updated as well?
