### ISSUE TITLE
As a designer I need to know how to align all components to the grid.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#264]
Blocked by #632 

Rules for alignment and check if any components must be adjusted. 

Comments  from workshop: 

Text input 

Write in documentation that the visuals should align when designing a form horizontally. Add to patterns > Forms 

Stepper 

Card title

**Comment by lucasveil** [comment]
Her er [linken til dokumentasjon](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=2%3A208) i figma @benkeq

**Comment by benkeq** [comment]
Her må vi sikkert få teksten inn i documentation-branchen før @BeckyBrekke ser på det, sånn at det er enklere å redigere teksten.

Mangler jo også litt formatering i teksten, men jeg regner med det blir lagt til før det blir lagt til i storefronten. Du kan også dra litt linjer til https://eds.equinor.com/guidelines/grid/ siden det basically er samme greia. Legg ved en lenke, og skriv hva en kan lese om en trykker på lenka. Kan også oppdatere teksten på https://eds.equinor.com/guidelines/grid/ sånn at den lenker tilbake til Patterns/Grid.

**Comment by vnys** [comment]
I can assist you in adding the pages to the storefront, @lucasveil, just let me know on Slack when you have the time. Then we can create a pull-request, and ask @BeckyBrekke to do a review.

**Comment by lucasveil** [comment]
Thanks @vnys I will rework the text and implement some of the "grid" documentation. Will let you know when ready
