### ISSUE TITLE
Investigate how to do documentation in Figma

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#2646]
In order to have a better flow for our user and documentation, eds-designers decided to have documentation on the same page as the component in Figma

**Comment by BirteThornquist** [comment]
I'm adding investigation resources and notes in [this](https://www.figma.com/file/z9Ccti3VWatpsYg2RSfiLL/Documentation-%F0%9F%91%80-and-%F0%9F%AA%B0?node-id=0%3A1&t=DmbyWZGxVEUbnoL7-1) Figjam file.

**Comment by BirteThornquist** [comment]
The investigation has been done and we have agreed to do design documentation in Figma. Closing this issue.
