### ISSUE TITLE
New EDS Icon for Wellbore

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#2656]
**Is your feature request related to a problem? Please describe.**

EDS icons are lacking a icon for wellbore

**Describe the solution you'd like**

The  [WitsmlExplorer](https://github.com/equinor/witsml-explorer) will contribute with a new wellbore icon 

**Describe alternatives you've considered**

**Additional context**

**Comment by marmid74** [comment]
Wellbore icon 
<img width="66" alt="image" src="https://user-images.githubusercontent.com/22211376/203245398-929153f0-1a38-490c-80d8-c1b6da32015d.png">

Used in button
<img width="501" alt="image" src="https://user-images.githubusercontent.com/22211376/203245542-7c61fd42-c8a3-4608-99f3-aba249d71f11.png">

**Comment by lucasveil** [comment]
Ready for review @BirteThornquist @benteljones 
under [Technical](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=3175%3A6905&t=oazGsR5RsdlOiUcE-0) category

**Comment by benteljones** [comment]
Looks great, @lucasveil , LGTM! 😊👍
