### ISSUE TITLE
As a designer I need a table component with multiple lines

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/design-system#266]
Need a component in Figma that can be used in the same way as text area, where text wraps over multiple lines when it doesn´t fit in the width.

![image](https://user-images.githubusercontent.com/56440483/76891850-f2b55600-6889-11ea-9174-9e21b26df0fd.png)

**Comment by lucasveil** [comment]
Solution here is that the user have to add manually 20 px in height for each line. Here is a proposal of explanation:
![cell-multiple-line-text](https://user-images.githubusercontent.com/65652493/92600799-52764200-f2ac-11ea-8d45-8febb3c4050b.png)

**Comment by benkeq** [comment]
@lucasveil Ser at dette ikke er gjort i Figma. Fontstil må endres i Design Tokens, og komponentene i UI—User Interface må oppdateres.

**Comment by lucasveil** [comment]
Updated :)
