### ISSUE TITLE
Reset Icon

### ISSUE THREAD

**Issue by Strepto** [equinor/design-system#2673]
**Is your feature request related to a problem? Please describe.**

I would like an official icon for a "Reset" action. This is frequently useful when you want to reset an input field, slider or similar to its initial value.

**Describe the solution you'd like**

I would like a mirrored "Refresh" icon to be a reset action. I feel this icon is a good representation of the action, and that it could be useful in multiple Equinor applications.

![image](https://user-images.githubusercontent.com/3185998/203956583-6896d721-aec9-4ceb-abe0-7a4401cef485.png)

**Describe alternatives you've considered**

`<Icon style={{ transform: 'rotateY(180deg)' }} data={refresh} />`

Using a "Reset" text instead of icon.

**Example:** 

![image](https://user-images.githubusercontent.com/3185998/203956945-6531751b-4824-4000-be38-e332098287cc.png)

Feel free to close this if you do not feel the need for a Reset Icon. Or if the solution proposed (of a mirrored Refresh) is not a valid design.

**Comment by BirteThornquist** [comment]
Closing this issue as we already have a rotation prop on the icon component and we don't see the need for a separate reset icon.
