### ISSUE TITLE
Autocomplete selects/deselects when pressing tab key

### ISSUE THREAD

**Issue by TormodNy** [equinor/design-system#2675]
**Describe the bug**

When using the `Autocomplete` component from `eds-core-react` with `multiple` enabled, pressing the `tab` key selects the highlighted option. The option is selected regardless if it is highlighted by using arrow keys or hovering with the mouse cursor.

**Steps to reproduce the bug**

Follow the steps in this simple reproduction: https://codesandbox.io/s/headless-pond-vz6toz?file=/src/App.tsx
1. Navigate to the combobox using TAB / click the combobox
2. Select options with arrow keys and enter
3. Press TAB
4. Highlighted option was selected/deselected

**Expected behavior**

Pressing the `tab` key should just move focus to the next element, not change which options are selected.

**Specifications**

- Version: 0.27.0
- Browser: Chrome
- OS: Windows

**Additional context**

https://codesandbox.io/s/headless-pond-vz6toz?file=/src/App.tsx

**Comment by oddvernes** [comment]
I agree, pressing `tab` in an Autocomplete with `multiple` should just close the dropdown without selecting/deselecting the focused item 👍
