### ISSUE TITLE
Need to customize the dialog box component from EDS 

### ISSUE THREAD

**Issue by ShikhaMishra9** [equinor/design-system#2680]
Currently the dialog component we are using from EDS is very narrow . It does not fulfil the criteria with respect to width as well.
Attached are both screen shots , how we are getting it through EDS and how we want it.
<img width="1112" alt="Screenshot 2022-11-29 at 10 32 21" src="https://user-images.githubusercontent.com/40306488/204492582-939b4a9e-d832-4106-b743-2f2b39c8ed98.png">
<img width="400" alt="Screenshot 2022-11-29 at 10 32 48" src="https://user-images.githubusercontent.com/40306488/204492616-bc24e3d2-2c92-42a0-9e5a-b879bb648844.png">

**Comment by oddvernes** [comment]
We might introduce an optional width prop, but note that you can also overwite the width using Styled components/className/style-attribute. for excample `style={{ width: 'clamp(300px, 90vw, 700px' }}`

**Comment by wenche** [comment]
Yup, that's what we did for the time being :) 

`width: clamp(25ch, 60vw, 600px)`

**Comment by BirteThornquist** [comment]
This will be solved in EDS 2.0 and will not be prioritized before the upgrade.
