### ISSUE TITLE
Button loading state design overhaul?

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2682]
As was mentioned in the eds slack channel, our design on eds.equinor.com for a "loading" button is a normal non-disabled button with a loader with neutral color. 
![bilde.png](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/e600051b-fd86-4839-9696-5376a4136068)
But usually, you want a button in a loading state to be disabled, which then looks like this:
![bilde.png](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/9bac501f-758d-4ef0-9c35-29b3e83df831)
[This](https://uxmovement.com/buttons/when-you-need-to-show-a-buttons-loading-state/) article has a good point that the button should be visually disabled but have a high contrast color for the indicator, which in our case would be this:
![bilde.png](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/60cbc84f-a46b-4bd9-85be-c75de8916ee5)

**Comment by BirteThornquist** [comment]
will be solved as a part of #2820
