### ISSUE TITLE
New optional 'closeOnClick' prop on Menu.Item

### ISSUE THREAD

**Issue by mariush2** [equinor/design-system#2683]
**Is your feature request related to a problem? Please describe.**

We sometimes want the 'Menu' component to keep open, even when onClick of a `Menu.Item` gets called.

**Describe the solution you'd like**

Adding an optional prop called something like `closeOnClick` which defaults to true on the `Menu.Item` component.

**Comment by oddvernes** [comment]
I know we have considered and discussed this in the past, but I forgot why we concluded not to add it at the time 😅. We will take another look now that it is a feature request 👍

**Comment by mariush2** [comment]
Just as an example, here we use a Menu with some (currently custom) Menu.Item elements and we don't want the menu to close when changing the selected qualification 😅 

https://user-images.githubusercontent.com/24507952/205037707-2b2a6b50-9853-4928-966b-be263c1145ba.mov

**Comment by oddvernes** [comment]
Interesting. Are you talking about the first or second popup here? Because the second one looks more like a case for `Popover` with all the form elements that probably should be  keyboard navigatable 🤔

**Comment by mariush2** [comment]
Haven't used the `Popover` component before, will that give us the `Menu.Item` and `Menu.Section` styling like it's being used here on the second menu?

**Comment by oddvernes** [comment]
No the popover is just an empty `paper` where you can put whatever content you want, while menu is made for a very particular purpose with special built in functionality for keybaord navigation with arrows etc. 

One important question that has arisen as we are working on this: do you need the `closeOnClick` per `Menu.Item` (so you can have some close and some not) for your use case, or on `Menu` so it either or for the entire menu?

**Comment by mariush2** [comment]
For our use-cases having it per `Menu.Item` would be the best, since we sometimes have menus within menus that only open when clicking certain `Menu.Item` children 😅

**Comment by oddvernes** [comment]
Alright 👍 by the way "nested menus" is another feature request on the board we are going to look into at some point, so closeOnClick would be a pre-requisite for that
