### ISSUE TITLE
New stop_circle icon

### ISSUE THREAD

**Issue by oysand** [equinor/design-system#2702]
**Is your feature request related to a problem? Please describe.**

For our solution we need pause, stop and play buttons and in our design we've went for *_circle icon. However when it comes to the implementation I cannot find a stop_circle icon.

**Describe the solution you'd like**

I'd like to be able to use a stop_circle icon in addition to pause_circle and play_circle.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/32652118/209080660-6072426d-0a90-4ec6-a3ad-44c0f2968aad.png)

**Comment by BirteThornquist** [comment]
Looking good to me @benteljones !

**Comment by benteljones** [comment]
😊👍

**Comment by oddvernes** [comment]
Resolved by #2723
