### ISSUE TITLE
Add support for changing the color on the input field in the Autocomplete component

### ISSUE THREAD

**Issue by krisolba1** [equinor/design-system#2712]
**Is your feature request related to a problem? Please describe.**

It would have been nice to be able to set the background color on the input field and Autocomplete to e.g. white , when page background is gray and so on.

**Describe the solution you'd like**

For example a custom property so I can do <Autocomplete style={{'--eds-input-background: #f7f7f7f7'}} would suffice.

**Comment by v3gard** [comment]
See relevant thread on Slack: https://equinor.slack.com/archives/CJT20H1B9/p1673006553158589

**Comment by benteljones** [comment]
![Skjermbilde 2023-01-06 kl. 16.43.09.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/f67d5ed8-02e9-47a1-9229-d30391c36b43)
