### ISSUE TITLE
Icons: "line" and "onshore_drone" are broken

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2713]
This was reported on [slack by Csaba Kiss](https://equinor.slack.com/archives/CJT20H1B9/p1673252465658589)

![line-icon.png](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/26966bf6-816e-46fc-a047-89eaa5e838e2)

From inspecting both versions of the icon in a browser, it looks like the icon depends on a mask element to not look bloated, but mask is not supported in the code version of the icons. The code version just takes the paths from the svgs and concatenate them into a single string, but masks are ignored. 

I also discovered one more icon with this problem while checking: `onshore_drone`

So both these icons should be recreated with no mask dependency if possible :sweat_smile:

**Comment by oddvernes** [comment]
For comparison,` subsea_drone` looks versy similar, but i notice in figma the paths (except one) are combined using **union** while in `onshore_drone` this has not been done, so doing that properly will _perhaps_ fix it?

**Comment by benteljones** [comment]
Then we looked at the icons and hopefully we have fixed the problem. We have adjusted 4 icons (see screenshot). Ready to check if it works  @oddvernes
 ![Skjermbilde 2023-01-11 kl. 15.23.36.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/2f39131f-1f43-4ec2-8025-57d6262c2c6a)?

**Comment by benteljones** [comment]
![Skjermbilde 2023-01-11 kl. 15.27.03.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/196cc3da-554d-4538-8852-947d5cc2ad21)

**Comment by oddvernes** [comment]
Tested in code OK

**Comment by oddvernes** [comment]
Resolved by #2723
