### ISSUE TITLE
Now feature for time/datetime in datepicker

### ISSUE THREAD

**Issue by Eddasol** [equinor/design-system#2745]
**Is your feature request related to a problem? Please describe.**
It can be confusing that you can only choose today when using datetime since it only affects date and not time

**Describe the solution you'd like**
It would be better if "now" was an option

**Describe alternatives you've considered**

**Additional context**

**Comment by oddvernes** [comment]
Please clarify if this is about the datepicker in eds-lab-react or Textfield from eds-core-react with type set to datetime-local

**Comment by Eddasol** [comment]
> Please clarify if this is about the datepicker in eds-lab-react or Textfield from eds-core-react with type set to datetime-local

Its about TextField

**Comment by oddvernes** [comment]
The entire date and time picker interface here is provided by the browser, so unfortunately it is not something we can modify 🤷‍♂️. This interface also differs between browsers, what operating system is used and device. For this reason there is a lot of third party datepicker solutions, but they are hard to get right 😬.

I recommentd reading [this article](https://adrianroselli.com/2019/07/maybe-you-dont-need-a-date-picker.html) about why datepickers are a mess 👍
