### ISSUE TITLE
Scrollable dialog has weird spacing

### ISSUE THREAD

**Issue by sebastianvitterso** [equinor/design-system#2747]
**Describe the bug**

The `<Dialog.CustomContent scrollable>` component looks very strange. There are gaps (from the flex) between the scroll bar and the lines above and below the content area.

![image](https://user-images.githubusercontent.com/37065184/215089785-9ec46e79-0f96-4d54-8f6c-cc669e155519.png)

**Steps to reproduce the bug**

Look at the scrollable dialog on EDS.

**Expected behavior**

It should look like this:
![image](https://user-images.githubusercontent.com/37065184/215096167-9d11fcd1-a267-4829-80b5-8abfd48c7af7.png)

I achieved this by adding the following styles to the CustomContent element in DevTools.
```css
margin-top: -16px;
margin-bottom: -24px;
padding-top: 16px;
padding-bottom: 16px;
```

**Specifications**

- Version: I assume 0.28.0 (whatever is currently live on the Storybook site)
- Browser: Chrome 109.0.5414.87
- OS: MacOS Ventura 13.1 (22C65)

**Comment by oddvernes** [comment]
Good, catch! I see it is because grid gap is used. We'll fix it 👍
