### ISSUE TITLE
Request for a new side sheet position icon 

### ISSUE THREAD

**Issue by LiveAaE** [equinor/design-system#2748]
**Is your feature request related to a problem? Please describe.**

I need to indicate that the side sheet will be on the right side

**Describe the solution you'd like**
Add a new sheet position icon

![image](https://user-images.githubusercontent.com/46713525/215473218-836f7faa-331f-4d74-bee7-769113b8a489.png)

**Comment by benteljones** [comment]
![Skjermbilde 2023-02-03 kl. 14.34.49.png](https://images.zenhubusercontent.com/617137275a2f3b5f9e07865a/4ffd9c48-c875-4b63-85af-a393172996ea)

Ready for a review, @BirteThornquist  UI views, last column. 😊

**Comment by BirteThornquist** [comment]
LGTM!
