### ISSUE TITLE
The Paper component adds elevation as a dom attribute

### ISSUE THREAD

**Issue by bjartebore** [equinor/design-system#2763]
**Describe the bug**

Setting elevation on a Paper components adds an irregular `elevation="..."` attribute to the rendered html component. This is not valid html and clutters the dom. 

**Steps to reproduce the bug**

1. Add a Paper component or other component as a Card
2. Add the elevation argument to the component
3. Inspect the dom

**Expected behavior**

The element should only show classnames used render the element

**Specifications**

- Version: ^0.28.0
- Browser: Chrome (109.0.5414.119)
- OS: MacOS

**Additional context**

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1978938/216274027-b29cb035-2442-46de-924e-c03ecb5e6f18.png">

**Comment by bjartebore** [comment]
Documentation for transient props can be found here:
https://styled-components.com/docs/api#transient-props

**Comment by oddvernes** [comment]
Good catch! I have already gotten rid of some attributes by using transient props here and there. We'll add it here too (there's probably more that should be transient too, its something wee need to look at)

**Comment by oddvernes** [comment]
resolved bu #2764
