### ISSUE TITLE
Make Autocomplete dropdown render in portal

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2773]
Reported by Vegard Haugland on [slack](https://equinor.slack.com/archives/CJT20H1B9/p1675782785371459).

copied from slack:

We encountered a fun bug in <Autocomplete/> when we upgraded from v0.28.0 to v0.29.1.
Long story short:

- Some (but not all) of our <Autocomplete/> instances didn't render the dropdown values when the onClick event was fired.
- We solved the issue by setting disablePortal to true for the troublesome instances.

Can anyone elaborate on how this solved the issue? Full disclosure: I don't know anything about the downshift library other than it is something that is being used by <Autocomplete/>.

![filters_doesnt_work.gif](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/e98f912b-0479-4488-b97b-facf6dda7e5f)

Here the bug is solved (by setting the` disablePortal` attribute to true on the two right-most instances of Autocomplete)
![filters_fixed.gif](https://images.zenhubusercontent.com/6143345153d23c1b5b6353fc/04649e7f-82a9-4b17-a1e2-c697e3c901be)

**Comment by oddvernes** [comment]
We were unable to replicate this bug and could not come up with a fix at the time. This ticket should be kept in the backlog for a period in case anyone else encounters this problem or the original reporter is able to replicate the bug in codeSandbox, and if not, we close it.

**Comment by skrulling** [comment]
We just had this same issue, and disabling portal seemed to fix it. It seems to us that different Autocomplete components mess with each others state. Since they all start out working just fine, but after selected something in one of our dropdowns, the other dropdowns stop displaying options when click. The options are actually present, just not displayed on click.

**Comment by oddvernes** [comment]
Since we replaced portal with [popover] attribute I assume this is no longer relevant/an issue
