### ISSUE TITLE
Fix publish to npm

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2796]
npm ERR! code ENEEDAUTH 
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/ 
npm ERR! need auth You need to authorize this machine using npm adduser

I have switched npm auth token to my own but that was not the problem as the old one was still valid. 
The github action just stopped working mysteriously 🤷 

Only tested publish icons but I assume it will be the same for the other packages.
Specifically I am trying to release branch `OOVE/2794-release-eds-icons-0.19.0 `

**Comment by nilsml** [comment]
Tried changing the way we set the token in the GH action. Let's see how it works.

**Comment by nilsml** [comment]
Resolved by setting NPM_TOKEN in ENV instead of `pnpm config set`. Probably this method has been deprecated.

**Comment by oddvernes** [comment]
One remaining issue to iron out are the warning we now get in unrelated scripts:
`WARN  Issue while reading "/home/runner/work/design-system/design-system/.npmrc". Failed to replace env in config: ${NPM_TOKEN}`
(scripts that runs while performing the` checks` whenever you push to a branch)


![Image](https://user-images.githubusercontent.com/4499531/222725529-a6b9e290-ab86-40d3-98e7-7425091d750f.png)

**Comment by oddvernes** [comment]
By the way it looks like the method we used to use was the "proper" way and the .npmrc way we replaced it with is the inproper way that results in these warnings everywhere https://stackoverflow.com/questions/52015748/npm-failed-to-replace-env-in-config-npm-token

I even get them when running pnpm commands in the console to updatye packages

**Comment by oddvernes** [comment]
As i was able to publish eds-core-react using the old syntax, I have changed all the actions back to that. So we'll see next icon-release if it magically started working again or if there is something special about the icons package. Closing for now
