### ISSUE TITLE
Create "scope" variant for Search component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#280]
**Description**

Search allows users to locate or refine content based on simple words or phrases.

**Documentation**

- [The storefront](https://eds.equinor.com/components/search/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=2805%3A15917) 
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#)

**General guidelines**

See [COMPONENT_GUIDELINES.md](https://github.com/equinor/design-system/blob/develop/COMPONENT_GUIDELINES.md) for general guidelines like browser support and common implementation details

**Sub tasks**

- [ ] Write tests
- [ ] Create variant

_Variant of `Search`, see #171 _

**Comment by mimarz** [comment]
@equinor/design-system What is this? 

Is this thought to be a autocomplete / multiselect component. Description is kinda vague...

**Comment by wenche** [comment]
> @equinor/design-system What is this?
> 
> Is this thought to be a autocomplete / multiselect component. Description is kinda vague...

Hmm, by the vague description I would guess so?

**Comment by mimarz** [comment]
Closing this as "scoped" variant has been removed
