### ISSUE TITLE
🚸 Improve padding and text truncate in Autocomplete

### ISSUE THREAD

**Issue by mholta** [equinor/design-system#2804]
**Is your feature request related to a problem? Please describe.**

This is an improvement of the Autocomplete input. When using the `hideClearButton` prop, the padding is still the same. As well, adding dots for truncated text will help the user understand that the content is overflowing.

Reproduction and suggested change: https://codesandbox.io/s/2023-03-07-eds-autocomplete-improvement-ig9eel

Reproduction and suggested change: https://codesandbox.io/s/2023-03-07-eds-autocomplete-improvement-ig9eel

The solution now is creating a wrapper around the component.

**Comment by oddvernes** [comment]
Thank you for the report! This should be fixable indeed. I think we can do the overflow with ellipsis on the general input component used by autocomplete (as well as textfield and search) and  fix the padding in autocomplete which is currently hardcoded `rightAdornmentsWidth={24 * 2 + 8 + 8}` 👍
