### ISSUE TITLE
Truncate Breadcrumbs text based on available width

### ISSUE THREAD

**Issue by TormodNy** [equinor/design-system#2808]
**Is your feature request related to a problem? Please describe.**

I am trying use the `Breadcrumb` component, but I don't want it to wrap to multiple lines when the width decreases. In my case, the breadcrumb trail won't have that many elements, but some of the individual names may be quite long meaning it will still be quite wide even if every breadcrumb is on their own line. When there is enough space I would like to show the full breadcrumbs, but if the window width decreases I don't want it to wrap, and instead truncate the text.

**Describe the solution you'd like**

It would be nice if there was a prop where I could choose to whether or not to wrap the breadcrumbs. When choosing not to wrap, each breadcrumb could scale independently with the available width and truncate the text with ellipsis.
I tried making an example here: https://codesandbox.io/s/2023-03-09-eds-breadcrumbs-improvement-owfyv5?file=/src/App.tsx

A bonus would be if I could set a minimum width on specific breadcrumbs or decide if they should truncate or not.

**Describe alternatives you've considered**

The current solution is to "hack" it by changing the styling of the internal elements in the `Breadcrumbs` and `Breadcrumbs.Breadcrumb` components similar to what I did in the codesandbox. However, this can easily break if the component's elements change at some point.

**Comment by oddvernes** [comment]
Thanks for the suggestion! This seems like a quick and easy improvement. We will go over with design to make sure it's all good and then see if we can't get this out soon 👍

**Comment by oddvernes** [comment]
Resolved by commit fdb178be39fd51ec474e85bd008f6a5f9a0f8ef3 to develop
