### ISSUE TITLE
Issue with two styling in EDS Button

### ISSUE THREAD

**Issue by ShikhaMishra9** [equinor/design-system#2816]
We are using button as link and for styling trying to pass two case:

1.) Highlight color
2.) Background color 

as shown in code below:

style={{ "--eds_interactive_secondary__highlight": "var(--baby-blue)", background: "var(--white)" }}

Here it is only picking background but now highlight.
If I just pass highlight then it works fine but not when there are two cases.

**Comment by oddvernes** [comment]
Wasn't it specifically the pagination component and applying a different hover color on the active page button? A screenshot would be helpful here I think 🙂

**Comment by ShikhaMishra9** [comment]
<StyledListItem>
        <Button
          color="secondary"
          disabled={isDisabled}
          isCurrent={isCurrent}
          inverted={inverted}
          variant="ghost_icon"
          aria-label={ariaLabel}
          /* @ts-ignore */
          style={{ "--eds_interactive_secondary__highlight": "var(--baby-blue)", background: "var(--white)" }}
        >
          {children}
        </Button>
      </StyledListItem>

**Comment by ShikhaMishra9** [comment]
<StyledListItem>
        <Button
          color="secondary"
          disabled={isDisabled}
          isCurrent={isCurrent}
          inverted={inverted}
          variant="ghost_icon"
          aria-label={ariaLabel}
          /* @ts-ignore */
          style={{ "--eds_interactive_secondary__highlight": "var(--baby-blue)", background: "var(--white)" }}
        >
          {children}
        </Button>
      </StyledListItem>

**Comment by oddvernes** [comment]
So with variant ghost_icon the background is hardcoded `transparent`. If you use `variant="contained_icon"` instead, you can set background, background hover and icon color with:
```
      style={
        {
          '--eds_interactive_primary__resting': 'red',
          '--eds_interactive_primary__hover': 'blue',
          '--eds_text__static_icons__primary_white': 'black',
        } as React.CSSProperties
      }
```

**Comment by ShikhaMishra9** [comment]
It still does not work properly . '--eds_interactive_primary__resting': 'red is not getting picked same as when i set background.

**Comment by ShikhaMishra9** [comment]
Works fine now . Updated and tested

**Comment by oddvernes** [comment]
Closing this issue as resloved
