### ISSUE TITLE
Decide which zeroheight plan to move to by April 15

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#2819]
Our zeroheight plan will not renew as of April 15 and we will be bumped down to the free plan. 

Need to decide which plan to go for - the starter plan is most like ours and sounds like the best choice but will run if by the core team. 

[Notes are here](https://statoilsrm.sharepoint.com/sites/Designsystem/_layouts/OneNote.aspx?id=%2Fsites%2FDesignsystem%2FShared%20Documents%2FGeneral%2FEDS&wd=target%28Zeroheight.one%7CCD16A171-E085-45B9-B22B-3C82E2DBA9BE%2FNew%20plans%7C9EA24DC9-E29D-44D0-AC4A-25A6B8DB526D%2F%29
onenote:https://statoilsrm.sharepoint.com/sites/Designsystem/Shared%20Documents/General/EDS/Zeroheight.one#New%20plans&section-id={CD16A171-E085-45B9-B22B-3C82E2DBA9BE}&page-id={9EA24DC9-E29D-44D0-AC4A-25A6B8DB526D}&end):

**Comment by BeckyBrekke** [comment]
Have decided to move to the starter plan with two editors in the beginning.
