### ISSUE TITLE
cmpEDSToggleCheckboxWithLabelCS checkbox goes invisible in "Play" mode until clicked

### ISSUE THREAD

**Issue by aaalea** [equinor/design-system#2821]
**Describe the bug**

Checkbox goes invisible when playing the app until clicked, it goes visible after that.

**Steps to reproduce the bug**

1. Insert a cmpEDSToggleCheckboxWithLabelCS component
2. Play the app (not from edit, but as normal)
3. Checkbox should be invisible, click to make visible

**Expected behavior**

Checkbox should be visible from start
![App Catalog](https://user-images.githubusercontent.com/128134081/225856983-a8d5b039-ceef-4dea-b425-23cf95512d09.gif)

**Comment by BirteThornquist** [comment]
@Hjaf Can you please take a look into this?

**Comment by Hjaf** [comment]
Are you still experiencing this issue @aaalea ?

I have recently observed the issue power apps studio, but I have not seen this in the player lately. I am closing this issue because we can't fix it directly.
