### ISSUE TITLE
Adjust the color palette with fewer and more equal numbers on the rows. Some few exceptions.

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#2823]

**Comment by benteljones** [comment]
![Image](https://user-images.githubusercontent.com/92795462/226362079-852239af-0c1e-4ff0-9ce4-b51a1886016b.png)

**Comment by benteljones** [comment]
![Image](https://user-images.githubusercontent.com/92795462/226689315-313ad5a8-b21b-40e6-86c2-3e1dcec590d8.png)
![Image](https://user-images.githubusercontent.com/92795462/226689316-0a55711a-2fa7-4c5d-8fcd-95ebd7543385.png)

**Comment by nilsml** [comment]
Done
