### ISSUE TITLE
Update zeroheight with new storybook url

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2825]
https://storybook.eds.equinor.com/ is now live. Zeroheight should be updated with this root url before the old one is taken down

**Comment by oddvernes** [comment]
The pinned url in the slack channel should also be updated

**Comment by BeckyBrekke** [comment]
I updated the Slack links, and all the main links to the Storybook. I need to update our zeroheight plan to do the Storybook integration, so I will do that in the next 2 weeks.

**Comment by BeckyBrekke** [comment]
Agreed to wait until upgrade to Storybook 7. Has been tested with 7 in Dev and prod being upgraded today. Will updating zeroheight.

**Comment by vnys** [comment]
use the dev url temporarily

**Comment by schoening** [comment]
Completed. Closing.
