### ISSUE TITLE
autocomplete: invalid state

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2836]
Autocomplete should have a visual invalid state in line with other form elements (in the case of `required` for example)

Currently this does not exist in figma either

**Comment by matskse** [comment]
This is something we need as well. Letting the user know that the input is in an error state is important for our forms. In addition to an error state an error message would be really useful to guide the user in the right direction to fix their input.

**Comment by BirteThornquist** [comment]
We will use the same invalid state as for text field. Shall we include custom error warning icon to the right inside the input field? If so, can it be placed to the right of the dropdown icon? See examples in the screenshot below. @oddvernes @denektenina 


![Image](https://github.com/equinor/design-system/assets/74531659/c19c5511-5cc8-46ad-b7cd-4eed022cbb2c)
