### ISSUE TITLE
Find the best way to handle theming in EDS 2.0

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2844]
What are the alternatives when it comes to theming, and how is it best for the designers in the product teams to switch themes?

**Comment by vnys** [comment]
Currently writing about this topic [in a gist](https://gist.github.com/vnys/c01e29bc79ffbda4804fbee220c96433).

**Comment by nilsml** [comment]
Please update this issue @vnys ! Did we conclude on how to do it?

**Comment by nilsml** [comment]
Please close this if it is done @vnys

**Comment by schoening** [comment]
Token Studio.
