### ISSUE TITLE
New icon - Active stream

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#2855]
**Is your feature request related to a problem? Please describe.**

The [WitsmlExplorer application](https://github.com/equinor/witsml-explorer/issues) has need to add a new icon into the EDS icon library. 
Hope that you can draw and add the proposed icon into the library as soon as possible

**Describe the solution you'd like**
Active stream icon
![image](https://user-images.githubusercontent.com/22211376/233969114-bfa53a90-67fa-401e-bf3d-b1208a0394e7.png)

![image](https://user-images.githubusercontent.com/22211376/234220319-79380c06-c0a7-4ce1-9149-b4afc97c80a5.png)

Example of the Active stream icon in use
![image](https://user-images.githubusercontent.com/22211376/233968745-abf18c46-73b3-4410-8f20-81bab95dbf9a.png)

**Comment by chrleon** [comment]
Can you use the 'beat' icon?
![image](https://user-images.githubusercontent.com/347919/234018538-b44389ad-5745-43e9-8704-ed1e839d35d4.png)

**Comment by marmid74** [comment]
Ah... That can actually work for us 👍. We have agreed to use the beat. I close this issue.
