### ISSUE TITLE
Create 3 Slack vignettes: Tips & tricks, Updates, Feedback wanted

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#2868]

**Comment by benteljones** [comment]
This issue is a part of #2532

**Comment by benteljones** [comment]
![Image](https://github.com/equinor/design-system/assets/92795462/89fa11b6-165d-4b9d-a0d7-da50638e5d87)

**Comment by benteljones** [comment]
You can find them here: https://www.figma.com/file/OSfh8uHiSD2u0M85EFCi97/EDS-branding?type=design&node-id=0-1

**Comment by benteljones** [comment]
I made a simple instruction manual next to the vignettes, same file. 😉


![Image](https://github.com/equinor/design-system/assets/92795462/af2d5721-4b42-4409-9d40-e637db828a23)

**Comment by vnys** [comment]
LGTM 👍
