### ISSUE TITLE
SideBarAccordion: isExpanded should work even if toggleExpand isn't present

### ISSUE THREAD

**Issue by denektenina** [equinor/design-system#2869]

**Comment by denektenina** [comment]
Resolved by #2870

**Comment by rokasbliudzius** [comment]
I came across this problem today. isExpected property for SideBar.Accordion didn't work. It only worked after I added toggleExpand.

**Comment by oddvernes** [comment]
We are trying for a new release hopefully next week @rokasbliudzius
