### ISSUE TITLE
Create colours to the Paper component, Dark, elevation

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#2875]

**Comment by benteljones** [comment]
I have made a colour suggestion. 

![Image](https://github.com/equinor/design-system/assets/92795462/ac850e42-f896-484d-96cc-dfcd7bafb434)

**Comment by benteljones** [comment]
The colour ranges are roughly tested with our other components, contrast requirements.

**Comment by vnys** [comment]
The darkest colours go darker than the background, which breaks the elevation illusion

**Comment by benteljones** [comment]
That is absolutely right. I will explain when we do a review together. 😊

**Comment by benteljones** [comment]
We have had a review yesterday. The next step is to decide which components should be on the various elevation levels. Make it     1:1 – paper component light and dark. When all the components have had their colour suggestions, we do a final review with the fine-tuning, if necessary.
