### ISSUE TITLE
Fix bug where Popover.Content last/first-child selectors applies to all last/first children of children nodes

### ISSUE THREAD

**Issue by abawolek** [equinor/design-system#2879]
**Describe the bug**

top/bottom-padding is applied to each first/last child at every node level in Popover.Content.

I ran into this when I was playing with table inside Popover, imagine additional padding on top/bottom of every first/last cell in every row;)

There was an [#2517 - issue ](https://github.com/equinor/design-system/tree/bug/ML-2517-popover-css-selector) and this pull request [#2524](https://github.com/equinor/design-system/pull/2524) selecting direct children instead of all children but it was described as intended behaviour, maybe we can have another look into that?

**Steps to reproduce the bug**

1. Add Popover to button, etc.
2. Define popover:
```
  <Popover
    open={isOpen}
    anchorEl={referenceElement.current}
    placement={'right-start'}
    withinPortal>
    <Popover.Content>
      <div>
        <div>First-First</div>
        <div>First-Last</div>
      </div>
      <div>
        <div>Mid-First</div>
        <div>Mid-Last</div>
      </div>
      <div>Last-First</div>
      <div>
        <div>Last-Mid-First</div>
        <div>Last-Mid-Mid</div>
        <div>Last-Mid-Last</div>
      </div>
      <div>Last-Last</div>
    </Popover.Content>
  </Popover>
```
  3. Render and review added paddings.
  4. Can also add a simple table for fun (copied from storybook examples):
  ```
  <Table>
    <Table.Head>
      <Table.Row>
        <Table.Cell>Item no.</Table.Cell>
        <Table.Cell>Name</Table.Cell>
        <Table.Cell>Price</Table.Cell>
      </Table.Row>
    </Table.Head>
    <Table.Body>
      <Table.Row>
        <Table.Cell>123-456</Table.Cell>
        <Table.Cell>Kiwi</Table.Cell>
        <Table.Cell>1.5</Table.Cell>
      </Table.Row>
      <Table.Row>
        <Table.Cell>789-012</Table.Cell>
        <Table.Cell>Apple</Table.Cell>
        <Table.Cell>0.5</Table.Cell>
      </Table.Row>
      <Table.Row>
        <Table.Cell>345-678</Table.Cell>
        <Table.Cell>Mango</Table.Cell>
        <Table.Cell>2.5</Table.Cell>
      </Table.Row>
    </Table.Body>
  </Table>
```

**Expected behavior**

Additional top/bottom padding shouldn't be applied to all children of Popover.Content, probably only to direct children of Popover.

**Specifications**

- Version: 0.31.1
- Browser: Chrome ver. 113.0.5672.93 (Official Build) (64-bit)
- OS: Microsoft Windows 11 Pro for Workstations, version: 10.0.22621, build: 22621

**Additional context**

Add any other context or screenshots about the bug. An example in [CodeSandbox](https://codesandbox.io/) is very helpful

**Comment by oddvernes** [comment]
Thanks for the report, we'll have a look at this!

**Comment by oddvernes** [comment]
@abawolek I am unable to reproduce this. I have tested in storybook and downstream in a create-react-app


![Image](https://github.com/equinor/design-system/assets/4499531/b2af718b-d694-4346-b0f9-1e3741db3683)


![Image](https://github.com/equinor/design-system/assets/4499531/81f11116-f92e-4207-a901-edbc76b06e82)

I do not get any additional padding in children, only top and bottom of `popover.content`. I have tested in chrome and firefox. What browser do you use? which version of core-react do you use? I am not sure if there is anything I am missing here 😅

**Comment by abawolek** [comment]
Hi!

Hah, that's nice;) I have created a test page one more time:

```
import React from 'react';

import { Button, Popover } from '@equinor/eds-core-react';

export default function Trial() {
  const [isOpen, setIsOpen] = React.useState(false);
  const referenceElement = React.useRef(null);

  const popover = (
    <Popover open={isOpen} anchorEl={referenceElement.current} placement={'right-start'}>
      <Popover.Content>
        <div>
          <div>First-First</div>
          <div>First-Last</div>
        </div>
        <div>
          <div>Mid-First</div>
          <div>Mid-Last</div>
        </div>
        <div>Last-First</div>
        <div>
          <div>Last-Mid-First</div>
          <div>Last-Mid-Mid</div>
          <div>Last-Mid-Last</div>
        </div>
        <div>Last-Last</div>
      </Popover.Content>
    </Popover>
  );
  return (
    <div
      style={{
        display: 'flex',
        width: '400px',
        height: '400px',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      {popover}
      <Button ref={referenceElement} onClick={() => setIsOpen(!isOpen)}>
        Popover
      </Button>
    </div>
  );
}
```

Got same results:/:

![image](https://github.com/equinor/design-system/assets/132441841/e2cb4ae8-ca7a-4376-8120-18e510df6e69)

You can see, that "bdlWwj" class is at Content level and the highlighted div is caught by "bdlWwj :first-child" selector.

Using:

- create-react-app
- package.json: "@equinor/eds-core-react": "^0.31.1"
- browser: Chrome ver. 113.0.5672.93 (Official Build) (64-bit)
- os: Microsoft Windows 11 Pro for Workstations, version: 10.0.22621, build: 22621

**Comment by abawolek** [comment]
Thanks for reply, yes - this sheds a bit of light on the issue. My generated css looks like:
![image](https://github.com/equinor/design-system/assets/132441841/8f137657-152d-4dcd-9853-94d50dab1cd8)

Maybe this indeed is a styled-components issue.. I am using version: 6.0.0-rc.1 (no emotion), what's yours?

**Comment by oddvernes** [comment]
That seems like a possible culprit. We are on 5.3.9. I see for some reason they have tagged 6.0.0-rc as `@latest` which is a terrible idea considering there is a bunch of breaking changes in this major upgrade and it is still a release candidate with bugs. Could you test using the latest 5.x.x and see if that "fixes" it? That would be a very helpful datapoint for us when we upgrade this package to 6.x.x 🙂

**Comment by abawolek** [comment]
Sorry for later replay, catching up the work..

I have downgraded styled-components to:
styled-components@5.3.11

and the result is:
![image](https://github.com/equinor/design-system/assets/132441841/63fe30d6-ffc0-473e-9273-9f9ad00bef37)

with css:
![image](https://github.com/equinor/design-system/assets/132441841/5e308f6a-1a21-4968-97a3-3fca49dfdacf)

..fixing the issue.

#btw it is no longer easy to check generated css in html with styled-components@5.3.11..

**Comment by oddvernes** [comment]
Good job! We have a ticket (#2884) to upgrade to styled-components v6 but we'll wait until it is released officially since clearly they are ironing out bugs still in these release candidates. We'll also add explicit `&` in the styled-components code some places as I suspect that will fix this particular issue

**Comment by abawolek** [comment]
Sure! Thanks for a kind approach and a good cooperation hah;)
