### ISSUE TITLE
Create colours on tooltip, light & dark

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#2881]

**Comment by benteljones** [comment]
![Image](https://github.com/equinor/design-system/assets/92795462/39d57256-19ef-43db-affc-55715bab1a66)

**Comment by benteljones** [comment]
https://www.figma.com/file/ewvs8oh3ZUVdyCvjIBnGOo/%F0%9F%A7%A9-EDS-2.0-button-preview-0.6-(final)-%2B-popover?type=design&node-id=0-1

**Comment by vnys** [comment]
Lets do a review together

**Comment by benteljones** [comment]
[like]  Bente Ljones reacted to your message:
________________________________
