### ISSUE TITLE
⬆️ Update styled-components to v6

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2884]
Another major update is around the corner as `styled-components` is currently making release candidates for v6.0.0. It may be the reason for this extremely strange bug reported in #2879. Something to be weary of when upgrading, in addition to other breaking changes.

We should wait until after they are out of rc and released 6.x.x officially before doing this

**Comment by vnys** [comment]
Waiting for the stable release of v6

**Comment by BirteThornquist** [comment]
Will be done in August.
