### ISSUE TITLE
🔧 Fix "purge cdn" step in publish storybook action

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2890]
Link to report (will probably get outdated and die at some point): https://github.com/equinor/design-system/actions/runs/5122261561

![Image](https://user-images.githubusercontent.com/4499531/242291414-eac69aa4-5da5-4aba-8884-1801a99ca6ee.png)

**Comment by nilsml** [comment]
Should be fixed now, but not tested yet.
