### ISSUE TITLE
Create UI Shell spacing tokens for default density

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2909]
Investigate which sizes we should add to our tokens for UI Shell spacing. @benteljones and I looked at an Amplify app that uses approximately 64 pixels, which is nice and spacious, but might not be a good fit for every use case, so we should have at least two.

**Comment by benteljones** [comment]
Some testing in the Research file:
https://www.figma.com/file/ILFJovpCG3BnZsOeL7wmvd/Research?type=design&node-id=506-497&mode=design
