### ISSUE TITLE
Use Autocomplete as a select (dropdown)

### ISSUE THREAD

**Issue by canxerian** [equinor/design-system#2921]
**Is your feature request related to a problem? Please describe.**

There are occasions when free typing isn't required on an Autocomplete but the dropdown functionality is still desired.

Add a `disableTextInput` attribute to the component:
```
<Autocomplete
    disableTextInput
    .... 
/>
```
A potential way to achieve this desired behaviour is to apply a `readonly` to the `<input>` element within the Autocomplete component.

![image](https://github.com/equinor/design-system/assets/1138440/1ecdf528-23e5-4d0d-993b-2b218602a54d)

![image](https://github.com/equinor/design-system/assets/1138440/7ae239a5-4764-44e7-b45b-8b33628fb183)

**Comment by canxerian** [comment]
Or perhaps `Autocomplete` can expose a `ref` to the `<input>` element in the same way `TextField` does: https://github.com/equinor/design-system/blob/bdba8c20eb379543e2fe7fdfcd2b3ddec7196b50/packages/eds-core-react/src/components/TextField/TextField.tsx#L47

**Comment by oddvernes** [comment]
Yes exposing the input ref sounds like a possible solution here, since there is already a `readonly` prop on Autocomplete which works differently (disables the dropdown as well)

**Comment by v3gard** [comment]
I also vote for exposing the `readOnly` attribute on the internal `<Input />` element. Either via `inputRef` or simply by just mapping the inner `readOnly` attribute to a different name `disableTextInput` since `readOnly` is already taken.

Until this is official, a workaround/hack is to add this. [Demo](https://codesandbox.io/s/patient-rgb-977nmw):

```ts
onKeyDown={(e) => {
    e.preventDefault();
    return false;
}}
style={{caretColor: "transparent"}}
```

**Comment by canxerian** [comment]
Awesome, thank you!
