### ISSUE TITLE
🚀Data-grid: publish new storybook

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#2928]
Set up azure and github actions to publish data-grid storybook. The url is not importan as we should use [Storybook composition](https://storybook.js.org/docs/react/sharing/storybook-composition) to make it a part of the regular storybook.

**Comment by nilsml** [comment]
URL to storybook: https://s478stedsstorybookdatag.z16.web.core.windows.net/

Linking together with main storybook is left to do.
