### ISSUE TITLE
Fix broken storybook links in documentation

### ISSUE THREAD

**Issue by Hjaf** [equinor/design-system#2941]
Links on eds.equinor.com point to **eds-storybook-react.azurewebsites.net** and not **storybook.eds.equinor.com**

Pages with broken links: 

- [Resources](https://eds.equinor.com/0b0c666ab/p/196746-resources)

- Also link the icons under NPM to NPM and not storybook

-  another broken link here: https://eds.equinor.com/0b0c666ab/p/12b5e3-figma/b/087f73, need to find where it should point, maybe here on Figma help pages: https://help.figma.com/hc/en-us/articles/360040450513-Create-layout-grids-with-grids-columns-and-rows

**Comment by BirteThornquist** [comment]
Birte to contact Rebecca

**Comment by BeckyBrekke** [comment]
Links are all fixed!
