### ISSUE TITLE
Put core colours into logical groups

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#2942]
We currently have the following core colour palettes in EDS 2.0 beta design tokens:

- Neutrals
- Slate Grey
- Slate Blue EDS
- Blue Grey
- Mist Blue Grey
- Mist Blue EDS
- Mist Blue Brand
- Blue Sky
- Blue Ocean
- Deep Purple
- Purple
- Fuschia
- Old Pink
- Magenta Red
- Pink X Brand
- Red Cold
- Red Warmer
- Spruce Wood
- Orange
- Ochre
- Yellow
- Success Green
- Lichen Green
- Moss Green 1
- Moss Green 2

To make it easier to understand the context in which to use a specific colour, and to reduce scrolling, I propose grouping them. For example: 

- EDS
  - Moss Green
  - Slate Blue
  - …
- Alarms
  - Orange
  - Yellow
  - …
- Infographics
  - Some colour
  - Other colour

**Comment by benteljones** [comment]
But before we do that, we need to go through the naming of the core colour palette. As I said, it is temporary to easily navigate between existing and new colors while we build it up.

**Comment by benteljones** [comment]
@vnys we need this rows at this stage:
- Neutrals
- Slate Grey
- Slate Blue EDS
- Blue Grey
- Mist Blue Grey
- Mist Blue EDS

- Blue Sky

- Pink X Brand
- Red Cold
- Red Warmer
- Spruce Wood
- Orange

- Success Green
- Lichen Green
- Moss Green 1
- Moss Green 2
