### ISSUE TITLE
Update Table component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#297]
**Description**
Update the `Table`, with missing states and latest changes from Figma

**Documentation**

- [The storefront](https://eds.equinor.com/components/table/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A25)
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#table)

**Sub tasks**

- [x] Write tests
- [x] Create set of tokens (from base tokens)

**Notes**
#148

**Comment by vnys** [comment]
- Add separate types for `th` and `td`, possibly by using function overload (specifically scope)
- Don’t use `th-tokens` for `thead`
- Rewrite sticky header example in story to use` position: fixed` on `th` (See [CSS Tricks article](https://css-tricks.com/position-sticky-and-table-headers/))

**Comment by mimarz** [comment]
> * Don’t use `th-tokens` for `thead`

We use `th-tokens` for `thead` because there is no tokens `thead`. Figma does not have this concept. We need to use the `background` and `border` from `th-tokens` for when the table is stretched to fit width and `th` not.

**Comment by mimarz** [comment]
blocked by #830
