### ISSUE TITLE
Increase hitbox of Slider "Thumb"

### ISSUE THREAD

**Issue by Strepto** [equinor/design-system#2973]
**Is your feature request related to a problem? Please describe.**

Hi! I think EDS sliders are frustratingly hard to use on mobile, and that this could be improved quite easily. Try grabbing the slider on https://storybook.eds.equinor.com/?path=/docs/inputs-slider--docs with your phone (tested on iPad). 

The reason its harder on touch than mouse is that there is no "on-hover"/focus on phones, so the draggable area on the "thumb" (which is increased on hover when using mouse) is tiny. I believe that tweaking the size of the non-hover "thumb" would work fine for both mouse and touch, and make the slider better. (it may be possible to do this without actually making the outline visible, but I did not o

**Describe the solution you'd like**

Either increase the visible or invisible hit-box of the slider thumb when not hovering, so touch has easier to grab the "thumb"

**Describe alternatives you've considered**

Being frustrated.

**Additional context**

**Comment by oddvernes** [comment]
Thanks for this report! I see this component is pretty much useless with touch input when it is a range slider. We will take a look and see if this can be fixed by creating different logic for touch input or hooking the existing logic into touch events 🙂 🤞
