### ISSUE TITLE
Custom separators for Breadcrumbs

### ISSUE THREAD

**Issue by marclistemann** [equinor/design-system#3001]
Especially when using Breadcrumbs for routing (e. g., in a header navbar), it is intuitive to display a ">" as a separator to indicate consecutive routes. 

Would be nice to have something along the lines of [Material-UIs solution](https://mui.com/material-ui/react-breadcrumbs/#custom-separator).

**Comment by oddvernes** [comment]
Thank you for the suggestion! I will bring this up with the designers if this is something we should allow 👍

**Comment by vnys** [comment]
@equinor/eds-ux Add this variant in Figma in the EDS 1.0 version of the breadcrumb component
