### ISSUE TITLE
`<Dialog open={true}>` no longer opens on mount

### ISSUE THREAD

**Issue by sebastianvitterso** [equinor/design-system#3002]
**Describe the bug**

The updated `Dialog` component has a breaking change which I would describe as a bug:
It is no longer possible for a component to do the following: 

```tsx
export function NotOkDialog() {
  return <Dialog open={true}>NOT OK!</Dialog>
}
```

For some reason, the component no longer opens on mount, if the `open` prop is set to a static (or initial) `true`. 

A workaround is the following:
```tsx
export function OkDialog() {
  const [open, setOpen] = useState(false)
  useEffect(() => {
    setOpen(true)
  }, [])
  return <Dialog open={open}>OK!</Dialog>
}
```

This change happened during the transition to the native `dialog`-element, so I assume it's related.

One might argue that the parent component could contain the dialog itself, but as I'd like my components to contain everything related to them (otherwise the parent might get really messy), I'd like for the component itself to contain the dialog. 

**Steps to reproduce the bug**

1. Make a React-component with a Dialog inside.
2. Give the dialog a static/initial `open={true}` value, so it _should_ be open on mount.
3. Notice that it doesn't open at all.

**Expected behavior**

I'd expect `open={true}` to make it open from component mount.

**Specifications**

- Version: `"@equinor/eds-core-react": "^0.32.3"`
- Browser: Electron 25.2.0
- OS: MacOS 13.4.1 (M1)

**Additional context**

https://codesandbox.io/s/quirky-bhabha-ryc24f?file=/src/App.js

**Comment by oddvernes** [comment]
Thanks for the report, this is not a use case I had considered! We'll take a look and I expect this to be an easy fix 🙂
