### ISSUE TITLE
Improve typing of Autocomplete

### ISSUE THREAD

**Issue by olavis** [equinor/design-system#3007]
@oddvernes How about this?
```typescript
type Options<T extends Array<unknown>> = T extends Array<string>
  ? Array<string>
  : { objects: T; label: (option: T[number]) => string }
  ```
 Defining options in Autocomplete: `options: Options<T[]>`

Example, using `string[]` and `MyOptionType` as object type:
```typescript
type StringType = Options<string[]> // string[]
type ObjectType = Options<
  {
    label: string
    symbol?: string | undefined
    trend?: string | undefined
  }[]
> /*
  {
    objects: {
        label: string;
        symbol?: string | undefined;
        trend?: string | undefined;
    }[];
    label: (option: {
        label: string;
        symbol?: string | undefined;
        trend?: string | undefined;
    }) => string;
  }
 */
```
Then you'd define options like this when you're using objects as options (it type errors if you don't include label and informs about the missing properties) `options={{ objects: options, label: optionLabel }}`, and yet no complaints from TypeScript if you define options as string array: `options={['Option1', 'Option2']}`.

_Originally posted by @olavis in https://github.com/equinor/design-system/issues/2976#issuecomment-1677448486_

**Comment by oddvernes** [comment]
resolved by #3408
