### ISSUE TITLE
Autcomplete crashes app when used inside a Dialog

### ISSUE THREAD

**Issue by jonasbjoralt** [equinor/design-system#3008]
**Describe the bug**
When using Autocomplete within an EDS Dialog, this gives the following error message: 
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Steps to reproduce the bug**

1. See code below. Run app 
2. Open the Dialog

**Sample Code**
https://github.com/equinor/tmp-eds-autocomplete-bug (standard create-react-app) 

Note that this codesandox with the exact same code works: 
https://codesandbox.io/s/thirsty-leakey-v6pmqd?file=/src/App.js 

**Expected behavior**
AutoComplete should work fine. It did work fine in v. 0.31.1 . Upgrading to 0.32.3 introduced the bug. 

**Specifications**

- Version: 0.32.3
- Browser: Firefox, Chrome
- OS: Win 10

**Additional context**

Add any other context or screenshots about the bug. An example in [CodeSandbox](https://codesandbox.io/) is very helpful

**Comment by oddvernes** [comment]
Seems related to #2889 which I just pushed a fix for for the next release. Do you get the error when clicking on an item?

**Comment by oddvernes** [comment]
Never mind I tested your create-react-app and it happened instantly when opening dialog. Fortunately it looks like my fix resolved this issue! We'll make a new release of eds-core-react probably today or tomorrow 👍

**Comment by jonasbjoralt** [comment]
Great, thanks for the quick resolution! 🙌 
Will try again to upgrade tomorrow then :)
