### ISSUE TITLE
Dialogs won't open from within Menu

### ISSUE THREAD

**Issue by jonasbjoralt** [equinor/design-system#3014]
Describe the bug
When using a Dialog inside a Menu, this causes two issues:
a) the Dialog does not open 
b) it somehow disables all other clicks in the page 

Steps to reproduce the bug

1. Pull code from repo and run (remember `npm i` since eds is updated)
2. Click the button
3. See that no dialog opens 

https://github.com/equinor/tmp-eds-autocomplete-bug (standard create-react-app), new commit

Expected behavior
This should work fine. It did work fine in v. 0.31.1 . Upgrading to 0.32.4 introduced the bug.

The reason we put Dialogs inside Menu is that we have components for each special menu item, which have forms for various setup. 
Example: 

```
function CustomMenuItem(): ReactElement {
  const [isDialogOpen, setDialogOpen] = useState<boolean>(false);
  return (
    <>
      <Menu.Item onClick={() => setDialogOpen(true)} >Setup stuff</Menu.Item>
      <Dialog open={isDialogOpen} onClose={() => setuDialogOpen(false)} isDismissable={true}>
        ... form to configure stuff
      </Dialog>
    </>
  );
}

<Menu>
   <CustomMenuItem />
</Menu>
```

Specifications

Version: 0.32.4
Browser: Firefox, Chrome
OS: Win 10
Additional context

Add any other context or screenshots about the bug. An example in [CodeSandbox](https://codesandbox.io/) is very helpful

**Comment by oddvernes** [comment]
Dialog is no longer supported inside Menu. As discussed on slack, this is resolved by moving Dialog outside of Menu
