### ISSUE TITLE
Breadcrumbs not center aligned

### ISSUE THREAD

**Issue by vegar** [equinor/design-system#3021]
**Describe the bug**

Adding icon to breadcrumb shows that items are not center aligned. 

![msedge_ahfpHJ9kpl](https://github.com/equinor/design-system/assets/764517/de3a9ecf-69f6-4ae8-b8da-3a78dd655680)

**Steps to reproduce the bug**

```
            <Breadcrumbs>
                <Breadcrumbs.Breadcrumb as={Icon} data={home}></Breadcrumbs.Breadcrumb>
                <Breadcrumbs.Breadcrumb href='#'>Item2</Breadcrumbs.Breadcrumb>
                <Breadcrumbs.Breadcrumb href='#' aria-current='page'>
                    Item3
                </Breadcrumbs.Breadcrumb>
            </Breadcrumbs>
```

**Expected behavior**

I would expect all items to be centered vertically.
I tried adding `align-items: center` to the `<Breadcrumbs>` styles, but that won't 'tickle down' to the `<ol>` element.
Even adding it to the `<ol>` item in the browser doesn't fix things right. The separator alignes with the icon, but the individual crumbs still is too high..

![msedge_2qllUVK6Wu](https://github.com/equinor/design-system/assets/764517/6dfaca1a-7530-4c1e-bc2b-11a51fcb3d14)

**Specifications**

- Version: 0.32.4
- Browser:  Microsoft Edge   Versjon 115.0.1901.200 (Offisiell build) (64-biters)
- OS: Windows 10

**Comment by oddvernes** [comment]
Thanks for the report! This should be an easy fix 🙂

**Comment by oddvernes** [comment]
I'm pushing a fix for the next release where vertical alignment is fixed when the breadcrumb child is an icon, but if you do the `Breadcrumb as={Icon}` then you should still add a `style={{marginBottom: '3px'}}` or so to get it properly aligned @vegar
