### ISSUE TITLE
Export Table index file. Add Cell, Body, Head, Caption, Row

### ISSUE THREAD

**Issue by thomasFjorstad** [equinor/design-system#3038]
Is it possible to add Body, Row, Cell, Caption and Head into the export of Table componet?

E.x: export {Table, Body, Row, Cell, Caption, Head}
Link: https://github.com/equinor/design-system/blob/develop/packages/eds-core-react/src/components/Table/index.tsx

**Comment by oddvernes** [comment]
We shall take a look!
