### ISSUE TITLE
🐛 Fix compatability with newest version of PNPM

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3052]
For some reason the latest version of pnpm fails when installing dependencies (`pnpm run init`) both locally and on gh actions. I have locked it to `8.6.5` in gh actions for now, as that is the version I have installed locally and is confirmned to be working

**Comment by oddvernes** [comment]
Since there are no breaking changes listed by pnpm release notes this is probably a bug in pnpm. It might even be fixed by now as I see a new release was made yesterday with some bug fixes that look relevant

**Comment by vnys** [comment]
Waiting for the next release of PNPM

**Comment by oddvernes** [comment]
Lately the newest version of pnpm appears to work fine on windows but breaks in github action (linux) and mac
