### ISSUE TITLE
Multiple Errors and Warnings in Browser Console.

### ISSUE THREAD

**Issue by Chibuzor-Nwemambu** [equinor/design-system#3058]
**Describe the bug**
Multiple errors and warnings in console regarding tha autocomplete.
I use the eds autocomplete with only the main/basic properties, but in my console, I get errors from properties I'm not even using. Please see images attached.
**Steps to reproduce the bug**
1. Create a dropdown using eds Autocomplete
2. Have `options`, `optionLabel`, `selectedOptions`, `onOptionChange`, `placeholder` and `clearSearchOnChange` as its properties
3. Run your code and view the console on your browser.
4.

**Expected behavior**

I didn't expect to get these warnings and errors in the console.
**Specifications**

- Version: 0.32.3
- Browser: Chrome
- OS:

**Additional context**
![Screenshot 2023-09-19 at 10 37 55](https://github.com/equinor/design-system/assets/75029767/87f7cb72-c860-4710-b43b-d75e12003529)
![Screenshot 2023-09-19 at 10 38 48](https://github.com/equinor/design-system/assets/75029767/8dfb5e8b-6355-47e7-bdf3-4b7ef19f7d09)
![Screenshot 2023-09-19 at 10 39 20](https://github.com/equinor/design-system/assets/75029767/6cd16d5e-740a-40da-ac38-dc5687cd63e7)
![Screenshot 2023-09-19 at 10 39 53](https://github.com/equinor/design-system/assets/75029767/454d9954-da1f-4bd4-932c-8ce10c03602e)
![Screenshot 2023-09-19 at 10 40 21](https://github.com/equinor/design-system/assets/75029767/5e1f395a-490b-41cb-b780-6f9795a67456)
![Screenshot 2023-09-19 at 10 40 45](https://github.com/equinor/design-system/assets/75029767/ac374ce8-98a3-4f5c-9089-832c6ddcdc44)
![Screenshot 2023-09-19 at 10 41 40](https://github.com/equinor/design-system/assets/75029767/1a9606b2-d7f7-473f-b008-d59d7722496b)
![Screenshot 2023-09-19 at 10 42 47](https://github.com/equinor/design-system/assets/75029767/07d3b6a0-0a92-43ee-90aa-85f68aef4e39)
![Screenshot 2023-09-19 at 10 43 14](https://github.com/equinor/design-system/assets/75029767/3fadc693-c2a6-4c41-b669-c7d73430dc69)
![Screenshot 2023-09-19 at 10 43 41](https://github.com/equinor/design-system/assets/75029767/d1846bf7-b507-42b4-a513-f25371a547c2)
![Screenshot 2023-09-19 at 10 44 13](https://github.com/equinor/design-system/assets/75029767/9d8c806a-5ac5-49b2-aa98-dee90a001dcd)
Add any other context or screenshots about the bug. An example in [CodeSandbox](https://codesandbox.io/) is very helpful

**Comment by oddvernes** [comment]
Solution: you are using styled-components v6. eds-core-react is not yet compatible with v6 and needs version 5. However, v6 compatability was just added to the code base and will be in the next release, which is probably at some point next week. So if it is possible for you to switch to v5 now and update to 6 later would be the best solution 🙂

**Comment by Chibuzor-Nwemambu** [comment]
@oddvernes thanks a lot for the speedy reply. I think I'll close this now.
