### ISSUE TITLE
Error when using Autocomplete with multiple enabled

### ISSUE THREAD

**Issue by vegsanden** [equinor/design-system#3059]
**Describe the bug**

We have seen an issue with Autocomplete when the multiple property is enabled. When selecting an option in the Autocomplete with the Enter-button and then immediately removing the alternative with the clear button by using the mouse, we get the error: "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

This happens when using basic properties of the Autocomplete. We also get the error "Error: Minified React error 185" when performing the same steps in the first example called "Multiple" in the EDS storybook. https://storybook.eds.equinor.com/?path=/story/inputs-autocomplete--multiple

**Steps to reproduce the bug**

1. Create an Autocomplete component and enable the multiple property such that you are able select multiple options from the list of alternatives. For example use the Autocomplete component in the EDS storybook example "Multiple"
2. Move to an option in the list with the up/down keys and hover your mouse over where you expect the clear button to be when you have selected an option.
3. Then select an option with the enter-key on the keyboard. After the option is selected, quickly remove the option selected by clicking the clear button "x". Then an error shows with "Maximum update depth exceeded"/ "Error: Minified React error 185".

**Expected behavior**

We expected the Autocomplete-component to remove the selections without giving an error. The component does not give the same error when multiple is disabled.

**Specifications**

- Browser: Edge
- OS: Windows 10
- Version eds-core-react: 0.31.1

**Additional context**

Error when running fusion application locally:
![image](https://github.com/equinor/design-system/assets/135705058/c5e08346-e860-4bda-9d8c-13f364e522ca)

Error when producing the bug in EDS storybook example:
![image](https://github.com/equinor/design-system/assets/135705058/f061b08b-aa40-46d4-a4d9-eea67459ec49)

**Comment by oddvernes** [comment]
We are aware of this "`Maximum update depth`" issue and was able to mitigate it somewhat in the previous release (it would always trigger in item click when using touch but we found a workaround for that). I see you found a new way to trigger it 😅.  It's an underlying problem with downshift ultimately (see https://github.com/downshift-js/downshift/issues/1511 and https://github.com/downshift-js/downshift/issues/1540) and hopefully they will patch this bug soon. In the meantime this [comment looks](https://github.com/downshift-js/downshift/issues/1540#issuecomment-1723501747) promising, we'll look into this workaround next
