### ISSUE TITLE
🔖Publish eds-core-react@0.33.0, eds-utils@0.8.2, eds-lab-react@0.7.2, eds-data-grid-react@0.1.0-beta.3

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3071]
adding support for styled-components v6 in all packages

**Comment by odinr** [comment]
i see [eds-core-react@0.33.0](https://www.npmjs.com/package/@equinor/eds-core-react/v/0.33.0) was published, but no tag, release or changeset was created for this release, will there be a changelog?

**Comment by oddvernes** [comment]
@odinr  Apologies for the delay, In the middle of making the releases I discovered our github actions to publish `lab-react` and `data-grid-react` have randomly stopped working and I was unable to resolve the issue today 😅. In the end I've published these packages manually this time so I can get the tags/release notes etc out in a more timely manner

**Comment by odinr** [comment]
i know the feeling of GH actions 🙄
just wanted to know if release was withdrawn and "unsafe" to install 😵‍💫

🍻 for quick response
