### ISSUE TITLE
👷🐛 Fix github actions: `publish lab-react`, `publish data-grid-react`

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3073]
For some reason lab and data-grid are not found in the building packages step

> eds@ build:data-grid-react /home/runner/work/design-system/design-system
> pnpm --filter ./packages/eds-data-grid-react run build

No projects matched the filters in "/home/runner/work/design-system/design-system"

> eds@ build:lab /home/runner/work/design-system/design-system
> pnpm --filter @equinor/eds-lab-react run build

No projects matched the filters in "/home/runner/work/design-system/design-system"

I'm wondering if it has anything to do with the "dist cache" step, it says 
`cache not found for input keys: 799bc25bbeb95d221eb91c058036ad161d711c93-dist--data-grid`

these same packages are found and built in the "checks" action but that does not have the "dist cache" step in "process packages"

**Comment by oddvernes** [comment]
It looks like adding --force to `pnpm m i  --force`  in the install-dependencies step of _setup.yml fixed it. Not sure if this is ideal to do in the CI though 🤷‍♂

**Comment by oddvernes** [comment]
Publishing lab did not work last time again so reopening this issue

**Comment by oddvernes** [comment]
related to #3052

**Comment by BirteThornquist** [comment]
Check if we should change to NPM(node package manager).

**Comment by oddvernes** [comment]
I was able to publish lab-react last week using github actions 🤷 Lets see next release if it has just randomly started working again (gh actions or "ubuntu-latest" changed?)

**Comment by oddvernes** [comment]
Update: publishing data-grid works fine, publishing lab fails

**Comment by torleifhalseth** [comment]
Looked at this with @oddvernes after updating workspace file in #3339 . The GitHub action is now running build of all packages as expected.

**Comment by oddvernes** [comment]
Addendum: the real reason was our sparse checkout for each action which then got cached and reused in another action where other required packages was then not included. This was fixed by checking out all packages in all actions in 7f5ba6be65ccfc6fccf52c5255b44957f6a8be18
