### ISSUE TITLE
Deal with button fullWidth prop

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3077]
As it turns out the `fullWidth` prop on `Button` does nothing but push the potential icon to the side when a button is stretched beyond is intrinsic width (either by a set width or by its container like flex or grid) as shown in this image

![Image](https://github.com/equinor/design-system/assets/4499531/edd0625f-ea0a-4d8d-b3ac-9686667bb806)

In storybook the description of the prop is "FullWidth (stretched) button" so this is very confusing. Trying to investigate i found [this](https://github.com/equinor/design-system/issues/1364) old issue where it seems like the prop was added in the connected pull request where the intention was to fix icon positioning for both cases (stretched and regularly sized button). I have not figured out if this prop was ever intended to make the button full width. 
So what should we do about this? (change behaviour to make button width 100% or change the name of the prop and its description to better reflect waht it does?)

**Comment by BirteThornquist** [comment]
We will keep the name Fullwidth to avoid breaking change, but update the documentation with a clearer description. The story will also be updated with better examples.

**Comment by vnys** [comment]
Heads up! Ensure that the label is centered when adding an icon
