### ISSUE TITLE
Expand the chips mockup with icon on both sides (+ left)

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#3090]

**Comment by BirteThornquist** [comment]
@marinalinn is this one solved?

**Comment by marinalinn** [comment]
I added the chip time ago to the Chip page on the Figma file, but there are two Chip pages, so I also added it to the other one: [https://www.figma.com/file/BKj1iiFncgfLb7iRMjz0nt/%F0%9F%A7%AA-Workshop?type=design&node-id=1%3A2&mode=design&t=bnCLPstFoahiw9us-1](https://www.figma.com/file/BKj1iiFncgfLb7iRMjz0nt/%F0%9F%A7%AA-Workshop?type=design&node-id=1%3A2&mode=design&t=bnCLPstFoahiw9us-1)
