### ISSUE TITLE
Simplify Figma image update for storefront

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#310]
All images of components/design from Figma are exported using `figma-broker`. When updating + publishing the storefront we need to make sure Figma images are up to date. This approach works but can lead to inconsistencies as people "forget" 

**Today:** 
1. Start `figma-broker` locally
2. Call endpoint `http://localhost:9001/create-figma-images` with POST
3. Commit updated images
4. Make sure these are included in the new bundle to be deployed

**Future?**
* Release check list
* `figma-broker` runs on service in Azure
* Figma images are stored in a seperate storage, maybe azure storage?
* Figma images can be update independently from storefront code
* Updates to figma images can be triggered manually by any core team member via admin portal or a batch job?

**Comment by BeckyBrekke** [comment]
No longer relevant with zeroheight
