### ISSUE TITLE
Table row improperly forwards active prop to underlying component

### ISSUE THREAD

**Issue by mhwaage** [equinor/design-system#3103]
**Describe the bug**

When rendering a table with a row labeled as active, styled component issues the warning:
```
styled-components: it looks like an unknown prop "active" is being sent through to the DOM, which will likely trigger a React console error. (...)
```
If we correctly use a boolean value for active, react also emits:
```
Warning: Received `true` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="true" or active={value.toString()}.
```
(As indicated, this warning can be suppressed by (incorrectly) mapping `true` to `"true"` and `false` to `undefined`).

**Steps to reproduce the bug**

Create a table:
```react
<Table>
  <Table.Caption>
    <Typography variant="h2">Files and their status</Typography>
  </Table.Caption>
  <Table.Head>
    <Table.Row>
      <Table.Cell>Col 1</Table.Cell>
      <Table.Cell>Col 2</Table.Cell>
    </Table.Row>
  </Table.Head>
  <Table.Body>
    <Table.Row active={true}>
      <Table.Cell>Val 1</Table.Cell>
      <Table.Cell>Val 2</Table.Cell>
    </Table.Row>
  </Table.Body>
</Table>
```

**Expected behavior**
No errors/warnings in console

**Specifications**

- Version: 0.33.0
- Browser: edge
- OS: Windows10

**Additional context**

codesandbox example: https://codesandbox.io/s/quirky-thunder-l6ny38?file=/src/App.js

**Comment by oddvernes** [comment]
This is a styled-components v6 issue, and it looks like a false positive (active is not passed to the dom, it is correctly converted to a transient prop beforehand). I will take a look and see if i can get rid of the "error" 👍
