### ISSUE TITLE
Fix default styling of Sidesheet with respect to Scrim

### ISSUE THREAD

**Issue by v3gard** [equinor/design-system#3108]
**Describe the bug**

From [Slack](https://equinor.slack.com/archives/CJT20H1B9/p1697622129642029):

>How is it expected we should use <Scrim> in combination with <SideSheet> ? I made an naive attempt [here](https://codesandbox.io/s/icy-wind-wkmkzk?file=/src/App.tsx), but it doesn't work as I expect with regards to scrolling inside the sidesheet. The scrim appears above the content as I scroll down. :exploding_head:
There seems to be some documentation [here ](https://storybook.eds.equinor.com/iframe.html?id=surfaces-sidesheet--docs&viewMode=docs#scrollable)regarding this subject (scrolling inside sidesheet) that references a SidesheetWrapper (that I perhaps wrongfully assumed was a plain `<div></div>` as the component wasn't included in EDS) but I honestly don't spot where I made the mistake in my example. Any input is appreciated!

Demo:
![sidesheet](https://github.com/equinor/design-system/assets/343078/ed174ae0-362c-41c0-9a8a-161eda510288)

**Steps to reproduce the bug**

See https://codesandbox.io/s/icy-wind-wkmkzk?file=/src/App.tsx

**Expected behavior**

Add the following explicit style to the `<SideSheet/>` component:
```ts
<SideSheet
          open={isOpen}
          onClose={() => setIsOpen(false)}
          style={{ height: "unset", minHeight: "100vh" }}
        >
```

Demo:

![unset](https://github.com/equinor/design-system/assets/343078/2b99dd33-39b3-4c1c-ad05-5fac9b62b618)

**Specifications**

N/A

**Additional context**

N/A

**Comment by oddvernes** [comment]
If you remove the style from Scrim (in the codesanbox example) and add `style={{position: 'fixed', overflow: 'auto'}}` to SideSheet instead it will scroll the SideSheet without Scrim overlaying it. @v3gard

**Comment by v3gard** [comment]
@oddvernes Yes, that seems to work.

I've added an example here: https://codesandbox.io/s/angry-jackson-njv7kc?file=/src/App.tsx

Should this component also consider that the app might have a header (e.g. 100px) that should always be available (i.e. not covered by the Scrim) - or is that a requirement that each app should handle?

**Comment by oddvernes** [comment]
Well the Scrim renders on top of all content (it is a styled FloatingOverlay from floating-ui) and we don't have support for rendering Scrim only inside a specific area. If something is inside a scrim then by nature it is temporary and must be closed before moving on so I don't think this is a problem. 
![bilde](https://github.com/equinor/design-system/assets/4499531/e1b8ba6f-c3e7-4174-9383-8d894f325d86)
Sidesheet can also be rendered inline, alongside the main content if you don't want it to block other actions in main content
![bilde](https://github.com/equinor/design-system/assets/4499531/a5364245-0b2c-493e-b341-b1fb424b806f)

**Comment by v3gard** [comment]
> If something is inside a scrim then by nature it is temporary and must be closed before moving on so I don't think this is a problem.

Cool. I guess we can settle this then! 😄 

The use case I thought about (take app header into consideration) is also handled by [this](https://equinor.github.io/fusion-react-components/?path=/docs/data-sidesheet--page) component (which uses the EDS scrim under the hood).
