### ISSUE TITLE
🐛Slider: Safari only: mouseover moves slider

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3119]
This only affects safari on mac when the slider is near max value. The entire slider moves a few pixels to the right on every mouseover on the slider.

How to Reproduce: 
use safari on a mac and go to slider in storybook, move the thumb to 99 and then do a few mouseovers on the thumb. Observe the slider jumping right and  out of the screen

https://github.com/equinor/design-system/assets/4499531/76d92bc2-2f88-4a7c-b217-0af7d63e1968

**Comment by lindsve** [comment]
Was about to report the same issue since we've experienced the same in our app
