### ISSUE TITLE
Evaluate and publish icon contribution

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3127]
We have received an icon contribution by our friend @chrleon 🎉 

The icons are in the [Designers Sandbox](https://www.figma.com/file/hjpavZkeUoRfn1N7mhIniK/EDS-designer-sandbox?type=design&node-id=4457-16233&mode=dev) in Figma

_Here’s what we need to do:_
- [x] Evaluate the contributed icons to ensure they’re built using the same guidelines as the existing ones
- [x] Evaluate the contributed icons’ usefulness for a broader range of products
- [x] Integrate the contributed icons into the Figma icon library
- [x] Integrate the new icons into @equinor/eds-icons

**Comment by BirteThornquist** [comment]
@marinalinn Did you do something with his issue?

**Comment by marinalinn** [comment]
@BirteThornquist two months ago I shared my evaluation for this contribution internally on Slack and also had some feedback from you about it. Actually I collected our icon requirements into a check list, so is easier for contributors to cover everything that is needed and make the review from our side faster as well. But needed feedback about the other two points in the checklist as well. But I will contact Christian directly to check those. 

Thread on Slack: https://equinor.slack.com/archives/C0648UHFNQG/p1698774548199129
Here is the Figma file: https://www.figma.com/file/8Y1KmlMuymgeholdwrxibU/Icon-Contributions?type=design&node-id=0%3A1&mode=design&t=3SMHhmOY7AIF4gGu-1

**Comment by marinalinn** [comment]
I assigned this task to me to add the updates :)

**Comment by benteljones** [comment]
![Image](https://github.com/equinor/design-system/assets/92795462/5fa3a33f-32bb-4998-a2c8-2a24c62507af)

**Comment by marinalinn** [comment]
Will have a meeting with Bente tomorrow Friday, to check the icon review and the icon contribution document related to this other task: [](https://github.com/orgs/equinor/projects/338/views/1?filterQuery=is%3Aopen+-label%3A%22%F0%9F%93%85+postponed%22+-type%3A%22%F0%9F%8E%AF+Epic%22+assignee%3Amarinalinn&pane=issue&itemId=49684157)

**Comment by marinalinn** [comment]
Icon added to [our library](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?type=design&node-id=2%3A3&mode=design&t=fK2WnhSXVYLMdxzO-1)

**Comment by marinalinn** [comment]
How this "Integrate the new icons into @equinor/eds-icons" is different from "Integrate the new icons into @equinor/eds-icons"?

**Comment by oddvernes** [comment]
"Integrate the new icons into @equinor/eds-icons" is my job, I need to run a script to fetch the icons from figma, check the new icons actually work and looks correct, then publish  @equinor/eds-icons on npm

**Comment by marinalinn** [comment]
The icons "Monopile" and "Jacket" are the ones that should be added :) 

![Image](https://github.com/equinor/design-system/assets/11398860/a8008d82-34e3-475e-a667-25c4d19deb39)

**Comment by oddvernes** [comment]
It looks like the icon `substation_offshore` has been removed, and I am guessing probably accidentally?
![bilde](https://github.com/equinor/design-system/assets/4499531/3bb5315a-ebea-4fff-82d5-035b6d20686b)

````
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M3 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-1v2l-2-1v-1H8v1l-2 1v-2H5a2 2 0 0 1-2-2V6Zm16 0H5v6h14V6Zm-2.998 10a6.985 6.985 0 0 1-4 1.28c-1.39 0-2.78-.43-4-1.28-1.22.85-2.61 1.32-4 1.32h-2v2h2c1.38 0 2.74-.35 4-.99 1.26.64 2.63.97 4 .97s2.74-.32 4-.97c1.26.65 2.62.99 4 .99h2v-2h-2c-1.39 0-2.78-.47-4-1.32Zm-4.694-6.75-.828 2.17 2.649-2.38-.76-.29.828-2.17-2.65 2.38.76.29Z"/>
</svg>

**Comment by benteljones** [comment]
Yes, that must be accidentally, I think. Designers still have the icon available in Figma, in the Asset file @oddvernes

**Comment by oddvernes** [comment]
It was fixed in figma by @marinalinn 

New icons have been published to npm
