### ISSUE TITLE
The EDS input type number accepts strings as input on Firefox. 

### ISSUE THREAD

**Issue by MarTorb** [equinor/design-system#3154]
**Describe the bug**

The EDS input type number accepts strings as input on Firefox. 

**Steps to reproduce the bug**

1. Go to https://storybook.eds.equinor.com/?path=/docs/inputs-input--docs#types in Firefox.
2. In the `Number` input type some text. 
3. See that the input is populated with the typed text.

**Expected behavior**

It should not be possible to type text into the number input. 

**Specifications**

- Version: 120.0 (64-bit)
- Browser: Firefox
- OS: macOS Ventura 13.6.2

**Additional context**
Firefox:
![image](https://github.com/equinor/design-system/assets/35423338/4ddab7b3-ed30-4185-9ab8-5816662eb63a)

**Comment by oddvernes** [comment]
Hello!
unfortunately `type` is a native input attribute controlled by the browsers, so it's out of our hands. [Here](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) is the relevant ticket for firefox, opened 6 years ago. Regardless, eds does not handle inputvalidation inside the components, as it would be too difficult to cover all use cases, so it is up to the developers consuming the components to add validation apropriate to their use case. We have a couple of examples [here](https://storybook.eds.equinor.com/?path=/docs/inputs-textfield--docs#validation) at the bottom of `TextField` documentation
