### ISSUE TITLE
Support for labels in a collapsed sidebar component

### ISSUE THREAD

**Issue by o-jorgensen** [equinor/design-system#3175]
**Is your feature request related to a problem? Please describe.**

For some users, certain icons will always be less familiar than others. The expanded sidebar solves this issue with corresponding labels, but it is somewhat limiting that only "universally known" icons will make a clear navigation in a _collapsed_ sidebar.

**Describe the solution you'd like**

If we could show labels in a collapsed sidebar, this could work as a navigation menu and in most(?) cases eliminate the need to expand it horizontally. It would be a good alternative for crowded interfaces where screen estate is a factor.

Material design 3 has the navigation rail component, and they have [specific guidelines](https://m3.material.io/components/navigation-rail/guidelines#b59dc6d4-54fd-4e94-8243-838505acbaf4) for how to use the label. 

**Additional context**

![image](https://github.com/equinor/design-system/assets/73646636/48591f32-bd44-4c3b-8f92-581c0c89e27c)

**Comment by oddvernes** [comment]
Thanks for the request!
The current solution displays the label in a tooltip on hover/focus to deal with the size constraint, and we have previously concluded not to include text labels inline in the collapsed sidebar. 
But we could take it up for discussion once more considering the above design examples. It would probably require the collapsed sidebar to be wider, and probably introduce a `collapsedLabel` prop that would be a shortened title with a maximum number of characters.

**Comment by o-jorgensen** [comment]
Much appreciated, thanks for the feedback so far 👍

**Comment by BirteThornquist** [comment]
This will not be prioritised for now since we went for the tooltip solution and changing it will require a lot.

**Comment by espenmaa** [comment]
I also support the ability to have text labels on icons as it helps with the usability and accessibility. It is nice to see that Material Design guidelines has become more specific on this as well: 
![image](https://github.com/equinor/design-system/assets/82512310/78cefd77-80ac-446c-9c53-c6cba0a81bf8)
