### ISSUE TITLE
Clearable TextField and Input components

### ISSUE THREAD

**Issue by ana-cepuran** [equinor/design-system#3191]
**Is your feature request related to a problem? Please describe.**

It is bad UX to not be able to clear the content of a TextField / Input field with a "clear" button ("x" button at the end of the input field). The user now has to manually delete the content by using the keyboard). 

**Describe the solution you'd like**

Clear the content of the text field or input field by clicking a "clear" ("x") button inside the field when there is an existing value.

**Describe alternatives you've considered**

The only alternative solution I see is to manually implement a "clear" button whenever the TextField has value and call the onChange function when the button is clicked.

**Additional context**

Existing clearable input field example from Quasar (Vue.js):

<img width="316" alt="Screenshot 2023-12-19 at 15 36 53" src="https://github.com/equinor/design-system/assets/135026519/74db36e5-3989-49b1-9036-ebb3f88d8a17">

**Comment by BirteThornquist** [comment]
Thank you for the suggestion, but we will not prioritise to implement a clear button at this point.
