### ISSUE TITLE
Typography 'lines' prop is applied to all Typography elements in page

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/design-system#3192]
**Describe the bug**

Using the 'lines' prop on _any_ `Typography` element in the pages causes the styling to be applied to _all_ `Typography` elements on the page.

**Steps to reproduce the bug**

See repro: https://codesandbox.io/s/ecstatic-shannon-v5vr48?file=/src/App.js

**Expected behavior**

Expect the 'lines' property to only apply the styling to the given `Typography` react element.

**Specifications**

- EDS version: 0.35.0
- React version: 18.2.0
- style-components version: 6.1.2
- Browser: Chrome 120.0.6099.110 (Official Build) (64-bit)
- OS: Windows 11

**Comment by v3gard** [comment]
This bug is also confirmed on MacOS Ventura 13.5.2. Both in Safari and Chrome.

**Comment by oddvernes** [comment]
It is an  issue with styled components v6 and higher, it does not happen when using styled components v5 from what i can see. I have a fix ready soon 👍
