### ISSUE TITLE
Create typography tokens

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3198]
In order to enable the product designers to create interfaces with well-designed typography, we’re going to offer a typography component in Figma – which will also be implemented in code, and eventually replace the React `<Typography />` component.

In EDS 2.0 we use a hard grid, meaning that the spacing between text elements is based on the font baseline as opposed to a soft grid where the spacing is based on the (non-existing) bounding box of the text frame.

In Figma we are going to use vertical trim and top padding to make the baseline grid snap to the nearest layout grid, but since the top padding will vary based on the font-size, we’re going to hide the complexity and the calculations inside a component. This will ensure a consistent use of typography while saving the product designers the trouble of doing the calculations themselves.

The exception to the baseline grid snapping is cases where we only have one line of text, such as a button label. In this case it’s better that the text is vertically centred. The typography component therefore needs a toggle button to turn off snapping in these cases. 

The Atlassian design system uses [three categories](https://atlassian.design/foundations/typography-beta/#text-styles) for their typography tokens: Title, body and UI. We are considering using the same terminology to differentiate between tokens intended for use inside components, and tokens intended for use in body copy.

**Sub tasks:**

- [x] #3278
- [x] #3279
- [x] #3343
- [x] #3280
- [x] #3281
- [x] #3282
- [x] #3342
- [x] #3418
- [x] #3420
- [x] #3419
- [x] #3421
- [x] #3422
- [x] #3424
- [x] #3469
- [x] #3470
- [x] #3471
- [x] #3495
- [x] #3496
- [x] #3501
- [x] #3502
- [x] #3503
- [x] #3504
- [x] #3505

**Comment by vnys** [comment]
Update: We’re currently waiting for feedback from Figma about an estimated time of delivery for typography variables

**Comment by marinalinn** [comment]
As we don't have any answer from Figma yet, we will to figure out a Plan B to work on this @vnys

**Comment by vnys** [comment]
Update: Send another email to Fabian about the typography variables release date

**Comment by marinalinn** [comment]
We had an answer and they will not have the features we need as soon as we expected, so we will need to proceed with plan b, that is basically do things in a way and when they have the feature re-make it. Now we will work on the Typography component after Victor finish the syntax task that has highest priority.

**Comment by vnys** [comment]
We have received feedback from Figma, we can proceed with Plan B.

**Comment by marinalinn** [comment]
Released on 17 of June 🎉🎉🎉
