### ISSUE TITLE
Structure and processes: improve ways to search and find material

### ISSUE THREAD

**Issue by marinalinn** [equinor/design-system#3215]
Goals:

- Designer´s ways of working and processes
- A common design language
- Improve knowledge transfer (internal)

Identify which topics we should review to improve the structure and processes in a next step.

List: 
- [x] How we search information internally
- [x] How we find information internally
- [x] File´s structure (author, updates, file's history, etc)
- [x] Layer´s structure (do and don'ts)
- [x] Templates needed (for videos, files, covers, and maybe to check where we could have all of those together?)
- [x] Templates with an EDS stamp? 
- [x] Icons contributions
- [x] Component contributions
- [x] Collect UX Writing guidelines

**Comment by marinalinn** [comment]
See how to merge this task with a similar one that is around there 🤔

**Comment by marinalinn** [comment]
Now we have a better overview of the topics we need to cover, so it would be good to have a review with Bette to close the task this week (Sprint 5)

**Comment by vnys** [comment]
@marinalinn and @benteljones will have a meeting about this on February 2.

**Comment by marinalinn** [comment]
[https://www.figma.com/file/kc6cFfgzUm1gHn8BmXdHW2/Structure-and-processes?type=design&node-id=1%3A2&mode=design&t=8Tgy4zeqdlTcB02t-1](https://www.figma.com/file/kc6cFfgzUm1gHn8BmXdHW2/Structure-and-processes?type=design&node-id=1%3A2&mode=design&t=8Tgy4zeqdlTcB02t-1)
