### ISSUE TITLE
Fix border on 'Selection controls/Switch on and off'

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#322]
Fix whatever is wrong with the 'Resting' layer.
https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1471%3A2

**Comment by mimarz** [comment]
Is this still relevant @lucasveil ?

**Comment by lucasveil** [comment]
No the link isn't relevant and not making any sense. The selection control will be fixed when we implement the new focus frame.
