### ISSUE TITLE
Prevent accidental changes to main branches in Figma

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3228]
**Find out if it’s possible to restrict edit access to main branches in Figma so it’s easier to keep  track of changes in the files. Right now if we accidentally move something, and then move it back, it counts as a change when we publish the file.** 

> You and your team can create as many branches as you like. To create a branch, you need a paid seat on Figma design and view or edit access to the main file. (From Figma’s [Guide to branching](https://help.figma.com/hc/en-us/articles/360063144053-Guide-to-branching))

…and also

> Caution: The [Allow viewers to copy, share, or export from the file](https://help.figma.com/hc/en-us/articles/360040045574) setting must be enabled for viewers to create branches. If this is disabled, viewers will not see the option to create or edit branches.

So in order to protect the main branch, it looks like the best way is to only have view access for most of the team, and then edit access for two people responsible for publishing updates.

That means that in order to make a change to a file, the EDS designers will have to create a branch just like we do in code, and then have that reviewed by another designer in the team, and then merged (and published).

Please react to this message with a thumbs up or a thumbs down depending on what you think about implementing that, and add a comment if you want to discuss it further.

Reviewers: @equinor/eds-ux

**Comment by marinalinn** [comment]
That is great!! At least until we agreed on better ways to transfer decisions and knowledge internally on the team (which is what we are doing on this structure and processes task), this is a very safe and good way to maintain the main sources of truth protected.
