### ISSUE TITLE
Review videos in our channel

### ISSUE THREAD

**Issue by Hjaf** [equinor/design-system#3236]
Review the videos in our channel, delete outdated videos and content which is no longer relevant.
 
> ... 
> [EDS stream channel](https://teams.microsoft.com/l/channel/19%3A08081ac3d7134608b312d8480aa87efc%40thread.tacv2/tab%3A%3A8811928f-4ce0-4460-a391-cffb915ddc0b?context=%7B%22channelId%22%3A%2219%3A08081ac3d7134608b312d8480aa87efc%40thread.tacv2%22%7D&tenantId=3aa4a235-b6e2-48d5-9195-7fcf05b459b0)
> 
> 
> 
> They should be deleted, but maybe someone wants to go through them first and see if this is something you want to make a newer version of? People found them very helpful at the time and was a way to onboard to Figma and EDS.
>  ...
 _Originally posted by @BeckyBrekke in [#2216](https://github.com/equinor/design-system/issues/2216#issuecomment-1907678726)_
 
 [Direct link to channel (web)](https://web.microsoftstream.com/channel/158dde99-a052-4842-8627-fdcc90f64c7d)

**Comment by marinalinn** [comment]
[EDS demo - using and creating components in Figma](https://web.microsoftstream.com/video/bb71ee95-52e2-4e9a-9686-7d5a932428ce?channelId=158dde99-a052-4842-8627-fdcc90f64c7d) : The video is updated, basically they teach what to prioritize when it comes to use or create components so the information is still very useful, ofc it would be great to have the info updated with current members of the team but is not a priority for now so I recommend to upload it to Degreed.

[EDS developer demo - Icons](https://web.microsoftstream.com/video/aff5d2fd-5c46-45f0-bd78-06d7534d1f76?channelId=158dde99-a052-4842-8627-fdcc90f64c7d) : From the design perspective this is updated but I would like to know @oddvernes point of view. If the information is updated from the devs perspective, I would also add this to Degreed and mark it as mandatory videos to watch during the devs and designers onboarding. 

[EDS demo - Figma auto layout](https://web.microsoftstream.com/video/6f8ba352-3fba-4d0c-962e-a3483aea3c95?channelId=158dde99-a052-4842-8627-fdcc90f64c7d) : Also updated information to move to Degreed. Is not updated as the video shows Figma on 2020, which is very different to the features it has today, but is useful information about how to use auto layout (that hasn't change in Figma).

[EDS Demo 040919](https://web.microsoftstream.com/video/5cd3d523-cc80-46e2-9f0a-3edf7d1c0e38?channelId=158dde99-a052-4842-8627-fdcc90f64c7d) : The video shows a little about how a design system works but with more focus on how Figma works very from the basics, and kind of outdated as today our users are more familiar with the tool, so I would recommend to delete it.

**Comment by oddvernes** [comment]
The icons video is still useful i think even if some details are slightly changed:

- cdn icons outdated - not sure if we still host the icons on cdn after we switched to new subscription but if we do, we wouldn't reccommend using this
- structure on github outdated (no big deal)
- how to run script to export icons changed
- react icon component now support multi path svg

**Comment by marinalinn** [comment]
Thank you @oddvernes 🎉

**Comment by marinalinn** [comment]
Agreed on Monday 19th planning meeting to move those videos to Degreed 🤟

**Comment by vnys** [comment]
Update: @BeckyBrekke moved the last video, and deleted the Stream channel
