### ISSUE TITLE
Redesign 'Stepper' component in Figma

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#324]
- [x] Change icon size from 26px to 24px
- [x] Ensure that component fits in 8px grid
- [x] Use 'divider' component instead of "------"
- [x] Make Auto layout-compatible

**Comment by benkeq** [comment]
Tried to recreate with auto layout. Will have to do more research, or cooperate with someone to get the divider to adapt.

**Comment by lucasveil** [comment]
Variants has been implemented for this component
