### ISSUE TITLE
Auto complete - Hover title option

### ISSUE THREAD

**Issue by chrisw-n** [equinor/design-system#3250]
**Is your feature request related to a problem? Please describe.**

When having similar options in the AutoComplete option list it is difficult to distinguish between items. Having the option to enable hover text on the AutoComplete control would be useful.

**Describe the solution you'd like**

Option to enable hover text in the AutoComplete control options

**Additional context**
End up with something like this
![image](https://github.com/equinor/design-system/assets/74707844/fddcdf5a-5975-41dc-a207-43d436fb09bf)

**Comment by oddvernes** [comment]
Thank you for the feature request, we will discuss this in the team 👍. Note that Autocomplete have a `multiline` prop that will wrap text such as in the example picture above. Useful alternative for cases where you use autoWidth but need the full text to be readable regardless of length

**Comment by chrisw-n** [comment]
Yeah I am planning on enabling the multiline properties guess it just makes the list longer
