### ISSUE TITLE
✨ Autocomplete: select all feature

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3254]
This is a ressurection of #961 and was implemented by @yusijs 

![Image](https://github.com/equinor/design-system/assets/4499531/c7d78009-904a-4f6a-86cf-6303fbe2089f)

![Image](https://github.com/equinor/design-system/assets/4499531/998abee2-f97b-4db3-9c5a-15c7a63b966d)

![Image](https://github.com/equinor/design-system/assets/4499531/88330a76-caae-47c8-b83a-70ebaa97a8ff)

Select all item is sticky

![Image](https://github.com/equinor/design-system/assets/4499531/2109da32-af7d-4d9e-86e2-3784dc83053f)

**Comment by BirteThornquist** [comment]
Design review: 
The inclusion of the "Select All" option looks fine. There is one issue that requires attention. The "Select All" option remains sticky at the top of the selection list causing select list items to become hidden behind it. The selection list should stop just below the "Select All" item to prevent overlap.
