### ISSUE TITLE
I can't find the active text in text/interactive/elevation-level-2 in the variables panel. Is it me or has something been changed? 🙈

### ISSUE THREAD

**Issue by benteljones** [equinor/design-system#3264]

**Comment by benteljones** [comment]
![Image](https://github.com/equinor/design-system/assets/92795462/f5dc88f5-3444-4b51-98ce-297918e3be30)

**Comment by BirteThornquist** [comment]
Someone please investigate @equinor/eds-design

**Comment by benteljones** [comment]
As @torleifhalseth found out very quickly: the scoping has been changed and has incorrect markings. 👏
It would be fantastic if someone with access could update the main branch. ❤️

**Comment by torleifhalseth** [comment]
Request submitted with changes in EDS Themes @vnys 💅
