### ISSUE TITLE
Allow general width/height descriptors for eds-data-grid?

### ISSUE THREAD

**Issue by mhwaage** [equinor/design-system#3275]
Hi! Currently, the eds-data-grid accepts height, width, and virtualHeight as numbers. In order to have a more dynamic design, I would prefer to pass a relative size, e.g. "100%". Currently, I do exactly that; 
```typescript
<EdsDataGrid
       ...
        virtualHeight={"100%" as unknown as number}
        height={"100%" as unknown as number}
        width={"100%" as unknown as number}
      />
```

can this be officially supported?

**Comment by oddvernes** [comment]
Hello! I see width and height are of type` string | numbe`r at least in the latest release. it also appears i can use string in the storybook at least. Are you on the latest version of data-grid? 
`virtualHeight` type is `number` though so this should be `number | string` as well i recon

**Comment by mhwaage** [comment]
I think the casting for height/width is a holdover from when we were on 0.2.0, I see that I can now omit in the current version. Thanks!

**Comment by oddvernes** [comment]
Update: We realized `virtualHeight` is no longer needed and to use `height` instead, so we are deprecating that prop
