### ISSUE TITLE
Evaluate the usability of the Equinor font in mobile and web apps

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3278]
The Equinor font is made first and foremost for marketing and not user interfaces. We’ve had recurring discussions to replace it in UI components with a more legible font, and then keep the Equinor font for titles. 

[Original Figma file](https://www.figma.com/file/FGCvFmmnxXPbgQ9dV49Ejx/Equinor-font-issues?type=design&node-id=0-1&mode=design&t=5A5R37JBwxa1P8y2-11) created to propose an upgrade the Equinor font

Research and WIP can be seen in [the Typography file in Figma](https://www.figma.com/file/Pj6T5bqP8lz2TFnJMBVDkH/%F0%9F%85%B0%EF%B8%8F-Typography?type=design&node-id=3-152&mode=design&t=4B3HIlodyN4UX0em-11).

**Definitions of done:**

Make an overview of existing products to evaluate how the Equinor font is working in terms of usability and accessibility

**Comment by marinalinn** [comment]
Figma file: [](https://www.figma.com/file/7D2nMHjqDpw7kVUiTcmzzn/%F0%9F%93%B1-Apps?type=design&node-id=1%3A37&mode=design&t=X01Ltl9DFVYzS9zv-1)
