### ISSUE TITLE
Create proposal for pairing the Equinor font with a UI font

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3279]
Following the results of #3278 create a proposal that works with headers, body and UI elements. We already know that we need to consider a system font for ios called San Francisco. 

**Sub tasks**

- [x] #3283

**Definition of done**

Create proposal in Figma the following cases:

| Component | Web apps | Mobile |
|--|--|--|
| Table | ✅ |  |
| Body copy | | ✅ |
| Filters | | |
| Tabs | ✅ |  |
| Menu | | ✅ |
| Button | ✅ | ✅ |
| Card | | |

**Comment by marinalinn** [comment]
Figma file [here](https://www.figma.com/file/7D2nMHjqDpw7kVUiTcmzzn/%F0%9F%93%B1-Apps?type=design&node-id=1%3A37&mode=design&t=X01Ltl9DFVYzS9zv-1)
