### ISSUE TITLE
Present the typography proposal with product teams

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3280]
Present the arguments and proposal to include a new UI font in addition to the Equinor font in relevant components as outlined in #3278 

#### Product teams

- [x] #3388
- [x] #3389
- [x] #3390
- [ ] #3391
- [x] #3392
- [ ] #3409

**Comment by marinalinn** [comment]
Building [a file](https://www.figma.com/file/B0fimAoET7GXevflKt64o1/Spacing?type=design&node-id=570%3A1503&mode=design&t=loIkyANFuaQLy18g-1) where we can have a comparison overview with the components from different teams, apply the typography component and spacing, present and discuss the result with: 

- Amplify
- Echo
- Fusion
- Appraise
- Mobility

**Comment by marinalinn** [comment]
Proposal presented to Mobility team (how new foundations affect an entire app), and this Sprint the foundations will be applied to Amplify. Last Friday in a meeting with Amplify team we aligned accesses, products to take in consideration, goals and processes to speed it up things to reach this goal.

**Comment by marinalinn** [comment]
Proposal presented last Friday (April 19) to Amplify team, more details about it and next action points [here.](https://github.com/equinor/design-system/issues/3388)

- Amplify ✅
- Echo
- Fusion
- Appraise
- Mobility ✅

**Comment by marinalinn** [comment]
Proposal presented today (Tuesday 30) to Echo team, more details about it and next action points [here.](https://github.com/equinor/design-system/issues/3388)

- Amplify ✅
- Echo ✅
- Fusion ✅
- Appraise
- Mobility ✅

**Comment by marinalinn** [comment]
Now we are closing the proposal about density covering all teams needs collected.
Another ticket will be created for density sync with teams and there we will cover IOC and Appraise teams
