### ISSUE TITLE
Evaluate the line-heights with the EDS 2.0 typographic scale

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3285]
Taking colour tokens into considerations, what are the line-heights we need.

Research and WIP can be seen in [the Typography file in Figma](https://www.figma.com/file/Pj6T5bqP8lz2TFnJMBVDkH/%F0%9F%85%B0%EF%B8%8F-Typography?type=design&node-id=3-152&mode=design&t=4B3HIlodyN4UX0em-11).

**Comment by marinalinn** [comment]
Figma file [here](https://www.figma.com/file/7D2nMHjqDpw7kVUiTcmzzn/%F0%9F%93%B1-Apps?type=design&node-id=1%3A37&mode=design&t=X01Ltl9DFVYzS9zv-1)
