### ISSUE TITLE
Manage permissions to have access to Sanity

### ISSUE THREAD

**Issue by marinalinn** [equinor/design-system#3288]
Check why @marinalinn doesn’t have access to the EDS Mobile documentation project in Sanity

**Comment by marinalinn** [comment]
Note: check if is possible to have a final access this week

**Comment by marinalinn** [comment]
@vnys I think you said there is a last access isn't?

**Comment by vnys** [comment]
Added @marinalinn to the project. Log in with SSO on https://www.sanity.io and choose the equinor-eds project.

**Comment by marinalinn** [comment]
Tusen takk! I will check it
