### ISSUE TITLE
Renew certificate used on CDN

### ISSUE THREAD

**Issue by torleifhalseth** [equinor/design-system#3351]
Issue: https://equinor.slack.com/archives/CJT20H1B9/p1710484719430209
How to create new certificate: https://miro.com/app/board/uXjVPiRRT0k=/

- [ ] equinor/design-system-internal#85

**Comment by Hjaf** [comment]
New certificate requested (RITM3231266).

**Comment by Hjaf** [comment]
Certificates updated in the keyvault, the new version is selected for the CDN ✅

**Comment by vnys** [comment]
Change email from nlun@equinor.com to fg_eds@equinor.com

**Comment by Hjaf** [comment]
Closing this issue, new issue for updating notification is created (see description).
