### ISSUE TITLE
Allow more custom filtering

### ISSUE THREAD

**Issue by mhwaage** [equinor/design-system#3353]
**Is your feature request related to a problem? Please describe.**
In my project, I would like to allow users to use filters to search for files. Specifically, I would like to filter based on:
File names - each file name is unique, so the default filter that adds a multiselect is not helpful, instead I would want a simple search field.
Dates - again the default filter for strings is a multi-select which is unhelpful, instead (e.g.) a datepicker would be handy.

**Describe the solution you'd like**
The ability to pass in my own components for defining a filter function. Something along the line of (rough draft):

```javascript
function MyFilter() {
  const {setColumnFilterFn} = useColumnContext(); // <- Hypothetical column context for enabling the custom component to set/update the filter function, default filter undefined
  
  return (
    <input
      onChange={(e) => setColumnFilterFn((s) => s.includes(e.target.value))}
     />
  )
}
```

i.e. the custom component can update the column filter function via a context hook, and returns a component that will be displayed in the dialog

**Describe alternatives you've considered**
* Developers add custom filters outside of the data table. This is a bit inelegant for filters that are only intended for the data table.
* EDS adds more filters/explicit 'options' for which filter to use. This will likely become too bloated, although even with the current suggestion it would make sense to expose the 'default' functions (e.g. if users want to coerce a filter)

**Comment by mhwaage** [comment]
On more thinking, adding a context is over-complicating things - instead the setter could just be passed in as an argument

**Comment by yusijs** [comment]
Ref discussion on slack:
https://equinor.slack.com/archives/CJT20H1B9/p1710751667207079
