### ISSUE TITLE
Present the typography proposal with Appraise

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3391]
**General objective:**
To complete the typography and spacing proposal by inviting different teams to an open conversation where we can collect feedback and analyze together how this new foundations would affect their product, what we can have in consideration before to finalize the work and how we can improve the proposal. 

**Specific objectives:**

- To understand better our users needs and their projects.
- To ensure a high quality result with the typography and spacing work, where we make decisions covering potential coalitions in advance and avoid surprises. 
- To create a dialogue to strengthen our current external communication and align expectations with our users by explaining them the current state of our work, our processes and also our goals by sharing our roadmap. 

**Outcome:**
A meeting where we explain:

1. Current font scenario, how Inter came to the conversation and how it could be applied also on web products. 
2. From metrical alignment to optical alignment and how this affects icons and baseline grid.
3. Typography and spacing applied to their product.
4. Global or local density
5. EDS roadmap and alignment
6. Parallel project: a comparison between design systems and user experiences.

_Description of the task added by Marina*_

**Comment by marinalinn** [comment]
Meeting made on May 30 ✅
