### ISSUE TITLE
Agree on datepicker implementation details

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3393]
#### Evaluate the datepicker PR and align with Ronnie.

Based on initial discussions, I suggested adding a warning validation underneath the input field to be aligned with the other form components. Is this the best way to solve it? Or should we use the initial validation Ronnie implemented? Are there other concerns?

![image](https://github.com/equinor/design-system/assets/2081882/c4d8b1a4-6a30-4ec3-8303-ce0cfa9d77d1)

**Comment by BirteThornquist** [comment]
Collaborated with Ronnie to implement some UX enhancements:
Simplified navigation: Replaced double navigation arrows with single arrows for month navigation and integrated a dropdown for selecting years.
Introduced a "Today" ghost button for seamless navigation back to current date.
Made spacing adjustments for improved visual clarity.
Need to look into the double validation challenge where "internal rules" such as disabled dates could still be inputted via keyboard, resulting in accurate dates. Although these instances are not flagged as errors externally users will need a warning.
