### ISSUE TITLE
Override date format on DatePicker component

### ISSUE THREAD

**Issue by v3gard** [equinor/design-system#3405]
**Is your feature request related to a problem? Please describe.**

Here in the civilized part of the world, we use date formats like `dd/mm/yy`. To avoid confusing users that prefers `mm/dd/yy`  (i.e. those that doesn't follow the obviously preferred standard), we should consider providing a universally accepted solution to a problem like `03/08/24`

Depending on where you are in the world, this could mean
* August 3rd 2024
* March 8th 2024

**Describe the solution you'd like**

1. A callback function that provides the selected date according to the ISO standard (e.g. `yyyy-mm-dd` / `2024-03-08`, which allows me to fully customize the output value that is shown to the end user in the date picker.

2. An example in the Story Book (to make it obvious to developers on how to apply this).

**Describe alternatives you've considered**

Creating a local variant that exists in the app we're responsible for. This does not bring any community value though....

**Additional context**

![image](https://github.com/equinor/design-system/assets/343078/47591804-3b5d-4d5c-899b-9862bfdd1602)

**Comment by yusijs** [comment]
Spitballing a few potential implementations:

- Disallow input by text if a format-prop is passed in, only allow picking from the calendar (easiest to implement obviously)
- Show the formatted values when outside the field, but when focused we show the segmented inputs as today (ok-ish middleground?)
- Manually override the segments from `react-aria`'s `useDateFieldState` hook (seems like a bad road to go down)

**Comment by oddvernes** [comment]
My first thought was showing the formatted value when input is blurred and then switching to showing the actual inputs on focus (which differs depending on what language you have set in the browser settings, not sure if you was aware of that @v3gard )


![Image](https://github.com/equinor/design-system/assets/4499531/56baf141-4df7-4976-b423-9c7eac913718)

**Comment by v3gard** [comment]
> My first thought was showing the formatted value when input is blurred and then switching to showing the actual inputs on focus

I agree, this sounds like a good solution.

> which differs depending on what language you have set in the browser settings

@oddvernes Yes, I am aware of that. What confused me what this also overrides my local regional settings. 

Note that I prefer English in the Chrome UI (and not as locale)

![image](https://github.com/equinor/design-system/assets/343078/d2f2172c-96de-4b8b-b68d-96301f65b8d1)

I have set my locale (Windows regional settings) set to Norwegian

![image](https://github.com/equinor/design-system/assets/343078/3ec294f7-e57c-4c67-a31e-d9b5d9bd9ff4)

This is what the EDS component shows me today (US English locale):
![image](https://github.com/equinor/design-system/assets/343078/6aad67e5-4065-4882-8b8b-ecbf59a00c75)

This is what the native `<Input type="date"/>` component from EDS gives me: (Norwegian locale)

![image](https://github.com/equinor/design-system/assets/343078/0f32078a-a38c-4cc3-93cd-0096628ef5ec)

Perhaps this is a bug in the `DatePicker` component? That you incorrectly use  the UI language in the browser to determine locale settings, when you should have used locale (as defined in the OS)?

**Comment by yusijs** [comment]
> When I state (in the browser settings) that I prefer to read content in English, do I at the same time tell web sites "give me all dates in a non-preferred locale"?
> 
> * If yes, accept as-is (but provide a `format` prop that allows us to select a universal standard)
> * If no, perhaps this is a bug in the `DatePicker` component? That you incorrectly use  the UI language in the browser to determine locale settings, when you should have used locale (as defined in the OS)?

From what I can gather, it defaults to using the language to set the locale, which is the only locale-info that can be accessed (by javascript) as far as I'm aware of (`navigator.language`). So the answer to your question seems to be "Yes". 

To stick with standardization, I would prefer that we allow you to pass in `formatOptions` (matching Intl.DateTimeFormat.Options). This will still format the dates in the default locale, but it's also possible that we allow you to override the locale, so something like this:

```tsx
<DatePicker formatOptions={{
    month: 'long',
    day: '2-digit',
    year: 'numeric'
  }}
  format={'fr-FR'}
  value={new Date(2024, 11, 23})
 />
```

So if your language is set to english, the above would read `December 23, 2024`, but if you override it with French (as in the example above) it would be `24 décembre 2024`. 

Any thoughts?

**Comment by v3gard** [comment]
>>When I state (in the browser settings) that I prefer to read content in English, do I at the same time tell web sites "give me all dates in a non-preferred locale"?
>>* If yes, accept as-is (but provide a format prop that allows us to select a universal standard)
>>* If no, perhaps this is a bug in the DatePicker component? That you incorrectly use the UI language in the browser to determine locale settings, when you should have used locale (as defined in the OS)?

> From what I can gather, it defaults to using the language to set the locale, which is the only locale-info that can be accessed (by javascript) as far as I'm aware of (navigator.language). So the answer to your question seems to be "Yes".

This is a side discussion from what I originally reported. 

No, the native `<Input/>` component does that, hence the norwegian style, while the current `DatePicker` seems to favor the language in the browser. I'm not sure why this is the case.

|DatePicker (Norwegian locale is ignored, browser language is preferred)|Input (Norwegian locale)|
|-|-|
|![image](https://github.com/equinor/design-system/assets/343078/1a9599b1-6dc2-44dd-aa77-5e50ab8a949c)|![image](https://github.com/equinor/design-system/assets/343078/a191af0f-f8a7-4494-84d3-e9ce245e03a0)|

Here are some samples from commands I ran in the browser:
* `navigator.language` -> `'en-US'`
* `Intl.DateTimeFormat().resolvedOptions().locale;` -> `'nb'`

Back to the original question:

> Any thoughts?

Could we make it simpler? Just exposing a callback function provides the selected date as an ISO-date. In my example below, `selectedDate` would typically be `2024-11-23`.

```js
<DatePicker 
  formattedValue={(selectedDate) => doStuffWith(selectedDate)} 
  value={new Date(2024, 11, 23})
 />
```

**Comment by yusijs** [comment]
Part of the reason I wanted to go down the `formatOptions` path, is so we can make it part of the input-segments in a smoother way, where we change how the segments are worded based on these options, like in this video:

https://github.com/equinor/design-system/assets/11261560/def9fe84-6269-4c84-94df-b10084f8a4ee

I think this gives a better flow, keeps accessibility etc.

**Comment by yusijs** [comment]
Talked a bit about this, we landed on using the `formatOptions` prop as our official :tm: solution. 

As a future solution for more flexibility we will look into exposing the calendar as a standalone component, so you could create a custom input-field to control the format yourself.

Will be part of the next release of eds-core-react
