### ISSUE TITLE
When clicking select all in a controlled component, disabled options are also selected

### ISSUE THREAD

**Issue by mhwaage** [equinor/design-system#3427]
**Describe the bug**

In a controlled autocomplete, where some of the options are disabled, select all ignores that the options are disables and selects them anyway. (possibly

**Steps to reproduce the bug**

1. Create a controlled Autocomplete with some disabled options and Select All enabled
2. Click Select all
3. Disabled options are selected
4.

**Expected behavior**

Select All should not select disabled options
**Specifications**

- Version: 0.36.1
- Browser: Edge
- OS: Windows

**Additional context**
![image](https://github.com/equinor/design-system/assets/57612883/c399d50d-c416-4843-ab98-a7c6c719d0a6)

**Comment by oddvernes** [comment]
Good catch! We'll need to fix this
