### ISSUE TITLE
White background upon opening Autocomplete

### ISSUE THREAD

**Issue by AndreasPresthammer** [equinor/design-system#3449]
Opening autocomplete causes an overlay over the entire app.

https://github.com/equinor/design-system/assets/328539/76e03cef-ac44-4343-ba61-cf0b6bbf0382

**Expected behavior**

Expected the overlay not to appear. Expect same behaviors as in 0.37.0.

**Specifications**

- Version: 0.38.0
- Browser: Chrome Version 124.0.6367.209 (Official Build) (64-bit)
- OS: Windows 11

**Additional context**

Issue introduced in upgrade from 0.37.0 to 0.38.0.

**Comment by oddvernes** [comment]
If possible, could you inspect the dropdown in chrome devtools (you may have to click inspect twice after it closes the first time) and click on `::backdrop` and see if there isn't anything overwiting the default useragent style here which should be `transparent`
![bilde](https://github.com/equinor/design-system/assets/4499531/9b57ebbd-453f-41eb-9bbf-75694eb8ccde)

**Comment by AndreasPresthammer** [comment]
> If possible, could you inspect the dropdown in chrome devtools (you may have to click inspect twice after it closes the first time) and click on `::backdrop` and see if there isn't anything overwiting the default useragent style here which should be `transparent` ![bilde](https://private-user-images.githubusercontent.com/4499531/332435915-9b57ebbd-453f-41eb-9bbf-75694eb8ccde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDc1OTUsIm5iZiI6MTcxNjQ0NzI5NSwicGF0aCI6Ii80NDk5NTMxLzMzMjQzNTkxNS05YjU3ZWJiZC00NTNmLTQxZWItOWJiZi03NTY5NGViOGNjZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDY1NDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzNjMTkwMTVjNTBkMzNmMmNlMDNlNTM1MjZmNTg5ZGZkYzJlYzM1M2Q1MDAxYWVlYWUyMGY0MTcwM2Q1NzNmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._hOTxTDhhBSjT3ceS0FXi3wbXUZdUYGyzmUyaXBkukE)

I'm seeing the followin in chrome devtools (with the `::backdrop` element selected):

![image](https://github.com/equinor/design-system/assets/328539/6780c5f0-5afd-4e65-8052-023fb45ac8ed)

**Comment by AndreasPresthammer** [comment]
Manually disabling the marked `::backdrop` `background-color` style fixes the issue:

![image](https://github.com/equinor/design-system/assets/328539/904a0670-3faa-4dcd-b45b-3b1397434869)

**Comment by oddvernes** [comment]
Ah yes it inherits the style applied to ::backdrop on dialog. I have pushed a fix (add explicit backdrop color on the autocomplete) We will release a new version of core-react soon (early next week at the latest) 👍

**Comment by oddvernes** [comment]
Did this problem go away with the new release of eds-core-react?

**Comment by AndreasPresthammer** [comment]
yes, it's resolved 👍

**Comment by oddvernes** [comment]
Great! Closing as resolved
