### ISSUE TITLE
Use correct header levels in the stories

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#346]
In some of the stories we skip header levels, which is bad semantics and bad for screen readers. In the docs tab we get an `h1` header, which means the next level _must_ be `h2`. If the font-size of h2 is too big, then use the `as` attribute, for example:

```html
<Typography variant="h4" as="h2">
  h2 header styled as h4
</Typography>`

**Comment by mimarz** [comment]
Using mdx in storybook now this is solved by md annotations.
