### ISSUE TITLE
Deprecate density awareness from the Density collection

### ISSUE THREAD

**Issue by marinalinn** [equinor/design-system#3470]
Edited by Victor: Oddbjørn had a suggestion for how to override density in code which corresponds nicely with how Density already works in Figma. The Density Awareness collection can therefore be removed.

**Comment by vnys** [comment]
Update: The Density Awareness collection has two modes, True and False. By removing False instead of removing the entire collection we save some time. I’ve tested that it doesn’t pop up as an option for the end users.
