### ISSUE TITLE
Installing latest version of data-grid fails due to incompatible node versions

### ISSUE THREAD

**Issue by magnh** [equinor/design-system#3484]
## Describe the bug

I am not able to install the latest release of `@equinor/eds-data-grid-react` due to node incompatible node versions. I am running on `node v20`. This could possibly affect all packages.

With `node v20.9.0`, I am getting these errors with `npm` and `yarn`:

```
npm install @equinor/eds-data-grid-react@latest
...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@equinor/eds-data-grid-react@0.6.0',
npm WARN EBADENGINE   required: { pnpm: '>=8.15.4', node: '^18.20.2' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.4' }
npm WARN EBADENGINE }
```

```
yarn add @equinor/eds-data-grid-react@latest
...
error @equinor/eds-data-grid-react@0.6.0: The engine "node" is incompatible with this module. Expected version "^18.20.2". Got "20.9.0"
error Found incompatible module.
```

Installing works fine after downgrading to `node v18`.

### Steps to reproduce the bug

1. Use a node version higher than 18: (e.g. `node 20.9.0`)
2. Run `npm install @equinor/eds-data-grid-react@latest` or `yarn add @equinor/eds-data-grid-react@latest`
3. Observe error in console

### Specifications

- Version: `@equinor/eds-data-grid-react@0.6.0`
- Browser: N/A
- OS: MacOS

## Expected behavior

EDS should not lock into one specific major version, but rather specify a minimum version and allow greater node versions.

### Possible solution

This line was added since the previous release, so I suspect this is what introduced the _bug_. I assume the author ment using `>=18`, which allows greater major versions, instead of `^18`, which locks into `v18`, so probably just a typo.

https://github.com/equinor/design-system/blob/b33e888f70ca1e98cad0322e0ed5c97e256c4773/package.json#L5

I am no expert in this field, but looks like changing to `>=18` **across all `package.json`-files** would fix the issue ([npm docs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines)).

## Additional context

I think this should be addressed before any further releases of EDS.

**Comment by oddvernes** [comment]
I have made a patch release of data-grid-react that should hopefully resolve this specific issue, and then we just need to update the rest of the package.jsons before making any other npm releases
