### ISSUE TITLE
Expose DatePickerProps type

### ISSUE THREAD

**Issue by magnh** [equinor/design-system#3489]
**Is your feature request related to a problem? Please describe.**

`DatePickerProps` is not exported from `@equinor/eds-core-react`.

**Describe the solution you'd like**

As a developer, I want to import and use the `DatePickerProps` type. Currently it is not exported.

**Describe alternatives you've considered**

Export `DatePickerProps` from the package.

Current workaround is

```ts
type DatePickerProps = Parameters<typeof DatePicker>[0]
```

**Additional context**

Using `@equinor/eds-core-react@0.39.0`.

**Comment by oddvernes** [comment]
Is there any reason not to do this @yusijs ?
