### ISSUE TITLE
Cannot override styles of DatePicker with styled(DatePicker)

### ISSUE THREAD

**Issue by magnh** [equinor/design-system#3490]
**Describe the bug**

I cannot override styles of DatePicker using `styled(DatePicker)`. 

**Steps to reproduce the bug**

https://codesandbox.io/p/live/a0f3cab7-46ad-4c23-ba83-f14e79bd83c8

**Expected behavior**

Would expect `styled(DatePicker)` to work, as for other EDS components.

**Specifications**

- Version: 0.39.0
- Browser: N/A
- OS: N/A

**Suggested solution**

Did a quick test by modifying the component in `node_modules`.

Following this pattern on the DatePicker element worked: https://styled-components.com/docs/advanced#styling-normal-react-components

**Comment by oddvernes** [comment]
Good point, we just need to append  `& HTMLAttributes<HTMLDivElement>` to the DatePickerProps type
