### ISSUE TITLE
Wrong color on placeholder/date format indication (dd.mm.yyyy) value on DatePicker

### ISSUE THREAD

**Issue by eddiman** [equinor/design-system#3491]
**Describe the bug**

Wrong color on date format placeholder text.

**Expected behavior**
The (dd.mm.yyyy) date format placeholder text, should have same text color as placeholder text in TextField (eds_text__static_icons__tertiary).  

**Specifications**

- Version: `@equinor/eds-core-react 0.39.0`
- Browser:  Chrome 125
- OS: MacOS

**Additional context**

![image](https://github.com/equinor/design-system/assets/1317896/5eb1bf30-2e5d-4954-ac4f-76ba9edd7763)

**Comment by oddvernes** [comment]
Thanks for the report, this will be fixed 👍
