### ISSUE TITLE
Suggestion to remove unnecessary clear button when no date has been inputted on DatePicker

### ISSUE THREAD

**Issue by eddiman** [equinor/design-system#3492]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Clear-icon button is not needed when date has not yet been inputted. Adds noise to the component. See proposed solution below
![image](https://github.com/equinor/design-system/assets/1317896/1498187f-9380-442c-92da-2b73cbed374a)

**Comment by oddvernes** [comment]
This seems like a reasonable improvement 👍
