### ISSUE TITLE
Align font scales optically based on x-height

### ISSUE THREAD

**Issue by marinalinn** [equinor/design-system#3495]
**General objective:** 
Following the structure proposed for spacing: Selectables, Containers and Pages, we need to align the font scales for Equinor font and Inter font based on x-height. Currently the Equinor font has a much more little x-height what results on different optical results when we have different texts on the same font-size in Equinor and Inter font.

![image](https://github.com/equinor/design-system/assets/11398860/f4ef7b84-fe6d-4536-baba-effe7ae92da2)
Both texts has a 16px font-size, but the one on the left looks much bigger. 

This brings collisions when we try to make definitions for [vertical spacing between](https://github.com/equinor/design-system/issues/3471) Heading + Body, or Body + Body.

**Specific objectives:**

- To build an harmonic visual rhythm
- To align everything following a proportion
- To define how density will affect selectable items

**Outcome:**
A file with the font scale aligned for Equinor font and Inter font based on x-height.

**Comment by marinalinn** [comment]
**Inter font:**

- X-height: 1536
- Em size: 2816

**Equinor font:**

- X-height: 480
- Em size: 1000

**Comment by vnys** [comment]
![image](https://github.com/equinor/design-system/assets/2081882/a568d7e5-9049-43a6-bd34-8f528d8b24b7)

**Comment by vnys** [comment]
![image](https://github.com/equinor/design-system/assets/2081882/d3b552cb-5d5a-4660-a129-38678de58a58)

**Comment by marinalinn** [comment]
Observations: 

- The fonts are aligned in the font-size scale, so if the user switch from Inter font to Equinor font on SM font-size for example, the result will be switching from Inter 12px font-size to Equinor 10px font-size but these will have the same x-height. The font-size scales were aligned to reach the same x-height visual result.
- We were searching an optical alignment but in the result we can see that even with the same x-height, the Equinor font looks bigger but weaker, and the Inter font looks more little but stronger. Maybe working on their font-weight we will reach the optical alignment that we want.

**Comment by marinalinn** [comment]
The Primitives were aligned based on:

- Inter 16px = Equinor 16 * 1.136 = 18.18px
- Formula for the typographic scale using the Inter font = 0.5*rint(16*2^(0/5)/0.5)
- Formula for the typographic scale using the Equinor font = 0.5*rint(18.18*2^(0/5)/0.5)
