### ISSUE TITLE
Reconsider css padding shorthand

### ISSUE THREAD

**Issue by oddvernes** [equinor/design-system#3522]
Ref https://github.com/equinor/design-system-tokens/issues/232

![Image](https://github.com/equinor/design-system/assets/4499531/c1f280fe-659c-4fc7-9129-1ea0f92b6616)

- It makes the inline token meaningless because there is no corresponding stack token
- The stack token is misnamed becasuse it is no longer stack but rather all the sides
- What if I need the stack value for something individually, like putting it in a calc to subtract a thick border or something? It doesn't exist

 the shorthand and its complex transformer will also probably make it impossible to do the cyclical space toggle trick, so we have to choose

**Comment by vnys** [comment]
We (@oddvernes, @torleifhalseth, @vnys) agreed to skip the shorthand notation for now and revisit at a later point
