### ISSUE TITLE
Autocomplete clear should focus input-field

### ISSUE THREAD

**Issue by yusijs** [equinor/design-system#3524]
**Describe the bug**

When hitting the X to clear the selected option in the Autocomplete, it should revert focus to the input-field.

**Steps to reproduce the bug**

1. Open https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs
2. Select a value
3. Hit the X-icon
4. Focus is not on the input 

**Expected behavior**

I should be able to type a value in the input immediately after clearing the value

**Specifications**

- Version:
- Browser:
- OS:

**Additional context**

![image](https://github.com/equinor/design-system/assets/11261560/109ee1f8-418c-4b8a-ace6-8f9d5e2f827e)

**Comment by oddvernes** [comment]
This will be fixed 👍
