### ISSUE TITLE
Tooltip is displayed underneath Autocomplete

### ISSUE THREAD

**Issue by TormodNy** [equinor/design-system#3567]
**Describe the bug**
In our application we have some Autocomplete components with custom option components that show additional information in tooltips when hovering an icon. Previously this worked by changing the `z-index` of the tooltips to ensure they displayed above the Autocomplete modal. After the change which moves the Autocomplete to the top layer with the native popover API this does not work anymore and tooltips are displayed underneath the Autocomplete.
![image](https://github.com/user-attachments/assets/d3b01b18-39cd-4e99-a317-e93278b98e2c)

**Steps to reproduce the bug**

1. Go to [codesandbox example](https://codesandbox.io/p/sandbox/eds-autocomplete-with-tooltips-fzr5yc?file=%2Fsrc%2FApp.tsx%3A15%2C42)
2. Click Autocomplete to open it
3. Hover over info icons
4. See that tooltips are displayed underneath autocomplete

**Expected behavior**

Tooltips should display on top of Autocomplete modal (at least when Tooltip is inside Autocomplete).
Is it possible to move Tooltips to the top layer as well?

**Specifications**

- Version: 0.40.1
- Browser: Chrome
- OS: Windows

**Additional context**
https://codesandbox.io/p/sandbox/eds-autocomplete-with-tooltips-fzr5yc?file=%2Fsrc%2FApp.tsx%3A15%2C42

**Comment by oddvernes** [comment]
Yes we need to convert tooltip to a popover as well. Should be easy enough! We did autocomplete first as a test to see if anyone would run into any issues but it seems to work fine (I did not foresee this tooltip use case though 😅 )
