### ISSUE TITLE
Autocomplete inside Menu unusable since @equinor/eds-core-react 0.38

### ISSUE THREAD

**Issue by kebonarjee** [equinor/design-system#3580]
**Describe the bug**

When clicking on an item in an Autocomplete, given that the Autocomplete is inside a Menu, nothing happens.

**Steps to reproduce the bug**

1. Place an Autocomplete within a Menu
2. Open the Autocomplete and click on an item
3. Nothing happens

**Expected behavior**

onOptionsChange() fires.

**Specifications**

- Version: @equinor/eds-core-react >=0.38
- Browser: Chrome 127.0.6533.89
- OS: Windows 11 23H2

**Additional context**

See https://codesandbox.io/p/sandbox/eds-autocomplete-inside-menu-3lhlql for a minimal example.

**Comment by oddvernes** [comment]
I found the issue and fixed it, but it should be noted that putting Autocomplete inside Menu is not something we officially support as the Autocomplete will be inaccessible by keyboard within the menu ⚠️
