### ISSUE TITLE
DateRangePicker - onBlur not invoked after exiting field

### ISSUE THREAD

**Issue by jarlef** [equinor/design-system#3582]
The onBlur callback is never triggered by the DateRangerPicker component when the user leaves the input. The onBlur event is essential to know when the user is done editing the field so the frontend can persist the change ad-hoc since the onChange is triggered for almost every keystroke the user does

```tsx
 <DateRangePicker
              value={myRange}
              onChange={range => setMyRange(range)}
              onBlur={() => console.log('this will never be invoked')}
            />
```

**Comment by oddvernes** [comment]
I see that the "rest" `{...props}` is not applied in the `DaterangePicker`  as it is in the `DatePicker`. Putting it in seems to fix the issue. Note that onBlur is also triggered by opening the calendar popover since that then blurs the input as well.

**Comment by jarlef** [comment]
What is the timeline for when a new eds version is deployed?

**Comment by oddvernes** [comment]
I can probably make a release later today. I was hoping to get #3571 in but I think maybe they've gone on vacation 😅
