### ISSUE TITLE
Size property on icon inside button does nothing visually 

### ISSUE THREAD

**Issue by hkot1991** [equinor/design-system#359]
**Describe the bug**
This: 
```
    <Button variant="ghost_icon">
      <Icon name="save" title="save action" size={48}></Icon>
    </Button>
```

And this:
```
    <Button variant="ghost_icon">
      <Icon name="save" title="save action" size={16}></Icon>
    </Button>
```

Provide the same output. Changing the icon size should change the btn/icon size,

**Steps to reproduce the bug**

1. Go to https://eds-storybook-react-development.azurewebsites.net/?path=/story/components-button--ghost
2. see that the first btn icon has size 48 and the other has no size property, then see that they look the same:
![image](https://user-images.githubusercontent.com/61226854/84256871-ccaff280-ab14-11ea-96e1-554d000a4624.png)

**Expected behavior**

Changing the icon size should change the btn size,

**Specifications**

- Browser: Chrome

**Comment by mimarz** [comment]
@hkot1991 We have just release a change with increased icon size for ghost buttons to 24px, in version `0.4.0` of `eds-core-react` :)
