### ISSUE TITLE
Popover changes in 0.42.0 causes flickering

### ISSUE THREAD

**Issue by havardla** [equinor/design-system#3635]
**Describe the bug**

When updating to 0.42.0 hovering over a button that triggers a popover causes the popover to trigger a re-render that causes flickering. This behavior is only happening on chromium based browser in a vite production build

**Steps to reproduce the bug**

A bit hard to reproduce since it only happens when we have this in production (cannot reproduce in localhost)

1. Add a button that sets an open state on a popover 
2. Try to hit the button from the right side
3. This will cause the popover to flicker until the mouse hits the middle of the button
4. The Popover will no longer flicker until a site reload

**Expected behavior**

Popover to stay visible when hitting the right edge

**Specifications**

- Version: 0.42.0
- Browser: Chrome/Edge
- OS: WIndows 11

**Additional context**

We are running our application in radix using vite frontend tooling

**Comment by oddvernes** [comment]
Hello! Does this happen in version 0.41.5 as well, or did it only change in 0.42.0? Because I made some [changes](https://github.com/equinor/design-system/pull/3610/files) in 0.42 to try and fix another issue in another project where the popover would not render ast all unless the showPopover call was delayed. I think maybe this change should be reverted

**Comment by havardla** [comment]
It does not happen in 0.41.5 that we had to revert down to

**Comment by oddvernes** [comment]
@havardla I have made a test release with a possible fix. Would it be possible for you to test this in your prod enviroment since I am unable to reproduce this locally? `npm install @equinor/eds-core-react@next` if this works I'll make a patch release asap 👍

**Comment by havardla** [comment]
Cannot seem to trigger the flickering now

**Comment by oddvernes** [comment]
Thanks! The fix has now been released as [0.42.1](https://github.com/equinor/design-system/releases/tag/eds-core-react%400.42.1)
