### ISSUE TITLE
STATUS_ACCESS_VIOLATION when selecting in Autocomplete

### ISSUE THREAD

**Issue by Bjornar97** [equinor/design-system#3647]
**Describe the bug**

I have a Scrim component with isDismissable=false. Within that I have a SideSheet, and within the SideSheet I have an Autocomplete. 

When the CSS Property "container-type: inline-size" is on Sidesheet, or any child component within Sidesheet (but parent of Autocomplete), the browser crashes when you select a value in the Autocomplete, with ther error "STATUS_ACCESS_VIOLATION". Happens in Chromium, not in Firefox.

I have tested with EDS version 0.41.5 and 0.42. Same error.

**Steps to reproduce the bug**

1. Have this component tree: <Scrim> -> <SideSheet> -> <Autocomplete>
2. Set isDismissable to false on <Scrim>
3. Add CSS property "container-type: inline-size" to <SideSheet>
4. Open and select a value in Autocomplete
5. The browser crashes.

**Expected behavior**

The value is selected, and the page continues to work.

**Specifications**

- Version: 0.42.0
- Browser: Edge 129.0.2792.65 and Chrome 129.0.6668.89 
- OS: Windows 11

**Additional context**

Minimal reproduction code sandbox: https://codesandbox.io/p/sandbox/bug-eds-access-violation-w73gwp

**Comment by oddvernes** [comment]
This is an incredibly peculiar bug! 
Pasting the code into storybook does not produce the error, it works fine in all browsers. 
But trying it in a create-vite-app with latest eds-core-react - now it fails in chrome/edge but not firefox or chrome canary
I strongly suspect this is a bug in the current release of chromium, and the fact that it works in canary gives me hope that it will fix itself in the next major chrome release...

**Comment by oddvernes** [comment]
Well good news, as of chrome 130, whatever bug was causing this has been resolved and it no longer crashes the browser tab 🙂
