### ISSUE TITLE
Add prop for lighter text colour in ghost buttons on negative backgrounds

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#378]
We bumped into an issue with the `<Snackbar>` where the colour of the text in the ghostbutton is too dark against the dark background. 

![image](https://user-images.githubusercontent.com/2081882/85367754-20b1d280-b52a-11ea-9abf-00e20cf45365.png)

In Figma the ghost button uses 34% Moss Green, but that’s not an option we have at the moment. 

![image](https://user-images.githubusercontent.com/2081882/85367931-81d9a600-b52a-11ea-9920-b2286c653602.png)

We can get around the problem by overriding the button styles, but that’s not an ideal long term solution. Since we’ll get a similar problem with dark mode, where the text colour will be too light on a light background, I suggest we call the prop something that can be used in both scenarios, such as ~`contrastTextColor`~. `invertedTextColor` sounds better, as @wenche suggested. Other suggestions can be added in the comments.

**Comment by pomfrida** [comment]
Was a bit too eager so started with inverted logic yesterday. Need to wait for all the colours first.

**Comment by benkeq** [comment]
![Snackbar](https://user-images.githubusercontent.com/53559062/92219389-cbcff800-ee9a-11ea-87c7-4070b2605289.png)

The color `Interactive/Link in snackbars` has been updated with the primary color from dark theme. This may change after the dark theme testing.

**Comment by mimarz** [comment]
This was fixed in #535
