### ISSUE TITLE
Bump node version in Dockerfiles

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#392]
Bump node version in the Dockerfiles for the Storybook and Storefront to 14.x to be consistent with #178 

- [x] Storybook
- [x]  Storefront 
- [x]  Figma Broker

**Comment by wenche** [comment]
[Bumped in storefront ](https://github.com/equinor/design-system/pull/480/commits/998374a0c3a93ce6a0be9ee54e15b47e0d48aa9f)as part of docz rewrite
