### ISSUE TITLE
Create Toggle Button component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#394]
We need to evaluate if this is a expansion of `Button`, a new component or both. Maybe we need a `ButtonGroup` of some sorts... 🤔

Edit:
 `ButtonGroup` vs Button Toggle, maybe Figma would need a reference or tag to `ButtonGroup` as it makes more sense in react? 

Documentation: https://eds.equinor.com/0b0c666ab/p/22cd7f-toggle-button/b/86826a

**Comment by mimarz** [comment]
Prioritising this as we need more issue for development and this seems like a good "low hanging fruit"

**Comment by mimarz** [comment]
I think **mui** has a good example on how these are very similar, _but different_. 
* [Button Group](https://mui.com/components/button-group/)
* [Toggle Button](https://mui.com/components/toggle-button/)

I guess the confusion for us is that it looks like a button group but acts like a toggle button in [Figma](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=763%3A1).  

* Should toggle support ghost button variant? Looks like a toggle button with just icons might be relevant @equinor/eds-ux 
* Either way, it feels like we go with option 3 here, both? @equinor/eds-dev 

![the-road-to-el-dorado-both](https://user-images.githubusercontent.com/1070981/145970541-76224a3c-6e26-478b-9242-2ea114226332.gif)

**Comment by BirteThornquist** [comment]
@mimarz I am a bit confused about the differences between a toggle button and a button group actually is. A toggle button with just icons is relevant, yes. It's not quite the same as ghost button. It's not quite the same as a ghost button.

**Comment by mimarz** [comment]
> @mimarz I am a bit confused about the differences between a toggle button and a button group. A toggle button with just icons is relevant, yes. It's not quite the same as ghost button. 

The toggle button is more like group of radio or checkboxes in that they can be checked, single or multiple. Made to look like buttons.

The button group is just a grouping of normal buttons to indicate that they Are connected somehow. They still work as regular buttons.

**Comment by laliq** [comment]
> The button group is just a grouping of normal buttons to indicate that they Are connected somehow. They still work as regular buttons.
So why to create `Button Group`, when is just `Button`, so you can create `Button Group` from `Button` component?

**Comment by laliq** [comment]
- `Button Group` - The ButtonGroup component can be used to group related buttons.
- `Toggle Buttons` - Toggle buttons can be used to group related options.

**Comment by BirteThornquist** [comment]
What we have today is toggle button that can be active/inactive. Question is if we shall introduce group buttons as well. In my mind that is a separate issue...?

**Comment by mimarz** [comment]
As discussed during standup yesterday, I suggest we create the grouping component first due to everyone going on holiday next week and finishing outstanding tasks before then :) #1812

**Comment by mimarz** [comment]
Moving this back to todo as we need create #1812 first.

**Comment by oddvernes** [comment]
This component should be well specced out before making it as I see several different ways this could work

**Comment by martalalik** [comment]
### Research

1. [Exclusive selection](https://mui.com/material-ui/react-toggle-button/#exclusive-selection) - With exclusive selection, selecting one option deselects any other. Exclusive selection does not enforce that a button must be active.

**Comment by martalalik** [comment]
Closing this issue. The ground research is made and moved to an Epic #2450.
