### ISSUE TITLE
Spike component theming

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#401]
We need to decide on how to do theming. There are two alternatives:

1. Use the built-in theming feature in Styled Components
1. Use CSS Custom Properties

The benefit of using the last approach is that if we ever get to create a CSS library, we could use them same themes-file. There aren’t a lot of examples of using styled components with css variables in the wild, but I assume that’s mostly because  it’s not supported by Internet Explorer – which is not an issue for us.

**Comment by wenche** [comment]
We have decided to use the second approach with CSS Custom Properties. See example repositories in Area 51 on Github (private) and issue #1118. The work to add theming support for EDS components will mainly be driven by the Energy Vision project.
