### ISSUE TITLE
Table header is center aligned instead of right aligned

### ISSUE THREAD

**Issue by lindsve** [equinor/design-system#407]
**Describe the bug**

I've created a table based on the documented example, but header cells seems to be center aligned instead of right aligned.

<img width="453" alt="Skjermbilde 2020-07-02 kl  14 12 18" src="https://user-images.githubusercontent.com/159861/86357662-785ce600-bc6e-11ea-92ce-c9deeed8600b.png">

**Steps to reproduce the bug**
```
    <Table>
      <Head>
        <Row>
          <Cell as="th" scope="col" width={"240px"}>
            Wellbore
          </Cell>
          <Cell as="th" scope="col" width={"120px"}>
            DtectLoss
          </Cell>
        </Row>
      </Head>
      <Body>
        <Row>
          <Cell>NO 12/34-C-B1</Cell>
          <Cell>OK</Cell>
        </Row>
        <Row>
          <Cell>NO 12/34-C-B2</Cell>
          <Cell>OK</Cell>
        </Row>
        <Row>
          <Cell>NO 34/12-A</Cell>
          <Cell>Alarm</Cell>
        </Row>
      </Body>
    </Table>
```

**Expected behavior**
I expect that the header cells are aligned like the content cells

**Specifications**

- Version: @equinor/eds-core-react: 0.4.0,
- Browser: Microsoft Edge 83.0.478.50
- OS: MacOS 10.15.5

**Comment by vnys** [comment]
Thanks for reporting this, we’ll take a look at it early next week 👍
