### ISSUE TITLE
`size` property for Progress components

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/design-system#417]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like to be able to adjust the size of the `Progress` components, similar to how `Icon`s may be resized.

**Describe alternatives you've considered**

@vnys suggested overriding the style directly, which works well.
The downside, is that I would have to set both the width, and height to ensure the aspect ratio remains constant.

**Additional context**

*Some background*
When the dotted progress "bar" is the main component on a site (e.g. the data for the page is loading), it seemed rather small on a full desktop.

**Comment by mimarz** [comment]
Better late than never! 😅  Sorry for the late reply @sindre-nistad 

We have decided to have a look at this feature soon™️ (#1061) so any more feedback or insight to use-cases would be appreciated 😄

**Comment by mimarz** [comment]
![tenor (1)](https://user-images.githubusercontent.com/1070981/106602313-1c887180-655d-11eb-8331-78ff7467fff1.gif)

We have added `size` option for the progress indicator`Dots`. Current size is the smallest at `32`, with steps up to `48` and `64`.

We have some smaller issues to get done before hopefully releasing this soon :)
