### ISSUE TITLE
Fix eslint errors in Storefront branch

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#418]
These eslint errors must be fixed before merging into develop

## Breadcrumb.jsx
- 44:24  `error`  Elements with ARIA roles must use a valid, non-abstract ARIA role  jsx-a11y/aria-role
- 53:22  `error`  Elements with ARIA roles must use a valid, non-abstract ARIA role  jsx-a11y/aria-role
- 96:46  `error`  Elements with ARIA roles must use a valid, non-abstract ARIA role  jsx-a11y/aria-role

## Card.test.jsx
- 85:11  `warning`  A control must be associated with a text label  jsx-a11y/control-has-associated-label

## TopBar.test.jsx
- 47:11  `warning`  A control must be associated with a text label  jsx-a11y/control-has-associated-label

**Comment by wenche** [comment]
Is this OK @vnys ?

**Comment by mimarz** [comment]
Deprecated
