### ISSUE TITLE
Create documentation for Menu

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#450]
Write documentation for [Menu](https://eds.equinor.com/components/menu/)

**Sub tasks**

- [ ] Write documentation
- [ ] Create examples
- [ ] Add props-table
- [ ] Add live preview

**Comment by mimarz** [comment]
Make sure to provide proper examples for use of Menu, ref #543 , [reply](https://github.com/equinor/design-system/issues/543#issuecomment-688661783)
