### ISSUE TITLE
Create documentation for Typography

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#452]
Write documentation for [Typography](https://eds.equinor.com/components/typography/)

**Sub tasks**

- [ ] Write documentation
- [ ] Create examples
- [ ] Add props-table
- [ ] Add live preview

**Comment by martalalik** [comment]
UX team working on Typography at that moment. So i put this issue on hold.

**Comment by mimarz** [comment]
We will do what we can with the documentation atm. Updating the documentation with potential typography changes will be done in a seprarate task.

This task will implement the new documentation format we have for our stories. This includes converting to mdx, usage example, use decorators, better props table etc...
