### ISSUE TITLE
Centering ghost button icon in Safari/iOS

### ISSUE THREAD

**Issue by khollund** [equinor/design-system#465]
On ghost buttons the icon doesn't get centered in Safari/iOS. Reproduced in the EDS storybook. Fixed by adding margin: 0 auto to the svg. But might be more correct ways to fix. 

**Steps to reproduce the bug**

1. Open a ghost button in Safari
2. Get surprised by the left aligned icon

- Version: 
- Browser: Safari
- OS: Mac OSX and iOS

**Additional context**

![image](https://user-images.githubusercontent.com/25321939/87133739-0a30a880-c298-11ea-8949-25fd2717108f.png)

**Comment by mimarz** [comment]
Thanks for reporting this bug. It seems to be a problem with webkit and how we are using `css-grid`. This bug also occurs on normal button with icon + text. We'll find a fix :)
