### ISSUE TITLE
Tooltip issue with disabled button

### ISSUE THREAD

**Issue by bratli** [equinor/design-system#473]
**Describe the bug**

When adding the tooltip to a disabled button, the tooltip does not seem to appear. (When the button is enabled, the tooltip works as expected.)
I have a row of disabled buttons next to eachother, and sometimes, if I enter the disabled button with the tooltip (lets call it A) from another disabled button, B, the tooltip appears. However, it does not disappear when I leave button A. For it to disappear, I have to leave A by going directly onto button B. (FYI, B does not have a tooltip).

**Steps to reproduce the bug**

1. have two disabled buttons next to eachother, the left with a tooltip from EDS, and the left with no tooltip
2. try to enter the left button from above > no tooltip should appear
3. try to enter the right button, and then from the right button, enter the left button > tooltip should appear
4. leave the left button by leaving to the left > tooltip should not disappear
5. enter left button again, and leave to the right, onto the right button > tooltip should disappear

**Expected behavior**

I expect the tooltip to work on disabled buttons as any tooltip would. If this is not doable/desirable for other users, I would expect it to not have the odd behaviour as described above.

**Specifications**

- Version:  v0.5.1
- Browser: Chrome
- OS: 

**Additional context**

Let me know if you want me to show you :)

**Comment by vnys** [comment]
We’re currently all on vacation, but will take a look at this once we get back first week in August.

**Comment by bratli** [comment]
This is still an issue @pomfrida @equinor/design-system 
Contact me if you want me to show you.
