### ISSUE TITLE
As a designer I need a dark theme for all EDS (desktop) components.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#475]
- [x] Add colors to 'Design Tokens'
- [x] Create dark theme components
- [x] Plan testing
- [x] Publish library for testing
- [x] Make examples
- [x] QA
- [x] Write release note for storefront
- [x] Write release message for Slack/Yammer
- [x] Officially publish library
- [ ] Write documentation

**Comment by benkeq** [comment]
Test no. 2 published in Figma
