### ISSUE TITLE
Create Select components

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#492]
We will create a dropdown/select component for use in EDS

Linked/Dupicate? of US562
We will create a new Select component with two variants: 
* Single 
* Multi

Notable behaviour; 
* Typeahead for filtering options in select. 
* Checkboxes to select and deselect options
* Selected values out of a total will be displayed in the field

**Comment by pomfrida** [comment]
@akvam We should have a concrete design ready before starting to code. Dropdown is complex to create, so a simple dropdown (select) is recommended to start with. Like the one from the [Pagination](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A15) design

**Comment by mimarz** [comment]
Parent for #508 , #510 , #509

**Comment by cbuv** [comment]
I would like to have a EDS design for search inside the dropdown, above the options. 

Microsoft has an example of this in the careers page. 
https://careers.microsoft.com/us/en/c/business-development-strategy-jobs
![image](https://user-images.githubusercontent.com/48285335/92215776-9379eb00-ee95-11ea-9d46-50d9c42419d2.png)

Typeahead in a multiselect which is not text based is extremely hard because we can't have chips inside an input. 
You would need to use a div that imitate an input. Making this accessible with keyboard navigation and mouse (and touch) events is a lot of work. It also has to be cross browser compatibility.

**Comment by mimarz** [comment]
> I would like to have a EDS design for search inside the dropdown, above the options.
> 
> Microsoft has an example of this in the careers page.
> https://careers.microsoft.com/us/en/c/business-development-strategy-jobs
> ![image](https://user-images.githubusercontent.com/48285335/92215776-9379eb00-ee95-11ea-9d46-50d9c42419d2.png)
> 
> Typeahead in a multiselect which is not text based is extremely hard because we can't have chips inside an input.
> You would need to use a div that imitate an input. Making this accessible with keyboard navigation and mouse (and touch) events is a lot of work. It also has to be cross browser compatibility.

Yeah, we are aiming to support typeahead. Due to the complexity of a select, especially from a accessibility point of view we are currently looking into just re-skinning [react-select](https://react-select.com/home) to EDS style 🤔

**Comment by cbuv** [comment]
We already have all building blocks to make a multi select as I suggested, just need a design or guidelines.  The table is also just building blocks in the design system. 

I would think twice to officially support a react-select skin, which itself is a huge hack/workaround. The production minified file is actually larger than both react and react-dom. If a searchable multi-select release in eds is months ahead, I don't see why not having an alternative in figma can be an option.

**Comment by mimarz** [comment]
We recently had a design meeting about this and have added a [Select design ](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=15463%3A1) to Figma, Still missing docs and such, but you can have a look :) 

Yeah, we are still a little bit on the fence on how we are going to implement the `select` in code. It is hacky but the alternative is months of work to maybe make on that work kinda the same. Don't underestimate the small yet complex components 😅

**Comment by cbuv** [comment]
Yeah, that typeahead design is what forces the workaround, either by override styles in a lib or implement from scratch. Have you considered put this react component i a separate package? It is going to add a lot of code in the core-react package.

**Comment by wenche** [comment]
Also a parent for #896  and #897

**Comment by benkeq** [comment]
[Ready for review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17793%3A67) @lucasveil @wenche

**Comment by lucasveil** [comment]
Good for me @benkeq

**Comment by wenche** [comment]
We should consider to show the hover effect inside the options panel as well? In code we use the same as in the Menu. Beyond that it's OK for the 1. version! 👍

**Comment by wenche** [comment]
![Skjermbilde 2020-11-30 kl  11 31 27](https://user-images.githubusercontent.com/1568252/100598870-999a2f00-32ff-11eb-8817-c9b5c9443e78.png)
Like this.

**Comment by benkeq** [comment]
That would be shown in Patterns or Examples I think. The users in Figma would just change the state since all items in the select component are instances of the menu component.
