### ISSUE TITLE
As a EDS User I would like a standard way to mark mandatory information, applying to relevant component as table, text field etc.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#499]
- [x] Make a draft for QA
- [x] Add examples to 'Desktop/Examples' file
- [x] Write documentation

**Comment by benkeq** [comment]
I've tested some different varieties, but landed on 2-4 scenarios based on recommendations from NN/g. If accepted by @lucasveil I will add this to the Patterns file and add it to the storefront documentation. 

I will also add an example on how it should be done in tables, following the same pattern. 

<img width="704" alt="Marking required and optional fields" src="https://user-images.githubusercontent.com/53559062/92489489-20070f00-f1f0-11ea-85fc-b699d9816528.png">
<img width="2344" alt="marking-test" src="https://user-images.githubusercontent.com/53559062/92489498-21d0d280-f1f0-11ea-8259-a2ac1e714639.png">

**Comment by benkeq** [comment]
I've tested some different varieties, but landed on 2-4 scenarios based on recommendations from NN/g. If accepted by @lucasveil I will add this to the Patterns file and add it to the storefront documentation. 

I will also add an example on how it should be done in tables, following the same pattern. 

<img width="704" alt="Marking required and optional fields" src="https://user-images.githubusercontent.com/53559062/92489910-9a379380-f1f0-11ea-8a53-2593c470e8cc.png">
<img width="2344" alt="marking-test" src="https://user-images.githubusercontent.com/53559062/92489920-9c99ed80-f1f0-11ea-8c42-69068b6d28cc.png">

**Comment by benkeq** [comment]
The examples of marking required and optional fields in text fields are added to the Desktop/Examples page. While this US says "table, text field etc.", I'm not sure what etc. would mean. I need to know exactly what components @akvam is thinking about. And since we don't support danger/warning/success validation in tables, I haven't added that to the Examples page. We would need another US to first create new versions of the table component.

**Comment by benkeq** [comment]
Ready for QA @lucasveil 

[This](https://github.com/equinor/design-system/blob/documentation/apps/storefront/docs/components/text-fields/overview.mdx) is the page, and [these](https://github.com/equinor/design-system/commit/b80ad8a6a642ace9c7759ff9d6bb2bee036fa546) are the changes.

**Comment by lucasveil** [comment]
Looking good @benkeq
