### ISSUE TITLE
Create React Select component using native Select

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#509]
Anita Update 02.12.2020
This US has high priority. Not sure why it is on the low pri. milestone. 
Spike US can be done first, if it is needed. 

Create React component for Select. Consider using https://react-select.com/ or other librariers due to complexity of component

**Comment by mimarz** [comment]
blocked by #655

**Comment by wenche** [comment]
We have created [a discussion at Github](https://github.com/equinor/design-system/discussions/861)

**Comment by wenche** [comment]
We decided to split this task:
1. Native select (native version looking as much like the design as possible, but not 100% due to browser constraints)
2. Select (styled version like the Figma design)
3. Advanced version with some sort of search

**Comment by wenche** [comment]
To clarify this split and to avoid this issue to be around until forever and a day, I create separate issues for the more complex variants of select
