### ISSUE TITLE
Create Select page in Storefront

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#510]
Create documentation page for "Select" component in Storefront.
- [x]  Create Select page
- [x]  Make sure navigation is set up for Select page
- [x] Update component list with Select component
- [x]  Write documentation

**Comment by benkeq** [comment]
Update: Select is added to status page, but should be placed in alphabetical order. We also need a page with Overview and Usage to start the documentation process.

**Comment by wenche** [comment]
This currently causes a dead link atm from the component status page as we are linking to a page that doesn't yet exist.

**Comment by wenche** [comment]
The Select page is added in the components menu

**Comment by lucasveil** [comment]
[Example page](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=897%3A1246) ready for review @benkeq @BirteThornquist

**Comment by BirteThornquist** [comment]
Looks good @lucasveil ! Just noticed a small misspelling of 'Panel' in the section Usage/How to use. Maybe also avoid the two colons in a row here...?

**Comment by lucasveil** [comment]
Will update the typo. The text in Figma is only a draft, the documentation will be published in the storefront.
