### ISSUE TITLE
Add alternative filter icon (funnel)

### ISSUE THREAD

**Issue by Brynjulf** [equinor/design-system#545]
**Is your feature request related to a problem? Please describe.**

We are working on using EDS in our project, more specifically we are trying to replace old icons with your icons.

**Describe the solution you'd like**

We want to use the EDS filter funnel icon

**Comment by mimarz** [comment]
Do you have an example? We have the `filter_list` 🤔
![image](https://user-images.githubusercontent.com/1070981/92449317-2aa6b180-f1ba-11ea-8d2c-7568b5901976.png)

**Comment by lucasveil** [comment]
It is for REP product. I am on it.

**Comment by benkeq** [comment]
Have you seen the filter-list icon? Why is there a need for a funnel icon in addition to that?

**Comment by lucasveil** [comment]
After clarification, the funnel icon and filter would have the same functionality. Reason why the team wants to have the possibility to have a funnel icon is that it represents more familiarity (stakeholders are used to this icon as filter option also in other product) and consistency (no need to introduce a new visual) in the product. The question here is if we have 2 icons to show the same functionality, would it be more confusing for users? Or given the context is preferable to use one over the other? As  i checked material design, they use the name "filter_alt" for funnel and "filter_list" for the one EDS uses today.

**Comment by benkeq** [comment]
Understood. It's not easy to predict if it will be more confusing or not. As long as the product itself is consistent the confusion will be reduced, but once one of the users find their way to an app using the other icon, it may contribute to a weaker experience.

**Comment by lucasveil** [comment]
Icon is designed and ready to implement in EDS - Assets:
![Screenshot 2020-09-09 at 16 16 50](https://user-images.githubusercontent.com/65652493/92610352-e699d680-f2b7-11ea-9d53-9a3e98890db9.png)
