### ISSUE TITLE
Menu component prop onClose not called when MenuItem nested inside MenuSection

### ISSUE THREAD

**Issue by oanylund** [equinor/design-system#546]
**Describe the bug**

When a MenuItem is nested inside a MenuSection the Menu components prop onClose is not called when MenuItem fires onClick event.

**Steps to reproduce the bug**

```javascript
it('has called onClose when MenuItem is clicked', () => {
    const handleOnClose = jest.fn()
    const handleOnClick = jest.fn()

    render(
      <Menu open onClose={handleOnClose}>
        <MenuSection title="test">
          <MenuItem onClick={handleOnClick}>Item 1</MenuItem>
        </MenuSection>
      </Menu>,
    )

    const menuItem = screen.getByText('Item 1')

    fireEvent.click(menuItem)

    expect(handleOnClick).toHaveBeenCalled()
    expect(handleOnClose).toHaveBeenCalled()
})
```

**Expected behavior**

Expect handleOnClose to have been called, but it's not.

**Specifications**

- Version: equinor/eds-core-react v0.6.0
- Browser: Chrome 85.0.4183.83 
- OS: Windows 10

**Comment by mimarz** [comment]
Thanks for reporting!

You even added a test for us to use 🤩
