### ISSUE TITLE
Menu component - clicking outside the open menu should enable close menu (not only selecting a menuItem onClick action))

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#548]
**Is your feature request related to a problem? Please describe.**
If a user opens a menu, and decides not to select any of the menuItem options, she wants to close the menu. For example in  material ui she can click anywhere on the screen and the open menu is closed. 

**Describe the solution you'd like**
I would like the same feature as in material ui, that the menu closes  if you click anywhere else but on the menuItems. No further actions are executed.

**Additional context**

**Comment by mimarz** [comment]
Thanks for requesting this feature. We'll have a look in the not to far away future :)

**Comment by oanylund** [comment]
That would be nice. I was about to post a bug on the Menu component relating to this. 
When trying to get a ref to the Menu component to implement this feature i get a React.forwardRef error and the ref stays null.
Maybe worth it's own bug, but I haven't gotten around to reproduce the error.
