### ISSUE TITLE
Refactor Notification Banner to Typescript

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#554]
Create typings for [Notification Banner](https://eds.equinor.com/components/notification-banner/)

Make sure you fork the repository and branch from `typescript` before starting on this issue

**Comment by nicholasdalhaug** [comment]
I would like to do this one

**Comment by mimarz** [comment]
...1,2,3 Sold!

**Comment by mimarz** [comment]
> I would like to do this one

3, 2, 1, Sold! 🎉
