### ISSUE TITLE
Refactor Cards to Typescript

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#557]
Create typings for [Cards](https://eds.equinor.com/components/cards/)

Make sure you fork the repository and branch from `typescript` before starting on this issue

**Comment by jagnani73** [comment]
Can you please elaborate on what this issue is about?

**Comment by vnys** [comment]
First of all – apologies for not replying sooner, we’ve taken steps now to make sure we don’t miss issue comments in the future. We’re on our way to refactor all the components to Typescript, and thought the `<Cards />` component would be a good fit for a Hacktober issue. We have documented a couple of things we have discovered while refactoring other components in [Discussions](https://github.com/equinor/design-system/discussions/521) that might be helpful. Other than that, please take a look at the components that have already been refactored in [the typescript branch](https://github.com/equinor/design-system/tree/typescript). If you decide you want to take on the task, then please make a fork of the repository, and create a branch from the typescript branch. Do you want me to assign it to you?

**Comment by jagnani73** [comment]
I dont think ill be able to take it up now, Maybe after october
I am not participating in hacktoberfest and it would be a waste for someone if you assign it to me right now

**Comment by joelmheim** [comment]
I can take this one.

**Comment by vnys** [comment]
> it would be a waste for someone if you assign it to me right now

We’ve got plenty of issues @jagnani73 so no problem 😉 But you’re welcome to chip in another day, thanks for stopping by!
