### ISSUE TITLE
Refactor Chips to Typescript

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#581]
Create typings for [Chips](https://eds.equinor.com/components/chips/)

Make sure you fork the repository and branch from `typescript` before starting on this issue

**Comment by joelmheim** [comment]
I will start on the typescript conversion if it is ok with you all.

**Comment by mimarz** [comment]
@joelmheim Nice! Just a reminder to branch from the `typescript` branch for this and not `develop`
