### ISSUE TITLE
Adjust line-height for Cell Text

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#589]
Table component needs to be available for multiple line. Line-height needs to be adjusted to 20 px for:

- Cell text
- Cell text bold
- Cell text link
- Cell header

**Comment by mimarz** [comment]
In theory it should be enough to run token export for `base` and `components` to update this for code

**Comment by mimarz** [comment]
@lucasveil Whats the status on this? Saw there was some changes to table typography tokens...

**Comment by lucasveil** [comment]
The design has been updated in Figma. Need to update it in code.

**Comment by mimarz** [comment]
Sweet closing this issue as code tokens will be updated in #824 824
