### ISSUE TITLE
Accordion - compact mode

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#596]
**Is your feature request related to a problem? Please describe.**

Within drilling & well realtime center, the need to see a lot of information in one view. The accordion will be used in a new Rips Order Web solution. However the "airiness" of the component, will force the user to scroll vertically to view the whole dataset. A more compact version would be preferable for these users.

1. First image below is what users are used to today - a snapshot of an expandable tree structure.
2. Second image below is how these data currently are presented in new solution using Accordion.

**Describe the solution you'd like**

A compact mode of accordion
- less air over/under text
- possible change font size

**Describe alternatives you've considered**

**Additional context**
_As is in current application (which will be replaced by new app)_
![image](https://user-images.githubusercontent.com/22211376/92907921-0c44ee00-f426-11ea-8e38-e94c7298c085.png)

_New app - using current version of accordion_
![image](https://user-images.githubusercontent.com/22211376/92908394-78bfed00-f426-11ea-9fe0-de907b88d491.png)

**Comment by mimarz** [comment]
We have added this as a feature of part 2 for compact mode for EDS components #1303

**Comment by mimarz** [comment]
This will be solved by #1750 :)
