### ISSUE TITLE
Table - compact mode - design

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#597]
**Is your feature request related to a problem? Please describe.**

In D&W real time center the users have the need to see a lot of table information (vertically) in the same view.
The "airiness" of the EDS table component will introduce more vertical scroll to view the same amount of data as these users can today view in  "one page" in their current applications ( these are going to be replaced by new web aps using EDS components)

**Describe the solution you'd like**

A more compact mode of the EDS Table component. See example image below 

**Additional context**

Compact mode vs Comfortable mode
![image](https://user-images.githubusercontent.com/22211376/92910708-9b530580-f428-11ea-9c49-ecb7bad2659d.png)
![image](https://user-images.githubusercontent.com/22211376/92910881-c89fb380-f428-11ea-885e-ae774207f34c.png)

**Comment by akvam** [comment]
It is high priority to start on this on the design side. However on the implementation side it  Typescript has now focus, so the timeline there is not easy to estimate.

**Comment by benkeq** [comment]
Add documentation about right-aligning text only containing numbers. Applies to both compact and comfortable tables

**Comment by benkeq** [comment]
[Ready for review](https://github.com/equinor/design-system/commit/1549e4f2f09e8e8697dff980ac70363b03fc5811) @lucasveil
