### ISSUE TITLE
As a EDS Community I would like to have an example application implemented with EDS React components

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#617]
Include these tasks: 
- [ ] Make an example application from one of our design examples (or make a new design example as part of US 540)
- [ ] Readme file to give a short step by step introduction of how to build, what packages to include.

**Comment by BirteThornquist** [comment]
Is this still relevant? Or should we instead include linke to apps in the documentation? Or make better examples in Storybook playground? Closing this issue.
