### ISSUE TITLE
rename icons from "verticle" to "vertical"

### ISSUE THREAD

**Issue by olems** [equinor/design-system#619]
**Describe the bug**

Not a big typo but a lot of icons have "verticle" in their name where it should be "vertical". Should be renamed so people find them when searching, and also before they're in too widespread use.

**Comment by mimarz** [comment]
🙈  Correct grammar is important 😅

@benkeq @lucasveil Looks like copypasta typo in Figma. Can one of you have a look?

Update to `eds-icons`, CDN & storefront should be fine once fixed...

**Comment by benkeq** [comment]
I've seen that myself as well, but didn't recognize that it would create problems. I will update the components :) 

- [ ] Spacings
- [ ] Icons
- [ ] Stepper

**Comment by benkeq** [comment]
Done in Figma @mimarz. Will you close the issue when you have updated eds-icons, etc?

**Comment by mimarz** [comment]
> Done in Figma @mimarz. Will you close the issue when you have updated eds-icons, etc?

Nice👌 Will be resolved in issue #629 once we get to do that 🙈

**Comment by mimarz** [comment]
blocked by #629
