### ISSUE TITLE
Optimize eds-core-react bundle size

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#627]
Bundle size for `eds-core-react` has gotten a lot bigger, 1.8mb with just a few typescript components, expected to increase by much more when done with typescript.

Look at ways to reduce bundle size

~* Bundle all typescript declarations into one file `d.ts` file?~ withdrawn
~* Do we need all modules types still (umd/cjs/es)? Looking at you umd 👀~  withdrawn
* Seperate `.map` files from published and dev bundle

**Comment by vnys** [comment]
I think Storybook uses the UMD module 🤔 Must look into that. But the mapfiles can probably be omitted from production.

**Comment by vnys** [comment]
UMD is needed for the CDN, if someone wants to play around with the components in Codepen for example.

**Comment by mimarz** [comment]
The storybook needs the `.map` file, which makes sense. Was thinking of maybe making some more targeted builds. 

So maybe if we have something like?

* Development: esm, umd, cjs + map files
* Production (or npm?): esm + cjs
* CDN: umd

**Comment by vnys** [comment]
For bundling the type files take a look at [api extractor](https://api-extractor.com/pages/overview/demo_rollup/)

**Comment by mimarz** [comment]
* Using [api extractor](https://api-extractor.com/pages/overview/demo_rollup/) seemed to be buggy with our usage of compound components. **Postponing** this as we might need do other changes for "tree-shaking" of commonjs (like named imports)
* **Leaving umd files as is**, as it works nicely with [unpkg.com](https://unpkg.com/@equinor/eds-core-react@0.6.2/dist/core-react.umd.js) method letting people use it directly in html
