### ISSUE TITLE
Update Icons resources with latest changes

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#629]
- [x] Update eds-icons
- [x] Update storefront icon assets
- [ ] Update CDN svg icon files

resolves #619

**Comment by akvam** [comment]
@mimarz  what US(s) does this block?

**Comment by mimarz** [comment]
> @mimarz what US(s) does this block?

Forgot to add "blocks" comment, but its #619. 

Question is if we should release this with typescript on thursday or as a seperate release after, since its kinda a breaking change (changed name)
