### ISSUE TITLE
Base token export fails

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#630]
**Describe the bug**

Some changes in figma design tokens is breaking export. 

`/create-tokens` crashed when trying to parse a typography token

**Steps to reproduce the bug**

1. Start `figma-broker`
2. Run /create-tokens

**Expected behavior**

Successful token export

**Comment by vnys** [comment]
Possibly related to #589

**Comment by mimarz** [comment]
@benkeq @lucasveil 

Found the issue causing the failed export. When the token was updated for #589. 
The helper "Value info" was moved out of the "ignore" component starting with `.Token`, thus making figma-broker think this is a text token to be extracted.

Moving the " Value info text node back under `.Token row...` will fix this issue.
 
![typography bug](https://user-images.githubusercontent.com/1070981/94239941-d36f4380-ff12-11ea-83a5-ad6034c03ae6.png)

**Comment by benkeq** [comment]
Updated in Figma ✔️ @mimarz

**Comment by mimarz** [comment]
It works! 🕺
