### ISSUE TITLE
Video tutorial for "grid", "placement rules" and "spacing"

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#631]

**Comment by lucasveil** [comment]
First draft is available here: https://web.microsoftstream.com/video/0e656b87-3c5e-46f2-b5bc-8d19a6b1061d?list=studio
Need some general feedback on timing and/or other adjustments @benkeq

**Comment by lucasveil** [comment]
Teksten til video er her: https://statoilsrm.sharepoint.com/:w:/r/sites/Designsystem/_layouts/15/doc.aspx?sourcedoc=%7B249afb6a-6fbb-4570-9f61-d6f4ab2f58f0%7D&action=edit

**Comment by mimarz** [comment]
Is this done maybe? @lucasveil

**Comment by lucasveil** [comment]
Yes is this released in EDS stream channel
