### ISSUE TITLE
Publish storefront updates

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#633]
After #632.

- [x] Publish 'Typography'
- [ ] Publish 'Grid alignment'
- [ ] Publish 'Spacings'
- [ ] Publish 'Placement and order'
- [ ] Publish 'Changelog'
- [ ] Publish documentation for 'variants' (related to #953)
- [ ] Publish 'Select'

**Comment by mimarz** [comment]
Storefront is ready to be published, only [spacings](https://eds-storefront-development.azurewebsites.net/patterns/spacings) looks a bit weird / out of sync with the other pages. What do you think? @lucasveil @benkeq @BirteThornquist
