### ISSUE TITLE
AutoComplete

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#634]
**Is your feature request related to a problem? Please describe.**

The userStory is to create a list of contact persons, primarily with equinor colleagues with name/email/phone.  By using the microsoftGraph api, it is possible to search for equinor employees in order to get correct name/email/phone.

**Describe the solution you'd like**

An EDS Autocomplete component and updated EDS TextField component to work in a similar way as material-ui  Autocomplete see code exampl https://codesandbox.io/s/d07uv?file=/demo.js  with the EDS design style

**Describe alternatives you've considered**

Current alternative used is  material-ui Autocomplete and Textfield, used with default material ui styling

**Additional context**
Example on current use of material-ui autocomplete
![image](https://user-images.githubusercontent.com/22211376/94549733-f1aaab80-0252-11eb-807f-c26aa1dd970f.png)
![image (2)](https://user-images.githubusercontent.com/22211376/94549771-0129f480-0253-11eb-87e3-655f14ee8ffa.png)

**Comment by wenche** [comment]
Hi @marmid74  

Check out the [new release of eds-core-react](https://github.com/equinor/design-system/releases/tag/eds-core-react%400.8.0) to see if the new `<SingleSelect>` component will float your boat 👍

**Comment by wenche** [comment]
I'm closing this issue as the Select component should solve the issue.
