### ISSUE TITLE
Communication around video (yammer & slack)

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#644]
Videos for grid, spacing and placement are published on stream: https://web.microsoftstream.com/group/204b36ea-ba52-4cee-aeac-895f675e91b0

**Comment by lucasveil** [comment]
Need to know in which yammer channel it should be posted @vnys @akvam

**Comment by vnys** [comment]
_I propose posting in these channels:_
- Digital At Equinor
- Software Development
- GBS IT Software Innovation
