### ISSUE TITLE
Pagination component generates react warning on first and last component

### ISSUE THREAD

**Issue by oanylund** [equinor/design-system#647]
Get a react warning when Pagination reaches first or last page.

The bug in console from react:
"Expected `onClick` listener to be a function, instead got `false`."
"If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead."

**Steps to reproduce the bug**

1. Use the Pagination component and look in console. 
2. Click on first or last page.
3. Will happen each time activePage < 1 or activePage > pages

**Expected behavior**

Expect not to get any warnings from component.

**Specifications**

- Version: 0.6.0
- Browser: Chrome
- OS: Windows

**Additional context**

Add any other context or screenshots about the bug.
![image](https://user-images.githubusercontent.com/16743890/95199741-9726c780-07dd-11eb-82fc-0cdc55b6274c.png)

Fix will probably be changing from conditionally omit to ternary in these two places:
https://github.com/equinor/design-system/blob/develop/libraries/core-react/src/Pagination/Pagination.jsx#L117-L120
https://github.com/equinor/design-system/blob/develop/libraries/core-react/src/Pagination/Pagination.jsx#L158-L161

Before:
```javascript
activePage > 1 && ((event) => { onPageChange(event, activePage - 1) })
```

To:
```javascript
activePage > 1 ? ((event) => { onPageChange(event, activePage - 1) }) : undefined
```

**Comment by mimarz** [comment]
Thanks for reporting @oanylund ! 

We'll try to have a look at it asap.

**Comment by vnys** [comment]
Thanks for bringing this to our attention! I remember seeing [Kent C. Dodds warn about using the conditionally omits](https://twitter.com/kentcdodds/status/957613270667378690?lang=en) instead of ternary operators – so this obviously proves his point.
