### ISSUE TITLE
As a Product Owner I need the target scope of EDS Select component to be defined, so this can guide good solutions when creating the component in React

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#652]
Resolves #492

**Comment by benkeq** [comment]
Can you please explain this US a bit better?

**Comment by akvam** [comment]
This US covers: 

Define the scope of the Select Component both for Figma Component and the React implementation. 
Coordinate with developers to see if it is “not to hard” to make “the defined scope” this in React. Invite me to the discussion if there is a cost / value issue. 
When the scope is define: 
Make sure all these scenarios have examples in Figma and are described in StoreFront. 

My initial thinking on the scope is:
Single Select, with “filter”
Multiple Select, with “filter”
