### ISSUE TITLE
Spike usage of react-aria

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#655]
Closed. Will be solved as part of #164 

Edit: 
In order to help us decide whether or not to offer complex React components a developer must build a select component using React Aria so that we can see if this approach makes it easier and more time efficient to build complex components that meet WCAG 2.1 requirements

[Select and multiselect](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=7%3A2):

**Definition of done**

- [ ] User can filter items
- [ ] User can select multiple items

**Comment by mimarz** [comment]
Blocks #509

**Comment by wenche** [comment]
For the select case, we decided to start with a simple native select and than move on with this spike. Moving to `waiting` for the time being
