### ISSUE TITLE
Design of video section in storefront

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#656]

**Comment by lucasveil** [comment]
Her er [linken](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=606%3A17199) til utkast i figma @benkeq

**Comment by benkeq** [comment]
Looks good to me. Hører du med devs om det er greit å få til dette i storefronten?

**Comment by vnys** [comment]
We need to add a video player component to the storefront, that should be a separate issue linking to this one.

**Comment by mimarz** [comment]
> We need to add a video player component to the storefront, that should be a separate issue linking to this one.

... We already have a video component on storefront 🤪

**Comment by vnys** [comment]
…then we should be good to go 😊
