### ISSUE TITLE
Align Table-component with the rest of the components

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#672]
Don't use table.json file. Do not have tests

Update: table.json file is removed.

**Comment by mimarz** [comment]
Whats the matter with `table.json`? 🙈 @wenche

**Comment by wenche** [comment]
Did I misunderstand the conclusion? Thought you would like to use js instead

**Comment by mimarz** [comment]
> Did I misunderstand the conclusion? Thought you would like to use js instead

We should still use the table token, but convert it to `js` or `ts` with some defined types for ease of use 😅

**Comment by wenche** [comment]
> > Did I misunderstand the conclusion? Thought you would like to use js instead
> 
> We should still use the table token, but convert it to `js` or `ts` with some defined types for ease of use 😅

Whatever floats your boat! 😅

**Comment by mimarz** [comment]
This might be a duplicate. Maybe update issue #297 with the new changes we have uncovered that needs to be done?
