### ISSUE TITLE
Conform popup logic

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#673]
* Menu
* Popover
* Tooltip

These componenets are all using seperate implementations of logic for attaching and popping up on an anchor element. 

Find a way to conform this logic using a popover hook.

Notes:
* https://reactjs.org/docs/portals.html
* https://medium.com/better-programming/create-a-tooltip-component-using-react-hooks-cb9fd00a2ff0
* https://www.npmjs.com/package/react-popover-hook
* https://github.com/popperjs/popper-core

Features:
* Requested feature for popup placement #952
* Related feature #984 that could be fixed

**Comment by mimarz** [comment]
blocked by #887

**Comment by wenche** [comment]
See #719  as well
