### ISSUE TITLE
AccordionItem - feature to toggle isExpanded outside the component - possible Octoberfest item?

### ISSUE THREAD

**Issue by marmid74** [equinor/design-system#677]
**Is your feature request related to a problem? Please describe.**

In our application we have an Accordion table which is default collapsed at initial render. However we want to toggle isExpanded when the user starts to fill in a filter search string.
Initial render:
![image](https://user-images.githubusercontent.com/22211376/96085718-7dfad680-0ec1-11eb-82a3-bd97c1e5578e.png)

**Describe the solution you'd like**

Render and set AccordionItem to isExpanded when entering a filter search string.
We wish to toggle "isExpanded" when user enters a filter search string.
![image](https://user-images.githubusercontent.com/22211376/96085825-ae427500-0ec1-11eb-90f7-5ade1714f305.png)

**Additional context**

This feature could be suitable as an OctoberFest issue

**Comment by vnys** [comment]
Thanks for the feature request, being able to control the accordion from the outside from a query param or url segment has been discussed previously, so that’s another use case that would be solved by adding this feature. If it’s a good _first_ issue is another discussion 😉 Would you be willing to have a look at it yourself if we make this a hacktober-issue?

**Comment by marmid74** [comment]
Vi gjør et forsøk :-)

**Comment by imp-dance** [comment]
If I understand correctly, this can be solved by adding a useEffect to **[AccordionItem.jsx](https://github.com/equinor/design-system/blob/develop/libraries/core-react/src/Accordion/AccordionItem.jsx)** : 

```jsx

React.useEffect(() => {
   setExpanded(isExpanded)
}, [isExpanded]);

```

Which would allow users to programatically change the `isExpanded`-prop on demand. 

This would be my first contribution, so if you guys think this is a decent solution then I can submit a pull request from my fork.
