### ISSUE TITLE
Adding style to `Cell` seems to remove existing styles

### ISSUE THREAD

**Issue by lindsve** [equinor/design-system#707]
**Describe the bug**

When adding style to a `Cell` component using styled-components, existing styles seem to be removed/replaced

```
const FixedWidthCell = styled(Cell)`
  width: 100px;
  min-width: 100px;
`
```

Example codesandbox: https://codesandbox.io/s/mystifying-cache-57jv3

**Steps to reproduce the bug**

1. Apply custom style to a `Cell` component like the above snippet/codesandbox

**Expected behavior**

In this case, a fixed width `Cell` component with a width of 100px and with original styles applied (font/color/..)

**Specifications**

- Version: 0.6.2
- Browser: MS Edge 86.0.622.43 
- OS: MacOS 10.15.7

**Comment by vnys** [comment]
This bug has to do with the combination of overriding styles and using the as-prop at the same time. So if I have a component that looks like this: 

```jsx
const StyledComponent = styled.div`
  background: lime;
  font-weight: 900;
`
export const SomeComponent = ({ className = '', children }) => (
  <StyledComponent className={className}>{children}</StyledComponent>
)
```

…and I extend that component somewhere else with 

```jsx
import { SomeComponent } from '@equinor/eds-core-react'

const StyledSomeComponent = styled(SomeComponent)`
  background: deeppink;
`

export default {
  title: 'Components/SomeComponent',
  component: SomeComponent,
}

export const SomeStory = () => (
  <>
    <SomeComponent>Tjobing!</SomeComponent>
    <StyledSomeComponent as="p">Tjobang!</StyledSomeComponent>
  </>
)
```

…then you would expect `StyledSomeComponent` to have the styles `font-weight: 900; background: deeppink;` but what happens instead is it looses the original styles. So not solved yet, but working on it.

**Comment by vnys** [comment]
Turns out this is a know bug in Styled Components. There _is_ a workaround, but it’s not very pretty. In the case above, it works as expected if I do it like this: 

```jsx
import { SomeComponent } from '@equinor/eds-core-react'

const StyledSomeComponent = styled(SomeComponent).attrs({ as: 'p' })`
  background: deeppink;
`

export default {
  title: 'Components/SomeComponent',
  component: SomeComponent,
}

export const SomeStory = () => (
  <>
    <SomeComponent>Tjobing!</SomeComponent>
    <SomeComponent as={StyledSomeComponent}>Tjobang!</SomeComponent>
  </>
)
```

**Comment by vnys** [comment]
After doing some more digging, this can be solved by using the [forwardedAs](https://styled-components.com/docs/api#forwardedas-prop) prop. So all you need to do then is to replace  `<StyledSomeComponent as="p">Some text</StyledSomeComponent>`  
with  
`<StyledSomeComponent forwardedAs="p">Some text</StyledSomeComponent>`

**Comment by vnys** [comment]
I originally wrote something about a workaround, which I deleted to avoid confusion when I discovered the `forwardedAs` prop, but on second thoughts I think it should remain as part of this discussion. So the code below will work, but it’s a cumbersome workaround and not really recommended.

```jsx
import { SomeComponent } from '@equinor/eds-core-react'

const StyledSomeComponent = styled(SomeComponent).attrs({ as: 'p' })`
  background: deeppink;
`

export default {
  title: 'Components/SomeComponent',
  component: SomeComponent,
}

export const SomeStory = () => (
  <>
    <SomeComponent>Some text</SomeComponent>
    <SomeComponent as={StyledSomeComponent}>Some text</SomeComponent>
  </>
)
```
