### ISSUE TITLE
Tests fail due to `..` imports

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#708]
**Describe the bug**

Imports are `undefined` in tests, most likely because ts-jest can’t handle `..` imports.
 
**Steps to reproduce the bug**

1. Run `pnpm run test:core-react`

**Expected behavior**

Tests should not fail unless there are bugs in the code

**Specifications**

- Version: 0.6.2
- Browser: Terminal
- OS: macOS

**Comment by mimarz** [comment]
Quick look, we have a few components which uses `..` imports... 
![image](https://user-images.githubusercontent.com/1070981/96550961-e24adb00-12b1-11eb-9eec-68cf7b38515b.png)
