### ISSUE TITLE
Clean up use of spacings in Card/CardMedia

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#717]
` tokens.spacings.left` is passed and used for left, right and top spacings in `Card.CardMedia`, aswell as being passed as a prop to the "styled" component, which it doesn't need to...

This needs to be cleaned up to avoid bugs and errors if spacings are changed in tokens/figma in the future.

* Use the correct top, left, right, bottom spacings tokens in css.
* Remove spacing as prop for "styled" component

**Comment by nicholasdalhaug** [comment]
I want to try this one!
