### ISSUE TITLE
Conform close logic across components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#719]
Conform components that can be dismissed to having the same "api" and behaviour.

Examples of behavoiur:

* Close on click outside of component?
* Callback with `onClose` when closed is triggered?
* Should they have a `isDismissable` to toggle "close" features ( click outside, close button/action, disappear after x amount of time ). If they have a `isDimisssable` prop, it should have an `onClose` callback which is called.
* Disappear after x amount of time?

Relevant components:

- [x]  Menu
- [x] Popover
- [x] Dialog
- [x] Scrim
- [x] Tooltip (?)
- [x] Snackbar (?)
- [x] Sidesheet

Other notes:

* We have a hook for `outsideClick` which should be used when this feature is needed

**Comment by pomfrida** [comment]
Now both `Menu` & `Popover` have `useOutsideClick` hook #1113 
`Tooltip` close logic is controlled outside of the component.

**Comment by pomfrida** [comment]
`isDismissable={false}` or any choice to disable `useOutsideClick` on Popover would also solve feature request #754 👍

**Comment by mimarz** [comment]
# Analysis of properties and behaviour

✅  has property. 
❌ not applicable. 
⚠️ should maybe have property. 

## Snackbar

✅ open (visibility triggered from outside)  
✅ onClose  
❌ isDismissable

## Scrim

⚠️ open (users must inline component)
✅ onClose  
✅ isDismissable

## Dialog

⚠️ open (users must inline component)  
⚠️ onClose  
❌ isDismissable

## Popover

✅ open (visibility triggered from outside)  
✅ onClose  
⚠️ isDismissable

## Menu

✅ open ((visibility triggered from outside)  
✅ onClose  
❌ isDismissable (outside click hides menu)

## Tooltip

✅ open (visibility triggered from outside)  
❌ onClose  
❌ isDismissable

**Comment by pomfrida** [comment]
We agreed that `Menu`, `Tooltip` and `Popover` has conformed close logic for next release (v0.10.0). 
A few improvements are needed on `Scrim` (#1176) and `Dialog` (#1177), but not prioritised at the moment.
