### ISSUE TITLE
As a developer I need the stories to be migrated to typescript for the prop tables in Storybook to work

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#735]
Add a tick when you _start_ on a component so it's easier to see what other people are doing
- [x] Accordion
- [x] Avatar
- [x] Banner
- [x] Breadcrumbs
- [x] Button
- [x] Card
- [x] Chip
- [x] Dialog
- [x] Divider
- [x] Icon
- [x] List
- [x] Pagination
- [x] Popover
- [x] Progress
- [x] Scrim
- [x] Search
- [x] Selection controls
- [x] SideSheet
-  [x] Slider
- [x] Table
- [x] TOC
- [x] Textfield
- [x] Tooltip
- [x] Top bar
- [x] Typography
- [x] Tabs
- [x] Snackbar
- [x] Menu

**Comment by mimarz** [comment]
I'll take Typography

**Comment by pomfrida** [comment]
Accordion ✋
