### ISSUE TITLE
Icon shrinks if placed in flexbox container with other content

### ISSUE THREAD

**Issue by SvSven** [equinor/design-system#749]
**Describe the bug**

The SVG element that is produced by the `<Icon />` component sometimes shrinks in width when it's placed in a flexbox container with other content, if the other content exceeds the width of the container.

For example:

![image](https://user-images.githubusercontent.com/7661362/97178731-336a3b80-1798-11eb-942f-6f3a2f26e9a8.png)

**Steps to reproduce the bug**

See: https://codesandbox.io/s/angry-hellman-nz36p?file=/src/App.js

**Expected behavior**

The width and height attributes should be respected.

**Additional context**

Wrapping the icon in a div with a set width seems to fix the issue, for example:

```jsx
<li>
  <div style={{ width: '24px', display: 'inline-box' }}>
    <Icon name="error_outlined" />
  </div>
  <span>This is a long piece of text here.</span>
</li>
```

Not sure if that's an ideal solution however.

**Comment by SvSven** [comment]
Adding a `width: 100%` to the span in my example seems to fix it as well. Not really sure why, since just changing it to for example a `div`, or adding `display: block` does not fix it 🤔

**Comment by mimarz** [comment]
Its fixable if you apply `flex-shrink` to `svg` in `ListItem`.

```css
  svg {
    flex-shrink: 0;
  }
```

Question is if we should force flex stuff inside `<Icon/>` or not tho 🤔

**Comment by SvSven** [comment]
Ah I thought that having a fixed width and height overruled `flex-shrink` and `flex-grow` 🤔 

My particular use case was to vertically align the icon with accompanying text - which seems like it would be a fairly common use case. But if this is the default behaviour then it should _probably_ not be overwritten by the library? I guess it depends on how opinionated the EDS should be.
