### ISSUE TITLE
Conform on sub-components

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#755]
* Do we still want sub-components to be exposed on parent or on the same level as the rest... (latter is breaking change)
* Sub-components naming with or without "parent"; `const { Actions, Header, CustomContent } = TopBar` vs `const { BannerIcon, BannerMessage, BannerActions } = Banner`

**Comment by wenche** [comment]
This one should be solved and can be closed?

**Comment by mimarz** [comment]
solved by #1088
