### ISSUE TITLE
Convert Buttons to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#762]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Test to see if moving of components from Secondary, Danger, and Disabled to Primary does and breaking changes for users of the library (if so, create a new issue for solving this problem)
- [x] Combine Primary, Secondary, Danger, and Disabled
- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_Color:_ `Primary`/`Secondary`/`Danger`
_State:_ `Enabled`/`Focus`/`Hover`/`Pressed`/`Loading`/`Disabled`
_Variant:_ `Contained`/`Outlined`/`Ghost`/`Ghost Icon`
_Icon:_ `None`/`Leading`/`Trailing`

**Comment by benkeq** [comment]
Vil du ta en sjekk når du har tid, @lucasveil ? Bare dra ut et instance fra component settet, test litt, også slett eller angre det du har gjort.

**Comment by lucasveil** [comment]
Looking really good @benkeq
