### ISSUE TITLE
Convert Accordion to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#763]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
Ready for review @benkeq

**Comment by benkeq** [comment]
Rename "Action" to "Icon placement", and reorder and rename the alternatives so that "Left is first, Right is second, and Dual is third"

**Comment by lucasveil** [comment]
Ready for new review @benkeq

**Comment by benkeq** [comment]
Good to go :)
