### ISSUE TITLE
Convert Buttons Toggle to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#764]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_State:_ `Enabled`/`Focus`/`Hover`/`Pressed`
_Active:_ `True`/`False`
_Icon:_ `True`/`False`
_Alignment:_ `Left`/`Center`/`Right`

**Comment by lucasveil** [comment]
Little bit confused to have "active" to have "outline" state. Maybe recall the variant from active to outline to make it more clear  @benkeq? (just a suggestion)

**Comment by benkeq** [comment]
The names over the frame is changed from "Contained" and "Outlined" to "Active" and "Inactive" now. I just forgot to update it. The variants were called contained and outlined until now, but since we in the documentation explains that contained=active, and outlined=inactive, I thought it would be better to have "Active" as a property.
