### ISSUE TITLE
Convert Cards to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#765]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
Ready for review @benkeq 
I had to rename all the layer for "Title" in order to have a functional variant. If you can double ckeck if i did it right.

**Comment by benkeq** [comment]
It may be best to take a Teams call to solve this.

**Title**
- I would use Ubuntu Mono Medium outside the component sets (as you have done with Container, Rich media, and Supplemental actions) 
- I would place the components horizontally instead of vertically. In other component sets we have placed states in the vertical axis, and variants/styles horizontally. 
- Change "Size" in Title to "Heading size", and reorder the alternatives (H4 on top, H6 on bottom)
- Use letter casing for all variants (True, False instead of true, false; Caption instead of caption, and so on)
- Remove - from "body-short", and just call it "Body short"
- Maybe we need to add more variants to the Title-component set, so that there's all the possible variants? 

**Rich media**
- Reorder the alternatives (Leading image first, Middle second, Last third)

**Supplemental actions**
- Rename "Actions" to "Action type"
- Two of the Ubuntu labels are called "Icons" when they should be called "Meta"

**Comment by lucasveil** [comment]
Ready for review @benkeq 
After meeting:

- aligned all the variants on 1 line,
- named all variants with title,
- set 240 px width between each variant

**Comment by benkeq** [comment]
LGTM :)
