### ISSUE TITLE
Convert Chips to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#766]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_Remove icon:_ `True`/`False`
_Custom icon:_ `True`/`False`
_Avatar:_ `True`/`False`
_Selected:_ `True`/`False`
_Error:_ `True`/`False`
_State:_ `Enabled`/`Disabled`/`Focus`/`Hover`/`Pressed`

**Comment by lucasveil** [comment]
Looking good. The text resets when we switch to dark mode. Probably a Figma system issue but wanted to remind it so we don't forget to mention it when deployed :)

**Comment by benkeq** [comment]
Yes, good catch. That's still a bug that is reported every day by the community 😆 Closing the issue.
