### ISSUE TITLE
Convert Date picker to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#767]
[Save until onboarding]

[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [ ] Add documentation link

This can be designed by making all the `Day` and `Period` components into a variant, and change the name of the component set to ".Date" or something similar. After that another variant is created out of the date picker itself. This method allows the user to insert a date picker, and easily change the variants of the dates in the calendar.

Variant properties for `date picker`:
_Dark theme:_ `True`/`False`

Variant properties for `date:`
_Dark theme:_ `True`/`False`
_Today:_ `True`/`False`
_Position:_ `Single`/`Left period`/`Center period`/`Right period`
_Selected:_ `True`/`False`
_State:_ `Enabled`/`Disabled`/`Hover`/`Pressed`/`Focus`

**Comment by benkeq** [comment]
Moved back to **To do** to save it for onboarding of new designer.

**Comment by BirteThornquist** [comment]
Ready for review @lucasveil

**Comment by lucasveil** [comment]
Good to go @BirteThornquist
