### ISSUE TITLE
Convert App launcher to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#769]
[Save until onboarding]

[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link
Create the same way as date picker

**Comment by BirteThornquist** [comment]
Ready for review @benkeq @lucasveil

**Comment by lucasveil** [comment]
I would have written the state next to app buttons. Other than date, ready to go for me @BirteThornquist

**Comment by benkeq** [comment]
LGTM :) Remember to tick the checkbox in the issue @BirteThornquist

**Comment by BirteThornquist** [comment]
State written and checkbox ticked @lucasveil @benkeq
