### ISSUE TITLE
Convert Navigation drawer to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#771]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
When I resize horizontally "child" the icon follows well but for "parent" and "grand parent" the icon doesn't follow the resize. The same happens for "Listing". Not sure if it is intentional.
Otherwise good to go @benkeq
