### ISSUE TITLE
Convert Pagination to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#772]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_Range and total:_ `True`/`False`
_Range select:_ `True`/`False`

**Comment by lucasveil** [comment]
In Dark Mode, the Pagination doesn't resize properly when range and range select is activated @benkeq

**Comment by benkeq** [comment]
Ready for another review @lucasveil

**Comment by lucasveil** [comment]
Perfect
