### ISSUE TITLE
Convert Table of Contents to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#773]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
Ready for review @benkeq

**Comment by benkeq** [comment]
Fixed, but I would always name variants with a "normal mixed casing/sentence casing", so instead of true/false, I would use True/False. Also in that order, positive first, negative second. 

I also had to adjust some of the text set in Ubuntu to make it centered. 

Other than that, looks good :) You can close the issue.
