### ISSUE TITLE
Convert Top Bar to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#775]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_With navigation:_ `True`/`False`

**Comment by lucasveil** [comment]
If "with navigation" is false, i would recommend to set the "Application name - Subtitle" on the left (starting where the icon should be) such as there is no empty space @benkeq

**Comment by benkeq** [comment]
This has been redesigned before. There are some issues with alignment in the top bar in context with navigation drawer. This might be something we would have to look at later. I'm creating a new issue. @lucasveil 

Other than that, good to go?

**Comment by lucasveil** [comment]
Good to go :)
