### ISSUE TITLE
Convert Dialog to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#777]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_Variant:_ `Text + actions`/`Placeholder + actions`/`Placeholder`/`Scrollable placeholder + actions`/`No title + text + actions`

**Comment by lucasveil** [comment]
Looking good @benkeq
