### ISSUE TITLE
Convert Popover to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#780]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_Caret direction:_

**Comment by lucasveil** [comment]
Looking good!

Extra ❤️  for this one:
![Screenshot 2020-11-17 at 10 50 41](https://user-images.githubusercontent.com/65652493/99374373-ccd1cc80-28c2-11eb-9096-de4c20cf984e.png)

**Comment by benkeq** [comment]
❤️ Thanks. If you find any other places where it would be nice with emojies, feel free :)
