### ISSUE TITLE
Convert Search to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#781]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
Ready for review @benkeq

**Comment by benkeq** [comment]
I think that we maybe should split them into two variants; "Search" and "Scope". Scope does still have an unclear description, but I still think it would be better with two component sets.

**Comment by lucasveil** [comment]
Ready for new review @benkeq

**Comment by benkeq** [comment]
Corrected "True/False".

I also changed the order of the state-variants. I know that it's set up in the same order as in the frame, but I disagree with that order, so I would always put it in the order a user would do an action. Enabled, Focus, Hover, Active, Filled in this case. (Check text fields for instance). 

I also moved the component sets 33px up so that it's 120px from the contributor-card. 

All of this is changed, so the issue is solved and can be closed 👍
