### ISSUE TITLE
Convert Side sheet to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#784]
Blocked by #918 and #928

[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link
- [x] Test to see if it's possible to solve #263 with variants. 

Variant properties:
_Dark theme:_ `True`/`False`
_Width:_ `Small`/`Medium`/`Large`/`X Large`

**Comment by lucasveil** [comment]
Ready for review @benkeq 
Didn't have enough informations to solve #263. Wants a user to use all types of H in headlines?

**Comment by lucasveil** [comment]
Variants are ready for review @benkeq 
Was unsure how to deal with components that looks the same in single / multi. 
Also, didn't find any related documentation in the storefront

**Comment by benkeq** [comment]
Since you've got a lot of tasks, and the rest is for onboarding, do you want me to take this? @lucasveil

**Comment by lucasveil** [comment]
Go for it @benkeq :)

**Comment by benkeq** [comment]
Waiting for typography meeting regarding #263

**Comment by mimarz** [comment]
blocked by #918

**Comment by benkeq** [comment]
Since it's blocked by #918 and #928, this will probably not be solved until late December, or next year. I'm removing myself as assignee. 

I think the best solution to this issue and #263  is to create new variants with other heading sizes. This will result in 8*x where x is how many different sizes we would like to offer. If all heading sizes are made available, we would have 56 variants, but I think it's better to choose a few.

**Comment by nilsml** [comment]
Not relevant anymore
