### ISSUE TITLE
Convert Slider to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#785]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link
- [x] Test out nested variants (Stepper as main. Dot, handle, indicator, and track as nested)
- [x] Divide into 4 different component sets (dot, handle, indicator, and track)

Variant properties:
`Dark theme` and `state`

**Comment by lucasveil** [comment]
Looking good!
