### ISSUE TITLE
Convert Table to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#787]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link
- [x] Combine Table and Table compact with property "Density" and variants "Compact" and "Comfortable"
- [x] Divide into "Header" and "Cell" (test nested variants)

Variant properties:
_Dark theme:_ `True`/`False`
_State:_ `Enabled`/`Active`/`Active Resting`/`Focus`/`Hover`/`Pressed`/`Disabled`/`Error`/`Error Resting`
_Variant:_ `Icon`/`Left aligned`/`Right aligned` (for headers), `Icon`/`Text`/`Monospaced`/`Placeholder`/`Input` (for cells)
_Density:_ `Default`/`Compact`

**Comment by lucasveil** [comment]
In Figma, i would have written title on the top of the variants frame "Header" and "Cell". Thinking about a new user that is not used to have 2 style of variant in a Figma file.

For header, text don't go to the line when it goes outside the box. It does it today with the current version.
![Screenshot 2020-11-17 at 10 27 35](https://user-images.githubusercontent.com/65652493/99372056-f6d5bf80-28bf-11eb-8f70-9d3958bfb40c.png)

Quick question. If a user wants to have the whole row in red in a tab and has an icon in the middle of the row, then the state error for icon is not available. Should we implement it?
![Screenshot 2020-11-17 at 10 35 21](https://user-images.githubusercontent.com/65652493/99372553-9eeb8880-28c0-11eb-888f-c17994c1a74b.png)

**Comment by benkeq** [comment]
I agree with your first point. Will add that 👍 

The line doesn't break into mulitple lines today. I think you might think of table cells? Table headers should always be a single line, if this is going to be changed there has to be added another issue.

And yes, I don't know why it's not been added yet? Will add that as well, and notify you when it's ready for another review.

**Comment by benkeq** [comment]
Ready for another review @lucasveil

**Comment by lucasveil** [comment]
Good to go @benkeq
