### ISSUE TITLE
Convert Text fields to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#788]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

Variant properties:
_Dark theme:_ `True`/`False`
_State:_ `Enabled`/`Active`/`Filled`/`Read only`/`Disabled`/`Focus`/`Hover`
_Validation:_ `None`/`Error`/`Warning`/`Success`
_Multiline:_ `True`/`False`

**Comment by lucasveil** [comment]
Shouldn't the helper text be a variant "enable icon" @benkeq

**Comment by benkeq** [comment]
As you've already explained on Slack, this would have created double the amount of variants, as well as it would create breaking changes for our users. In a perfect world, we would have it as a variant.
