### ISSUE TITLE
Convert Tooltip to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#790]
[Save until onboarding]

[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [ ] Add documentation link
Make it the same way as [popover](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=792%3A823)

**Comment by BirteThornquist** [comment]
Ready for review @benkeq @lucasveil

**Comment by benkeq** [comment]
Good job! I don't know what's the best order out of Popover and Tooltip regarding the "Caret direction". That's up to you and @lucasveil to find out, and whatever is the preferred way, change the other component to that as well so that they have the same order. 

Another thing I would consider is to make this into an auto layout component. That should be an issue for itself though :)

**Comment by lucasveil** [comment]
Nice! For me the order is good. It follows the common reading pattern.

**Comment by BirteThornquist** [comment]
Regarding the order I think we should change the popover to match the headings
