### ISSUE TITLE
Convert Divider to Variants

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#791]
[Variants in Figma](https://help.figma.com/hc/en-us/articles/360055471353-Prepare-for-Variants)

- [x] Add documentation link

**Comment by lucasveil** [comment]
Ready for review @benkeq

**Comment by benkeq** [comment]
Teksten til "Small" og "Medium" på Light theme står litt høyt oppe i forhold til komponentet. Det gjør ingenting mtp. komponentet, så issuen er her good to go. Du kan dra ut to instances av komponentene, for så å sentrere label med hjelp av de. @lucasveil
