### ISSUE TITLE
Remove unnecessary files from npm module

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#82]
The npm module `@equinor/eds-core-react` contains debug, config and src-files which could be added to .npmignore.

**Comment by mimarz** [comment]
I think this is also already been solved? @vnys @wenche @pomfrida ?

**Comment by mimarz** [comment]
related to #627 ?

**Comment by mimarz** [comment]
Quick test shows that we don't have anymore unwanted files in `core-react` npm package. Closing issue.

![image](https://user-images.githubusercontent.com/1070981/104884535-cfa27980-5966-11eb-935f-fc69f09ae05a.png)
