### ISSUE TITLE
Set up beta/next release for typescript

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#822]
- [x] Set `link-workspace-packages = false` in `.npmrc`
- [x] Publish beta/next release
- [x] Create a CRA app in `/app/` and test the published components
- [x] Draft an announcement for Slack

**Comment by wenche** [comment]
@vnys have created 3 releases:

- `@equinor/eds-tokens: 0.5.1-beta.1`
- `@equinor/eds-icons: 0.5.0-beta.1`
- `@equinor/eds-core-react: 0.7.0-beta.1`

**Comment by pomfrida** [comment]
✔️  Posted announcement on the EDS Slack community and created a [Github discussion](https://github.com/equinor/design-system/discussions/867) to collect test reports
