### ISSUE TITLE
Decide on compact mode component api

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#823]
How do users or developers trigger compact mode on components which support this? 

Food for thought
* Do we have a boolean prop which triggers compact mode for the respective component
* Or do we have a global variable which triggers compact mode for all components
* Or some additional context switcher on the component for users to decide mode

**Comment by mimarz** [comment]
blocks #811

**Comment by wenche** [comment]
MUI's approach
![Skjermbilde 2020-12-17 kl  08 49 38](https://user-images.githubusercontent.com/1568252/102459171-8ac4b380-4045-11eb-85bb-aa4e8dfd8443.png)

**Comment by wenche** [comment]
We discussed this on today's standup.

In Figma it's designed as a boolean at component level. This feature is located in the top menu. We decided to keep it as simple as possible for the time being, and add a prop density on the `<Table>` component.

**Comment by wenche** [comment]
![Skjermbilde 2020-12-17 kl  10 14 01](https://user-images.githubusercontent.com/1568252/102467581-c022ce80-4050-11eb-8034-740b715860b4.png)

**Comment by mimarz** [comment]
> We discussed this on today's standup.
> 
> In Figma it's designed as a boolean at component level. This feature is located in the top menu. We decided to keep it as simple as possible for the time being, and add a prop density on the `<Table>` component.

`density` sounds good. Suggest we have atleast ` "comfortable" | "compact"` as values. A `"default"`value could be applicable so that users can save the preference in the localstorage or so, but maybe save that for later 🤪
