### ISSUE TITLE
As a developer using EDS I need EDS to conform to SemVer

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#827]
According to [Semantic Versioning](https://semver.org/) 
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Currently `eds-core-react` is on 0.6.2 for instance. This can be a issue for users as they don't know what to expect from the API. Also from the specification
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

The task of deciding breaking|feature|fix should not be manually, but should be [automated with CI](https://css-tricks.com/how-to-automate-project-versioning-and-releases-with-continuous-deployment/)

**Comment by mimarz** [comment]
related to #1401

**Comment by BirteThornquist** [comment]
Will be solved by #2741
