### ISSUE TITLE
🐛 Props first tab renamed to 'Story' instead of using main component name

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#842]
[Storybook bug](https://github.com/storybookjs/storybook/issues/12357), we should find a workaround and/or update if/when Storybook has released a fix 

Applies to these components:
- [ ] Accordion
- [ ] Breadcrumbs
- [ ] Card
- [ ] Popover
- [ ] Tabs

**Comment by mimarz** [comment]
is this still relevant @pomfrida ?

**Comment by pomfrida** [comment]
Looks like this has been fixed 🎉
