### ISSUE TITLE
🐛 Fix weird behaviour on Table of Contents controlled docs

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#843]
Reproduce bug: 
1. Go to TOC in Storybook
2. Use the props controls to make TOC sticky = true
3. See sticky TOC outside the docs window 

The sticky TOC should show inside the docs window

**Comment by mimarz** [comment]
Is this still relevant @pomfrida ?

**Comment by pomfrida** [comment]
<img width="1062" alt="Screenshot 2021-09-29 at 13 58 58" src="https://user-images.githubusercontent.com/31915755/135264067-1f39baae-7ae7-4ba5-8b4f-bcb07d2011b1.png">

Yeah but don't know if it's fixable, it's iframe's fault. The Canvas story doesn't have this problem

**Comment by mimarz** [comment]
Ok, then lets close this.
