### ISSUE TITLE
Stepper guideline in storefront

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#845]
Update guidelines in usage for stepper variant

**Comment by benkeq** [comment]
Vil du dele en direktelenke til det jeg skal gjøre review av @lucasveil ?

**Comment by benkeq** [comment]
[Jeg fant, jeg fant.](https://github.com/equinor/design-system/commit/ae4f0500dd351f342fdd0a3633d0e501beb9c440)

**Comment by lucasveil** [comment]
https://github.com/equinor/design-system/blob/documentation/apps/storefront/docs/components/stepper/usage.mdx

**Comment by benkeq** [comment]
[Ny kommentar ](https://github.com/equinor/design-system/commit/1dae3dd24f3439e368450e89c9e6cd940bfdf907)
