### ISSUE TITLE
Change license from AGPL to MIT

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#852]
As we have discussed internally, we want to change the license from AGPL to MIT to make it easier to use the EDS. We need to make sure that everyone _outside_ the company who has contributed to the EDS agree with this decision. This process has begun.

**Comment by vnys** [comment]
We need to get in touch with you @imp-dance – where can I find your email-address?

**Comment by imp-dance** [comment]
@vnys You can reach me at haakon@underbakke.net ! 👍
