### ISSUE TITLE
Update stepper in storefront

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#858]
- Merge Stepper usage page in storefront

- Update Figma link in guideline page

Related to #845

**Comment by mimarz** [comment]
Is this still relevant @equinor/eds-ux ?

**Comment by lucasveil** [comment]
If you publish the updates from [our last comment](https://github.com/equinor/design-system/commit/1dae3dd24f3439e368450e89c9e6cd940bfdf907) then this one is closed @mimarz

**Comment by mimarz** [comment]
> If you publish the updates from [our last comment](https://github.com/equinor/design-system/commit/1dae3dd24f3439e368450e89c9e6cd940bfdf907) then this one is closed @mimarz

This will not be published as Storefront is in a broken state now, and will not be fixed due to being replaced by Zeroheight. Your are better off just copying the text to Zeroheight now @lucasveil
