### ISSUE TITLE
Convert Buttons to Auto Layout

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#860]
[Auto Layout in Figma](https://help.figma.com/hc/en-us/articles/360040451373-Create-dynamic-designs-with-Auto-Layout)

- [ ] Find a solution to solve Auto Layout in Buttons
- [ ] Update changelog
- [ ] Send out message to #eds-design-system 

It's very important to use the label and icon already in the buttons. If those are removed or replaced by new labels and icons, the users will lose the connection. 

Converting require spacings, 'Button' and clickbound to be removed. A button with auto layout can be placed inside a frame with auto layout to keep clickbounds. [See example](https://www.figma.com/file/KyI0glVqaxcYTCKuNLhAZn/Auto-layout?node-id=1%3A5).

**Comment by benkeq** [comment]
Unfortunately, I had to move this back to to do. There is no easy way to convert this component to auto layout while having focused, pressed, hover hands and so on. Waiting for a change in Figma, maybe where you can select z-axis?

**Comment by lucasveil** [comment]
On hold for now since the "focus" state is not compatible to build with variants.

**Comment by akvam** [comment]
DONE :-)
