### ISSUE TITLE
Convert Table Caption to typescript

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#873]
Convert sub-component, `Caption` under `Table` to typescript

**Comment by mimarz** [comment]
blocks #870

**Comment by vnys** [comment]
I suggest we do this by cherry-picking [0275e3bc85737fd3b538000958fec26caa17b81e](https://github.com/equinor/design-system/commit/0275e3bc85737fd3b538000958fec26caa17b81e) as a separate commit and then change the suffixes so we don’t rewrite history more than necessary.

**Comment by mimarz** [comment]
> I suggest we do this by cherry-picking [0275e3bc85737fd3b538000958fec26caa17b81e](https://github.com/equinor/design-system/commit/0275e3bc85737fd3b538000958fec26caa17b81e) as a separate commit and then change the suffixes so we don’t rewrite history more than necessary.

Cherrypick what? There is already a `Table.Caption` in develop, albeit not updated in `index` or `story`

**Comment by vnys** [comment]
Ah, of course… hadn’t checked :wink: Then maybe it’s not that important if we add to the story and index ourselves – the component is the most important one.
