### ISSUE TITLE
Update Table Caption with missing features

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#874]
blocked by #875

- [ ] Add missing typography
   - Had a meeting with @benkeq about this. If caption is `top`, then it can be any of the `headings`, else its `paragraph/caption`

❗Suggest having a resolution for [Typography discussion](https://github.com/equinor/design-system/discussions/875) before starting on this issue

**Comment by vnys** [comment]
It should be a prop then, since the font-size should be determined by the parent header level.

**Comment by mimarz** [comment]
Closing this issue as [flow content is valid conent](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption) for a `caption` element. We will instead update documentation to reflect guidelines for which typography to use in these #1028
