### ISSUE TITLE
♿ Remove superfluous <title /> element

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#894]
There are two <title /> elements on each page in the storefront

_This is correct:_

```html
<title data-rh="true">
  Documentation overview | Equinor Design System
</title>
```

_This must be removed:_

```html
<title data-react-helmet="true"></title>
```

**Comment by wenche** [comment]
Hmm, seems like the `<SEO>` element is imported both in `index.js` and  in`wrapper.js`. Probably some refactoring gone wild? 🤷‍♀️

**Comment by vnys** [comment]
Yes, that could be the case. But there’s some weird stuff here when it comes to hydration as well, so some of what’s reported in SiteImprove seem to be the SSR pages before they hydrate in the browser. And that seems a bit outdated, I would have thought the days when things were expected to work without javascript were over.
