### ISSUE TITLE
Replace the Equinor typeface with Nunito Sans in components with font-size equal to or lower than 16px

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#916]

**Comment by mimarz** [comment]
Recommended reading: https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/?ref=heydesigner

**Comment by mimarz** [comment]
Is this still relevant? @vnys

**Comment by mimarz** [comment]
closed as equinor font was adjusted
