### ISSUE TITLE
Add unit and custom icon as properties in text field component

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#927]
Requires to duplicate the ones we have today twice. Do not delete layers, just hide or show.

**Comment by benkeq** [comment]
[Ready for review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=1%3A26) @lucasveil @BirteThornquist

**Comment by lucasveil** [comment]
Good for me :) @benkeq Må bare nevne at success ikon ser litt "usentrert" (fant ikke norsk ord på det) med unit tekst.
