### ISSUE TITLE
Search component overlays Scrim

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#929]
EDS scrim does not cover a EDS search component

**Comment by pomfrida** [comment]
👋  `Scrim` should definitely cover `Search`. I'm curious if you may have wrapped `Search` inside `Scrim`, as `Scrim` does not cover child elements (to be used with `Dialog`, `SideSheet` etc). We updated `Scrim`'s z-index in the latest release, from 11 to 300. `Search` have z-index: 0.

**Comment by HansKristianVikOlsen** [comment]
You can close this issue now. I had a Z-index issue. Thanks for the help!
