### ISSUE TITLE
EDS libraries does not work for older than v3.8 Typescript

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#931]
We are using the `import type` syntax for type-only imports which was introduces in [Typescript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

Using Typescript older than 3.8 gives an error when trying  to read the declaration files generated for our EDS libraries.

Example when using core-react.
![image](https://user-images.githubusercontent.com/1070981/100595824-b92f5880-32fb-11eb-8d2f-fd1a9b920142.png)

**Comment by pomfrida** [comment]
I vote on just specifying this requirement in the README and in the docs in general. The users should be responsible for keeping their TS version up to date
