### ISSUE TITLE
Add auto layout to Table

### ISSUE THREAD

**Issue by lucasveil** [equinor/design-system#934]

**Comment by BirteThornquist** [comment]
Ready for review [here](https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/?node-id=11%3A6668) @lucasveil

**Comment by lucasveil** [comment]
![Screenshot 2021-01-06 at 16 08 21](https://user-images.githubusercontent.com/65652493/103783754-6868f900-5039-11eb-94ac-7af13c06e465.png)
2 ting:
- Når jeg skrive en lang tekst formatter seg cellen bra men den grå strek under følger ikke med
- Når jeg resize hele cellen da blir alt sentrert. Tror ikke det er meining eller?

**Comment by BirteThornquist** [comment]
Har fikset punkt 1 i base komponenten, men det er et problem med resize i instanser fortsatt som jeg ikke finner helt ut av...
Trenger å drøfte litt med deg @lucasveil ang mulige løsninger her....
Punkt 2 er fikset.

**Comment by BirteThornquist** [comment]
I have added auto layout to the table cell and table header. The component set is now based on a base component for the table header and cell. 
There is however an issue; the user will not be able to resize the cells/header instances to fit their own table with. With auto layout it is the content in the cell that decide the size, either horizontally or vertically.
Currently there is no solution/workaround for this in Figma. Until a fix exists, this version 2 of table cell with auto layout stays in Birte's test file. A new issue < > is added to the back log for this fix and will be done once Figma upgrade the auto layout function.
