### ISSUE TITLE
Wrong placement of Menu (context menu)

### ISSUE THREAD

**Issue by lindsve** [equinor/design-system#935]
**Describe the bug**
I'm trying to use the `Menu` component as a context menu, but it seems that the placement is all wrong. The X/Y coordinates seem to be 2* their actual value (see screenshot. Blue line from anchor element to the menu with the single Mute-item)

![Skjermbilde 2020-11-30 kl  15 30 38](https://user-images.githubusercontent.com/159861/100622771-88621a00-3321-11eb-99b2-0e98ae15e4c7.png)

**Expected behavior**

Menu with "Mute" option should be placed anchored to the anchor element.

**Specifications**

- Version: 0.7.1
- Browser: Edge
- OS: MacOS

**Comment by mimarz** [comment]
Thanks for reporting this! 

Thats weird... We are using the "bounding" values for the [calculation  of the position](https://github.com/equinor/design-system/blob/313b00e213e7d983583fe25447cbf0896425e6ec/libraries/core-react/src/components/Menu/Menu.context.tsx#L38), so not sure whats happening here..

We have noticed some irregularities when it comes to the "popup" when using `Menu` and `Popover`. We have planned to have a look at this in issue #673, so this will make for a good use-case to test also!

**Comment by lindsve** [comment]
For reference, I run this when opening the menu: `console.log(anchorRef.getBoundingClientRect().toJSON());`

And the values seem to be correct:
`{x: 574, y: 279, width: 200, height: 46, top: 279, …}`

**Comment by mimarz** [comment]
> For reference, I run this when opening the menu: `console.log(anchorRef.getBoundingClientRect().toJSON());`
> 
> And the values seem to be correct:
> `{x: 574, y: 279, width: 200, height: 46, top: 279, …}`

Weird, the calculation for position is pretty simple 

```typescripy
const calculatePosition = (
  { left, top, height }: ClientRect, // anchorRef.getBoundingClientRect()
  offset: number,
) => ({
  top: top + height + offset,
  left: left,
})
```
