### ISSUE TITLE
As a designer I need a complete set of states for the Date Picker

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/design-system#938]

**Comment by benkeq** [comment]
[Ready for review](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/?node-id=35%3A6) @lucasveil @BirteThornquist

**Comment by lucasveil** [comment]
There is a bug with dark theme. When state is active and i switch to dark mode, then it reset to default. And on Dark theme, when i set to active, it resets to default light theme @benkeq

**Comment by benkeq** [comment]
Should be fixed now @lucasveil

**Comment by lucasveil** [comment]
One last thing i found out. If you are on a single day and state disabled. When you change the position (left period etc.) it switches the component to "select" active and state "enable". Not sure why @benkeq

**Comment by benkeq** [comment]
Because there are no left positioned disabled state. The position is just used for the selected dates.

**Comment by benkeq** [comment]
The property for Position could be renamed from "Position" to "Position (selected only)". What do you think? @lucasveil @BirteThornquist

**Comment by lucasveil** [comment]
Ok, was unsure if it was a bug. Additional infos never hurts. I was just stress testing all the buttons, and no user will do that when they use the component. So for me good to go :)

**Comment by BirteThornquist** [comment]
LGTM!
