### ISSUE TITLE
As a designer I want components relevant for forms to have a consistent set of form features.

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#939]
- [ ] Define list of relevant components
- [ ] For each component define form features

Form features includes 
- [ ] Validation messages
- [ ] Help text
- [ ] Validation states for components (which components have warning, error, success, states)

For each component check if new US is needed to implement this in the React components.

Components so far:
- TextField
- Select

**Comment by nilsml** [comment]
Perhaps create an epic for validation

**Comment by akvam** [comment]
No more US on this => closed
