### ISSUE TITLE
Add missing table states

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#940]
States for active and error cell in table. 
How to show active and hover on both row and cell?

Edit:
~- [ ] Active state, row only~ Replaced by #981
- [x] Hover state, row only
- [x] Error (Validation) state, cell only

**Comment by mimarz** [comment]
@equinor/eds-ux Should the active & hover style be applicable to single cells or just row? Feel like row is the most common way of doing these features.... 🤔

**Comment by lucasveil** [comment]
As in the example [here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=2549%3A57177) it applies on the row

**Comment by mimarz** [comment]
> As in the example [here](https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=2549%3A57177) it applies on the row

Thanks! Ok, so only error (validation) state can be per. cell if I understood that example correctly.

**Comment by mimarz** [comment]
@equinor/eds-ux Having background color change on hover for Table Header Cell looks kinda off in conjunction with a whole row being highlighted on hover in table...

Also, what is meaning of table focus state? Don't think I have ever seen a table cell being focusable 🤔
