### ISSUE TITLE
Rename packages to match npm name

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#942]
Its considered best practice to have the same folder name on packages that are published to npm as their npm name. This change will need to be done when we have no PRs with changes into `develop`. 

So `core-react` should be called `eds-core-react`, since our package name is `@equinor/eds-core-react` (@equinor being the npm organization name).

Suggested for updated names: 
* `core-react` -> `eds-core-react`
* `icons` -> `eds-icons`
* `tokens` -> `eds-tokens`
* `static` -> `eds-static`
  
  Edit: doing `libraries` -> `packages` rename in separate issue+pr for tracebility #1835

**Comment by mimarz** [comment]
Suggest doing this Christmas 2021 🎅 @equinor/eds-dev

**Comment by vnys** [comment]
And similarly for #1800. We just need to close everything and turn off the lights before we leave for the holiday.
