### ISSUE TITLE
Should outlined button background be transparent?

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#945]
When looking at outline button, it has no background now, making it transparent.

Is this intended? Can cause some weird issues if people use it on a grey or any other colourful backgrounds.

Figma: https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A47297

**Comment by benkeq** [comment]
Have a look at [this test](https://www.figma.com/file/keRBUZFF3TydIZSWqtHYq6/?node-id=3366%3A123) @lucasveil and @BirteThornquist. What do you think?

**Comment by BirteThornquist** [comment]
LGTM. I think it works well to use this black and white as background color instead of transparent. In that way we secure contrast while it is still an outlined (secondary) button.

**Comment by lucasveil** [comment]
Litt usikkert med [denne knapp](https://www.figma.com/file/keRBUZFF3TydIZSWqtHYq6/Bendik-test-2.0?node-id=3366%3A8054). Ghost skal ikke ta så mye oppmerksomhet, men det blir plutselig det med et grå bakgrunn. Men svar til det kan vær at vi i så fall safe UU godkjenning på det. Bare en headsup hvis noe spør tenker jeg.

**Comment by benkeq** [comment]
Ghost skal være ghost, men dette er outlined. Men jeg er veldig usikker på hva som er riktig og ikke. Spørs om det skal gjøres litt research på andre designsystemer.

**Comment by lucasveil** [comment]
Blandet litt ja. [Carbon Design](https://www.carbondesignsystem.com/components/button/usage) bruker ikke noe hvite bakgrunn på knapp.

**Comment by benkeq** [comment]
Skal vi da legge den død frem til noen etterspør, eller så du noen problemer med å ha outlined knapp uten bakgrunnsfarge @mimarz ?

**Comment by mimarz** [comment]
Beholder den transparent inntil videre :)
