### ISSUE TITLE
As a designer for EDS I would like the button component to be made out of a base component, so that it would be easier to maintain

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#949]
After Auto Layout and Variants came to Figma, it has been a lot clearer that our system is difficult to maintain. A solution could be to add another component set/variant set of buttons, and rename the old one "Old button" or something in that matter. That would make it easier to communicate that this shouldn't be used in new solutions and screens. Anyway, it would be important to maintain both the old and the new component set for a while. 

I would have made the new component set with the help of a base component. That would be a component that includes everything; icon left, label, icon right, hover hand, disabled hand, pressed overlay, focus border, and loading icon. Name this ".base-button", and create an instance of the base component. Make that instance into a component, and start creating variants by hiding and showing layers, as well as changing the colors. Create the base component with the help of auto layout, and the result will be a component that is really easy to use, as well as maintain.

**Comment by benkeq** [comment]
This may not be possible for the time being.

**Comment by mimarz** [comment]
Is this still relevant? @equinor/eds-ux

**Comment by lucasveil** [comment]
This issue is blocked @mimarz We want to set auto-layout to all our component but ourr focus state won't let us do it. Waiting for Figma update or delete the focus state for our component.

**Comment by akvam** [comment]
Need to decide if we need the focus state.

**Comment by akvam** [comment]
The main goal is to get auto-layout.

**Comment by akvam** [comment]
Already done by EDS 2.0 - issue close.
