### ISSUE TITLE
Lowered opacity on a Tooltip component lowers the z-index

### ISSUE THREAD

**Issue by lindsve** [equinor/design-system#950]
**Describe the bug**
Consider the following code:
```
<Wrapper>
    <Tooltip title={moment(eventMessage.timestamp).fromNow()} placement="topRight">
        <Icon name="time" size={16}/>
    </Tooltip>
</Wrapper>
```
When the opacity of `Wrapper` is turned down, then the z-index for the tooltip seems to be lowered as well.

Opacity=0.3
![Skjermbilde 2020-12-03 kl  14 35 50](https://user-images.githubusercontent.com/159861/101024763-db7fdb00-3574-11eb-996d-4c7c60a5374b.png)

Opacity=1
![Skjermbilde 2020-12-03 kl  14 37 03](https://user-images.githubusercontent.com/159861/101024865-04a06b80-3575-11eb-86af-0c05dab8a483.png)

**Expected behavior**

Opacity turned down, but without changing the z-index level of the tooltip itself

**Specifications**

- Version: 0.7.1
- Browser: MS Edge
- OS: MacOS

**Additional context**

I'll be able to work around this for now by only tuning the opacity of the Icon and not the Tooltip

**Comment by mimarz** [comment]
Huh, this is weird 🤔

We'll try to have a look at it as soon as possible!

**Comment by vnys** [comment]
Changing the opacity on an element affects the stack-order, and takes precedence over z-index. Robin Metcalfe has a [codepen](https://codepen.io/solarisedesign/pen/qOEQMB) that demonstrates it – so even though it might seem odd, it’s just part of how CSS works 🤷‍♀️

solarisedesign

**Comment by lindsve** [comment]
> Changing the opacity on an element affects the stack-order, and takes precedence over z-index. Robin Metcalfe has a [codepen](https://codepen.io/solarisedesign/pen/qOEQMB) that demonstrates it – so even though it might seem odd, it’s just part of how CSS works 🤷‍♀️

Yeah, I figured it most likely would be a CSS issue since it didn't make any sense that this would be applied by code.

> May I ask what you want to achieve by lowering the opacity of the wrapper?

It was simply a simplification of setting opacity once instead of for each icon inside the wrapper. I have changed it so that opacity is set on the icons instead now and that works just as good (and honestly makes more sense visually ;) ).

Feel free to close the issue
