### ISSUE TITLE
Menu: Choose position of where menuitem drops

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/design-system#952]
![image](https://user-images.githubusercontent.com/35257765/101145421-08d29480-361a-11eb-9bc9-2fa9afa4b922.png)

This, instead of this for example

![image](https://user-images.githubusercontent.com/35257765/101145468-1d169180-361a-11eb-977d-54a294ab7823.png)

**Comment by mimarz** [comment]
Yeah, we are placing the menu from top left.

We have multiple stuff gathering up for the Menu now, so we'll take this into consideration on our next iteration for the Menu.

Thanks for the input! 🤘
