### ISSUE TITLE
Include references to font files in core-react

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#959]
Today, as a user of `eds-core-react` you have to add a reference to our CDN in your `index.html` file to get the correct font (Equinor font).

This can be easy to overlook and we have seen instances of people forgetting to do this. 

I suggest we add this reference to the CDN to be included in `eds-core-react`, either by including a css file or styled-components [createGlobalStyle](https://styled-components.com/docs/api#createglobalstyle)

This way we ensure that the users of our component library are using the correct font. This will be even more important with the inclusion of Nunito Sans as a secondary font.

**Comment by vnys** [comment]
EDS is an open source design system but the font is not. As long as we don’t allow users outside of Equinor to use the Equinor font, we can’t include it in the components. Closing this issue.
