### ISSUE TITLE
MultiSelect, select all feature

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#961]
As [mentioned in an issue in Downshift's repository](https://github.com/downshift-js/downshift/issues/935#issuecomment-738689141)  the `useMultiselect` hook will be improved. 

This will provide a better foundation for adding `Select all` option/action, to solve the issue of an easy overview on selected options and improve accessibility by making it easier to find the selected options.

**Comment by mimarz** [comment]
I am ready to start implementing this feature soon. Will you have a look at how we can solve this ux/design wise @lucasveil ?

**Comment by lucasveil** [comment]
After contacting different teams that uses the multi-select, the best way to fix this is to implement the "select all" option inside the drop down as discussed in our intern meeting with @mimarz 
Here comes the screenshot of the teams:
Echo:
![image (1).png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/cb2cdd42-aad5-492b-979c-ada987170443) ![image (2).png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/38239fde-7174-4ff4-85e6-3c005f321a2f)![image.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/56414915-ec39-4233-89b2-47d960d2b26e)

And Amplify:
![Screenshot 2022-01-19 at 14.31.45.png](https://images.zenhubusercontent.com/608123fcbee65b40f5b36b26/ab8a8351-a737-442d-8b6d-6fb79e52d309)

**Comment by mimarz** [comment]
hmm, I would argue these are two different features/approaches. @lucasveil 

* The first is a whole different approach with "tree-select" functionality, this will require a lot more work. 
* The second with just a "select all" option is simpler. 

They both fulfill the same role (kinda) or do we want both?

**Comment by lucasveil** [comment]
In the example in the storybook we don't have the "tree organisation", so i would suggest just having a "select all" on the top.

**Comment by mimarz** [comment]
> In the example in the storybook we don't have the "tree organisation", so i would suggest just having a "select all" on the top.

Jepp! if anything, I see the need for the "tree organisation" so maybe an issue for the future? 😅 We should reach out to echo and see if the want can contribute on this 🤔

**Comment by lucasveil** [comment]
Definitely worth a try :)

**Comment by mimarz** [comment]
related to #1651

**Comment by lucasveil** [comment]
Maybe check with DOTCOM Team

**Comment by mimarz** [comment]
Suggest just having an example on how our users can make this themselves as it reduces the component complexity and gives our users more flexibility in creating other "shortcuts" for selections. 

Current example looks like this @lucasveil 
![image](https://user-images.githubusercontent.com/1070981/154470388-9c5d159d-d2c1-4adb-92af-7b7284ad9c46.png)
