### ISSUE TITLE
Combine pages in Figma to create a better structure and hierarchy

### ISSUE THREAD

**Issue by benkeq** [equinor/design-system#962]
Sort components in categorized pages such as "Navigation", and "Inputs".

**Data display**
- Chip
- Divider (MUI have added it under data display, is that the best place for it?)
- Lists (not a component)
- Popover
- Table
    * Header
    * Cell
- Tooltip

**Feedback/Notifications** 
- Banner
- Dialog
- Progress indicators
    * Linear
    * Circular
    * Dots
    * Star
- Scrim
- Snackbar

**Inputs/Data entry/Forms**
- Button
- Date picker
- Search
    * Search
    * Scope
- Select
- Selection controls
    * Checkbox
    * Radio button
    * Switch
- Slider
    * Dot
    * Handle
    * Indicator
    * Track
- Text fields
- Time picker
- Toggle button

**Navigation**
- App launcher
- Breadcrumbs
- Drawer
    * Listing
    * Container
    * Subtitle
    * Destination item
- Link (not a component)
- Menu
    * Menu
    * Container
    * Item
    * Subtitle
- Pagination
- Stepper
- Table of Contents
    * Item
    * Listing
- Tabs
- Top bar

**Surfaces**
- Accordion
- Card
    * Container
    * Title
    * Rich media
    * Supplemental actions
- Side sheet
- Toolbar

**Comment by vnys** [comment]
Looks good 👍 We do have some components in code that we don’t have in Figma – `<Typography>` for example. I think that would fit under “display”. So maybe add that to the list with “code only” in parentheses since we’ll use the same structure in the Storybook. How about `<Avatar>`, don’t we have that in Figma?

**Comment by mimarz** [comment]
Looks good. Maybe a stupid question, but does everything need to be categorised?  

> ... We do have some components in code that we don’t have in Figma – `<Typography>` for example. I think that would fit under “display”. So maybe add that to the list with “code only” in parentheses since we’ll use the same structure in the Storybook...

Typography is defined as a design token in Figma, and implemented as component in code. Which is not wrong by any mean but dunno.  🤷‍♂️

> ...How about <Avatar>, don’t we have that in Figma?

I think its time we add this to Figma to for consistency :D Maybe some notes on sizing and such for avatars?

**Comment by vnys** [comment]
> Typography is defined as a design token in Figma, and implemented as component in code. Which is not wrong by any mean but dunno. 🤷‍♂️

No of course not, we implement it the way it makes sense 😊 But we should make users aware that that’s what we’ve done.

**Comment by benkeq** [comment]
Any feedback to the [layout in Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=18442%3A38077&viewport=653%2C1459%2C0.051727842539548874) so far, @BirteThornquist @lucasveil ?

**Comment by BirteThornquist** [comment]
This layout suggestion makes sense to me 👍

**Comment by lucasveil** [comment]
Really like the way it gives a better overview but everything is kind of floating around at the first look due to lot of space between each component. [UI2](UI2) has a good suggestion if you are looking for inspiration :)

**Comment by benkeq** [comment]
I agree that it's a bit messy, but I've tried as good as I can by having a consistent space between the components. The reason for the amount is because you're always starting out zoomed out with an overview of every component, and if there's less space it will be harder to navigate (I think). In UI2 it's structured in another way where everything is on one page, and they can therefore frame objects into categories. While our system is structured on multiple pages, and we can't frame those objects again without having another level in the hierarchy. I will try to find another way though :)

**Comment by benkeq** [comment]
Any last reviews @BirteThornquist @lucasveil?

**Comment by lucasveil** [comment]
I think it looks good. We could try this version out and can adjust if we get any feedback from users. Good job!
