### ISSUE TITLE
As a Designer I would like to know the process for how others can contribute to and our EDS Component design in Figma

### ISSUE THREAD

**Issue by akvam** [equinor/design-system#97]
- [ ] Add info to the storefront ref. meeting in Bergen. Make it simple. Ask for examples.

Useful links:
- https://brand.ruter.no/d/3LOphUstQWYz/identitet#/om-designsystemet/vil-du-bidra

**Comment by mimarz** [comment]
We have the "meet the designer" & Figma Sandbox for this now
