### ISSUE TITLE
import eds-icons triggered typescript compiled error

### ISSUE THREAD

**Issue by jiyangye** [equinor/design-system#972]
When just import the eds-icon into the React typescript code, a typescript error triggered.  I have asked the question in Equinor eds slack channel.  

Version:
    "@equinor/eds-core-react": "^0.8.0",
    "@equinor/eds-icons": "^0.6.0",
    "typescript": "~3.7.2"
    "react": "^16.14.0",

`import { Icon as EDSIcon } from '@equinor/eds-core-react'; // FIXME this triggered typescript error.`

error:
```
Failed to compile.

/home/jiyang/kalkulo/sr-predictor-cloud/frontend/node_modules/@equinor/eds-core-react/dist/types/components/Accordion/Accordion.d.ts
TypeScript error in /home/jiyang/kalkulo/sr-predictor-cloud/frontend/node_modules/@equinor/eds-core-react/dist/types/components/Accordion/Accordion.d.ts(2,13):
'=' expected.  TS1005

    1 | import * as React from 'react';
  > 2 | import type { AccordionProps } from './Accordion.types';
      |             ^
    3 | declare const Accordion: React.ForwardRefExoticComponent<AccordionProps & React.HTMLAttributes<HTMLDivElement> & React.RefAttributes<HTMLDivElement>>;
    4 | export { Accordion };
```

**Comment by wenche** [comment]
@jiyangye  See #931 . Are you able to upgrade your Typescript version? I'm pretty sure that it's the same problem.

**Comment by jiyangye** [comment]
> @jiyangye See #931 . Are you able to upgrade your Typescript version? I'm pretty sure that it's the same problem.
