### ISSUE TITLE
Should table header have a default sort state

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#983]
Should table headers have a "default" state to indicate that a column is sortable without hover/interacting. 

Icons & state for: ascending, descending and none.

Active styling is only applied for asc and desc.

Related to #653 

Sketches: https://www.figma.com/file/luNobpDIWTuQ9rhyovGLBI/Desktop?node-id=624%3A0

**Comment by lucasveil** [comment]
Ready for review and talk [here](https://www.figma.com/file/bqGObONc5xXZeuo5MXzPXD/Lucas-Test?node-id=1011%3A53022) @mimarz @pomfrida
