### ISSUE TITLE
Fix the Button Icon to the sides

### ISSUE THREAD

**Issue by pomfrida** [equinor/design-system#992]
Button Icon is currently centered with the Button text, it should be fixed to the sides instead

**Comment by pomfrida** [comment]
![Screenshot 2021-01-05 at 11 13 15](https://user-images.githubusercontent.com/31915755/103635638-1e084f00-4f49-11eb-8813-6356ae7ed06b.png)

**Comment by mimarz** [comment]
Suggest adding a new story in Storybook with full width examples of this

**Comment by wenche** [comment]
Verify in Figma how the text alignment should behave.

**Comment by BirteThornquist** [comment]
@lucasveil can you pls take a look?  I have outlined some examples [here](https://www.figma.com/file/dCtGxSjiufV5C6YcXSs3MD/?node-id=159%3A0). My preference is left aligned text, but I also think todays solution works. What do you say?

**Comment by lucasveil** [comment]
Looking really good @BirteThornquist. My only concern with left aligned text is if a user uses the button with no icon context and decides to resize it, having the left align text would look weird. Is it overkill to have a variant "left aligned text"?

**Comment by BirteThornquist** [comment]
Absolutely @lucasveil . This change of text alignment will only apply for text and icon type button. Do we need a new variant? Or can we just have the text left aligned for the variants; icon trailing/leading?

**Comment by BirteThornquist** [comment]
@lucasveil I actually wonder if it is best to keep todays solution... The problem with a messy look for situations where several buttons are stacked vertically will also be a problem for text buttons... And I do think it works with centered text and right/left aligned icons.

**Comment by lucasveil** [comment]
Yes agreed :)

**Comment by BirteThornquist** [comment]
After doing some design testing we have decided to keep the text centered as it is done in Figma today. Thus the design tag is removed.
