### ISSUE TITLE
Wrong icon name 

### ISSUE THREAD

**Issue by maiaht** [equinor/design-system#993]
`close_cricle_outlined` should be `close_circle_outlined` [here](https://github.com/equinor/design-system/blob/e9c1c64fdf4de744e2dec456b7cab8da06260cb6/libraries/icons/src/data.ts#L882)

**Comment by mimarz** [comment]
Thank you for bringing this to our attention! 

This looks to be a typo we need to fix in our [assets in Figma](https://www.figma.com/file/BQjYMxdSdgRkdhKTDDU7L4KU/Assets?node-id=103%3A2380), so it affects all our instances of icons hosting.

**Comment by mimarz** [comment]
@equinor/eds-ux Will you have a look at this in Figma?

**Comment by lucasveil** [comment]
Name is now updated
